### ISSUE TITLE
New bindings: bimg

### ISSUE THREAD

**Issue by bonenaut7** [LWJGL/lwjgl3#1001]
### Library

bimg

### Project page

https://github.com/bkaradzic/bimg

### Source repository

https://github.com/bkaradzic/bimg

### Platforms

Linux x64, macOS x64, macOS arm64, Windows x64, Windows x86

### Description

bimg is a image library used in bgfx, which bindings already present in LWJGL

This is pretty good tool for reading and decoding textures of [huge pile of different formats](https://github.com/bkaradzic/bimg/blob/master/src/image.cpp#L28-L123) including compressed ones, more of all it looks pretty good as a companion for bgfx bindings, as an example: conversion of texture formats, screenshots in BGFX are retained in BGRA, but stbi could write only RGBA color format as a png file.
It's the most simpliest case of possible bimg usage.

This library also capable of mipmaps generation and image encoding/decoding and some other features

As far as i know platforms should be the same as for bgfx itself. And it looks like this library doesn't have any documentation :(

**Comment by Spasi** [comment]
Hey @bonenaut7,

The bimg library does not have a C API, therefore LWJGL cannot expose it.

See the [KTX](https://github.com/KhronosGroup/KTX-Software) bindings for the recommended way to load/transcode textures.
