### ISSUE TITLE
Missing latest lwjgl.zip download under Releases -> 3.3.4 -> Assets

### ISSUE THREAD

**Issue by philipguin** [LWJGL/lwjgl3#1009]
### Version

3.3.4

### Platform

Linux x64, Linux arm64, Linux arm32, macOS x64, macOS arm64, Windows x64, Windows x86, Windows arm64

### JDK

NA

### Module

NA

### Bug description

The latest stable release (3.3.4) is missing the usual zip file for download under [Releases](https://github.com/LWJGL/lwjgl3/releases). Specifically under the 'Assets' section.

This wouldn't be a big deal, except A) it's linked from the [LWJGL download page](https://www.lwjgl.org/download), and B) as I recall, the folder name/organization is slightly different than the ones output from the website, so swapping breaks configuration. (It's a pain to adjust this, at least not without editing the IntelliJ XMLs by hand.)

The [URL](https://github.com/LWJGL/lwjgl3/releases/download/3.3.4/lwjgl.zip) you might expect the file to be hosted at is also unavailable.

**Comment by Spasi** [comment]
Hey @philipguin,

I have removed the file until #1005 is resolved. There hasn't been any progress on that though. It still looks like false positives and I'm still not sure what we can do about it.

Also note that there will be a 3.3.5 release soon.

**Comment by Spasi** [comment]
LWJGL `3.3.5` is now available.
