### ISSUE TITLE
opencl support for cpu: amd cpus not showing up as opencl devices

### ISSUE THREAD

**Issue by goofyseeker311** [LWJGL/lwjgl3#1010]
### Question

what is with the amd ryzen 5000 series cpus not showing up as opencl devices on windows 11?
nvidia gpus and amd igpus show up just fine in the CLDemo java program. where is the issue?

self-answer: downloading and installing the intel opencl runtime for cpu works for amd cpus too.
https://www.intel.com/content/www/us/en/developer/articles/technical/intel-cpu-runtime-for-opencl-applications-with-sycl-support.html

**Comment by goofyseeker311** [comment]
A second question, why is java lwjgl opencl simple math calculations much slower on nvidia discrete cpus than even amd cpus and igpus, by like 2-4x (multiplication and float4[] matrix multiplication).

**Comment by goofyseeker311** [comment]
what is wrong with the opencl/cuda, it gets about 1/1000 floating point operations of what it should be getting. say 2gflops instead of 0.7-2tflops for cpu. and 20gflops instead of 20tflops, for a gpu.

**Comment by goofyseeker311** [comment]
How can you get an long type event, from PointerBuffer, to be used for event profiling for NDRangeEnqueued kernel running. there is no overload for PointerBuffer type of clGetEventProfilingInfo, just the long event types. also the NDRangeEnqueue function only accepts PointerBuffer events, not long type of events.

**Comment by Spasi** [comment]
Hey @goofyseeker311,

The `cl_event * event` parameter of `clEnqueueNDRangeKernel` is an **output** parameter. If you pass a `PointerBuffer` there, when the call returns a `cl_event` value will have been written to it. Example code:

```java
PointerBuffer pe = ...; // cl_event *
clEnqueueNDRangeKernel(..., pe);

long e = pe.get(0); // cl_event
clGetEventProfilingInfo(e, ...);
```
