### ISSUE TITLE
Better Support for all systems

### ISSUE THREAD

**Issue by mrGoodWolf** [LWJGL/lwjgl3#1012]
### Description

# my point
let's set things straight opengl drivers are TERRIBLE!
so it could be very easy for everyone to use lwjgl if drivers weren't needed and  lwjgl could use portablegl or something for opengl by default and the devolper uses something like:
      @setuse("system driver")
       public class someprogramcaller {
this to tell lwjgl that they want to use system drivers.

**Comment by Spasi** [comment]
Hey @mrGoodWolf,

This is already supported with `Configuration.OPENGL_LIBRARY_NAME.set("<path>");` or running with `-Dorg.lwjgl.opengl.libname=<path>`. It will make LWJGL use that particular shared library for OpenGL and there's also interop with GLFW (it will use the same library internally).

Providing a particular implementation of OpenGL, whether in software or emulated on top of another API, is outside the scope of LWJGL.
