### ISSUE TITLE
opencl images faster transfers to java/gpu?

### ISSUE THREAD

**Issue by goofyseeker311** [LWJGL/lwjgl3#1014]
### Question

there is quite significant lag transferring and converting, painting an opencl gpu image to java BufferedImage painted by java gpu. goal is not to use opengl interop with opencl, even if it would directly solve the issue but would also involve using opengl.
so I look for a way to get opencl gpu image to java default environment faster than 10ms at 720p, 20ms at 1080p and 100ms at 4K. the transfer phase uses pure integer buffers and conversion uses BufferedImage custom color/sample models. painting from the cpu-only image is slow, as it needs to be uploaded to the java gpu and then painted or painted by the cpu if no transfer happens automatically in java. opencl gpu to java transfer times are 1/4 of the java cpu to gpu paint times (2.5ms for 720p, 5ms for 1080p, 25ms for 4K transfer times).

yes trying to use opencl as headless render device.

any ideas or possibly optimizations/additions to the lwjgl opencl api interface functions?

**Comment by Spasi** [comment]
Hey @goofyseeker311,

Not really, the bindings are as low-level as they can be. There are no additional copies or other overhead introduced by LWJGL that would limit transfer performance.

However, there are plenty of ways to misuse the bindings and AWT/BufferedImage are notoriously difficult/impossible to use effectively in performance-sensitive applications. You won't get much help from generic descriptions like above, so please post some code. Maybe someone will be able to spot inefficiencies that are simple to fix.

Btw, github issues are not the best place to ask such questions or seek advice. You may want to join the LWJGL discord server, there are plenty of people there with relevant experience and you'll be able to discuss specific issues in more detail.

**Comment by goofyseeker311** [comment]
Imho think github is the better place. as also my code is here.

below code creates usually accelerated BufferedImage images, so as long as the image is at some point converted to accelerated form then it can be painted by gpu directly fast as gpu buffered image. so only the conversion to the java gpu form take time. also  thinking that the image conversion time is only 3x of the transfer time means that its also as fast as possible right now. also gpu compute time is neglible below 0.1ms always.
```
BufferedImage GraphicsConfiguration.createCompatibleImage(graphicswidth, graphicsheight, Transparency.TRANSLUCENT);
```

currently on the java BufferedImage side I'm doing it like below code.
```
private class RenderThread extends Thread {
private static boolean running = false;
public void run() {
	if ((!running)&&(program!=NULL)) {
		running = true;
		long frametimestart = System.nanoTime();
		computetime = computelib.runProgram(device, queue, program, "renderview", gfxbuffer, 0, graphicsbuffer.length, true);
		computetimeavg = computetimeavg*0.9f+computetime*0.1f;
		computelib.readBufferi(device, queue, gfxbuffer[0], graphicsbuffer);
		DataBufferInt readdatabuffer = new DataBufferInt(graphicsbuffer, graphicsbuffer.length);
		WritableRaster readraster = WritableRaster.createWritableRaster(readsamplemodel, readdatabuffer, null);
		BufferedImage readimage = new BufferedImage(readcolormodel, readraster, false, null);
		BufferedImage newimage = gc.createCompatibleImage(graphicswidth, graphicsheight, Transparency.TRANSLUCENT);
		Graphics2D newimage2d = newimage.createGraphics();
		newimage2d.setComposite(AlphaComposite.Src);
		newimage2d.drawImage(readimage, 0, 0, null);
		graphicsimage = newimage;
		long frametimeend = System.nanoTime();
		frametime = (frametimeend-frametimestart)/1000000.0f;
		frametimeavg = frametimeavg*0.9f+frametime*0.1f;
		running = false;
	}
}
```
readBufferi() function is like below code.
```
public void readBufferi(long device, long queue, long vmem, int[] v) {
        IntBuffer resultBuff = BufferUtils.createIntBuffer(v.length);
        CL12.clEnqueueReadBuffer(queue, vmem, true, 0, resultBuff, null, null);
        Arrays.fill(v, 0);
        CL12.clFinish(queue);
        resultBuff.rewind();
        resultBuff.get(0, v);
}
```

**Comment by goofyseeker311** [comment]
Some benchmark data: at 720p (2.5ms readBufferi() function time total usually):
IntBuffer creation: 0.6ms.
CL12.clEnqueueReadBuffer with clFinish(): 0.8ms.
resultBuff.get() stuff: 0.7ms.

**Comment by goofyseeker311** [comment]
This issue was solved by converting and rendering the opencl int[] image buffer with lwjgl opengl glfw window and glTexImage2D.
