### ISSUE TITLE
The most simplest opengl texture drawing will not work.

### ISSUE THREAD

**Issue by goofyseeker311** [LWJGL/lwjgl3#1015]
### Question

The opengl window shows up normally and otherwise its working. even the triangles are drawn with the color, but not with the texture data. graphicsbuffer is an int[] buffer with working int8888 data.

What would be the problem. also fbo's blitting did not seem to work either with same data. if its about the core profile missing functions then why does GL46 include any pointers to missing deprecated code.

```
while(!GLFW.glfwWindowShouldClose(window)) {
    GL46.glClear(GL46.GL_COLOR_BUFFER_BIT | GL46.GL_DEPTH_BUFFER_BIT);
    
    GL46.glColor3f(0.0f, 0.0f, 1.0f);
    GL46.glTexImage2D(GL46.GL_TEXTURE_2D, 0, GL46.GL_RGBA8, graphicswidth, graphicsheight, 0, GL46.GL_RGBA, GL46.GL_UNSIGNED_INT_8_8_8_8, graphicsbuffer);
    GL46.glBindTexture(GL46.GL_TEXTURE_2D, 0);
    
    GL46.glEnable(GL46.GL_TEXTURE_2D);
    
    GL46.glBegin(GL46.GL_TRIANGLE_STRIP);
    GL46.glTexCoord2f(1.0f, 0.0f); GL46.glVertex2f(1.0f, -1.0f);
    GL46.glTexCoord2f(1.0f, 1.0f); GL46.glVertex2f(1.0f, 1.0f);
    GL46.glTexCoord2f(0.0f, 0.0f); GL46.glVertex2f(-1.0f, -1.0f);
    GL46.glTexCoord2f(0.0f, 1.0f); GL46.glVertex2f(-1.0f, 1.0f);
    GL46.glEnd();
    GL46.glFlush();
    
    GLFW.glfwSwapBuffers(window);
    GLFW.glfwPollEvents();
}
```

**Comment by goofyseeker311** [comment]
Self-answer: if you change TEXTURE_2D to TEXTURE_RECTANGLE in both the TexImage2D() function and the glEnable() function, then it will work. but the TEXTURE_2D will not work.

**Comment by liskar-dev** [comment]
Please learn how to use modern OpenGL before creating issues. https://learnopengl.com/ should help you

**Comment by goofyseeker311** [comment]
issues and especially questions are just for questions eh.
