### ISSUE TITLE
screen tearing on full screen app on linux

### ISSUE THREAD

**Issue by goofyseeker311** [LWJGL/lwjgl3#1017]
### Question

on rtx 3080 on ubuntu 24.04 LTS linux with proper nvidia drivers has screen tearing when in full screen mode with lwjgl opengl glfw window. when in windowed mode there is no screen tearing. no screen tearing in windows in full screen or windowed mode.

using typical swapinterval(1). any ideas why this is happening?

(side note: if you put all the different platforms native lwjgl opengl jars in the .jar file, it will not run on linux, but will run on windows. ie you have to make a separate jar for at least the linux distribution of the app, to get it running.)

(side note: also gpu (opencl) fps is somehow locked to 62-63fps, even opencl cpu mode is not locked to 62fps.)

**Comment by goofyseeker311** [comment]
Also side question: hdr screen usage on lwjgl glfw opengl?

**Comment by Spasi** [comment]
Closing as offtopic. These questions have nothing to do with LWJGL itself.
