### ISSUE TITLE
3.3.4 reported as containing Trojan:Win32/Vigorf.A by Windows Defender

### ISSUE THREAD

**Issue by OndrejSpanel** [LWJGL/lwjgl3#1024]
### Question

This is what happened after SBT has downloaded lwjgl 3.3.4 from Maven:

![image](https://github.com/user-attachments/assets/35f9dba2-560c-45ce-bcc9-c078b2572716)

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Vigorf.A

I guess it is another false positive, but how can this be confirmed, and what can be done so that the product users are not hit by the issue, given I have no control over what Antivirus protection they use?

**Comment by OndrejSpanel** [comment]
I have ran a scan using one online tool, found nothing:

https://virusscan.jotti.org/en-US/filescanjob/07udjmoejk

**Comment by TheMrMilchmann** [comment]
This is a known issue. It is a false positive and there is, unfortunately, not much LWJGL can do about it. See https://github.com/LWJGL/lwjgl3/issues/1005 for further information.
