### ISSUE TITLE
GLFW Window not visible

### ISSUE THREAD

**Issue by ImplementsLegend** [LWJGL/lwjgl3#1028]
### Version

3.3.5 (snapshot), 3.3.4

### Platform

Linux x64

### JDK

AdoptOpenJDK 21

### Module

glfw

### Bug description

window does not show, but glfw thinks its created and visible
works fine on older versions of lwjgl

fedora kinoite 41
nvidia drivers 565.77

**Comment by Spasi** [comment]
Hey @ImplementsLegend,

Most likely explanation is that GLFW uses the Wayland backend, but LWJGL is trying to use GLX. See #748 for a simple workaround.

**Comment by ImplementsLegend** [comment]
that issue lists lwjgl 3.3.0 as affected, but that version works fine for me
suggested workaround also doesn't help me

lwjgl, opengl and everything else initializes fine, i just can't see the window

**Comment by ImplementsLegend** [comment]
that seems to have fixed the issue

**Comment by Spasi** [comment]
Which workaround did you try exactly with the original code? Try:

```java
Configuration.OPENGL_EXPLICIT_INIT.set(true);
GL.create(EGL.getFunctionProvider());
```

this needs to run before touching the OpenGL bindings (usually happens on `GL.createCapabilities`).  Also, try exporting `__GL_THREADED_OPTIMIZATIONS=0` before running your application. Are you sure there is no difference?

**Comment by ImplementsLegend** [comment]
this does nothing:
```
Configuration.OPENGL_EXPLICIT_INIT.set(true);
GL.create(EGL.getFunctionProvider());
```
these two help on their own:
`__GL_THREADED_OPTIMIZATIONS=0`
`glfwInitHint(GLFW_PLATFORM, GLFW_PLATFORM_X11);`

**Comment by Spasi** [comment]
The `glfwInitHint(GLFW_PLATFORM, GLFW_PLATFORM_X11);` call forces GLFW to use the X11 backend, so this is expected. What I'm interested in is the behavior **without** it, i.e. what happens when the Wayland backend is used instead.

So, could you please confirm that your application run correctly with only the following?

1. `export __GL_THREADED_OPTIMIZATIONS=0`
2. This code: 
 
```java
Configuration.OPENGL_EXPLICIT_INIT.set(true);
GL.create(EGL.getFunctionProvider());
```

I know that 2 looks like it doesn't do anything and 1 on its own fixes the issue, but it really is required.

**Comment by ImplementsLegend** [comment]
what i meant was that `export __GL_THREADED_OPTIMIZATIONS=0` also works, no matter whether i use `glfwInitHint(GLFW_PLATFORM, GLFW_PLATFORM_X11);` or `Configuration.OPENGL_EXPLICIT_INIT.set(true);GL.create(EGL.getFunctionProvider());` or both

unless i'm misunderstanding where to put `Configuration.OPENGL_EXPLICIT_INIT.set(true);GL.create(EGL.getFunctionProvider());`, it has no effect

**Comment by Spasi** [comment]
Hey @ImplementsLegend,

The latest build (`3.3.5-snapshot+4`) includes `Configuration.OPENGL_CONTEXT_API` and automatic Wayland detection, which should resolve this issue without extra code.

(`__GL_THREADED_OPTIMIZATIONS=0` is still required until the Nvidia driver is fixed)
