### ISSUE TITLE
Bindings for Wingdi.h and Linux/OS X alternatives

### ISSUE THREAD

**Issue by httpdigest** [LWJGL/lwjgl3#105]
Somehow I was under the impression that LWJGL3 already provides all functionality to create an OpenGL context with platform-specific API, but I think there are some pieces missing.
For example, the [functions](https://msdn.microsoft.com/en-us/library/windows/desktop/dd368826%28v=vs.85%29.aspx#see_also) and [structs](https://msdn.microsoft.com/en-us/library/windows/desktop/dd369059%28v=vs.85%29.aspx) of Wingdi.h (for Windows), such as the [ChoosePixelFormat](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318284%28v=vs.85%29.aspx) function and the [PIXELFORMATDESCRIPTOR](https://msdn.microsoft.com/en-us/library/windows/desktop/dd368826%28v=vs.85%29.aspx) struct.
I am trying to build a custom SWT GLCanvas, since SWT does not support creating OpenGL >= 3.0 contexts.
Can bindings to those be added please?

**Comment by Spasi** [comment]
These bindings were removed with d9c4a1b6f45f665ae2546c0b9c2326fa963e0267. We should re-introduce those that are needed for custom context management.

**Comment by httpdigest** [comment]
Absolutely! Or if you don't want to have it in core LWJGL3, then we can maybe also make a shared library / optional module out these?

**Comment by Spasi** [comment]
Having them in core is fine. Creating a context using a foreign window handle should be available out of the box.

**Comment by httpdigest** [comment]
Cool! When those functions are reintroduced, having full SWT support with GL 3.0 contexts is a walk in the park. Just augmenting SWT's GLCanvas to use the additional context attributes.

**Comment by Spasi** [comment]
Bindings for wingdi.h are in 3.0.0b build 51. I think you're good to go on Linux/OSX with the existing GLX/CGL bindings, but let me know if you need anything else.

**Comment by httpdigest** [comment]
Thank you for reintroducing it! So far only Wingdi GetDC and ReleaseDC is missing.

**Comment by httpdigest** [comment]
I used GetDC and ReleaseDC so far from SWT and now I have a problem that I think I did stumble on a year ago when creating a custom GL context. The problem is the chicken-egg-problem with LWJGL that I cannot use `wglCreateContext` unless I already have a context.
```
Exception in thread "main" java.lang.IllegalStateException: No GLCapabilities instance has been set for the current thread.
	at org.lwjgl.opengl.GL.getCapabilities(GL.java:214)
```
How would I go about solving this without using GLFW?

**Comment by httpdigest** [comment]
Sorry, I forgot that LWJGL3 even provides more lowlevel facilities to access native functions. I now resort to:
```
		DynamicLinkLibrary lib = new WindowsLibrary("opengl32.dll");
		long wglGetProcAddress = lib.getFunctionAddress("wglCreateContext");
		long context = callPP(wglGetProcAddress, hdc);
```
Works like a charme without needing to initialize full LWJGL3 context. :)

**Comment by Spasi** [comment]
Better solution:

```
WGL wgl = new WGL(GL.getFunctionProvider());
long context = callPP(wgl.CreateContext, hdc);
```

**Comment by httpdigest** [comment]
Nice! :D
That works really nice. Now it's tidying up and a new SWTGLCanvas is ready.

**Comment by Spasi** [comment]
Changes in 3.0.0b build 52:

- Added the `User32` class which provides `GetDC` and `ReleaseDC`.
- Renamed `WinGDI` to `GDI32`. I think it's cleaner to use the dll name, rather than the header in which the functions are defined (a single dll might export functions from multiple headers).

**Comment by httpdigest** [comment]
Thanks for the quick changes! I think we can close this issue now and track the progress of the new SWT GLCanvas somewhere else.
