### ISSUE TITLE
Custom cross-platform solution for GL context creation

### ISSUE THREAD

**Issue by httpdigest** [LWJGL/lwjgl3#106]
I am opening this ticket since I am about to create a revised SWT GLCanvas based on the old/current SWT-provided GLCanvas as a drop-in replacement with additional features such as specifying sample buffers and most importantly: using the platform-specific extensions to create a GL >= 3.0 (and GL>=3.2 core/compatibility) context.

However, instead of coding that capability into a SWT-specific Canvas class, I was thinking about providing a general solution for creating contexts. I know this existed in LWJGL2 and I will see how I can make use of that. Otherwise I will look at GLFW and of course at the platform vendor-provided documentation for best practices on how to create contexts.

The interface to that could be:
```Java
long createContext(long hwnd, ContextAttribs attribs);
boolean makeCurrent(long context, long hwnd);
boolean isCurrent(long context);
boolean destroyContext(long context);
```
I want to open this issue both for tracking progress and for discussions.

**Comment by malobre** [comment]
It would be super useful, I'm currently using the code below to create and use a context from an hidden 1x1 window.

````java
public static long context() {
    long context = GLFW.glfwGetCurrentContext();
    
    if(context == MemoryUtil.NULL) {
        glfwWindowHint(GLFW_VISIBLE, GL_FALSE);

        context = glfwCreateWindow(1, 1, "", 0l, MemoryUtil.NULL);

        if (context == MemoryUtil.NULL)
            throw new IllegalStateException("Hidden window creation failed");

        glfwMakeContextCurrent(context);

        GL.createCapabilities();
    }

    return context;
}
````

**Comment by malobre** [comment]
It would be super useful (background assets loading and all that stuff) however GLFW don't allow context creation without a window and the window creation function can only be called from the main thread.

**Comment by httpdigest** [comment]
Closing this since this is not possible in a cross-platform/cross-windowtoolkit way.
Every solution is necessarily tailored to the window toolkit being used (win32, gtk, cocoa), since each needs different information and must intertwine window-system-specific calls in-between context creation.

**Comment by Spasi** [comment]
The platform-specific bindings for this currently live in the [offscreen-context](https://github.com/LWJGL/lwjgl3/commit/9a986327287d5e3e3fd41c3b072d617d3177d86e) branch. It is not complete (mostly what I needed for the JavaFX lwjgl3 backend) and I haven't worked on it for some time, got distracted by the 3.0.0b release.

**Comment by httpdigest** [comment]
Cool, thanks, CreateWindow back again! :) Now I can revive my begun Direct3D 11 bindings.
Would be cool if we could figure out a way to auto-parse those C++ header files and generate pleasing mappings without generic Pointer\<Pointer\<Pointer\<Byte>>> things. :)
Maybe I am having a look at clang's parser API, like you mentioned once.
But damn, I want a Direct3D binding! :)
It's not about losing cross-platformness - it's about gaining guaranteed driver compatibility across all GPU vendors. :)
