### ISSUE TITLE
memRealloc reset buffer position

### ISSUE THREAD

**Issue by malobre** [LWJGL/lwjgl3#108]
`memRealloc(buffer, size)` return a buffer with 0 for position.
Maybe the position of the buffer passed as first arg should be kept as it's more convenient.

Example:

````java
InputStream inputStream = ... // An inputStream
ByteBuffer buf = memAlloc(64 * 1024);
try(ReadableByteChannel rbc = Channels.newChannel(inputStream)) {
    while(rbc.read(buf) != -1) {
        if(buf.remaining() == 0) {
            int pos = ttf.position();
            buf = memRealloc(buf, buf.capacity() * 2);
            buf.position(pos);
        }
    }
} catch (IOException e) {...}
````
would become:
````java
InputStream inputStream = ... // An inputStream
ByteBuffer buf = memAlloc(64 * 1024);
try(ReadableByteChannel rbc = Channels.newChannel(inputStream)) {
    while(rbc.read(buf) != -1) {
        if(buf.remaining() == 0) {
            buf = memRealloc(buf, buf.capacity() * 2);
        }
    }
} catch (IOException e) {...}
````

**Comment by httpdigest** [comment]
I am also in favor of not resetting the Buffer's position.
Realloc is usually used in situations where one does not know the required size of a buffer when filling it and therefore need to dynamically grow the buffer as it reaches its capacity, like the example with the InputStream shows. And one generally wants to resume filling the buffer at the last position after reallocating it.

**Comment by Spasi** [comment]
This is useful indeed. Thanks!
