### ISSUE TITLE
Cannot use OpenCL

### ISSUE THREAD

**Issue by httpdigest** [LWJGL/lwjgl3#109]
When not doing `CL.create()` as first invocation, but trying to enumerate the devices, I get:
```
Exception in thread "main" java.lang.NullPointerException
	at org.lwjgl.system.Checks.checkPointer(Checks.java:80)
	at org.lwjgl.opencl.CL10.nclGetDeviceIDs(CL10.java:625)
	at org.lwjgl.opencl.CL10.clGetDeviceIDs(CL10.java:664)
```
and when calling `CL.create()` as the very first action in the program, I get:
```
Exception in thread "main" java.lang.IllegalStateException: OpenCL has already been created.
	at org.lwjgl.opencl.CL.create(CL.java:164)
	at org.lwjgl.opencl.CL.create(CL.java:150)
	at org.lwjgl.opencl.CL.create(CL.java:37)
```

My code is just this:
```Java
CL.create(); // <- crashes here
PointerBuffer pb = BufferUtils.createPointerBuffer(4);
IntBuffer num = BufferUtils.createIntBuffer(1);
int ret = CL10.clGetDeviceIDs(0L, CL10.CL_DEVICE_TYPE_GPU, pb, num); // <- if no CL.create() then crashes here
```
I was just following [this hello world example](https://developer.apple.com/library/mac/samplecode/OpenCL_Hello_World_Example/Listings/hello_c.html).

I am actually wondering why the tests in CLTest.java in LWJGL3 work, because they also seem to do `CL.create()` as first step and `ant tests` works just fine.

**Comment by httpdigest** [comment]
Aha, I could get away with the "penCL has already been created." exception by specifying:
```Java
Configuration.EXPLICIT_INIT_OPENCL.set(true);
```
And that `Checks.checkPointer` check is actually for the first parameter `platform` of `clGetDeviceIDs`, which is allowed to be `NULL` as per:
https://www.khronos.org/registry/cl/sdk/1.0/docs/man/xhtml/clGetDeviceIDs.html

Could this check be disabled?

**Comment by Spasi** [comment]
Removed the check because the spec allows it, but I wouldn't recommend using a `NULL` platform. Especially if the same code runs on Windows/Linux.

**Comment by httpdigest** [comment]
Thanks! Yes, I won't. Nvidia returns -32 (CL_INVALID_PLATFORM) with NULL platform.
