### ISSUE TITLE
Multiple calls to glfwMakeContextCurrent on Linux crash

### ISSUE THREAD

**Issue by piotr-piastucki** [LWJGL/lwjgl3#116]
Hi,
If I modify the Threads demo (https://raw.githubusercontent.com/LWJGL/lwjgl3/master/modules/core/src/test/java/org/lwjgl/demo/glfw/Threads.java) so that 
glfwMakeContextCurrent(window);
is added right after
glfwShowWindow(window);
the demo crashes with:
Exception in thread "Thread-0" java.lang.NullPointerException
	at org.lwjgl.system.Checks.checkPointer(Checks.java:100)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:273)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:225)
under Linux (Ubuntu, Nvidia proprietary drivers)
It seems to work OK on a Mac.
I thought it should be possible to pass the ownership of the OpenGL context between threads, but maybe I am missing something.

**Comment by httpdigest** [comment]
Yes, it is possible to pass the ownership of an OpenGL context between threads. However, you must detach the OpenGL context from a thread before making it current in another thread.
Read the documentation of GLFW's [glfwMakeContextCurrent](http://www.glfw.org/docs/latest/group__context.html#ga1c04dc242268f827290fe40aa1c91157).
So before making the context current in thread B you first have to call `glfwMakeContextCurrent(0L)` in thread A.

**Comment by piotr-piastucki** [comment]
Thank you very much for the info. I have read the documentation but it is not obvious you must detach the context first.
