### ISSUE TITLE
Update OpenAL

### ISSUE THREAD

**Issue by wyozi** [LWJGL/lwjgl3#122]
It'd be especially nice to get access to SOFT_HRTF extension (http://kcat.strangesoft.net/openal-extensions/SOFT_HRTF.txt)

**Comment by Spasi** [comment]
Hey @wyozi, there have been several improvements to OpenAL after the beta release, you can download a nightly build to try it out. OpenAL Soft has been updated to 1.17.1 and all extensions are now supported, including SOFT_HRTF.
