### ISSUE TITLE
Black screen + freeze on fullscreen

### ISSUE THREAD

**Issue by gitluke2006** [LWJGL/lwjgl3#126]
Hi,

Having some issues getting a fullscreen window working; when the program runs, the screen goes black, I can't offer any input (CTRL+ALT+DELETE, ESC, WINDOWS+D, etc etc), and I'm forced to do a hard shutdown (with the power button). My code works when I don't specify a monitor when creating a window with dimensions not equal to my full screen dimensions.

The following code recreates the issue:
``` java
import org.lwjgl.glfw.GLFW;
import org.lwjgl.system.MemoryUtil;
public class Game {
    public static void main(String args[]) {
        GLFW.glfwInit();
        long monitor = GLFW.glfwGetPrimaryMonitor();
        long window = GLFW.glfwCreateWindow(640, 480, "Game", monitor, MemoryUtil.NULL);
        GLFW.glfwDestroyWindow(window);
        GLFW.glfwTerminate();
    }
}
```

Java version (from java[c] -version): jre 1.8.0_60, jdk 1.8.0_51
LWJGL version: tried with current downloads for Release (3.0.0b build 64) and Nightly (3.0.0 build 8)
GL version (from GL11.glGetString(GL11.GL_VERSION)): 3.3.0 - Build 8.15.10.2696
GLFW version (from src\org\lwjgl\glfw\GLFW.java): 3.2.0
Windows version: Win 7 Home Premium

Any more information required?
Cheers,
Luke

**Comment by SilverTiger** [comment]
Have you tried creating a key callback?
In the simplest example you should be able to close the windows with `ESC`:

``` java
GLFWKeyCallback keyCallback = new GLFWKeyCallback() {
    @Override
    public void invoke(long window, int key, int scancode, int action, int mods) {
        if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS) {
            glfwSetWindowShouldClose(window, GLFW_TRUE);
        }
    }
};
```

Note that you should have a strong reference to that callback, e.g. store it as field of your class.
After creating the window you should call `glfwSetKeyCallback(window, keyCallback);` to register it to the window.

**Comment by gitluke2006** [comment]
Thanks for the response!

I just tried adding a callback; same problem. I also tried using the static imports on the off chance that was making a difference; all the examples I see do that. Problem persists. I believe it's hanging somewhere in the glfwCreateWindow() function; otherwise it would hit the close and terminate statements... Here's the new offending code:

import org.lwjgl.*;
import org.lwjgl.glfw.*;
import org.lwjgl.opengl.*;
import static org.lwjgl.glfw.GLFW.*;
import static org.lwjgl.opengl.GL11.*;
import static org.lwjgl.system.MemoryUtil.*;
public class Game {
    public static void main(String args[]) {
        glfwInit();
        long monitor = glfwGetPrimaryMonitor();
        GLFWKeyCallback keyCallback = new GLFWKeyCallback() {
            @Override
            public void invoke(long window, int key, int scancode, int action, int mods) {
                if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS)
                    glfwSetWindowShouldClose(window, GLFW_TRUE);
            }
        };
        long window = glfwCreateWindow(640, 480, "Game", monitor, NULL);
        glfwSetKeyCallback(window, keyCallback); 
        glfwDestroyWindow(window);
        glfwTerminate();
    }
}

Files:
+ Test
|--+ bin
|  |--- Game$1.class
|  |--- Game.class
|--+ lib
|  |--- lwjgl.jar
|  |--- all dlls
|--+ src
   |--- Game.java

Compilation command:
> javac -cp src;lib\lwjgl.jar -d bin src\*

Run command:
> java -Djava.library.path=lib -cp bin;lib\lwjgl.jar Game

If there's anything else I can do to assist diagnosis, let me know!
Cheers,
Luke

**Comment by Spasi** [comment]
Try calling `glfwCreateWindow` without specifying the monitor (pass `NULL` instead). The monitor is required only for fullscreen mode.

**Comment by gitluke2006** [comment]
That works, and it's what I'm doing so I can continue development, but I want full screen mode!

**Comment by httpdigest** [comment]
You could have fullscreen mode without display mode change in GLFW with using the `GLFW_DECORATED` = `GLFW_FALSE` window hint and using the resolution of the desktop display mode, like so:
```Java
glfwWindowHint(GLFW_DECORATED, GLFW_FALSE);
GLFWVidMode vidMode = glfwGetVideoMode(glfwGetPrimaryMonitor());
window = glfwCreateWindow(vidMode.width(), vidMode.height(), "Desktop fullscreen", NULL, NULL);
glfwSetWindowPos(window, 0, 0);
```

**Comment by gitluke2006** [comment]
Apologies, haven't been at my computer this week. Tried the previous suggestion; still no bueno :( I'll try running on another machine, though I suspect that'll work given you've all been unable to reproduce the issue.

**Comment by httpdigest** [comment]
Can you try the following with the latest LWJGL3 build? It should show a fullscreen window (at the desktop resolution) with some blueish color and with a crosshair cursor. It should also react on the ESC button by closing itself.
```Java
import static org.lwjgl.system.windows.WinBase.*;
import org.lwjgl.system.windows.MSG;
import org.lwjgl.system.windows.WNDCLASSEX;
import org.lwjgl.system.windows.WindowProc;
import static org.lwjgl.system.windows.User32.*;

public class DesktopFullscreenWindow extends WindowProc {
    void run() {
        long hInstance = GetModuleHandle((String) null);
        WNDCLASSEX wcex = WNDCLASSEX.calloc();
        wcex.cbSize(WNDCLASSEX.SIZEOF);
        wcex.style(CS_HREDRAW | CS_VREDRAW);
        wcex.lpfnWndProc(this);
        wcex.hInstance(hInstance);
        wcex.hbrBackground(3);
        wcex.hCursor(nLoadCursor(0L, IDC_CROSS));
        wcex.lpszClassName("MyLwjgl3WindowClass");
        if (RegisterClassEx(wcex) == 0)
            throw new AssertionError("Could not register window class");
        int width = GetSystemMetrics(SM_CXSCREEN);
        int height = GetSystemMetrics(SM_CYSCREEN);
        long hWnd = CreateWindowEx(WS_EX_APPWINDOW, "MyLwjgl3WindowClass", "Test window",
                WS_VISIBLE | WS_POPUP, 0, 0, width, height, 0L, 0L, hInstance, 0L);
        if (hWnd == 0L)
            throw new AssertionError("Could not create window");
        MSG msg = MSG.calloc();
        while (true) {
            while (PeekMessage(msg, hWnd, 0, 0, PM_REMOVE) == 1) {
                TranslateMessage(msg);
                DispatchMessage(msg);
            }
            if(msg.message() == WM_QUIT)
                break;
        }
    }
    public static void main(String[] args) {
        new DesktopFullscreenWindow().run();
    }
    public long invoke(long hWnd, int msg, long wParam, long lParam) {
        if (msg == WM_KEYDOWN && wParam == VK_ESCAPE)
            System.exit(0);
        return DefWindowProc(hWnd, msg, wParam, lParam);
    }
}
```

**Comment by gitluke2006** [comment]
Thanks for your continued help! I have (hopefully) good news; I ran the above code (with the latest night build), and got a full screen window with a bluish color and cross hair that exited on escape!! What does that tell us?

Note that reattempting full screen through GLFW with the new jar and natives still caused the black screen.

**Comment by httpdigest** [comment]
That tells us that basic windowing works, since GLFW does that too in the same way (or maybe slightly different). However that also tells us that OpenGL context creation might be buggy.

**Comment by gitluke2006** [comment]
Okay! How can I get you more information? :)

**Comment by httpdigest** [comment]
What I'd do in your place is first to debug the program in Java. Step over each method invocation in your own class and see where it hangs. (unless the fullscreen window makes Windows unresponsive and not able to get back to the IDE, that is).
If that does not get you anywhere, you could use "Visual Studio 2015 Community Edition" and actually debug the native code of GLFW and see where that hangs. To do that you also need "cmake" to build GLFW locally with debugging information/symbols. Building GLFW yourself is really easy. It has documentation on how to do that with cmake.

**Comment by Spasi** [comment]
Before going through all that, I'd try another OpenGL application to discard any driver issues.

**Comment by httpdigest** [comment]
Yepp, that's better. :) Like some GLUT application. The sources for fullscreen demo GLU programs are out there in C. I could build some small executable for you.

**Comment by gitluke2006** [comment]
Thanks, all! :)

Okay, so I ran that .exe and saw the exact same symptoms as described above; screen went black and locked up. Note that I'm running Win 7 64 bit, though; is that likely to make a difference?

Also, I'm not sure if this is remotely correct, but I downloaded a whole lot of GL/GLUT .h, .dll and .lib files, chucked them in a single folder, put together a .cpp script using GLUT to create a fullscreen window, and that worked. I'm not working with Visual Studio or Cygwin or anything; I've just got some Microsoft c++ build tools. So maybe (is this possible?) the opengl lib on my system is broken or something?

**Comment by httpdigest** [comment]
That's what I wanted to test with the 32-bit version. Whether your SysWOW64 DLLs also cause this problem. Apparently, they do. :(
Then the bitness will not make a difference, because it both happens with 32-bit and your 64-bit JRE with LWJGL3. Well, try to reinstall or upgrade the graphics driver.

**Comment by gitluke2006** [comment]
Interesting. I downloaded some new drivers for a Radeon HD 7700M (also have an Intel HD Graphics 4000), restarted, and then ran that .exe you (httpdigest) sent earlier. And it worked!

But then I attempted to run my game and the JVM crashed when creating a window. Tried it with both the nightly and release versions of LWJGL. Hopefully I didn't do something stupid in setup, can't remember the full process - pretty much, I just copy all the .dll files from lwjgl\natives and the .jar from lwjgl\jar to my project's lib folder, compile, and run. The crash spits out the attached log file (previously with a .log extension, which I've changed).
[hs_err_pid5872.txt](https://github.com/LWJGL/lwjgl3/files/95285/hs_err_pid5872.txt)

**Comment by Spasi** [comment]
Hey @gitluke2006, could you please try again with the latest nightly build?

**Comment by gitluke2006** [comment]
Hi,
Thanks for revisiting this Spasi. I think it's best to just close the bug. It's almost certainly not the fault of LWJGL, given that I have other games that crash on full screen (e.g. tried to play Batman Arkham Asylum yesterday in FS). Just something wrong with my machine somewhere.
Cheers,
Luke
