### ISSUE TITLE
Please add additional User32 functions

### ISSUE THREAD

**Issue by httpdigest** [LWJGL/lwjgl3#128]
Please add the following User32 functions:

User32.AdjustWindowRect
User32.DispatchMessage
User32.GetMessage
User32.GetWindowLongPtr
User32.GetWindowRect
User32.MoveWindow
User32.PeekMessage
User32.ShowWindow
User32.SetWindowLongPtr
User32.SetWindowPos
User32.UpdateWindow

I need those for reviving my old Direct3D Window class with LWJGL 3.

**Comment by httpdigest** [comment]
That was quick. Awesome work! Thanks.

**Comment by httpdigest** [comment]
Erm... now it always complains whatever I do with User32 that `SetWindowText` is unavailable.

**Comment by httpdigest** [comment]
When I append a 'W' suffix to all failing lookups, it works. I had to change the following function names to make it work (append 'W' suffic):
```
SetWindowTextW
GetMessageW
PeekMessageW
DispatchMessageW
SetWindowLongPtrW
GetWindowLongPtrW
SetClassLongPtrW
GetClassLongPtrW
```

**Comment by Spasi** [comment]
Thanks, fixed in d746f9e5c6f73c099f391ebc9322639246aff576.

**Comment by httpdigest** [comment]
Now only two more and then I have everything that I had with a past LWJGL3 beta/alpha release for the D3D11 binding window creation:
- [User32.LoadIcon](https://msdn.microsoft.com/en-us/library/windows/desktop/ms648072(v=vs.85).aspx)
- [User32.LoadCursor](https://msdn.microsoft.com/en-us/library/windows/desktop/ms648391(v=vs.85).aspx)

**Comment by Spasi** [comment]
Added with 0bfe8f32c48ffaea72d0c8e04c5bc9e54c4dc68b.
