### ISSUE TITLE
Win32 API: Change display mode

### ISSUE THREAD

**Issue by httpdigest** [LWJGL/lwjgl3#130]
In order for an SWT (or any other non-AWT based) application to change the display mode (resolution, refresh rate) and not always use the desktop display mode, I'd like to have support for the following:

- [User32.ChangeDisplaySettings()](https://msdn.microsoft.com/en-us/library/windows/desktop/dd183411(v=vs.85).aspx) or probably [ChangeDisplaySettingsEx()](https://msdn.microsoft.com/en-us/library/windows/desktop/dd183413(v=vs.85).aspx)
- [User32.EnumDisplayDevices()](https://msdn.microsoft.com/en-us/library/windows/desktop/dd162609(v=vs.85).aspx)
- [User32.EnumDisplaySettings()](https://msdn.microsoft.com/en-us/library/windows/desktop/dd162611(v=vs.85).aspx)
- [Wingdi.h::DEVMODE struct](https://msdn.microsoft.com/en-us/library/windows/desktop/dd183565(v=vs.85).aspx)

This would allow to write a real fullscreen game with SWT.

**Comment by httpdigest** [comment]
According to this: http://stackoverflow.com/questions/2382464/win32-full-screen-and-hiding-taskbar
a proper fullscreen solution might also need:
- User32.SendMessage()
- User32.GetMonitorInfo()
- User32.MonitorFromWindow()
- User32.GetWindowPlacement()
- User32.SetWindowPlacement()

**Comment by httpdigest** [comment]
Thanks alot for adding this so quick, again!

However, I cannot set any fields on the MONITORINFOEX struct. I need to set at least the cbSize field, but there is no setter for it anymore, only an instance and a static getter.

**Comment by httpdigest** [comment]
Ah, it seems to be because of that "mutable = false" on the struct definition in the kotlin template.
That is good, and can stay this way, if we could automatically let LWJGL compute and set the cbSize, which is present in many structs that can be "overwritten".
But since LWJGL would probably provide each such overwrite/subtype as a separate struct definition, it can also calculate and set the cbSize field on instantiation of that struct.

**Comment by Spasi** [comment]
Added support for partially mutable structs with 2cbfb0c00cabcdeeab44b6e287adcbd9792ce961.

**Comment by httpdigest** [comment]
Cool. Next problem is `ChangeDisplaySettingsEx`. Its first parameter `LPCTSTR lpszDeviceName` allows null, but LWJGL crashes with a null ByteBuffer.

**Comment by Spasi** [comment]
Fixed with f4a44205a5ad796313c5838bc001fac639a2f6a9.

**Comment by httpdigest** [comment]
Also I think the CharSequence overload is a bit dangerous. When invoked with null the `__buffer.stringParamUTF16(lpszDeviceName, true)` will return -1 and then the address is `__buffer.address(-1)` o.O

**Comment by httpdigest** [comment]
Ah, sorry, it was fixed with your last commit also.

**Comment by Spasi** [comment]
> Also I think the CharSequence overload is a bit dangerous. 

Indeed, the stringParam methods weren't robust for non-nullable parameters, fixed with e387ad0abdc9d6e7d9a56370be9e407d27680170.

**Comment by httpdigest** [comment]
Okay, everything working great so far. Fullscreen SWT application at 640x480 :)
