### ISSUE TITLE
LWJGL 3.0.0 SNAPSHOT broken - Freeze / natives broken

### ISSUE THREAD

**Issue by JuKu** [LWJGL/lwjgl3#131]
Hi,

We use 3.0.0 SNAPSHOT Build, because it integrats nanovg and one of our developer needs this feature.
Since yesterday, our application doesnt work anymore.
I have added some logger outputs to enclose the problem.
The application thread freezes or doesnt do anymore after the GLFW.glfwInit() call.

Code example:
```java
Logger.getRootLogger().debug("GLFWContextMaster: try to initialize glfw context master.");

if(GLFW.glfwInit() == GL11.GL_FALSE)
{
	throw new IllegalStateException("Initialization of glfw failed.");
}

Logger.getRootLogger().debug("create glfw error callbacks.");
```

The first logger output is be shown, the second isnt shown.

**Comment by Spasi** [comment]
Is there any output from the GLFW error callback? Note that `glfwSetErrorCallback` is one of the few GLFW functions that can be called before `glfwInit`.

**Comment by Spasi** [comment]
Also, please post some information about your OS and JVM. You should get the relevant information if you run the JVM with `-Dorg.lwjgl.util.Debug=true` (or call `Configuration.DEBUG.set(true)`).

**Comment by JuKu** [comment]
Hi,

I have changed the code to following:
```java

if (DeveloperOptions.isRendererLogActivated()) {
    Logger.getRootLogger().debug("create glfw error callbacks.");
}

//create error callback
errorCallback = GLFWErrorCallback.create((int error, long description) -> {
    Logger.getRootLogger().error("OpenGL Error: " + error + ", description: " + description + ".");
    GLFWContextMaster.this.invoke(error, description);
});
monitorCallback = GLFWMonitorCallback.create(this);

if (DeveloperOptions.isRendererLogActivated()) {
    Logger.getRootLogger().debug("set glfw error callbacks.");
}

//set error callback
GLFW.glfwSetErrorCallback(errorCallback);
GLFW.glfwSetMonitorCallback(monitorCallback);

if (DeveloperOptions.isRendererLogActivated()) {
    Logger.getRootLogger().debug("GLFWContextMaster: try to initialize glfw context master.");
}

if(GLFW.glfwInit() == GL11.GL_FALSE)
{
    throw new IllegalStateException("Initialization of glfw failed.");
}

if (DeveloperOptions.isRendererLogActivated()) {
    Logger.getRootLogger().debug("set glfw swap interval to 1.");
}

GLFW.glfwSwapInterval(1);

```

The LWJGL Debugger Output shows the following:
```
[LWJGL] Version: 3.0.0 build 13
[LWJGL] 	 OS: Windows 7 v6.1
[LWJGL] 	JRE: 1.8.0_65 amd64
[LWJGL] 	JVM: Java HotSpot(TM) 64-Bit Server VM v25.65-b01 by Oracle Corporation
```

**Comment by httpdigest** [comment]
Erm... I get the exact same error too, now with the latest Maven Central deployed 3.0.0 version.
Everything was working fine until a minute ago because I was using self-build lwjgl3. Now that I use the Maven Central-provided version, no applications work anymore. :(
Right the first GLFW call to glfwSetErrorCallback freezes the process for about three seconds and then crashes the JVM without it producing a hserrlog. Very strange.

**Comment by httpdigest** [comment]
Okay, the process dies away while trying to load the native library "lwjgl".
I put a breakpoint at System.loadLibrary.
This is the stacktrace from the debugger while being trapped at System.loadLibrary before the crash. When I step over there the process crashes:
```
Thread [main] (Suspended (entry into method loadLibrary in System))	
	System.loadLibrary(String) line: 1028	
	Library.loadSystem(String) line: 97	
	Library.<clinit>() line: 48	
	MemoryUtil.<clinit>() line: 56	
	Closure.<clinit>() line: 57	
```

**Comment by Spasi** [comment]
Thanks, reproduced. It's UPX that creates the problem. The x86 dll works fine, but the x64 one fails to initialize.

**Comment by httpdigest** [comment]
Okay. I upx'ed my VS2013 build with `upx -9` too, that however still loads fine.

**Comment by Spasi** [comment]
Could you try the new nightly please? (build 14)

**Comment by httpdigest** [comment]
Build 14 works:
```
[LWJGL] Version: 3.0.0 build 14
[LWJGL] 	 OS: Windows 7 v6.1
[LWJGL] 	JRE: 1.6.0_45 amd64
[LWJGL] 	JVM: Java HotSpot(TM) 64-Bit Server VM v20.45-b01 by Sun Microsystems Inc.
[LWJGL] Loaded library from java.library.path: lwjgl
[LWJGL] MemoryUtil accessor: MemoryAccessorUnsafe
[LWJGL] Loaded native library: D:\workspace-neon-M4\lwjgl-libs\lib\jemalloc.dll
[LWJGL] MemoryUtil allocator: JEmallocAllocator
[LWJGL] Loaded native library: D:\workspace-neon-M4\lwjgl-libs\lib\glfw.dll
[LWJGL] Loaded native library: opengl32.dll
...
```

**Comment by JuKu** [comment]
Build 14 works also fine for me.
Thanks!

But there is some new logger output:
```
[LWJGL] Failed to locate address for GL function glVertexArrayVertexAttribDivisorEXT
```

Here is also some logger output, which doesnt do some affects:
```
[LWJGL] Version: 3.0.0 build 13
[LWJGL] 	 OS: Windows 7 v6.1
[LWJGL] 	JRE: 1.8.0_65 amd64
[LWJGL] 	JVM: Java HotSpot(TM) 64-Bit Server VM v25.65-b01 by Oracle Corporation
[LWJGL] Loaded library from org.lwjgl.librarypath: lwjgl
[LWJGL] MemoryUtil accessor: MemoryAccessorUnsafe
[LWJGL] Loaded native library: <Path>/jemalloc.dll
[LWJGL] MemoryUtil allocator: JEmallocAllocator
[LWJGL] Loaded native library: <Path>/glfw.dll
GLFW Error: The GLFW library is not initialized
574 [ui-thread] ERROR root  - OpenGL Error: 65537, description: 8791501830200.
GLFW Error: There is no current context
596 [ui-thread] ERROR root  - OpenGL Error: 65538, description: 8791501830240.
596 [ui-thread] DEBUG root  - initRenderer() Thread: ui-thread
603 [ui-thread] DEBUG root  - create GLFWContext in Thread ui-thread.
[LWJGL] Loaded native library: opengl32.dll
[LWJGL] Failed to locate address for GL function glVertexArrayVertexAttribDivisorEXT
```

**Comment by httpdigest** [comment]
> GLFW Error: The GLFW library is not initialized

You did not call `org.lwjgl.glfw.GLFW.glfwInit()`.

**Comment by Spasi** [comment]
> GLFW Error: The GLFW library is not initialized

Move `glfwSetMonitorCallback` after `glfwInit`

> GLFW Error: There is no current context

`glfwSwapInterval` requires a current context. You should first create a window and make its context current with `glfwMakeContextCurrent`.

> Failed to locate address for GL function glVertexArrayVertexAttribDivisorEXT

This is a function that was added to the ARB_instanced_arrays extension at a later time. It is not supported by all drivers (AMD iirc), so it's been made optional in LWJGL. This is from the extension spec:

> 7) How should EXT_direct_state_access interact with this extension?
>
>        Resolved:  Add glVertexArrayVertexAttribDivisorEXT selector-free
>        vertex array object command and glGetVertexArrayIntegeri_vEXT
>        query must accept VERTEX_ATTRIB_ARRAY_DIVISOR_ARB to return the
>        vertex array object's vertex attrib array divisor state.
>
>        The DSA interaction was added July 2013.  If implementations
>        respond to a wglGetProcAddress, etc. query for
>        "glVertexArrayVertexAttribDivisorEXT" with a NULL pointer,
>        the DSA functionality is not available.

The message you see is a simple warning in debug mode and can be ignored.
