### ISSUE TITLE
Closure names hide Number classes

### ISSUE THREAD

**Issue by kenzierocks** [LWJGL/lwjgl3#133]
If you extend any `Closure`, you end up needing to stick `java.lang.X` in front of `Void`, `Long`, `Integer`, etc. because those are defined as classes in `Closure`. Could different names be chosen so that there is no clash?

**Comment by Spasi** [comment]
I've renamed the Closure subclasses, they now use the corresponding JNI type signature. This is basically the first character of the previous names, except Boolean (Z) and Long (J).

May I ask why you're trying to extend Closure.X? Directly that is, not through one of their subclasses. The current code assumes that shouldn't ever need to do that. Using libffi directly may be more appropriate if customization is required.

**Comment by httpdigest** [comment]
I think @kenzierocks wasn't extending the inner classes of Closure, but subclasses of Closure themselves, such as `GLFWFramebufferSizeCallback`, which is very common, like so:
```Java
glfwSetFramebufferSizeCallback(window, fbCallback = new GLFWFramebufferSizeCallback() {
    Float notYourJavaFloat;
	public void invoke(long window, int width, int height) {
	    // Do something with notYourJavaFloat
	    notYourJavaFloat += 0.2f; // <- why?! Oh, not actually java.lang.Float
	}
});
```

**Comment by Spasi** [comment]
Right, the super type is in scope implicitly. Thanks.
