### ISSUE TITLE
Missing ARBVertexBufferObject.glBufferSubDataARB with Float-/Short-/DoubleBuffer

### ISSUE THREAD

**Issue by httpdigest** [LWJGL/lwjgl3#134]
The glBufferDataARB supports those typed buffers, just not the glBufferSubDataARB.
In GL15 however, everything is fine.

It seems the `data` parameter is lacking that `MultiType` thingy:
```
MultiType(
	PointerMapping.DATA_SHORT,
	PointerMapping.DATA_INT,
	PointerMapping.DATA_FLOAT,
	PointerMapping.DATA_DOUBLE
)
```

**Comment by Spasi** [comment]
Thanks!
