### ISSUE TITLE
STL demos not working

### ISSUE THREAD

**Issue by thomasfurst99** [LWJGL/lwjgl3#135]
When I tried to compile demos of STL bindings with LWJGL 3 it's not working and even the source looks a bit with errors

**Comment by httpdigest** [comment]
In the root directory of your checkout lwjgl3 sources do this on the command line: `ant compile-templates generate`
If that says that the command "ant" was spelled wrongly or could not be found, download [ant](http://ant.apache.org/bindownload.cgi), have it in your PATH and execute above command again.
Your IDE will also be able to execute ant buildscripts, but how to do that depends on the specific IDE.
