### ISSUE TITLE
Inconsistent documentation in GLFWWindowSizeCallback

### ISSUE THREAD

**Issue by scholza** [LWJGL/lwjgl3#136]
The javadoc of glfwSetWindowSizeCallback() specifies that the reported window size is in screen coordinates - what is in line with the documentation of glfw

The javadoc of GLFWWindowSizeCallback#invoke() specifies that the size is in pixels - what is inconsistent

I assume glfwSetWindowSizeCallback() is correct (unless there is some conversion going on in the native side?)

**Comment by Spasi** [comment]
Thanks!
