### ISSUE TITLE
Add @Deprecated Annotation for Deprecated GL Functions

### ISSUE THREAD

**Issue by sci4me** [LWJGL/lwjgl3#137]
A "@Deprecated" annotation should be added to the JavaDoc of all deprecated GL functions.
This would allow the Java compiler to warn users when they are using a deprecated GL function.

**Comment by intrigus** [comment]
Search for similar issues before creating a new: https://github.com/LWJGL/lwjgl3/issues/119

**Comment by sci4me** [comment]
Sorry and thanks.
