### ISSUE TITLE
STBTTPackRange appears to be immutable

### ISSUE THREAD

**Issue by kenzierocks** [LWJGL/lwjgl3#139]
I'm not really sure how I'm supposed to go about creating some `STBTTPackRange` for use in `stbtt_PackFontRanges`, is there some big thing I'm missing or was the use of `STBTTPackRange` misinterpreted to be a return value when it is actually an input value?

**Comment by Spasi** [comment]
It must be mutable indeed. Thanks!

**Comment by kenzierocks** [comment]
Do you know when a new nightly will go out with the fix?

**Comment by Spasi** [comment]
It should be up now.

**Comment by kenzierocks** [comment]
Yep, thanks!
