### ISSUE TITLE
OpenAL bug

### ISSUE THREAD

**Issue by germangb** [LWJGL/lwjgl3#141]
There's a problem with openal-soft in linux as discussed in [this issue](https://github.com/kcat/openal-soft/issues/26). It's fixed in the LWJGL Nightly releases

Also posted this on the [forum](http://forum.lwjgl.org/index.php?topic=6107.0)

**Comment by sriharshachilakapati** [comment]
This is not a valid issue, as all it does is refer to another issue and says that it is resolved in nightlies. I think this should be closed.

@germangb Please do not create an issue to say that it is resolved. GitHub issues are used to track on real existing issues, and creating an issue which is not valid is not just good.
