### ISSUE TITLE
Error when initializing/terminating GLFW multiple times.

### ISSUE THREAD

**Issue by ShchAlexander** [LWJGL/lwjgl3#143]
On last version of lwjgl (from [snapshot](https://oss.sonatype.org/content/repositories/snapshots/) server) when I trying to initialize glfw every second launch throws **GLFW_PLATFORM_ERROR: Win32: Failed to register window class**

 ```java

import org.lwjgl.glfw.GLFW;
import org.lwjgl.glfw.GLFWErrorCallback;

public class TestGLFW {
    public static void main(String[] args) throws InterruptedException {
        run();
        run(); // throws error
        run();
        run(); // throws error
        run();
        run(); // throws error
    }
    private static void run() throws InterruptedException {
        GLFW.glfwSetErrorCallback(GLFWErrorCallback.createPrint(System.err));
        int glfwInit = GLFW.glfwInit();
        System.out.println(glfwInit == 0 ? "ERROR" : "OK");
        if (glfwInit == 0) return;
        GLFW.glfwTerminate();
    }
}

````

On version 3.0.0b everything is ok.

**Comment by httpdigest** [comment]
This is definitely a bug in [GLFW](https://github.com/glfw/glfw). You should post it there, if it has not already been reported. It is also very simple to reproduce, so, it should get quick attention.

**Comment by httpdigest** [comment]
Indeed this can be reproduced with the current master of GLFW at 386b603 using this native app:
```C
#include <glfw3.h>
#include <stdio.h>

int main(int argc, char** argv) {
	int succ = glfwInit();
	fprintf(stderr, "%d\n", succ);
	glfwTerminate();
	succ = glfwInit();
	fprintf(stderr, "%d\n", succ);
	glfwTerminate();
}
```
It prints 1 followed by 0.

**Comment by ShchAlexander** [comment]
I post it on [GLFW](https://github.com/glfw/glfw).

**Comment by httpdigest** [comment]
I can confirm that the fix https://github.com/glfw/glfw/commit/f7228bb56294714e8cdb8b39be3b7c6967240c54 in GLFW does fix this issue. We just have to wait for a new LWJGL build to appear. :)

**Comment by Spasi** [comment]
The latest nightly build (3.0.0 23) includes the above fix.
