### ISSUE TITLE
Vulkan support?

### ISSUE THREAD

**Issue by sriharshachilakapati** [LWJGL/lwjgl3#144]
So Vulkan is now released, and we also got Vulkan support in [GLFW](https://github.com/glfw/glfw/commit/9b75bffc88939883d8ae77901b73182dda35e733) and the drivers are also available now..

It will be really cool to see the support in LWJGL3. Could you add this very soon please??

**Comment by nidefawl** [comment]
Wouldn't it make more sense to make a complete new library (similiar to lwjgl) but on top of vulkan?

**Comment by sriharshachilakapati** [comment]
I don't think so, since we already got support for Vulkan in GLFW that LWJGL3 already provides support for, it is better to use existing library here. Also there went a lot of work into LWJGL 3 till now.

**Comment by sriharshachilakapati** [comment]
Wait, this is a duplicate and already mentioned in #50 so I'm closing this issue. Sorry for not looking up early before posting.

**Comment by johnnic431** [comment]
Check issue #50.
Specifically this comment: https://github.com/LWJGL/lwjgl3/issues/50#issuecomment-159048360

**Comment by sriharshachilakapati** [comment]
@johnnic431 It's now available to public, and LunarG has also released a complete Vulkan SDK.

**Comment by johnnic431** [comment]
@sriharshachilakapati I'm aware, but the comment mentions that it will take a little while to release a LWJGL update.

**Comment by Spasi** [comment]
Hey guys,

I'm fully aware how excited everyone is to give Vulkan a try. But as I mentioned in #50, I haven't had access to the spec before today. I'm currently setting everything up and will be working on the bindings until late tonight. It's all new to me, but I'll try to push something usable as soon as possible.

**Comment by httpdigest** [comment]
The utmost respect to you, @Spasi , and all the sympathy for pulling this off and realizing a 631 pages spec with LWJGL. :)
I mean, it took a lot of time and effort for you guys to fully reflect the OpenGL API.
But now that there actually are C header files for Vulkan, it'd probably be good to first invest (if not already happened) to some automatic C header file to Kotlin template files generator?

**Comment by Spasi** [comment]
Yes, I'll think about that after 3.0 is released, it'd be useful to have a decent parser (libclang bindings?).   The converter we have in LWJGL is too limited and too OpenGL-oriented. I was actually just adding support for enums, there's a ton of them in Vulkan.

At least the work on struct support is paying off. 124 struct types in Vulkan 1.0 + first extensions, if my count is correct.

**Comment by httpdigest** [comment]
I'll see if I can help you with that. I started a clang project for that some months ago, which however made use of clang as a tool and interfaced with its printed AST output to parse that.
But that might not be your preferred solution, of course.
