### ISSUE TITLE
Incorrect VK_PHYSICAL_DEVICE_TYPE_ Enums

### ISSUE THREAD

**Issue by NegativeXero** [LWJGL/lwjgl3#145]
The LWJGL3 implementation of the physical device type enums `VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU` `VK_PHYSICAL_DEVICE_TYPE_DISCRETE_GPU` `VK_PHYSICAL_DEVICE_TYPE_VIRTUAL_GPU` and `VK_PHYSICAL_DEVICE_TYPE_CPU` are equal to 0, 1, 2, 3 respectively.

 However, the vulkan specs define them as 1, 2, 3, 4 respectively as `VK_PHYSICAL_DEVICE_TYPE_OTHER` is 0.

**Comment by Spasi** [comment]
Thanks!
