### ISSUE TITLE
Are you plannig to abstract Vulkan API 1.0? :) 

### ISSUE THREAD

**Issue by juanmf** [LWJGL/lwjgl3#146]
Hi! Thanks for this outstanding work! 

As Vulkan promised to outperform OpenGL, and does not have the single thread limitation, I'm eager to know if you plan to make an API to access Vulcan API. 

Thanks a lot! 
Juan

**Comment by huhlig** [comment]
Its already in upstream. See: https://github.com/LWJGL/lwjgl3/issues/50

**Comment by juanmf** [comment]
Thanks!
