### ISSUE TITLE
glfw32.dll isn't 32-bit in nightly download

### ISSUE THREAD

**Issue by phr00t** [LWJGL/lwjgl3#148]
Not sure where the best place was to report this, so I reported it here too. Sorry for the duplication otherwise!

Phr00t@SomebodyPC /cygdrive/c/Users/Phr00t/Downloads
$ file glfw32.dll
glfw32.dll: PE32+ executable (DLL) (console) x86-64, for MS Windows

http://forum.lwjgl.org/index.php?topic=6153.0

**Comment by Spasi** [comment]
Thanks, the latest nightly build should have the correct dll.
