### ISSUE TITLE
Window starts in background & CursorPosCallback.release crash in b41+ nightlies

### ISSUE THREAD

**Issue by phr00t** [LWJGL/lwjgl3#150]
Ever since b41 nightly, two problems have existed preventing me from staying up-to-date:

1) My game window starts in the background. If I use a build older than b41 (I think I might be on b37 or b38?), my game properly starts in the foreground. I can ALT+TAB to the background Window in b41-b44, but I shouldn't have to. What changed here?

2) This crash is new when closing my game -- doesn't happen with the previous builds:

java.lang.NoSuchMethodError: org.lwjgl.glfw.GLFWCursorPosCallback.release()V
	at com.jme3.input.lwjgl.GlfwMouseInput.destroy(GlfwMouseInput.java:196)
	at com.jme3.app.Application.destroyInput(Application.java:725)
	at com.jme3.app.Application.destroy(Application.java:746)
	at jmevr.app.VRApplication.destroy(VRApplication.java:633)
	at Game.Main.destroy(Main.java:229)
	at Game.Menu.MenuSystem.ActivateSelectedOption(MenuSystem.java:1069)
	at Game.Input.Manager$2.onAction(Manager.java:423)
	at com.jme3.input.InputManager.invokeActions(InputManager.java:169)
	at com.jme3.input.InputManager.onMouseButtonEventQueued(InputManager.java:439)
	at com.jme3.input.InputManager.processQueue(InputManager.java:857)
	at com.jme3.input.InputManager.update(InputManager.java:907)
	at com.jme3.app.Application.update(Application.java:712)
	at jmevr.app.VRApplication.update(VRApplication.java:543)
	at com.jme3.system.lwjgl.LwjglWindow.runLoop(LwjglWindow.java:380)
	at com.jme3.system.lwjgl.LwjglWindow.run(LwjglWindow.java:464)
	at com.jme3.system.lwjgl.LwjglWindow.create(LwjglWindow.java:307)
	at com.jme3.app.Application.start(Application.java:446)
	at jmevr.app.VRApplication.start(VRApplication.java:310)
	at Game.Main.StartGame(Main.java:212)
	at Game.Main.main(Main.java:134)

**Comment by RegaliaSly** [comment]
`GLFWCursorPosCallback.release()` is now `GLFWCursorPosCallback.free()` in the nightly build. Not sure about the window opening in the background though.

**Comment by Spasi** [comment]
> 1) My game window starts in the background. If I use a build older than b41 (I think I might be on b37 or b38?), my game properly starts in the foreground. I can ALT+TAB to the background Window in b41-b44, but I shouldn't have to. What changed here?

This is likely related to the new [glfwFocusWindow](https://github.com/glfw/glfw/commit/baf574494da1f1b6a07ff426c62670090e67b445) functionality in GLFW master. What OS are you on?

**Comment by phr00t** [comment]
Windows 10 x64. This something that has to be newly called somewhere?

**Comment by phr00t** [comment]
Calling glfwFocusWindow after glfwShowWindow does the trick. Changing .release to .free also fixes the other problem. Should be all set, thank you!

**Comment by Spasi** [comment]
Lets leave this issue open, because I'm not sure what the correct behavior is. This statement (in the glfwFocusWindow doc):

> By default, both windowed and full screen mode windows are focused when initially created. Set the GLFW_FOCUSED hint to disable this behavior.

and this (from the commit above):

> This removes the (undocumented) behavior where glfwShowWindow would bring the window to front and set input focus.

seem to contradict each other.

**Comment by elmindreda** [comment]
@phr00t Is your window full screen or windowed?

**Comment by phr00t** [comment]
Windowed.

**Comment by elmindreda** [comment]
@Spasi Yup, this is totally my fault. It's a regression I was hoping to get away with to introduce separation of behavior. If you prefer I'll revert to the old behavior (though still using the newer code).

**Comment by Spasi** [comment]
Ideally it would work like the documentation on `glfwFocusWindow` says: new windows are focused by default (same behavior as before), unless `glfwWindowHint(GLFW_FOCUSED, GLFW_FALSE)` is set.

**Comment by elmindreda** [comment]
(Due to headache I'm probably saying at least some obvious things below. Sorry.)

> By default, both windowed and full screen mode windows are focused when initially created.

This was poorly written. What I was trying to say with "initially created" was that this is done by `glfwCreateWindow` or not at all. If one turns off `GLFW_VISIBLE` (which appears to be what @phr00t did, hence the call to `glfwShowWindow`) then the default behavior of show plus focus is overridden.

Should I track whether the window has ever been shown and then additionally focus it the first time it is shown?

**Comment by phr00t** [comment]
If I'm not mistaken, I set GLFW_VISIBLE to false, because the documentation says you should if you want to reposition it (which I was doing). I later didn't show it, like I should have. Previously, it showed anyway, so I didn't think anything of it. I think the current behavior is more correct, if it is following @Spasi's description of the documentation.

**Comment by Spasi** [comment]
> What I was trying to say with "initially created" was that this is done by glfwCreateWindow or not at all.

Thanks, that explains it.

> Should I track whether the window has ever been shown and then additionally focus it the first time it is shown?

I think I would prefer it. It also doesn't change the behavior of existing programs.

**Comment by elmindreda** [comment]
The previous behavior has been restored with glfw/glfw@89f438de5a862802717a5d6e32ebfe462775cccf.
