### ISSUE TITLE
Vulkan Example

### ISSUE THREAD

**Issue by huhlig** [LWJGL/lwjgl3#151]
We need to create an end to end hello triangle example for LWJGL.

**Comment by intrigus** [comment]
Have a look at https://github.com/LWJGL/lwjgl3/blob/b670b2b5dcce28091f2bf2253ddf787da3a07d9c/modules/core/src/test/java/org/lwjgl/demo/vulkan/HelloVulkan.java

**Comment by huhlig** [comment]
Ok, perhaps we should push this link somewhere findable. :)

**Comment by Spasi** [comment]
More Vulkan examples in the lwjgl3-demos repo, [here](https://github.com/LWJGL/lwjgl3-demos/tree/master/src/org/lwjgl/demo/vulkan). Everything in there has been contributed by @httpdigest.

> One thing I noticed. Is the Triangle supposed to have its bottom repeatedly hidden and shown?

Yes, see the `demo_run` method, it's animating the depth clear value.

**Comment by r41d** [comment]
2000 lines for a triangle, what kind of joke is this? ^^
