### ISSUE TITLE
Font Rendering with STB

### ISSUE THREAD

**Issue by Guichaguri** [LWJGL/lwjgl3#153]
I was trying to use the [Truetype example](https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/test/java/org/lwjgl/demo/stb/Truetype.java) but it is broken with the latest release.

Is there another example or instruction for rendering truetype fonts?

**Comment by Spasi** [comment]
What exactly is broken with the Truetype demo? Did you try the latest nightly build?

**Comment by Guichaguri** [comment]
That explains why. Thanks
