### ISSUE TITLE
Mac & Linux libglfw library load errors (nightly b54)

### ISSUE THREAD

**Issue by phr00t** [LWJGL/lwjgl3#155]
Looks like problems with the libglfw.so & libglfw.dylib files for the latest nightly (b54) builds:

http://pastebin.com/h2Fd1nn1

http://steamcommunity.com/app/414510/discussions/0/458606877314671264/?tscn=1458580538#c392184342866516170

Windows seems to work fine.

EDIT: I confirmed SHA sums with the extracted files trying to be loaded & the ones from the website... they are the same.

**Comment by Spasi** [comment]
Thanks!
