### ISSUE TITLE
VM crash on jenkins build server

### ISSUE THREAD

**Issue by xupwup** [LWJGL/lwjgl3#158]
We have a rather odd setup on our build server. We use a windows server which runs Jenkins, but the build server does not have OpenGL support built in. Jenkins is also not allowed to open windows (because it runs in a service?). We managed to get OpenGL working by dumping opengl32.dll from the mesa project in the same folder as java.exe.

However, our setup no longer works with the latest LWJGL (today's sonatype snapshot), because the VM crashes. See [hs_err_pid676.txt](https://github.com/LWJGL/lwjgl3/files/185845/hs_err_pid676.txt). Do you have any idea how to fix this? Note that the problem does not occur on our development machines.

```
Stack: [0x000000001b8a0000,0x000000001b9a0000],  sp=0x000000001b99e790,  free space=1017k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [glfw.dll+0x62be]
C  [glfw.dll+0x2007]
C  0x0000000001825874

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.lwjgl.system.JNI.invokeI(J)I+0
j  org.lwjgl.glfw.GLFW.glfwInit()I+8
j  com.vi.render.core.Main.initWindow()V+15
j  com.vi.render.core.Main.run()V+18
v  ~StubRoutines::call_stub
```

**Comment by Spasi** [comment]
I cannot reproduce with Mesa 11.0.5. What build do you use?

**Comment by xupwup** [comment]
Mesa 11.1.2 (git-38e8691)

**Comment by Spasi** [comment]
Do you know where I can find binaries for the latest Mesa version?

Do you think you could build a debug version of GLFW and see where exactly it crashes?

**Comment by xupwup** [comment]
I got my mesa dll from here: https://sourceforge.net/projects/msys2/files/REPOS/MINGW/x86_64/

I'll look into building my own glfw, but that may take a while (I'm not very experienced with building c++ on windows).

**Comment by Spasi** [comment]
Latest version works for me too.

I've uploaded a GLFW debug build [here](https://s3.amazonaws.com/build.lwjgl.org/nightly/windows/x64/custom/glfw.dll).

**Comment by xupwup** [comment]
Ok, this is with your GLFW build:
Stack: [0x000000001a520000,0x000000001a620000],  sp=0x000000001a61e4e0,  free space=1017k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [glfw.dll+0x1436f]
C  [glfw.dll+0xa22c]
C  0x0000000001575874

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.lwjgl.system.JNI.invokeI(J)I+0
j  org.lwjgl.glfw.GLFW.glfwInit()I+8
j  com.vi.render.core.Main.initWindow()V+15
j  com.vi.render.core.Main.run()V+18
v  ~StubRoutines::call_stub

For some reason it's still not showing me any symbols...

**Comment by Spasi** [comment]
Hmm, this is what I get if I make it crash:

```
Stack: [0x0000000002160000,0x0000000002260000],  sp=0x000000000225eed8,  free space=1019k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [glfw.dll+0x20e80]  memset+0xc0
C  [glfw.dll+0x15537]  _glfwRegisterWindowClassWin32+0x27
C  [glfw.dll+0x11f47]  _glfwPlatformInit+0x97
C  [glfw.dll+0xa20e]  glfwInit+0x3e
C  0x0000000002465dd5

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.lwjgl.system.JNI.invokeI(J)I+0
j  org.lwjgl.glfw.GLFW.glfwInit()I+8
j  org.lwjgl.demo.glfw.Gears.init()V+10
j  org.lwjgl.demo.glfw.Gears.run()V+1
j  org.lwjgl.demo.glfw.Gears.main([Ljava/lang/String;)V+7
v  ~StubRoutines::call_stub
```

Tested on Windows 10, JDK 8u74.

**Comment by httpdigest** [comment]
With me, in about 90% of executions of a LWJGL3/GLFW application, glfwInit() also crashes when executing the application the first time after a PC boot. I thought this was strange, but it only ever happens only the very first time I execute any application. The next executions are fine.
That's why I thought "ah, what the hell. be it like it be."
But now that you provided the debug DLL I might have a look at it, too.

**Comment by xupwup** [comment]
glfwRegisterWindowClassWin32 sounds like it may have something to do with our setup. We're running this from a windows service, so no window actually opens when we start our application. For some reason this worked in the current stable version, but maybe it broke?

**Comment by Spasi** [comment]
> glfwRegisterWindowClassWin32 sounds like it may have something to do with our setup.

Please note that the crash above was triggered on purpose (I made `memset` write to address 0) to test if the debug symbols made it to the JVM crash log. The real issue could easily be unrelated to window class registration (or even unrelated to GLFW).

**Comment by xupwup** [comment]
We've "fixed" the issue on our end, by running the application differently. I don't know exactly what our configuration manager did, but now the program no longer runs from a service, so it can open windows. That makes it not crash.

That means the crash itself was probably caused by glfw not being happy in a windows service.

**Comment by pderoovere** [comment]
Hi guys,

I have a similar problem. Switching from 3.0.0b to 3.0.0 results in a VM crash when running tests on our Jenkins server. The server has no OpenGL support, so previously we got the following error:

```
[LWJGL] GLFW_API_UNAVAILABLE error
  Description : WGL: The driver does not appear to support OpenGL
  Stacktrace  :
    org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1168)
    org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1251)
```

With v3.0.0 the VM crashes when calling `glfwInit()`, see [hs_err_pid3356.txt](https://github.com/LWJGL/lwjgl3/files/393704/hs_err_pid3356.txt)
