### ISSUE TITLE
Pressing CTRL + Pause results in a -1 keycode

### ISSUE THREAD

**Issue by stelar7** [LWJGL/lwjgl3#159]
When using a GLFWKeyCallback, pressing CTRL and Pause at the same time makes the key = -1, when the expected result would be a key of GLFW_KEY_PAUSE, with a mod of GLFW_MOD_CONTROL.

**Comment by Spasi** [comment]
CTRL+Pause triggers SIGBREAK. The `scancode` changes from 69 to 326 (I'm testing on Windows) and looks like GLFW doesn't have a mapping for it.

You may want to report this to [GLFW](https://github.com/glfw/glfw/issues).

**Comment by Spasi** [comment]
Fixed with https://github.com/glfw/glfw/commit/3503cba5d9df2976fa94eeaf852e15f987a00fa0.

**Comment by stelar7** [comment]
Fixed in the latest commit https://github.com/glfw/glfw/commit/3503cba5d9df2976fa94eeaf852e15f987a00fa0
