### ISSUE TITLE
Add bindings for OpenVR, Valve's VR library - Allows support for more HMDs and platforms

### ISSUE THREAD

**Issue by me4502** [LWJGL/lwjgl3#160]
Valve's OpenVR, available at https://github.com/ValveSoftware/openvr,
would allow for usage of the HTC Vive, and other HMDs, as well as 'Direct Mode', which allows for the image to be sent straight to the HMD, rather than through a compositor that is currently windows only.

**Comment by 0-00** [comment]
Spasi, is there currently an ETA on OpenVR bindings?

**Comment by Spasi** [comment]
Current priority is releasing 3.0.1 (modular artifacts). Work on new bindings will start immediately after.

**Comment by Spasi** [comment]
The OpenVR bindings are now available in the latest snapshot (LWJGL 3.1.2 build 4).
