### ISSUE TITLE
[Javadoc] Incorrect default values for glfwWindowHint

### ISSUE THREAD

**Issue by DelZeta** [LWJGL/lwjgl3#166]
* GLFW_FLOATING defaults to false, not true.
* GLFW_REFRESH_RATE defaults to GLFW_DONT_CARE (and consequently, allows negative values)
* The zeroed bit counts, sample count, and auxiliary buffer count also support GLFW_DONT_CARE as values.
* Entries are missing for GLFW_FOCUSED and GLFW_DOUBLEBUFFER.

**Comment by Spasi** [comment]
Thanks!
