### ISSUE TITLE
Crash upon GL.createCapabilities() (OS X)

### ISSUE THREAD

**Issue by CraftedCart** [LWJGL/lwjgl3#168]
Upon trying to use the latest nightly build of LWJGL 3, with the example code on the website (or even just the line `GL.createCapabilities();`), the application crashes with the error
```
java(1028,0x7fff7eb3d000) malloc: *** error for object 0x7fcb8129f7f5: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

Further inspection via Apple's Instruments app reveals 36 memory leaks, although I'm slightly confused about this as it reports memory leaks when I've paused the app using IntelliJ's debugger before it hits the `GL.createCapabilities();` line, all reported entries however are from `malloc`.

If it helps (eg: If I'm using the wrong version), here's my build.gradle (Although I've tried running it using the download from the website instead of using Gradle)
```gradle
group 'io.github.craftedcart'
version '1.0-SNAPSHOT'

apply plugin: 'java'

sourceCompatibility = 1.6

def lwjglVersion = "3.0.0-SNAPSHOT"

repositories {
    mavenCentral()

    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots/"
    }
}

dependencies {
    compile "org.lwjgl:lwjgl:${lwjglVersion}"

    compile group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.5'
    compile group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.5'

    runtime "org.lwjgl:lwjgl-platform:${lwjglVersion}:natives-windows",
            "org.lwjgl:lwjgl-platform:${lwjglVersion}:natives-linux",
            "org.lwjgl:lwjgl-platform:${lwjglVersion}:natives-osx"

    testCompile group: 'junit', name: 'junit', version: '4.11'
}
```

Some Info:
- OS: OS X El Capitan 10.11.1
- Model: iMac (21.5-inch, Late 2013)
- CPU: 2.9 GHz Intel Core i5
- GPU: NVIDIA GeForce GT 750M 1024 MB
- Running via IntellliJ using JDK 1.7.0_80 - I have also tried using the DCEVM (IDK which JDK version)
- VM Args: `-XstartOnFirstThread`

**Comment by Spasi** [comment]
Thanks!
