### ISSUE TITLE
Add Oculus Platform SDK bindings

### ISSUE THREAD

**Issue by Spasi** [LWJGL/lwjgl3#169]
https://developer.oculus.com/documentation/platform/latest/concepts/developer-intro/

**Comment by huhlig** [comment]
This seems very out of scope for lwjgl.

> The Oculus Platform is designed to provide you with the infrastructure you need, so you can focus on creating a great game or experience. The Oculus Platform currently provides the following features:
> 
> Friend Management—to enable social functionality and increase engagement, this enables players to add friends and find friends that are currently online.
> Rooms—your app can create rooms where players gather or you can enable players to create them.
> Achievements—you can create trophies, badges, awards, medals, or challenges in your app and Oculus will manage it.
> Leaderboards—if your app or experience is competitive, you can create leaderboards to track the top players.
> Matchmaking—if players can't find a match, you can help them find available games. The platform supports both standard and skill-based pools.
> In-App Purchases—enables you to monetize your games and experiences.
> Peer-to-Peer Networking—enables players to communicate directly.

**Comment by kenzierocks** [comment]
I agree with @huhlig about making this a subproject. I think that if LWJGL starts including a lot of bindings then #100 should become a much higher priority.

**Comment by ShadowLordAlpha** [comment]
I wouldn't mind having libraries like this though #100 should really be finished first and maybe with it add a set of libraries that are less used and have less work out into them and are not part of the main jar but can be added if they are wanted by the user.
