### ISSUE TITLE
Generator non-kotlin Templates

### ISSUE THREAD

**Issue by ShadowLordAlpha** [LWJGL/lwjgl3#173]
As mentioned in #172 change from using kotlin files as templates to some other format that would, most probably, not need to be compiled. This would make contributions to the lwjgl bindings easier for other people to do as well as possibly making maintaining easier. This should also go hand in hand with #165.

**Comment by kappaOne** [comment]
Hopefully XML won't be the chosen format (tis really horrid). Not sure it offers enough but YAML might be a good option to consider, its nice to look at and read.

**Comment by ShadowLordAlpha** [comment]
I was thinking a more custom format but xml, yaml, or is in would also work

**Comment by kappaOne** [comment]
Using an existing format has the advantage of already having existing libraries, tools and validators that can be used. IDE's like Eclipse, Intellij, Netbeans all already support XML, JSON, YAML (via plugins if not built in support) which can provide syntax highlighting and error checking. Further there are much more documentation and tutorials for these formats and developers may already be familiar with them allowing lower entry for contributions.

This is something a custom format will be missing and it would require a lot more work to implement and maintain.

**Comment by ShadowLordAlpha** [comment]
> Using an existing format has the advantage of already having existing libraries, tools and validators that can be used. IDE's like Eclipse, Intellij, Netbeans (even GitHub) already support XML, JSON, YAML (via plugins if not built in support) which can provide syntax highlighting and error checking. Further there is existing documentation and tutorials for these formats and developers may already be familiar with them allowing lower entry for contributions.

It wouldn't really be any lower as all three of those are basically just ways to format data that can then be read so it would basically be its own format built on top of a more general format. It forces a set format which can be useful for parsing and validating data though so that would be useful.

> This is something a custom format will be missing and therefore require a lot more work to implement and maintain.

again all three of those are basically just key-value pair mappings so there isn't much syntax highlighting to miss in the first place but it could be useful.

**Comment by httpdigest** [comment]
> all three of those are basically just key-value pair mappings

Conceptually, you are right. But in practice there is much more to that than simply saying "this format is just a mathematical tree structure, so it is just as good as any other format."

Like kappa said, with XML (for example) there are uncountably many IDE plugins, validators and transformation tools _already existing_ that can be let loose on the data and that can aid in authoring the templates and transform them. Just think about XSLT to transform XML templates into Java sources or HTML documentation output or use XSL-FO to build printable PDF documentation documents, which would be one possible argument for using XML. (not saying that you should use that!)

You simply don't have any of that with a custom format.
You have to work everything from scratch and do everything by yourself, starting with a grammar definition which you, if you're smart, define in some form of EBNF and let a parser generator generate a working lexer, parser and AST for you. By no means would you implement a lexer and parser by hand.... :)

So, like kappa said: "Be smart and use a format that already has a healthy ecosystem around it."

**Comment by ShadowLordAlpha** [comment]
I agreed with him on that part I just disagreed with it lowering the entry point really (though thinking on it more it would technically lower it a bit more but not by all that much)

on the other side if one of those 3 is chosen I would hope that it is JSON as XML looks messy and confusing (its not that bad once you know how to use it though). YAML I haven't used much so I can't really speak for it but the indentation part would both be good for readability but also a headache I think though like I said I haven't really used it.

**Comment by kenzierocks** [comment]
I think YAML might require tabs (I know some implementations do) which could be troublesome/time-consuming if spaces are used accidentally.

**Comment by RUSshy** [comment]
JSON is horrible, can't even put comments

Kotlin + DSL is 1000x better than everything mentioned

**Comment by Spasi** [comment]
I've changed my mind about this.

The advantages of using Kotlin for the templates are hard to give up. The DSL has also improved considerably over the past couple of years and we now have the Template Extractor (powered by the Clang bindings), which makes writing new bindings much quicker.

Documentation is still a pain and makes the templates heavier than they need to be, so it's worth exploring possible solutions for #165.
