### ISSUE TITLE
SDL2 Binding?

### ISSUE THREAD

**Issue by renannprado** [LWJGL/lwjgl3#174]
What do you guys think?

**Comment by huhlig** [comment]
What value are you looking to derive from SDL2 you cannot get from GLFW?

**Comment by renannprado** [comment]
It's been a long time since I last used it, BUT when I did more or less a year ago, the big win for me was the simplified graphics API over OpenGL one.
But I'm certainly not expert in OpenGL nor SDL2.
Other people will probably have better arguments (against or for) than me.

**Comment by huhlig** [comment]
So you want to use SDL2 instead of GLFW inside a Java OpenGL library to draw graphics without OpenGL?

**Comment by RegaliaSly** [comment]
While it would be nice to see SDL2 get a working port to Java, it would have no point in LWJGL as GLFW already handles everything in terms of window, input and context handling.

**Comment by dustContributor** [comment]
Pretty much, want something like SDL2? Use libGDX.

**Comment by XenoAmess** [comment]
glfw have no method like SDL_JoystickRumble in SDL.///
But you can use Jamepad instead so that is no problem.
