### ISSUE TITLE
GLFW Issue

### ISSUE THREAD

**Issue by dragonslayer0531** [LWJGL/lwjgl3#178]
I am running into an issue where my game generates a crash log.  For some reason, all my textures decide to go translucent.  I have isolated it down to my GLFW window class.  My engine is located at [LuminosEngine](https://github.com/dragonslayer0531/Luminos).  I will have my log posted below.  Any help that can be given would be much appreciated!

[Log File](http://pastebin.com/V8pFtsar)

**Comment by Spasi** [comment]
Why do you think it is a GLFW issue? How did you isolate it down to your GLFW window class? Afaict it crashes in the OpenGL driver, not in GLFW.

The Java stacktrace is missing from the log above. Could you please edit your post to remove the log dump and attach the log as a file?

**Comment by dragonslayer0531** [comment]
Okay.  I isolated it down to this by seeing which file was causing it.  It may be something that is called inside the class itself.  Not 100% sure the issue.  How would I go about fixing it in the OpenGL driver?  I have both reverted to old drivers and updated to the newest and neither would fix my issue.

**Comment by Spasi** [comment]
You have not provided enough information. There's no Java stacktrace, so we can't see which LWJGL method triggers the crash.

Textures going translucent suggest a bug in your code, but how can you see translucent textures if the JVM crashes?

**Comment by dragonslayer0531** [comment]
Would it be helpful if I linked a runnable jar?

**Comment by Spasi** [comment]
Sure.

Btw, have you tried closing Raptr? `ltc_game32-109838.dll` seems to be involved in the crash.

**Comment by dragonslayer0531** [comment]
Here is the Jar [Test](https://www.dropbox.com/s/13u0akjriwxuo0z/Test.zip?dl=0).  After I stopped it, it started working, but there is a lot of lag that used not to be there.
