### ISSUE TITLE
fontstash bindings

### ISSUE THREAD

**Issue by kenzierocks** [LWJGL/lwjgl3#180]
I'd like to request `fontstash` bindings, specifically from https://github.com/lsmoura/fontstash. This is a fork that provides core OpenGL support controlled by a `#define`. I'm not sure if it would be easy to add a way to control that `#define` (I want the core functionality, but others might need the legacy functionality), but this seems like a good solution for people who need easy text bindings like `java.awt.Font` used to provide. What do you think about it?

If this isn't added as bindings, I'll probably just rewrite it in Java use that, but I think it would be easier to update and patch if it was added as bindings here.

**Comment by Spasi** [comment]
Have you tried NanoVG? It comes with 4 different back-ends (GL2, GL3, GLES2, GLES3) and has a very simple text rendering API. It also uses the original `fontstash` internally.

**Comment by kenzierocks** [comment]
OK, that looks like it'll cover me. Thanks!
