### ISSUE TITLE
GLFW Boolean return type

### ISSUE THREAD

**Issue by ShadowLordAlpha** [LWJGL/lwjgl3#181]
Both OpenAL and OpenGL have Boolean return methods that are used in place of their *_TRUE and *_FALSE return values. GLFW also does this but does not make a special type for the Boolean value and instead treats it as an int (OpenGL and OpenAL treat it as a byte if I remember correctly but only give it the true or false value) so it should be possible to make it so that certain GLFW functions that are documented Boolean returns actually return a Boolean java type. Its not really required as its easy enough to just do `glfwInit() != GLFW_TRUE` but it would be nice to have.

**Comment by Spasi** [comment]
Technically it's possible (and easy). LWJGL normally does this only when the native API has a dedicated boolean type.

Is anyone against such a change? It will affect the following functions:

- `glfwInit`
- `glfwWindowShouldClose`
- `glfwSetWindowShouldClose`
- `glfwJoystickPresent`
- `glfwExtensionSupported`
- `glfwVulkanSupported`
- `glfwGetPhysicalDevicePresentationSupport`

**Comment by iamcreasy** [comment]
GLFW has code like this,
`if (!glfwInit())`
But in LWJGL 3 we write it as,
`if ( glfwInit() != GLFW_TRUE )`

@Spasi Can you tell me, why instead of native Java boolean GLFW_TRUE was chosen in the first place?

**Comment by Spasi** [comment]
@iamcreasy I mentioned this, int is used because that's what the native API uses. C code can do:

```if ( !glfwInit() )```

because C supports numeric values in conditions (they are automatically compared against 0).

**Comment by arisona** [comment]
That would be great! In addition, there are a few callbacks that have boolean type arguments, such as the iconify callback or the cursor enter callback. Could this be done there as well for consistency?

**Comment by Spasi** [comment]
@arisona Thanks for the reminder, those callbacks have changed too.
