### ISSUE TITLE
In newest LWJGL Snapshot Callbacks doesnt work anymore

### ISSUE THREAD

**Issue by JuKu** [LWJGL/lwjgl3#183]
Hi,

We are using lwjgl 3 snapshot version and today i wanted to build our project, but it doesnt worked anymore.

I get errors like:
`
error: cannot find symbol
	GLFWKeyCallback.SAM
error: cannot find symbol
	GLFWCursorPosCallback.SAM
error: cannot find symbol
	GLFWMouseButtonCallback.SAM
error: cannot find symbol
	GLFWWindowCloseCallback.SAM
error: cannot find symbol
	GLFWWindowFocusCallback.SAM
error: cannot find symbol
public class GLFWContextMaster implements ContextMaster, GLFWErrorCallback.SAM, GLFWMonitorCallback.SAM
error: cannot find symbol
public class GLFWContextMaster implements ContextMaster, GLFWErrorCallback.SAM, GLFWMonitorCallback.SAM
`

Also the invoke() methods was removed so with the warning, the methods doesnt override or implement a method from a supertype.

Some other errors:
`
D:\Program Files\jmonkeyplatform\projects\Repo\Intellij\pentaquin\pentaquin-core\pentacore-context\src\main\java\com\pentaquin\core\context\GLFWContext.java:580: error: no suitable method found for create(GLFWContext)
		keyCallback = GLFWKeyCallback.create(this);
		                             ^
    method GLFWKeyCallback.create(long) is not applicable
      (argument mismatch; GLFWContext cannot be converted to long)
    method GLFWKeyCallback.create(GLFWKeyCallbackI) is not applicable
      (argument mismatch; GLFWContext cannot be converted to GLFWKeyCallbackI)

D:\Program Files\jmonkeyplatform\projects\Repo\Intellij\pentaquin\pentaquin-core\pentacore-context\src\main\java\com\pentaquin\core\context\GLFWContext.java:581: error: no suitable method found for create(GLFWContext)
		cursorCallback = GLFWCursorPosCallback.create(this);
		                                      ^
    method GLFWCursorPosCallback.create(long) is not applicable
      (argument mismatch; GLFWContext cannot be converted to long)
    method GLFWCursorPosCallback.create(GLFWCursorPosCallbackI) is not applicable
      (argument mismatch; GLFWContext cannot be converted to GLFWCursorPosCallbackI)
D:\Program Files\jmonkeyplatform\projects\Repo\Intellij\pentaquin\pentaquin-core\pentacore-context\src\main\java\com\pentaquin\core\context\GLFWContext.java:583: error: no suitable method found for create(GLFWContext)
		closeCallback = GLFWWindowCloseCallback.create(this);
		                                       ^
    method GLFWWindowCloseCallback.create(long) is not applicable
      (argument mismatch; GLFWContext cannot be converted to long)
    method GLFWWindowCloseCallback.create(GLFWWindowCloseCallbackI) is not applicable
      (argument mismatch; GLFWContext cannot be converted to GLFWWindowCloseCallbackI)
D:\Program Files\jmonkeyplatform\projects\Repo\Intellij\pentaquin\pentaquin-core\pentacore-context\src\main\java\com\pentaquin\core\context\GLFWContext.java:584: error: no suitable method found for create(GLFWContext)
		focusCallback = GLFWWindowFocusCallback.create(this);
		                                       ^
    method GLFWWindowFocusCallback.create(long) is not applicable
      (argument mismatch; GLFWContext cannot be converted to long)
    method GLFWWindowFocusCallback.create(GLFWWindowFocusCallbackI) is not applicable
      (argument mismatch; GLFWContext cannot be converted to GLFWWindowFocusCallbackI)
D:\Program Files\jmonkeyplatform\projects\Repo\Intellij\pentaquin\pentaquin-core\pentacore-context\src\main\java\com\pentaquin\core\context\GLFWContextMaster.java:44: error: no suitable method found for create(GLFWContextMaster)
		monitorCallback = GLFWMonitorCallback.create(this);
		                                     ^
    method GLFWMonitorCallback.create(long) is not applicable
      (argument mismatch; GLFWContextMaster cannot be converted to long)
    method GLFWMonitorCallback.create(GLFWMonitorCallbackI) is not applicable
      (argument mismatch; GLFWContextMaster cannot be converted to GLFWMonitorCallbackI)
D:\Program Files\jmonkeyplatform\projects\Repo\Intellij\pentaquin\pentaquin-core\pentacore-context\src\main\java\com\pentaquin\core\context\GLFWContextMaster.java:58: error: incomparable types: boolean and int
		if(GLFW.glfwInit() == GL11.GL_FALSE)
`

I have seen your commit fdbfde039e579f37beab1dd60a2dbc2e9c87f5f3 where you have refactored the callbacks. Was the SAM interfaces removed?

**Comment by Spasi** [comment]
Yes, the latest nightly build requires project recompilation (it's source compatible, but not binary compatible). If your code references the old SAM interfaces directly (it shouldn't, they were there only for Java 8 lambda conversion), you will also have to refactor your code to the new callback design.

Read [this reply](https://github.com/LWJGL/lwjgl3/issues/182#issuecomment-212920396) for more details.

**Comment by JuKu** [comment]
Thanks!
I could fixed it and it works now for me.
