### ISSUE TITLE
Customized OpenAL Demo: Looping doesnt really work

### ISSUE THREAD

**Issue by JuKu** [LWJGL/lwjgl3#185]
Hi,

I have an problem with an OpenAL code which is loading an Vorbis Ogg file (like the demo example) in the buffer and plays the sound. Looping is enabled, but it loops on an earlier point - not at the end of the sound file.

`
//generate new sound buffer
        this.buffer = alGenBuffers();
        checkALError();

        this.source = alGenSources();
        checkALError();

        //check for OpenAL error
        if(AL10.alGetError() != AL10.AL_NO_ERROR) {
            throw new OpenALException("An OpenAL Exception was thrown while loading sound track " + path + ".");
            //return AL10.AL_FALSE;
        }

        /*WaveData waveFile = WaveData.create(path);
        AL10.alBufferData(buffer, waveFile.format, waveFile.data, waveFile.samplerate);
        waveFile.dispose();*/

        STBVorbisInfo info = STBVorbisInfo.malloc();
        ShortBuffer pcm = SoundUtils.readVorbis(path, /*info.temp_memory_required() * 2*/64 * 1024/*64 * 1024*/, info);
        AL10.alBufferData(buffer, AL_FORMAT_STEREO16, pcm, info.sample_rate());

        //set source gain
        AL10.alSourcef(source, AL10.AL_GAIN, 1.0f);
        checkALError();

        //set pitch
        AL10.alSourcef(source, AL10.AL_PITCH, 1.0f);
        checkALError();

        //release memory
        info.free();

        //bindSound(1.0f, 1.0f);
        //set up source input
        alSourcei(source, AL_BUFFER, buffer);
        checkALError();

        //do another error check
        /*if (AL10.alGetError() == AL10.AL_NO_ERROR) {
            throw new OpenALException("An OpenAL Exception was thrown after loading sound track " + path + ".");
        }*/

        //lets loop the sound
        alSourcei(source, AL_LOOPING, AL_TRUE);
        checkALError();

        //play sound
        alSourcePlay(source);

        /*int repeats = 2;
        AL10.alSourcei(source, AL10.AL_LOOPING, AL10.AL_FALSE);
        for(int i = 0; i < repeats; i++)
            AL10.alSourceQueueBuffers(source, buffer);
        AL10.alSourcePlay(source);*/

        checkALError();
`

Is the buffer to small? What can be the cause of this problem?
The sound file has a size of 4MB and has sounds for 1 minute and 15 seconds.
Do i have to stream data parallel? How can i do this?

**Comment by Spasi** [comment]
> Is the buffer to small?

Not sure what `SoundUtils.readVorbis` is doing, but it looks like it.

You should start by adapting the [Vorbis demo](https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/test/java/org/lwjgl/demo/stb/Vorbis.java). It implements stream decoding to OpenAL in 4kb chunks (see `Decoder.BUFFER_SIZE`). The source Vorbis Ogg file is entirely in memory though. If you want to stream the file itself, you can:

- Use `stb_vorbis_open_filename`. Not an option if the file is inside a JAR.
- Use a NIO memory mapped file (`MappedByteBuffer`) and `stb_vorbis_open_memory`. Not an option if the file is inside a JAR.
- Implement your own streaming and use the "pushdata" API, i.e. `stb_vorbis_open_pushdata`, `stb_vorbis_decode_frame_pushdata` and `stb_vorbis_flush_pushdata`.

**Comment by JuKu** [comment]
Thanks for your answer!

Execuse me for my english, i am from Germany and my english is not the best.

I have implement the example from your vorbis demo:
https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/test/java/org/lwjgl/demo/stb/Vorbis.java

Now i have the problem, that it doesnt runs liquid, its like the application loads 0,5 seconds of the sound, plays it, wait a moment, load the next part, play it and so on.

`
//create new instance of sound track
Sound soundTrack = new VorbisSoundTrack();//new SoundTrack();

String path = "sound.ogg";

//load soundtrack
soundTrack.load(path);

//play music
soundTrack.play();

//create new thread to updating decoder and buffers
Thread updateThread = new Thread(() -> {
  while (!isInterrupted()) {
    //update soundtrack buffers for decoder and looping
    soundTrack.updateBuffers();
  }
});

//start thread
updateThread.start();
`

I have copied your decoder in a extra class:
`
/**
 * vorbis decoder from lwjgl demo
 *
 * @link https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/test/java/org/lwjgl/demo/stb/Vorbis.java
 *
 * Created by Justin on 22.04.2016.
 */
public class VorbisDecoder {

    private static final int BUFFER_SIZE = 1024 * 4;

    final ByteBuffer vorbis;

    final long handle;
    final int  channels;
    final int  sampleRate;
    final int  format;

    final int   lengthSamples;
    final float lengthSeconds;

    final ShortBuffer pcm;

    int samplesLeft;

    public VorbisDecoder(String filePath) {
        try {
            vorbis = ioResourceToByteBuffer(filePath, 256 * 1024);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        IntBuffer error = BufferUtils.createIntBuffer(1);
        handle = stb_vorbis_open_memory(vorbis, error, null);
        if ( handle == NULL )
            throw new RuntimeException("Failed to open Ogg Vorbis file. Error: " + error.get(0));

        STBVorbisInfo info = STBVorbisInfo.malloc();
        VorbisDecoder.getInfo(handle, info);
        this.channels = info.channels();
        this.sampleRate = info.sample_rate();

        this.format = getFormat(channels);

        switch (this.format) {
            case AL_FORMAT_MONO16:
                Logger.getRootLogger().debug("sound format: AL_FORMAT_MONO16, mono, 16kbit/s");
                break;

            case AL_FORMAT_STEREO16:
                Logger.getRootLogger().debug("sound format: AL_FORMAT_STEREO16, stereo, 16kbit/s");
                break;
            default:
                Logger.getRootLogger().debug("unknown sound format: " + this.format);
                break;
        }

        this.lengthSamples = stb_vorbis_stream_length_in_samples(handle);
        this.lengthSeconds = stb_vorbis_stream_length_in_seconds(handle);

        this.pcm = BufferUtils.createShortBuffer(BUFFER_SIZE);

        samplesLeft = lengthSamples;
    }

    private static void getInfo(long decoder, STBVorbisInfo info) {
        System.out.println("stream length, samples: " + stb_vorbis_stream_length_in_samples(decoder));
        System.out.println("stream length, seconds: " + stb_vorbis_stream_length_in_seconds(decoder));

        System.out.println();

        stb_vorbis_get_info(decoder, info);

        System.out.println("channels = " + info.channels());
        System.out.println("sampleRate = " + info.sample_rate());
        System.out.println("maxFrameSize = " + info.max_frame_size());
        System.out.println("setupMemoryRequired = " + info.setup_memory_required());
        System.out.println("setupTempMemoryRequired() = " + info.setup_temp_memory_required());
        System.out.println("tempMemoryRequired = " + info.temp_memory_required());
    }

    private static int getFormat(int channels) {
        switch ( channels ) {
            case 1:
                return AL_FORMAT_MONO16;
            case 2:
                return AL_FORMAT_STEREO16;
            default:
                throw new UnsupportedOperationException("Unsupported number of channels: " + channels);
        }
    }

    private boolean stream(int buffer) {
        int samples = 0;

        while ( samples < BUFFER_SIZE ) {
            pcm.position(samples);
            int samplesPerChannel = stb_vorbis_get_samples_short_interleaved(handle, channels, pcm);
            if ( samplesPerChannel == 0 )
                break;

            samples += samplesPerChannel * channels;
        }

        if ( samples == 0 )
            return false;

        pcm.position(0);
        alBufferData(buffer, format, pcm, sampleRate);
        samplesLeft -= samples / channels;

        return true;
    }

    public float getProgress() {
        return 1.0f - samplesLeft / (float)(lengthSamples);
    }

    public float getProgressTime(float progress) {
        return progress * lengthSeconds;
    }

    public void rewind() {
        stb_vorbis_seek_start(handle);
        samplesLeft = lengthSamples;
    }

    public void skip(int direction) {
        seek(min(max(0, stb_vorbis_get_sample_offset(handle) + direction * sampleRate), lengthSamples));
    }

    public void skipTo(float offset0to1) {
        seek(round(lengthSamples * offset0to1));
    }

    private void seek(int sample_number) {
        stb_vorbis_seek(handle, sample_number);
        samplesLeft = lengthSamples - sample_number;
    }

    public boolean play(int source, IntBuffer buffers) {
        for ( int i = 0; i < buffers.limit(); i++ ) {
            if ( !stream(buffers.get(i)) )
                return false;
        }

        alSourceQueueBuffers(source, buffers);
        alSourcePlay(source);

        return true;
    }

    public boolean update(int source, boolean loop) {
        int processed = alGetSourcei(source, AL_BUFFERS_PROCESSED);

        for ( int i = 0; i < processed; i++ ) {
            int buffer = alSourceUnqueueBuffers(source);

            if ( !stream(buffer) ) {
                boolean shouldExit = true;

                if ( loop ) {
                    rewind();
                    shouldExit = !stream(buffer);
                }

                if ( shouldExit )
                    return false;
            }
            alSourceQueueBuffers(source, buffer);
        }

        if ( processed == 2 )
            alSourcePlay(source);

        return true;
    }

    public void cleanUp () {
        stb_vorbis_close(this.handle);
    }

}
`

After this i have implemented an class VorbisSoundTrack, which is responsible for 1 vorbis sound:
`
/**
 * Created by Justin on 22.04.2016.
 */
public class VorbisSoundTrack implements Sound {

    /**
    * flags, if sound is loaded, playing and looping
    */
    protected AtomicBoolean isLoaded = new AtomicBoolean(false);
    protected AtomicBoolean isPlaying = new AtomicBoolean(false);
    protected AtomicBoolean isLooping = new AtomicBoolean(false);

    /**
    * vorbis decoder
    */
    protected VorbisDecoder decoder = null;

    /**
    * path to vorbis sound file
    */
    protected String path = "";

    /**
    * sourceID of vorbis sound in OpenAL
    */
    protected int source = 0;

    /**
    * sound buffer
    */
    protected IntBuffer buffers = BufferUtils.createIntBuffer(2);

    public VorbisSoundTrack () {
        //
    }

    @Override
    public void load(String path) throws SoundNotFoundException, SoundFileException, OpenALException {
        this.path = path;

        Logger.getRootLogger().debug("try to load vorbis soundtrack " + path + ".");

        if (!new File(path).exists()) {
            throw new SoundNotFoundException("Couldnt find vorbis sound file " + path + ".");
        }

        if (!isVorbisFile(path)) {
            throw new SoundFileException("Currently only .ogg soundtracks are supported.");
        }

        //generate and get sourceID of sound file in OpenAL
        this.source = AL10.alGenSources();

        //generate buffer for vorbis sound file in OpenAL
        AL10.alGenBuffers(buffers);

        //create new instance of vorbis decoder
        this.decoder = new VorbisDecoder(path);

        //set gain and pitch
        this.setGain(1.0f);
        this.setPitch(1.0f);
        this.setLooping(true);

        isLoaded.set(true);
    }

    @Override
    public void play() throws OpenALException {
        checkIfSoundIsLoaded();

        if (!decoder.play(source, buffers)) {
            System.err.println("Playback failed.");

            throw new OpenALException("Error oncurred while trying to play soundtrack " + path);
        }

        isPlaying.set(true);
    }

    @Override
    public void stop() {
        checkIfSoundIsLoaded();

        isPlaying.set(false);
    }

    @Override
    public void setGain(float gain) throws OpenALException {
        //set source gain
        AL10.alSourcef(source, AL10.AL_GAIN, gain);
        checkALError();
    }

    @Override
    public void setPitch(float pitch) throws OpenALException {
        //set pitch
        AL10.alSourcef(source, AL10.AL_PITCH, pitch);
        checkALError();
    }

    @Override
    public void setLooping(boolean looping) {
        /*if (looping) {
            //lets loop the sound
            AL10.alSourcei(source, AL_LOOPING, AL_TRUE);
        } else {
            AL10.alSourcei(source, AL_LOOPING, AL_FALSE);
        }

        checkALError();*/

        isLooping.set(looping);
    }

    @Override
    public void updateBuffers() throws OpenALException {
        if (!decoder.update(source, isLooping.get())) {
            Logger.getRootLogger().warn("Cannot update vorbis decoder for soundtrack " + this.path);
            throw new OpenALException("Cannot update soundtrack " + path + ".");
        }
    }

    @Override
    public boolean isPlaying() {
        return isPlaying.get();
    }

    @Override
    public void release() {
        isLoaded.set(false);

        AL10.alDeleteBuffers(buffers);
        AL10.alDeleteSources(source);

        this.decoder.cleanUp();
        this.decoder = null;
    }

    private void checkIfSoundIsLoaded () {
        if (!isLoaded.get()) {
            throw new IllegalStateException("sound isnt loaded yet.");
        }
    }

    private boolean isVorbisFile (String path) {
        return path.endsWith(".ogg");
    }

}
`

By the way, SoundUtils (for old version, see first post in this issue):
`
public class SoundUtils {

    /*
    * from lwjgl demo
    */
    public static ShortBuffer readVorbis(String resource, int bufferSize, STBVorbisInfo info) {
        ByteBuffer vorbis;
        try {
            vorbis = ioResourceToByteBuffer(resource, bufferSize);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        IntBuffer error = BufferUtils.createIntBuffer(1);
        long decoder = stb_vorbis_open_memory(vorbis, error, null);
        if ( decoder == 0l )
            throw new RuntimeException("Failed to open Ogg Vorbis file. Error: " + error.get(0));

        stb_vorbis_get_info(decoder, info);

        int channels = info.channels();

        int lengthSamples = stb_vorbis_stream_length_in_samples(decoder);

        ShortBuffer pcm = BufferUtils.createShortBuffer(lengthSamples);

        stb_vorbis_get_samples_short_interleaved(decoder, channels, pcm);
        stb_vorbis_close(decoder);

        return pcm;
    }

}
`

**Comment by Spasi** [comment]
Your code works fine for me. Things you can try:

- Don't use a background thread for the decoding.
- Try a different buffer size.
- Try a different ogg file.
