### ISSUE TITLE
GLU perspective

### ISSUE THREAD

**Issue by jediminer543** [LWJGL/lwjgl3#19]
My main perspective initialization in LWJGL 2 was GLU.gluPerspective
Is there an equivalent method in LWJGL 3?

**Comment by afiskon** [comment]
I tryed, lwjgl_util 2.9.3 does NOT work with lwjgl 3. For example, gluPerspective throws an exception:

```
Exception in thread "main" java.lang.NoSuchMethodError: org.lwjgl.opengl.GL11.glMultMatrix(Ljava/nio/FloatBuffer;)V
	at org.lwjgl.util.glu.Project.gluPerspective(Project.java:218)
	at org.lwjgl.util.glu.GLU.gluPerspective(GLU.java:286)
...
```

I believe a lot of people would appreciate if GLU would included in lwjgl 3.

**Comment by httpdigest** [comment]
I recommend you use the very nice [lwjglx](https://github.com/kappaOne/lwjglx) project by kappa, which is a compatibility layer on top of LWJGL 3 to adapt some of the APIs of LWJGL 2, including GLU, Display, Mouse and Keyboard.
It works really well with existing projects that require LWJGL 2, such as the Themable Widget Library.
If you merely want to have the "math" aspect of GLU, such as building a lookat or projection matrix, you could use [JOML](https://github.com/JOML-CI/JOML).
