### ISSUE TITLE
Bad allocation size in MemoryStack.callocPointer

### ISSUE THREAD

**Issue by juliencl** [LWJGL/lwjgl3#191]
The MemoryStack.callocPointer(int) function calls ncalloc(POINTER_SIZE, size, POINTER_SHIFT) (line 453). But ncalloc takes the size in bytes of each element to allocate in its third argument, not a bit shift. So the call to ncalloc should be replaced by: ncalloc(POINTER_SIZE, size, **POINTER_SIZE**)

**Comment by Spasi** [comment]
Thanks!

**Comment by juliencl** [comment]
You're welcome!
