### ISSUE TITLE
LWJGL 3.0.0 does not produce a window after upgrading from 3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by YohBen** [LWJGL/lwjgl3#198]
It seem like the LWJGL 3.0.0-SNAPSHOT is available anymore, so I had to go for LWJGL 3.0.0. However, to me it looks like the Mac binaries are broken.

I have downloaded the natives using the following script, that have been working in the past. The only line that has changed is:

     <lwjgl.version>3.0.0SNAPSHOT</lwjgl.version> -> <lwjgl.version>3.0.0</lwjgl.version>

**pom.xml:**

    <?xml version="1.0" encoding="UTF-8"?>
    <project xmlns="http://maven.apache.org/POM/4.0.0"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>Meltdown</groupId>
    <artifactId>Bitflip</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    
    <name>Bitflip</name>
    
    <properties>
        <lwjgl.version>3.0.0</lwjgl.version>
        
        <swt.version>4.5.1</swt.version>
        <joml.version>1.8.0</joml.version>
        <class>game.SpaceGame</class>
        <source>1.8</source>
        <target>1.8</target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <profiles>
        <profile>
            <id>mac</id>
            <activation>
                <os>
                    <family>Mac</family>
                </os>
            </activation>
            <dependencies>
                <dependency>
                    <groupId>org.lwjgl</groupId>
                    <artifactId>lwjgl-platform</artifactId>
                    <version>${lwjgl.version}</version>
                    <classifier>natives-osx</classifier>
                </dependency>
                <dependency>
                    <groupId>org.eclipse.swt</groupId>
                    <artifactId>org.eclipse.swt.cocoa.macosx.x86_64</artifactId>
                    <version>${swt.version}</version>
                </dependency>
            </dependencies>
        </profile>
    </profiles>
    <build>
        <sourceDirectory>src</sourceDirectory>
        <resources>
            <resource>
                <directory>res</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.5.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.4.3</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>org.lwjgl.demo.${class}</mainClass>
                                </transformer>
                            </transformers>
                            <finalName>lwjgl3-demos</finalName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>oss.sonatype.org</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>swt-repo</id>
            <url>http://maven-eclipse.github.io/maven</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>org.joml</groupId>
            <artifactId>joml</artifactId>
            <version>${joml.version}</version>
        </dependency>
        <dependency>
            <groupId>org.lwjgl</groupId>
            <artifactId>lwjgl</artifactId>
            <version>${lwjgl.version}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>RELEASE</version>
        </dependency>
    </dependencies>
    </project>

To be sure I made a test running the example code from LWJGL's web page: 

    package org.gooeybits.meltdown.alt;
    
    import org.lwjgl.Version;
    import org.lwjgl.glfw.*;
    import org.lwjgl.opengl.*;
    
    import static org.lwjgl.glfw.Callbacks.*;
    import static org.lwjgl.glfw.GLFW.*;
    import static org.lwjgl.opengl.GL11.*;
    import static org.lwjgl.system.MemoryUtil.*;
    
    public class Test {
    
        // The window handle
        private long window;
    
        public void run() {
            System.out.println("Hello LWJGL " + Version.getVersion() + "!");
    
            try {
                init();
                loop();
    
                // Free the window callbacks and destroy the window
                glfwFreeCallbacks(window);
                glfwDestroyWindow(window);
            } finally {
                // Terminate GLFW and free the error callback
                glfwTerminate();
                glfwSetErrorCallback(null).free();
            }
        }
    
        private void init() {
            // Setup an error callback. The default implementation
            // will print the error message in System.err.
            GLFWErrorCallback.createPrint(System.err).set();
    
            // Initialize GLFW. Most GLFW functions will not work before doing this.
            if (!glfwInit())
                throw new IllegalStateException("Unable to initialize GLFW");
    
            // Configure our window
            glfwDefaultWindowHints(); // optional, the current window hints are already the default
            glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE); // the window will stay hidden after creation
            glfwWindowHint(GLFW_RESIZABLE, GLFW_TRUE); // the window will be resizable
    
            int WIDTH = 300;
            int HEIGHT = 300;
    
            // Create the window
            window = glfwCreateWindow(WIDTH, HEIGHT, "Hello World!", NULL, NULL);
            if (window == NULL)
                throw new RuntimeException("Failed to create the GLFW window");
    
            // Setup a key callback. It will be called every time a key is pressed, repeated or released.
            glfwSetKeyCallback(window, (window, key, scancode, action, mods) -> {
                if (key == GLFW_KEY_ESCAPE && action == GLFW_RELEASE)
                    glfwSetWindowShouldClose(window, true); // We will detect this in our rendering loop
            });
    
            // Get the resolution of the primary monitor
            GLFWVidMode vidmode = glfwGetVideoMode(glfwGetPrimaryMonitor());
            // Center our window
            glfwSetWindowPos(
                    window,
                    (vidmode.width() - WIDTH) / 2,
                    (vidmode.height() - HEIGHT) / 2
            );
    
            // Make the OpenGL context current
            glfwMakeContextCurrent(window);
            // Enable v-sync
            glfwSwapInterval(1);
    
            // Make the window visible
            glfwShowWindow(window);
        }
    
        private void loop() {
            // This line is critical for LWJGL's interoperation with GLFW's
            // OpenGL context, or any context that is managed externally.
            // LWJGL detects the context that is current in the current thread,
            // creates the GLCapabilities instance and makes the OpenGL
            // bindings available for use.
            GL.createCapabilities();
    
            // Set the clear color
            glClearColor(1.0f, 0.0f, 0.0f, 0.0f);
    
            // Run the rendering loop until the user has attempted to close
            // the window or has pressed the ESCAPE key.
            while (!glfwWindowShouldClose(window)) {
                glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT); // clear the framebuffer
    
                glfwSwapBuffers(window); // swap the color buffers
    
                // Poll for window events. The key callback above will only be
                // invoked during this call.
                glfwPollEvents();
            }
        }
    
        public static void main(String[] args) {
            new Test().run();
        }
    }

I have also set the following VM options: 

    -XstartOnFirstThread 
    -Djava.awt.headless=true 

The following native binaries was downloaded (Maven):

    libglfw.dylib
    libjemalloc.dylib
    liblwjgl.dylib
    libopenal.dylib

When compiling and running the project, it executes normally with no warnings/errors or exceptions. The only thing missing is the window. I have tried both fullscreen and stand alone. But nothing. 

My question is can you see anything weird that I'm doing or have you had somthing similar happening?

**Comment by Spasi** [comment]
I cannot reproduce this with the 3.0.0 release build. Could you please try running the test from the command line (no maven or IDE)?

**Comment by YohBen** [comment]
Hi and thanks. I just ran it from the command prompt too, but no window. What Java version are you using?

$> javac HelloWorld.java  -cp .:lwjgl-3.0.0.jar:lwjgl-platform-3.0.0-natives-osx.jar
$> java -cp .:lwjgl-3.0.0.jar:lwjgl-platform-3.0.0-natives-osx.jar -Djava.library.path=./natives/ -Dorg.lwjgl.util.Debug=true -XstartOnFirstThread HelloWorld

Hello LWJGL 3.0.0 SNAPSHOT!
[LWJGL] Version: 3.0.0 SNAPSHOT
[LWJGL] 	 OS: Mac OS X v10.11.5
[LWJGL] 	JRE: 1.8.0_92 x86_64
[LWJGL] 	JVM: Java HotSpot(TM) 64-Bit Server VM v25.92-b14 by Oracle Corporation
[LWJGL] Loading library (system): lwjgl
[LWJGL] 	Loaded from java.library.path: ./natives/liblwjgl.dylib
[LWJGL] ThreadLocalUtil state: UnsafeState
[LWJGL] MemoryUtil accessor: MemoryAccessorUnsafe
[LWJGL] Loading library: glfw
[LWJGL] 	Loaded from java.library.path: ./natives/libglfw.dylib
[LWJGL] Loading library: objc
[LWJGL] 	libobjc.dylib not found in java.library.path=./natives/
[LWJGL] 	Loaded from system paths

$> java -version

java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

Thank you for looking into this.

**Comment by Spasi** [comment]
The Java version is not important, as long as it's Java 8 or newer.

A couple of issues with the above output:

- The LWJGL version printed should be `3.0.0 build 90`, not `3.0.0 SNAPSHOT`. Are you sure you're using the 3.0.0 release build?
- When you specify the natives in the classpath, you don't need to specify `java.library.path`.

**Comment by YohBen** [comment]
I'm going to double check that. Thanks

**Comment by YohBen** [comment]
Ok, This time I downloaded the stable from LWJGL's main webpage. Still no window.

This is the call that is never returned:
`return invokePPPP(__functionAddress, width, height, title, monitor, share); `
it is called in: 	
```
public class GLFW {...}
public static long nglfwCreateWindow(int width, int height, long title, long monitor, long share) {...}
```

I.e.: 
`GLFW.nglfwCreateWindow(...)`

I wonder if it could be something wrong in my libobjc.dylib?
```
$> ls -al /usr/lib/libobjc.dylib 
lrwxr-xr-x  1 root  wheel    15B 13 Jan  2015 /usr/lib/libobjc.dylib@ -> libobjc.A.dylib

$> cat /usr/lib/libobjc.A.dylib | md5 
20fa59e01787d76a8de77170e0eca416
```

Here is the output from running with the latest download:
```
$ java -cp .:./jar/*:./native -Djava.library.path=./native/ -Dorg.lwjgl.util.Debug=true -XstartOnFirstThread HelloWorld
Hello LWJGL 3.0.0 build 90!
[LWJGL] Version: 3.0.0 build 90
[LWJGL] 	 OS: Mac OS X v10.11.5
[LWJGL] 	JRE: 1.8.0_92 x86_64
[LWJGL] 	JVM: Java HotSpot(TM) 64-Bit Server VM v25.92-b14 by Oracle Corporation
[LWJGL] Loading library (system): lwjgl
[LWJGL] 	Loaded from java.library.path: ./native/liblwjgl.dylib
[LWJGL] ThreadLocalUtil state: UnsafeState
[LWJGL] MemoryUtil accessor: MemoryAccessorUnsafe
[LWJGL] Loading library: glfw
[LWJGL] 	Loaded from java.library.path: ./native/libglfw.dylib
[LWJGL] Loading library: objc
[LWJGL] 	libobjc.dylib not found in java.library.path=./native/
[LWJGL] 	Loaded from system paths
```

**Comment by YohBen** [comment]
Solved, thank you so much for your time. 

I uninstalled CUDA drivers and the JDK. Rebooted and installed Java 8 build 91, instead of build 92. 

And it worked. However I still do not know if it was something wrong with my CUDA installation, or if it was the JDK.

Big thanks,

```
java -cp .:./jar/*:./native -Djava.library.path=./native/ -Dorg.lwjgl.util.Debug=true -XstartOnFirstThread HelloWorld
Hello LWJGL 3.0.0 build 90!
[LWJGL] Version: 3.0.0 build 90
[LWJGL] 	 OS: Mac OS X v10.11.5
[LWJGL] 	JRE: 1.8.0_91 x86_64
[LWJGL] 	JVM: Java HotSpot(TM) 64-Bit Server VM v25.91-b14 by Oracle Corporation
[LWJGL] Loading library (system): lwjgl
[LWJGL] 	Loaded from java.library.path: ./native/liblwjgl.dylib
[LWJGL] ThreadLocalUtil state: UnsafeState
[LWJGL] MemoryUtil accessor: MemoryAccessorUnsafe
[LWJGL] Loading library: glfw
[LWJGL] 	Loaded from java.library.path: ./native/libglfw.dylib
[LWJGL] Loading library: objc
[LWJGL] 	Loaded from java.library.path: ./native/libobjc.dylib
[LWJGL] Loading library: /System/Library/Frameworks/OpenGL.framework
[LWJGL] 	Success
```
