### ISSUE TITLE
Centralized examples/starters module

### ISSUE THREAD

**Issue by httpdigest** [LWJGL/lwjgl3#201]
When further utilizing the repository mechanism with a modular LWJGL3 build, a next step could be to centralize different LWJGL3 tutorials/demos/examples as parts of a "starters" module.
The goal is that people trying to find LWJGL3 examples/tutorials on the internet with running code, can directly get them as part of a LWJGL3 build.

All different starter projects can be deployed anywhere by anyone on any Maven-compatible repository and be referenced by the lwjgl3-managed "starters" module.

When a user then goes to lwjgl.org/ all available starters will be presented and can be chosen to be packaged alongside the LWJGL3 library to form a readily executable project.

This is in an attempt to first bring all scattered LWJGL3 demos/examples/tutorials together for people to find more easily, and secondly, to encourage the community to build examples/demos.

**Comment by J-Ibarra** [comment]
I would like to contribute two small example I have done on physics, from the book Game Physics Engine Development by Ian Millington, the source code is in C ++ and uses the GLUT library , I 'm doing in Java using LWJGL and JOML

**Comment by httpdigest** [comment]
Sounds good. If people stick to deploying to a Maven repository (can also be done with Gradle) then the only thing necessary is a sources jar. Such a sources jar will for example be built when using the Maven Source Plugin when using a Maven build.

The current idea is to automatically download that sources jar from the repository, unpack its sources and use that as the sourc files in a downloaded LWJGL3 zip, along with the LWJGL3 libraries.

So, preferably you also have a hosted source repository somewhere to look at and test a build.

**Comment by httpdigest** [comment]
It should be noted that there is also issue #199, which discusses possible starters. This issue here is rather meant to document progress on a system that supports centralized management of such starters.

**Comment by J-Ibarra** [comment]
excuse me , I'm not an expert on Maven , Gradle or ant , just realize projects in eclipse, I 'm starting in the programming for video games fan , you could see these examples tranajando seguire them and adding new demos [JPhysicsEngine](https://github.com/J-Ibarra/JPhysicsEngine)

**Comment by httpdigest** [comment]
Closing this as it hasn't gotten any intereset in the last five years and it's probably on the off-topic-edge for LWJGL 3: teaching people how to use a library that LWJGL provides bindings for.
