### ISSUE TITLE
SVG parsing

### ISSUE THREAD

**Issue by czyzby** [LWJGL/lwjgl3#202]
Correct me if I'm wrong, but it seems that you currently cannot load SVG images. Since NanoVG bindings were added, it would make sense to include a parser for (arguably?) the most common vector graphics format. There seem to be relatively simple SVG parsers for Android ([like this one](https://github.com/japgolly/svg-android), [this one](https://github.com/pents90/svg-android/tree/master/svgandroid) or [this one](https://github.com/Pixplicity/sharp)), which obviously use pure Java and could potentially be ported to LWJGL.

**Comment by Spasi** [comment]
What about [Apache Batik](https://xmlgraphics.apache.org/batik/)?

Another option would be adding support for [NanoSVG](https://github.com/memononen/nanosvg), by the creator of NanoVG, but I'd like to avoid it if Batik does the job.

**Comment by iamcreasy** [comment]
Do you prefer Batik over NanoSVG because Batik is a entirely Java?

**Comment by Spasi** [comment]
We usually add bindings to LWJGL when there's no Java option or the native option is better. I personally haven't done any SVG parsing, so I'm just wondering whether Batik is a viable option. Being pure Java is an obvious advantage, but there are certainly other aspects to consider (binary size, runtime performance and GC pressure, features supported, etc).

**Comment by czyzby** [comment]
I went for simplicity when suggesting a possible solution - hence the listed Android libraries. I thought Batik relies on Swing/AWT, but it does seem highly modular.

**Comment by Spasi** [comment]
LWJGL now includes [NanoSVG](https://github.com/memononen/nanosvg) in the `NanoVG` bindings. I've also added a [demo](https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/test/java/org/lwjgl/demo/nanovg/SVGDemo.java) that downloads a `.svg` file, which then gets parsed, rasterized, converted to a texture and displayed on a canvas (similarly to the `stb_image` demo):

![lwjgl_nanosvg](https://user-images.githubusercontent.com/1545420/31125302-8b1c25d8-a850-11e7-957d-9c7365396510.jpg)

**Comment by GitFogux** [comment]
> LWJGL now includes [NanoSVG](https://github.com/memononen/nanosvg) in the `NanoVG` bindings. I've also added a [demo](https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/test/java/org/lwjgl/demo/nanovg/SVGDemo.java) that downloads a `.svg` file, which then gets parsed, rasterized, converted to a texture and displayed on a canvas (similarly to the `stb_image` demo):
> 
> ![lwjgl_nanosvg](https://user-images.githubusercontent.com/1545420/31125302-8b1c25d8-a850-11e7-957d-9c7365396510.jpg)

Le lien vers la demo n'est plus valide, je suppose que c'est désormais [:ici](https://github.com/LWJGL/lwjgl3/blob/master/modules/samples/src/test/java/org/lwjgl/demo/nanovg/SVGDemo.java)
