### ISSUE TITLE
Vulkan sample out of date

### ISSUE THREAD

**Issue by justin-gerhardt** [LWJGL/lwjgl3#208]
The Vulkan sample references methods that are no longer present

**Comment by Spasi** [comment]
All demos are synced with code changes that will appear in the next release (3.0.1). If you'd like to test the current Vulkan sample, you'd have to use the latest nightly/snapshot build.

If you're using the 3.0.0 build, you can see the state of the Vulkan sample at the corresponding point in time*, [here](https://github.com/LWJGL/lwjgl3/blob/9bebd53761f022863fe4c0ac72c9974e69e2cc5d/modules/core/src/test/java/org/lwjgl/demo/vulkan/HelloVulkan.java). There is indeed a breaking change, struct members that accept `VK_TRUE`/`VK_FALSE` are mapped to Java booleans now.

\* You can do this for any release by going to releases -> release version -> commit link (e.g. 9bebd53) -> Browse files
