### ISSUE TITLE
Release 3.0.1

### ISSUE THREAD

**Issue by benalexau** [LWJGL/lwjgl3#210]
I was just wondering if there's a timeframe on officially releasing 3.0.1? @Spasi added a LWJGL LMDB benchmark to https://github.com/lmdbjava/benchmarks and that code requires LWJGL 3.0.1-SNAPSHOT. The additional repository checking slows down builds, as Maven keeps checking for a new snapshot each day, plus I cannot enable our default organisation-wide enforcer rules as these are configured to reject [POM-defined repositories](https://maven.apache.org/enforcer/enforcer-rules/requireNoRepositories.html) as per Maven best practices. As 3.0.0b was released in November 2015, it would be great if you could please release 3.0.1 soon.

**Comment by samestep** [comment]
I am also interested in the release of 3.0.1. The [modular artifacts] will make it possible to write [wrappers][cljgl] of specific LWJGL bindings that work together in a way that makes sense, rather than wrapping *all* LWJGL bindings together (waste of time) or forcing users of wrapper libraries to pull in parts of LWJGL that they don't need.

[cljgl]: https://github.com/cljgl
[modular artifacts]: https://github.com/LWJGL/lwjgl3/issues/100

**Comment by Spasi** [comment]
LWJGL 3.0.1 will be released once the work for #100 is complete. Currently pending is the deployment of the various bindings as separate artifacts on Maven Central.

**Comment by Spasi** [comment]
LWJGL 3.1.0 has been released. Maven dependencies for `lwjgl-lmdb` on Linux:

```xml
<dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl</artifactId><version>3.1.0</version></dependency>
<dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl-lmdb</artifactId><version>3.1.0</version></dependency>

<dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl</artifactId><version>3.1.0</version><classifier>natives-linux</classifier><scope>runtime</scope></dependency>
<dependency><groupId>org.lwjgl</groupId><artifactId>lwjgl-lmdb</artifactId><version>3.1.0</version><classifier>natives-linux</classifier><scope>runtime</scope></dependency>
```

**Comment by benalexau** [comment]
@Spasi thanks for making the release. I reverted the removal in the LmdbJava benchmarks, and also updated to LWJGL 3.1.0 in commit https://github.com/lmdbjava/benchmarks/commit/e5209d65604619e57f2b4bdfb257c31a79da0bd9.
