### ISSUE TITLE
setting _JAVA_OPTIONS creates non working jars

### ISSUE THREAD

**Issue by chriscamacho** [LWJGL/lwjgl3#211]
if I use
```
    ant release
```
while the environment variable _JAVA_OPTIONS is set, the build works fine but when later trying to actually use the jars I see:
```
Picked up _JAVA_OPTIONS: -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
Buildfile: /home/chris/development/phys-ed/build.xml

compile:
    [javac] Compiling 241 source files to /home/chris/development/phys-ed/bin
    [javac] error: error reading /home/chris/development/phys-ed/libs/lwjgl-glfw.jar; invalid header field name: Picked up _JAVA_OPTIONS
    [javac] 1 error
```
simply unsetting the environment variable and running the release target makes working jars

just to be clear, if the jars are made with the variable set, unsetting it has no effect on attempting to use the jar, they can be opened with an archive application and *seem* normal

in case it helps? here is an example manifest.mf
```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.7
Created-By: 1.8.0_101-b13 (Oracle Corporation)

Name: org/lwjgl/
Specification-Title: Lightweight Java Game Library - GLFW
Specification-Version: 3.0.1 SNAPSHOT
Picked up _JAVA_OPTIONS: -Dswing
 .defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel
Specification-Vendor: lwjgl.org
Implementation-Title: lwjgl-glfw
Implementation-Version: SNAPSHOT
Implementation-Vendor: lwjgl.org
```

**Comment by Spasi** [comment]
I'm not sure what's happening here, but I don't think it's something we'll be able to fix from our side. We don't do anything special when building JARs.

Setting global variables that affect all Java processes doesn't sound like a good idea anyway.

**Comment by chriscamacho** [comment]
while I agree with you its the only way to make the Arduino SDK actually readable! and its a pain if I forget, the feed back from Java of

Picked up _JAVA_OPTIONS: -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel

must be somehow be getting included into parsed output and included in the meta by the build process, is there any parsing done by the build system to make the manifest ?

I had a quick look but time was limited and its a reasonably complex build, thought it would be better reporting here for those more familiar with how it works...

**Comment by Spasi** [comment]
I think I found the problem, could you please try again with the above commit?

**Comment by chriscamacho** [comment]
I think you did indeed, top work, much appreciated, keep up the good work!
