### ISSUE TITLE
license in comments points to 404 

### ISSUE THREAD

**Issue by chriscamacho** [LWJGL/lwjgl3#212]
```
/*
 * Copyright LWJGL. All rights reserved.
 * License terms: http://lwjgl.org/license.php
 */
```

```
[chris@xpslaptop ~]$ wget  http://lwjgl.org/license.php
--2016-08-03 12:46:52--  http://lwjgl.org/license.php
Resolving lwjgl.org (lwjgl.org)... 54.173.212.243
Connecting to lwjgl.org (lwjgl.org)|54.173.212.243|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://www.lwjgl.org/license.php [following]
--2016-08-03 12:46:52--  https://www.lwjgl.org/license.php
Resolving www.lwjgl.org (www.lwjgl.org)... 54.173.212.243
Connecting to www.lwjgl.org (www.lwjgl.org)|54.173.212.243|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-08-03 12:46:52 ERROR 404: Not Found.
```

**Comment by apostolos** [comment]
Temporarily fixed with an NGINX rewrite ( 301 Moved Permanently ) to the correct URL [https://www.lwjgl.org/license](https://www.lwjgl.org/license)

@Spasi Please update license URL to avoid redirects ( one from http://lwjgl.org to https://www.lwjgl.org  and one for the actual path ).

**Comment by kappaOne** [comment]
While we're talking licence, on the footer of the lwjgl.org site it says "Licensed under GPL" shouldn't that say "Licensed under BSD" ?

**Comment by apostolos** [comment]
@kappaOne It should! My bad.

https://github.com/LWJGL/lwjgl3-www/commit/9ec95247f5996fbe99b7fc7066d735a0aa6d3e07
