### ISSUE TITLE
Jack error message

### ISSUE THREAD

**Issue by CreamyCookie** [LWJGL/lwjgl3#214]
I'm getting the following message when I use lwjgl3 (with LibGDX):

```
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
```

I get this whether or not I'm playing or initializing a sound. Audio works though. I don't get this with lwjgl 2. I'm on Ubuntu 16.04. 

I don't know what else I need to provide, so feel free to ask me about any information you need to fix this.

**Comment by kappaOne** [comment]
This is a message thrown by [OpenAL-Soft](https://github.com/kcat/openal-soft) (libopenal.so) and not LWJGL3. If it is a problem and you need a quick fix you could always just replace libopenal.so with an older version (such as the one bundled with LWJGL2).

**Comment by CreamyCookie** [comment]
@kappaOne Oops, sorry! I'll report it there. 
Thanks for the quickfix suggestion!
