### ISSUE TITLE
org.lwjgl.ntd.NativeFileDialog refers to non-existing demos

### ISSUE THREAD

**Issue by TheMrMilchmann** [LWJGL/lwjgl3#215]
The documentation within `org.lwjgl.ntd.NativeFileDialog` refers to the non existing demos at:

> "https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/test/java/org/lwjgl/demo/nfd/HelloNFD.java#L104" (Single file open dialog)

> "https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/test/java/org/lwjgl/demo/nfd/HelloNFD.java#L126" (Multiple file open dialog)

> "https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/test/java/org/lwjgl/demo/nfd/HelloNFD.java#L151" (Save dialog)

_Not sure if an issue should be submitted for this since it's an minor "bug"._

**Comment by Spasi** [comment]
Thanks!
