### ISSUE TITLE
Native library loading seems to be OSGi-incompatible again

### ISSUE THREAD

**Issue by io7m** [LWJGL/lwjgl3#216]
Hello.

LWJGL was at one point incompatible with OSGi due to the way that it attempted to load native libraries:

https://github.com/LWJGL/lwjgl3/issues/41

It seems that this was fixed by one of the referenced commits:

https://github.com/LWJGL/lwjgl3/commit/2543603d062a268bea6adf871c8afa592bddd97b

However, that commit seems to reference a class called `LWJGLUtil.java`. That class doesn't appear to be part of the 3.0.0 release:

```
$ unzip -l ~/.m2/repository/org/lwjgl/lwjgl/3.0.0/lwjgl-3.0.0.jar | grep LWJGLUtil
$
```

It seems that the 3.0.0 release makes calls into the `org.lwjgl.system.Library` class, which then calls `System.load`, which then fails under OSGi (where `System.loadLibrary` would work), and then falls back to manually searching for native libraries, which of course also fails.

I'm trying to produce an application using OSGi, and LWJGL currently can't be packaged for that environment due to the above issue. Is it possible to get `System.loadLibrary` back? Even if it's just an optional code path taken when a specific property is set, that would be fine.

**Comment by Spasi** [comment]
The native library loading code in LWJGL has been enhanced in order to output useful information under debug mode. This has been very useful to debug startup issues and helps a ton when users report issues to us.

Indeed, the current implementation does not call `System.loadLibrary` anymore; it's opaque and we can't print the information we need.

LWJGL should work fine without doing anything special for the native libraries, except adding them to the classpath. Do you really have to use OSGi's native library loading functionality? What happens if you skip `Bundle-NativeCode:`? Is there a benefit you'd miss if you do that?

**Comment by io7m** [comment]
Hi. I'll try to address each thing individually:

> LWJGL should work fine without doing anything special for the native libraries, except adding them to the classpath.

As you may know, there isn't a classpath in OSGi. There is, in some sense, a classpath inside each individual bundle. Bundles cannot see native libraries loaded by other bundles, and each bundle is assigned its own classloader.

This means that at a minimum, in order for LWJGL to work, the LWJGL jar and individual platform jars have to be re-packed into a single bundle. This isn't an issue, can be done in an automated manner externally, and doesn't require any changes on the part of LWJGL right now. However, I can see a problem looming ahead introduced by the need to merge the jars. This ticket for example: #206 

Right now, the binaries inside each LWJGL platform jar are named generically and placed in the root of the jar file. This means that (assuming the current structure stays the same) if, for example, LWJGL gains ARM support on Linux, there'll be a `liblwjgl.so` in the root of the x86 platform jar, and a `liblwjgl.so` in the root of the ARM platform jar. This means that the platform jars can no longer be packed into a single OSGi bundle without file collisions unless an extra bit of indirection is added in a manner that LWJGL's library loading code can understand (such as moving each library to `natives/linux/x86/liblwjgl.so`, `natives/linux/armv6/liblwjgl.so` directories in each platform jar so that the jars could be merged without any collisions).

We could instead avoid all of this, unpack the native libraries manually into the filesystem and use `java.library.path`. Unfortunately, this would then seriously complicate OSGi's live upgrades of packages/bundles (some code would have to run *somewhere* to manually clean up the directory used to hold the natives).

> Do you really have to use OSGi's native library loading functionality?

There's one major thing that would be lost without it. For one, the metadata in each bundle specifies exactly which native libraries are present and on which platform they work. When a bundle is installed, it begins in the `INSTALLED` state and is then moved to the `RESOLVED` state when all dependencies have been accounted for and the system is sure that the bundle can actually work in the current execution environment. If the metadata for the native libraries states that the bundle doesn't support the current platform, you get a very unambiguous error message describing the exact problem, and the bundle will not be `RESOLVED`. This sort of error reporting is standardized across OSGi, and various OSGi services use this information for performing deployments and the like. If OSGi's native library loading can't be used, the LWJGL bundle basically becomes a second class citizen with any native library issues occurring at the latest possible moment and in a manner that the OSGi container can't "see".

> Indeed, the current implementation does not call System.loadLibrary anymore; it's opaque and we can't print the information we need.

I suspected this would be the case, and it's why I suggested a property that can be set at run-time to enable it. Something along the lines of `-Dlwjgl.i.am.using.osgi.and.know.what.i.am.doing=true` that would cause the loading code to fall back to the mindless `loadLibrary` path for use in OSGi. In other words, if you don't turn on that property, nothing about LWJGL's library loading code changes.

**Comment by Spasi** [comment]
Thanks for the detailed explanation. You were correct to assume that I don't know much about OSGi, the above helped a lot.

> As you may know, there isn't a classpath in OSGi. There is, in some sense, a classpath inside each individual bundle. Bundles cannot see native libraries loaded by other bundles, and each bundle is assigned its own classloader.

> This means that at a minimum, in order for LWJGL to work, the LWJGL jar and individual platform jars have to be re-packed into a single bundle.

Is there a 1:1 relationship between a "bundle" and a JAR? Isn't it possible to define a bundle using multiple JARs?

> This means that the platform jars can no longer be packed into a single OSGi bundle without file collisions unless an extra bit of indirection is added in a manner that LWJGL's library loading code can understand (such as moving each library to natives/linux/x86/liblwjgl.so, natives/linux/armv6/liblwjgl.so directories in each platform jar so that the jars could be merged without any collisions).

LWJGL 3 initially used a similar structure. At some point it became clear that users preferred a flat structure, as in LWJGL 2. For this reason we now have binaries with architecture/ABI suffixes (e.g. `lwjgl.dll` on Win64, `lwjgl32.dll` on Win32). When we add ARM support, the new binaries will have appropriate suffixes (e.g. `liblwjgl-arm64-vfp-hflt.so` and `liblwjgl-arm32-vfp-hflt.so`), so collisions won't be an issue. Ugly, but it'll work.

> I suspected this would be the case, and it's why I suggested a property that can be set at run-time to enable it.

Yes, that would be a solution. But I'd like to first consider other, possibly cleaner, options.

**Comment by io7m** [comment]
> Is there a 1:1 relationship between a "bundle" and a JAR? Isn't it possible to define a bundle using multiple JARs?

Yes, a bundle is just a single jar file with some extra data in the manifest that says what packages are exported, what packages are imported, etc. Now you mention it, there actually is a way to split a bundle across several jars, but I'm not sure it was ever intended for doing things like this. There's such a thing as "fragment bundles". Basically, a bundle can specify a "host" bundle and its contents are effectively added to the host. It's usually used for localization (overriding resources with locale-specific strings and the like). All things being equal, it probably could be used for adding native libraries (but we'd still miss out on the nice benefits of OSGi's native library loading).

> When we add ARM support, the new binaries will have appropriate suffixes (e.g. liblwjgl-arm64-vfp-hflt.so and liblwjgl-arm32-vfp-hflt.so), so collisions won't be an issue.

Good to know!

**Comment by Spasi** [comment]
I made it work without a special flag. Could you please test with the above commit?

Btw, this applies to "JNI" libraries only (native libraries that the JVM links with Java native methods). Other libraries (jemalloc, glfw, openal-soft that are bundled with LWJGL and system libraries like OpenGL, Vulkan, etc) are loaded using platform specific APIs (`LoadLibrary`, `dlopen`, etc).

**Comment by io7m** [comment]
Silly question: I've compiled the java and native code, but what's the right command to use to produce the jar files? I'd like to make sure I'm producing them exactly the same way that you would in order to have some degree of confidence that I'm giving the OSGi tools the same sort of input that I'd receive had I just downloaded the LWJGL binaries.

**Comment by Spasi** [comment]
Running `ant release` should do it.

Or, you could download the latest [nightly build](https://www.lwjgl.org/download) (3.0.1 b14), it includes the above commit.

**Comment by io7m** [comment]
It'll take me a little longer than expected to report results as I was still working with the old monolithic jar from 3.0.0, as opposed to the new modular jars from 3.0.1. Currently redoing the scripts that produce an OSGi bundle.

**Comment by io7m** [comment]
OpenGL seems to work. Thanks!
