### ISSUE TITLE
Format error in the source code

### ISSUE THREAD

**Issue by Sogomn** [LWJGL/lwjgl3#217]
https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/main/java/org/lwjgl/opengl/GL.java#L329
Will always throw an error. "%X" is not a valid string format.

**Comment by Spasi** [comment]
It is valid. From [Formatter](https://docs.oracle.com/javase/8/docs/api/java/util/Formatter.html)'s documentation:

```'x', 'X'    integral    The result is formatted as a hexadecimal integer```

**Comment by Sogomn** [comment]
Throws an exception for me. Java 8, precompiled LWJGL.

**Comment by Spasi** [comment]
That bug has been fixed with #194. Try the 3.0.1 nightly build.
