### ISSUE TITLE
Play video with LWJGL

### ISSUE THREAD

**Issue by JuKu** [LWJGL/lwjgl3#218]
Hi,

Is there an feature to easy play an video on LWJGL window?

**Comment by Spasi** [comment]
Not at the moment. There are several options available, but so far we've been trying to focus on more important bindings and keeping the library size small enough (i.e. comparable to LWJGL 2).

This will change once the work on #100 is complete. We'll be able to add more bindings without worrying about how it will affect the default distribution. This includes bindings to tools that are used only offline (e.g. SPIR-V/glslang), or heavyweight stuff like video decoding.

**Comment by arisona** [comment]
I have started an independent project some time ago. The idea is to use the native OS libraries (AVFoundation on Mac, WMF on Windows) for decoding. It's incomplete as of now, but decoding on Mac works reasonably well. I will continue when I find time, but contributions are of course welcome. https://github.com/arisona/avion

**Comment by Speiger** [comment]
@Spasi i know this is most likely asked to death. 
But has there been any updates on this specific feature?
I would say providing a full video player sounds overkill, but a decoding library where you can at least implement your own video player would be interesting.

At least a comment of the current situation would be nice :)

**Comment by Spasi** [comment]
Hey @Speiger,

Have you tried the ffmpeg module from [javacpp-presets](https://github.com/bytedeco/javacpp-presets)? If it's complete and working reasonably well, I don't think it's worth duplicating that effort in LWJGL.

**Comment by Speiger** [comment]
Hey @Spasi I wasn't aware of that modul!
That is a treasure trove!

Thank you I will try that out :)
