### ISSUE TITLE
glfwDestroyWindow throws NullPointerException

### ISSUE THREAD

**Issue by samestep** [LWJGL/lwjgl3#220]
## Expected behavior

In GLFW, `glfwDestroyWindow` [explicitly ignores][glfw] a `NULL` argument:

> ```c
> // Allow closing of NULL (to match the behavior of free)
> if (window == NULL)
>     return;
> ```

So this C program executes without error:

```c
#include <GLFW/glfw3.h>

int main(void) {
  glfwInit();
  glfwDestroyWindow(NULL);
  glfwTerminate();
}
```

## Actual behavior

However, in LWJGL, `glfwDestroyWindow` [explicitly fails][lwjgl] on a `NULL` argument:

> ```java
> if ( CHECKS )
>         checkPointer(window);
> ```

So this Java program throws a `NullPointerException`:

```java
import static org.lwjgl.glfw.GLFW.*;
import static org.lwjgl.system.MemoryUtil.*;

class DestroyNull {
  public static void main(String[] args) {
    glfwInit();
    glfwDestroyWindow(NULL);
    glfwTerminate();
  }
}
```

[glfw]: https://github.com/glfw/glfw/blob/3.2.1/src/window.c#L382-L384
[lwjgl]: https://github.com/LWJGL/lwjgl3-generated/blob/520cdce9894071f4f44451c5b15fc21d5f118918/java/org/lwjgl/glfw/GLFW.java#L1664-L1665

**Comment by Spasi** [comment]
Thanks!
