### ISSUE TITLE
LWJGL 3.0.1-SNAPSHOT api jar is broken

### ISSUE THREAD

**Issue by JuKu** [LWJGL/lwjgl3#222]
LWJGL 3.0.1-SNAPSHOT api jar is broken.
Maven has updatet the current LWJGL 3.0.1-Snapshot from Maven Central and couldnt find the most classes.
Only the system package is available anymore.

Here is the jar file:
[LWJGL_Snapshot_Build.zip](https://github.com/LWJGL/lwjgl3/files/438050/LWJGL_Snapshot_Build.zip)

Maven log is like this:
```
Download https://oss.sonatype.org/content/repositories/snapshots/org/lwjgl/lwjgl/3.0.1-SNAPSHOT/lwjgl-3.0.1-20160825.134649-7.pom
Download https://oss.sonatype.org/content/repositories/snapshots/org/lwjgl/lwjgl/3.0.1-SNAPSHOT/lwjgl-3.0.1-20160825.134649-7.jar
D:\Users\Justin\IdeaProjects\pentaquin-core\pentacore-context\src\main\java\com\pentaquin\core\context\GLFWContext.java:17: error: package org.lwjgl.glfw does not exist
import org.lwjgl.glfw.*;
^
<Path>GLFWContext.java:18: error: package org.lwjgl.opengl does not exist
import org.lwjgl.opengl.*;
^
<Path>GLFWContext.java:21: error: package org.lwjgl.stb does not exist
import org.lwjgl.stb.STBImage;
                    ^
<Path>GLFWContext.java:52: error: cannot find symbol
	private GLFWKeyCallback keyCallback;
	        ^
  symbol:   class GLFWKeyCallback
  location: class GLFWContext
<Path>GLFWContext.java:53: error: cannot find symbol
	private GLFWCursorPosCallback cursorCallback;
```

And so on.

**Comment by Spasi** [comment]
The snapshot isn't broken, see [this reply](https://github.com/LWJGL/lwjgl3/issues/100#issuecomment-242405634). The *lwjgl* artifact now contains the core library only. There are new artifacts for each binding that you have to declare in your Maven/Gradle builds.

**Comment by JuKu** [comment]
@Spasi Thanks!
Is there an Changelog available?
Which modules (maven coordinates) do we have to include to have all features from versions before this SNAPSHOT?

**Comment by Spasi** [comment]
> Is there an Changelog available?

The work-in-progress 3.0.1 changelog is available [here](https://github.com/LWJGL/lwjgl3/blob/master/doc/notes/3.0.1.md).

> Which modules (maven coordinates) do we have to include to have all features from versions before this SNAPSHOT?

For now, you can see the list of available artifacts [here](https://oss.sonatype.org/content/repositories/snapshots/org/lwjgl/). Ignore the following: `lwjgl-natives-linux`, `lwjgl-natives-macosx`, `lwjgl-natives-windows`, `lwjgl-platform`. The Maven coordinates look like `'org.lwjgl:lwjgl:3.0.1-SNAPSHOT'`. Many artifacts come with native libraries, you use classifiers to get them, e.g. `'org.lwjgl:lwjgl:3.0.1-SNAPSHOT:natives-linux'`.

We'll soon have a tool on the website that will generate the Maven/Gradle dependency declarations for you. You'll be able to select only the bindings you need (or all of them), the target platform, the declaration style, etc, then you'll just copy/paste the output in your project.

**Comment by kappaOne** [comment]
Something seems to have broken on my mac system (OSX 10.11) between "LWJGL 3.0.1 build 16" and "LWJGL 3.0.1 build 17" with OpenAL, the following calls now return just '0', whereas previously they returned proper values:

`int bytes = AL10.alGetBufferi(buffer, AL10.AL_SIZE);

int bits = AL10.alGetBufferi(buffer, AL10.AL_BITS);

int channels = AL10.alGetBufferi(buffer, AL10.AL_CHANNELS);`

Same code with build 17 works fine on linux.

**Comment by JuKu** [comment]
@Spasi Thanks! :D
