### ISSUE TITLE
Setup a messaging app like slack or gitter

### ISSUE THREAD

**Issue by Firenox89** [LWJGL/lwjgl3#226]
In my opinion it would be a good idea to set up some messaging service like [slack](https://slack.com/) or [gitter](https://gitter.im/), so this "issues" labeled as questions could be moved to there.
Also it would enable more chat-like conversation than the forum and potential contributors (like me :)) could ask some project related questions there. (e.g. is there a reason for some c file to be inside your include directory).

**Comment by kenzierocks** [comment]
I think gitter would be better, but there is still a very inactive IRC channel on Freenode.

**Comment by Spasi** [comment]
I would prefer Slack, because I'm already using it for work. It's not ideal for open source communities (up to 10k messages archived, user count limits), but some projects use it successfully (e.g. `kotlinlang` with over 3900 users atm).

**Comment by Spasi** [comment]
> up to 10k messages archived

[This](http://slackarchive.io/) looks like a solution for that. Does anyone have experience with it?

**Comment by Firenox89** [comment]
So I had a quick look at gitter and slack, my impression was that slack is a bit richer feature-wise. Like share files or select a language for highlighting code snippets. On slack it seems that you need to give permission for joining, while on gitter you don't need to do this, don't know if that is a up or downside for you.
When googling for it, this story pops up about the guys who regret using slack, but they seem to have +8000 users and then reached the limits for free usage. Also as you already pointed out, there are solutions for the message limit, so I would suggest to go with slack.

**Comment by JuKu** [comment]
Gitter is newer.

The best thing of Slack are the integrations, you can add an channel, where Github post, if someone pushed an commit or if an build failed. Or you can be notified, if someone write an issue.
https://medium.freecodecamp.com/so-yeah-we-tried-slack-and-we-deeply-regretted-it-391bcc714c81#.mysggpdd6

But Slack has a few limitations, Gitter not.
https://gitter.im/#pricing-panel

Gitter has also Integrations:
https://gitter.im/#integrations-panel

Also Gitter is modern, but its an little bit IRC like.

**Comment by JuKu** [comment]
@Spasi You need an Slack account for every team, so you need an new slack account to use it for LWJGL.
Maybe Gitter can be the better choice.

**Comment by JuKu** [comment]
Maybe also Discord can be interesting for you:
https://discordapp.com/

Its an Text and voice messanger in one app.
But i havent tested it yet.

**Comment by Spasi** [comment]
A Slack team for LWJGL is now available. Visit [this page](https://www.lwjgl.org/slack/) to invite yourselves.
