### ISSUE TITLE
IDE Setup refers to missing directory

### ISSUE THREAD

**Issue by kenzierocks** [LWJGL/lwjgl3#229]
[This](https://github.com/LWJGL/lwjgl3/blob/master/doc/README.md#user-content-installation) mentions a pre-configured IDEA setup, but that simply [doesn't exist](https://github.com/LWJGL/lwjgl3/tree/master/config/ide).

**Comment by Spasi** [comment]
Thanks, the IDEA project has recently been moved to the repository root. The Gradle plugin hated the nested project structure.
