### ISSUE TITLE
The SharedLibraryLoader does not detect changes in bindings

### ISSUE THREAD

**Issue by kenzierocks** [LWJGL/lwjgl3#230]
When using `nvgCreateGL3`, I get [this crash](https://gist.github.com/kenzierocks/5b1c85c4c308f7099b97cee7909dd59f#file-hs_err_pid70787-log).
Code that reproduces the crash: https://gist.github.com/kenzierocks/87901318e0109cfb4861e1d9b2e9e63c

Logs: https://gist.github.com/kenzierocks/5b1c85c4c308f7099b97cee7909dd59f

**Comment by Spasi** [comment]
It looks like it's crashing in the OpenGL driver at `glGetProgramInfoLog`. This is only called by NanoVG if its shader program fails to link.

I cannot reproduce this on my Mac (El Capitan with Intel Iris 6100, driver version 10.14.73). Both your code and the LWJGL samples work fine. It could be a bug in the updated Intel driver (10.18.65) on Sierra.

**Comment by kenzierocks** [comment]
Interestingly, I didn't get this crash in build 18 of LWJGL. Did you change something recently related to this?

**Comment by Spasi** [comment]
Hmm, [yes](https://github.com/LWJGL/lwjgl3/commit/90dccf4172d1b32c96e74cf22ac5053497191b82).

**Comment by kenzierocks** [comment]
I tried out the ExampleGL3 demo, and it worked fine, so it might be something in my code, although I'm not sure what yet.

**Comment by kenzierocks** [comment]
I've figured out the problem. I guess that the library extractor doesn't clean up old versions of files, so I had old natives lying around that I needed to remove. Perhaps the extractor should be cleaning these up when the build number differs?

**Comment by Spasi** [comment]
You're correct, the current `SharedLibraryLoader` implementation is problematic with the modular structure. It only checks for changes in the core library, which from now on is going to change very rarely.
