### ISSUE TITLE
MacOS: some tests/demos do not run when built from source

### ISSUE THREAD

**Issue by code-disaster** [LWJGL/lwjgl3#234]
I'm on OS X 10.11.6. If I build LWJGL3 from source, any tests and demos depending on libjemalloc.dylib or libglfw.dylib do not run.

I got them working by manually replacing both libraries in lwjgl3/libs/ with copies I pulled from my local folder of lwjgl3-demos/target/. So, for some reason it doesn't seem to like the .dylibs pulled from the AWS server during update-dependencies.

**Comment by Spasi** [comment]
I may have fixed the issue, could you please try again?

**Comment by code-disaster** [comment]
Yes, can confirm it's working now. Thanks!
