### ISSUE TITLE
nk_style_from_table() doesn't take in table.

### ISSUE THREAD

**Issue by surGeonGG** [LWJGL/lwjgl3#236]
First of all, I'm really new to programming and I don't understand most of the things going on in lwjgl or its nuklear bindings so maybe this is just me being stupid. 

Here's the issue though: I'm struggling to find out how to style a nuklear gui that I've been able to hack together by looking at the demo code. Going by [this](https://github.com/vurtun/nuklear/blob/master/demo/style.c) demo in the original C library it should be possible to do it with nk_style_from_table(), but the problem is that nk_style_from_table() in lwjgl doesn't take in an array of NkColors. It takes in a NkColor. 

Is this a bug or am I missing something?

**Comment by Spasi** [comment]
Thanks, it was indeed a bug in the binding. In the next nightly build, the `table` parameter will be an `NkColor.Buffer`. A `Buffer` inner class is how an array of structs of the corresponding struct type is represented in LWJGL.

**Comment by surGeonGG** [comment]
[I'm helping](http://i.imgur.com/zsJcxSG.jpg)
