### ISSUE TITLE
Nuklear demos naming scheme

### ISSUE THREAD

**Issue by dustContributor** [LWJGL/lwjgl3#247]
Another tiny suggestion.

When reading Nuklear demos I come across various methods named as if they were native Nuklear functions, 'nk_glfw3_render' for example, instead of nkGlfw3Render or something more "Java-like".

It makes reading the examples pretty confusing since I'm not sure if I'm looking at a Nuklear function or at a Java method being called.

**Comment by dustContributor** [comment]
I get now that its a direct port from Nuklear demos. Maybe I should raise the issue there and ask them not to start those functions with "nk_"?

**Comment by Spasi** [comment]
> Maybe I should raise the issue there and ask them not to start those functions with "nk_"?

It's OK, I'll rename the methods in our port.

**Comment by dustContributor** [comment]
Thanks!
