### ISSUE TITLE
ThreadLocalUtil questions

### ISSUE THREAD

**Issue by dustContributor** [LWJGL/lwjgl3#248]
So the first question is, it works by hijacking and wrapping the Runnable of whatever thread you're running on right?

Second is about this line:
https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/main/java/org/lwjgl/system/ThreadLocalUtil.java#L105

Why "ThreadLocalState.class.isInstance(target)" instead of "(target instanceof ThreadLocalState)"? Shouldn't the instanceof operator run faster than dynamically checking the type through isInstance? Or the VM detects the static receiver there and compiles it down to the same instructions?

**Comment by Spasi** [comment]
> So the first question is, it works by hijacking and wrapping the Runnable of whatever thread you're running on right?

Yes. It's the dirtiest hack in LWJGL, but faster than the `ThreadLocalMap` lookup. The performance difference is negligible for most functions, but important in some cases. It inlines better, compiles to much fewer instructions and there is no slow-path fallback.

> Why "ThreadLocalState.class.isInstance(target)" instead of "(target instanceof ThreadLocalState)"? Shouldn't the instanceof operator run faster than dynamically checking the type through isInstance? Or the VM detects the static receiver there and compiles it down to the same instructions?

I don't remember why I used `isInstance`, but yes, it should be equivalent to `instanceof` in this case. I'll re-run the benchmarks to verify.

**Comment by Spasi** [comment]
JMH results, in CPU cycles:

- `ThreadLocal`: 9-10 (~3.1ns)
- Unsafe with `isInstance`: 4
- Unsafe with `instanceof`: 3

I will change it to `instanceof` in the next nightly.

I also tested with [OPENGL_CAPABILITIES_STATE](https://github.com/LWJGL/lwjgl3/blob/83f54ad103ddac83fcef76aa3ac60c0d3e9888b1/modules/core/src/main/java/org/lwjgl/system/Configuration.java#L310) set to `static`: 1 CPU cycle. This is also completely eliminated in real code (i.e. when doing multiple OpenGL calls). Make sure you read the documentation before using. OpenAL and OpenGL ES have an equivalent option.

**Comment by dustContributor** [comment]
You could call it like "25% performance gain in thread locals!" for the next stable changelog :stuck_out_tongue_closed_eyes:
