### ISSUE TITLE
Including the native jar-files of LWJGL 3.1.0 in Eclipse

### ISSUE THREAD

**Issue by Lein4d** [LWJGL/lwjgl3#249]
Hi,

I'm wondering how to reference the native libraries of version 3.1.0 build 40 in Eclipse, for example lwjgl-glfw-natives-windows.jar. Just referencing the main jar like lwjgl-glfw.jar gives me an UnsatisfiedLinkError-Exception, but also adding the native jar file to the build path doesn't resolve the error. I've also tried setting the native library location, but as there aren't any native libraries anymore (at least not as .dll files) it didn't work as well.

So what is the right way of doing it?

**Comment by httpdigest** [comment]
Adding the native jar libraries to the normal Java build path suffices and should work.

However, if you want to avoid having to manage the modules' jar files manually in Eclipse, the by far easiest setup would be to use Maven or Gradle.

For this, go to https://lwjgl.org/download , hit the "Nightly" tab, select "Mode" = "Maven" and copy the resulting "Snippet" into your pom.xml. Eclipse supports generating a scaffold pom.xml for you in the default installation, by simply right-clicking your project (either in "Package Explorer" view or in the "Navigator" view) and selecting "Configure -> Convert to Maven Project".

Now you can just paste the Snippet from the lwjgl.org/download site into the generated pom.xml as child of the <project> root element.

**Comment by Lein4d** [comment]
I added them to the build path and it didn't work. I've also tried extracting the natives from the jars and adding them by setting the native library location, without success.

So for the moment I'll stick to the 3.0.0 version and switch to your suggested solution when I actually need the 3.1.0 version. Maybe someone else encounters the same problem and comes up with a solution.

**Comment by Lein4d** [comment]
Or do you think, it would be helpful to post a minimal Eclipse project, where the error occurs?

**Comment by Spasi** [comment]
> Or do you think, it would be helpful to post a minimal Eclipse project, where the error occurs?

Yes, please.

You can also try `-Dorg.lwjgl.util.Debug=true` and `-Dorg.lwjgl.util.DebugLoader=true` to get more information on why loading the shared libraries fails.

**Comment by Lein4d** [comment]
I created the demo project and - I don't know why - it worked with just adding the jars to the build path. Afterwards I've cleared and set the build path of the original project again and suddenly it also worked fine. So I guess it was a spurious Eclipse problem.

Anyway, thanks for your help.
