### ISSUE TITLE
Hash of Native Files in Non-Native Jars

### ISSUE THREAD

**Issue by flortsch** [LWJGL/lwjgl3#251]
Hello guys.

I noticed that the API-only jar files of LWJGL contain all SHA1-hashes of the corresponding natives.
The native jars only contain the corresponding natives without the hashes.

Is this intended to be so?

I figured it out when I set up a Maven project for my application.
I used the Maven Assembly Plugin to build a jar-with-dependencies for each platform.
But these jars contained the SHA1-hashes of all the other platforms.

It would be great if these hashes could be placed in the corresponding native jars.
Then one could provide a clean application jar for every platform.

**Comment by Spasi** [comment]
Hey @flortsch,

The latest snapshot (3.1.1 build 4) includes the SHA-1 hashes in the natives JAR files, as requested.

They also include the git revision used to build the shared library, which lets you know whether the binary includes a specific change in the upstream project. This was requested by @code-disaster and is especially useful with libraries that change frequently (e.g. bgfx and GLFW). For example, `lwjgl-glfw-natives-linux.jar` now includes:

- libglfw.so (the shared library)
- libglfw.so.sha1 (SHA-1 digest of the shared library)
- libglfw.so.git (git revision used to build the shared library)

Note that `lwjgl_*` shared libraries, whose source is included in LWJGL and are built with the core library, do not have a corresponding `*.git` file.

**Comment by flortsch** [comment]
Nice, thank you for the reply @Spasi.
