### ISSUE TITLE
Add bindings for OSVR, The Open Source VR Library

### ISSUE THREAD

**Issue by ExE-Boss** [LWJGL/lwjgl3#258]
The OSVR library, available at: http://osvr.org
would allow usage of any supported HMD, motion controls, etc., without needing to write different code for all of them yourself (Sort of like Java).
They also have their own HMD called the HDK or Hacker Development Kit, which is also open source.
### See also:
- http://osvr.org/what-is-osvr.html
- http://osvr.org/getting-started.html
### Appendix:
This would, in my own opinion, be a lot better than having a lot of different APIs for each HMD manufacturer and support open source software.

**Comment by Spasi** [comment]
This request is similar to #160. I don't think it's worth putting any effort into it after the [Khronos Virtual Reality Standard Initiative](https://www.khronos.org/vr/) announcement. Unless:

- someone is seriously making a VR application and needs it asap or
- someone contributes the bindings, or at least does the majority of the work - like it happened with bgfx and assimp).

**Comment by Spasi** [comment]
LWJGL will have OpenXR bindings in the near future.
