### ISSUE TITLE
Issue with pom.xml copied from download page

### ISSUE THREAD

**Issue by stelar7** [LWJGL/lwjgl3#261]
If you copy xml from the [download page](https://www.lwjgl.org/download) that includes JOML or steamworks, and the the "Do not use variables" toggle is off, the closing tag is missing for both.

```
<properties>
	<maven.compiler.source>1.8</maven.compiler.source>
	<maven.compiler.target>1.8</maven.compiler.target>
 	<lwjgl.version>3.1.0</lwjgl.version>
 	<joml.version>1.9.0<joml.version>
 	<steamworks4j.version>1.5.0<steamworks4j.version>
</properties>
 
```

**Comment by Spasi** [comment]
Thanks! Fixed with https://github.com/LWJGL/lwjgl3-www/commit/ac3fee637feda92533b7d392f7fdece3cd201273.
