### ISSUE TITLE
NVOGLV64.dll Crashes

### ISSUE THREAD

**Issue by dragonslayer0531** [LWJGL/lwjgl3#264]
I am receiving NVOGLV64 crashes with LWJGL 3.1.0.  I am not getting any log files to reference and find the reason for the crash.  Can anyone give me any insight as to why this would happen?

GPU: GeForce GTX 1070 (latest drivers)

**Comment by Spasi** [comment]
Are the crashes random or easily reproducible? Could you reduce your program to something simple that you can share and reproduces the crash?

Can't help you more without additional information, other than mentioning the basics:

- Create a debug OpenGL context and register a debug callback (e.g. with `GLUtil.setupDebugMessageCallback()`).
- Enable LWJGL's debug mode (with `-Dorg.lwjgl.util.Debug=true` or `Configuration.DEBUG.set(true)`).

See the [Troubleshooting](https://github.com/LWJGL/lwjgl3-wiki/wiki/2.5.-Troubleshooting) page in the LWJGL wiki for more information.

**Comment by dragonslayer0531** [comment]
@Spasi I am getting a wrong component type or count.  Is there any way to see which line is causing the error, or do I need to debug my entire program to determine this.

**Comment by httpdigest** [comment]
I adapted LWJGL's GLUtil class to this: https://gist.github.com/httpdigest/5178da20f32b05700e7f957cdbdc94e8
to synchronously get an exception stack trace.

**Comment by dragonslayer0531** [comment]
Working so far.  I will let you know how that does @httpdigest .  Thank you so much!  Do you mind if I adapt this for my own needs?  If so, shoot me a link to the license for the code.

**Comment by dragonslayer0531** [comment]
Resolved.

**Comment by dragonslayer0531** [comment]
Sorry for the reopen, but the issues have reappeared.  All I get now is the "Notification" messages when I load models and textures, but there is nothing that points me to a specific issue.

**Comment by httpdigest** [comment]
Yeah, sorry. The DebugCallback implementation in the Gist should of course first check for "ERROR" type and only then throw the exception. I modified the linked code, also including proper license.
If by notification messages you mean something like this: `NOTIFICATION API OTHER: Buffer detailed info: Buffer object 1 (bound to GL_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations.`
then this is normal and can be ignored.

**Comment by dragonslayer0531** [comment]
Yup.  I have ignored those, but they are very helpful. Those are the only notifications I get now, even when I am using the GLUtil implementation of it.  Not sure what else could be the issue.  I have found no way to reproduce the error consistently.

**Comment by Spasi** [comment]
Try `-Dorg.lwjgl.util.DebugAllocator=true` and `-Dorg.lwjgl.system.allocator=system` (if you're using jemalloc).

**Comment by dragonslayer0531** [comment]
I am not using jemalloc.

**Comment by dragonslayer0531** [comment]
Update:  Went to 3.1.1 and it currently seems to work.  I will keep you all  posted.  Thanks to everyone for their help thus far!

**Comment by dragonslayer0531** [comment]
Found the error.  Not all of the natives linked properly, but I have that issue fixed.  Thanks for the help all.
