### ISSUE TITLE
Type

### ISSUE THREAD

**Issue by Levilutz** [LWJGL/lwjgl3#267]
This is an issue for the website, but I can't find where else to post this. On the "[Get Started](https://www.lwjgl.org/guide)" page, it says that attaching the Javadoc and source archives is "**hightly** recommended". I think this is a typo of "**highly** recommended". 
![screenshot](https://cloud.githubusercontent.com/assets/22489327/21947864/6708023a-d9b5-11e6-9ad3-05fd8b6163d8.png)

**Comment by Spasi** [comment]
Site issues can be reported in the [lwjgl3-www](https://github.com/LWJGL/lwjgl3-www/issues) repository.

Fixed with https://github.com/LWJGL/lwjgl3-www/commit/340914c17ed93868baef9e37ff000d807c65a276. I replaced the old instructions with a link to the wiki's install page.

Thanks!
