### ISSUE TITLE
Add maven host

### ISSUE THREAD

**Issue by ruseman** [LWJGL/lwjgl3#27]
I work primarily with Gradle, and so would greatly appreciate the creation of a maven repository to host the new LWJGL 3.

**Comment by dannypurcell** [comment]
I created a quick bash script that installs a snapshot zip in the local maven repo.
https://gist.github.com/dannypurcell/0c86ac1087eadd02d605

Runs in msys on windows, should also run fine in cygwin

**Comment by xiurobert** [comment]
LWJGL 3 release is out, maybe put it up now?

**Comment by Spasi** [comment]
The release is 3.0a, not the final 3.0 release, which is what I meant above. With that said, I plan to do this earlier, possibly before 3.0b. Right now I'm working on porting the LWJGL build to Gradle, will look into maven deployment after that.

**Comment by philipwhiuk** [comment]
Gradle and Maven use the same repositories (e.g. Nexus) so it should only be necessary to do it once and deploy it somewhere.

**Comment by Spasi** [comment]
LWJGL 3 is now on Central, use `org.lwjgl:lwjgl:3.0.0a`.

Nightly builds are also published as snapshots, use version `3.0.0b-SNAPSHOT` and the `https://oss.sonatype.org/content/repositories/snapshots` repository url.

See the [demo project](https://github.com/badlogic/lwjgl3-maven-gradle) for more information.
