### ISSUE TITLE
More helpful native error messages

### ISSUE THREAD

**Issue by jediminer543** [LWJGL/lwjgl3#270]
I've started messing arround with Nuklear, I have looked at the examples in the examples directory, and have managed to succesfully cause several access violations. Would it be feasable to check for these sorts of errors and throw a java error than to cause an access violation that is a pig to debug.  

I.e. The access violation I ran into was because there was no font set. The access violation says nothing about this, stating that it is because of me calling Nk_Begin.

**Comment by Spasi** [comment]
> Would it be feasable to check for these sorts of errors and throw a java error than to cause an access violation

I'm afraid not. It's outside the scope of LWJGL to fix such issues. Some native libraries are hardened against invalid state/input and others are not. Some have mechanisms to report errors and others just crash. This isn't ideal, but it would be impossible for LWJGL to guard against all failure cases. LWJGL is simply a binding layer over the native libraries and doesn't know anything about what's going on inside them.

LWJGL does protect Java developers with features such as auto-sizing of buffer parameters and null-checks. If you encounter a function that should not accept `NULL` but does, you're welcome to report it and it will be fixed asap. For more complicated cases (such as validation of correct API use), your best bet is contacting developers of the affected library.

**Comment by jediminer543** [comment]
Thanks, is there some good documentation for nuklear or should I just be looking at the samples?

**Comment by Spasi** [comment]
I don't think there is any documentation, other than what little you can find in the [header](https://github.com/vurtun/nuklear/blob/master/nuklear.h). The API is fairly simple and consistent though and the examples/demos in the nuklear repo should be enough to get you started.
