### ISSUE TITLE
Exit Value -1073740791 when creating window

### ISSUE THREAD

**Issue by ThomasAunvik** [LWJGL/lwjgl3#271]
private static GLFWErrorCallback errorCallback = GLFWErrorCallback.createPrint(System.err);
	
	public static void main(String[] args) {
		
		GLFW.glfwSetErrorCallback(errorCallback);
		
		if(!GLFW.glfwInit()) throw new IllegalStateException("Failed to initialize GLFW!");
		
		GLFW.glfwWindowHint(GLFW.GLFW_VISIBLE, GLFW.GLFW_FALSE);
		long window = GLFW.glfwCreateWindow(640, 480, "Programmers Life", 0, 0); <<< where it stops
		if(window == 0) throw new IllegalStateException("Failed to create window");
		
		GLFWVidMode videomode = GLFW.glfwGetVideoMode(GLFW.glfwGetPrimaryMonitor());
		GLFW.glfwSetWindowPos(window, (videomode.width() + 640) / 2, (videomode.height() + 480) / 2);
		
		GLFW.glfwShowWindow(window);
	}

Computer specs:
Intel Core i5-7200U 2.50GHz
GeForce 920Mx
8GB RAM
JRE and JDK version: 1.8.0 121

Installed Libs:

joml-1.9.2
lwjgl-glfw-natives, mac, windows,linux
lwjgl-glfw
lwjgl-openal-natives
lwjgl-openal
lwjgl-opengl-natives
lwjgl-opengl
lwjgl-stb-natives
lwjgl-stb
lwjgl-natives
lwjgl
steamworks4j-1.6.1

**Comment by httpdigest** [comment]
Are you on Windows and does your installed Nvidia driver version happen to be 378.49?
If so, then see:
- http://forum.lwjgl.org/index.php?topic=6439.msg34284#msg34284
- http://forum.lwjgl.org/index.php?topic=6443.0

It is a bug in Nvidia's driver and Nvidia is aware of this.
One solution is to start your Java application on the command line via `java.exe ...`. It is _very_ important to name the `.exe` extension after `java`.

**Comment by ThomasAunvik** [comment]
Thanks, now that i know that i could just downgrade my driver version
