### ISSUE TITLE
Properly handle tests which depend on runtime conditions.

### ISSUE THREAD

**Issue by TheMrMilchmann** [LWJGL/lwjgl3#275]
Tests which rely on checks to be enabled cannot succeed when run without checks. This may lead to distracting results when running tests. Eventhough currently only one specific test case is effected (`StackTest.testOOME()`), this number might increase in future updates. Additionally finding and implementing an appropriate solution should not be complicated. In fact, there are already two different approaches lined out below.

1. **Simply wrap an if statement around the actual test block.**
This method goes without much of an explanation and might be suitable for one test, however in this case the test would be marked as successful even though it never ran.

2. **Use an AnnotationTransformer**
By providing IAnnotationTransformer we can specify which tests should be skipped at runtime and therefor disable tests that depend on similar conditions as lined out above.

An implementation could look like this:
``` java
public final class TestAnnotationTransformer implements IAnnotationTransformer {

    @Override
    public void transform(ITest annotation, Class testClass, Constructor testConstructor, Method testMethod) {
        if (testMethod.isAnnotationPresent(RequiresChecks.class) {
            annotation.setEnabled(CHECKS);
        }
    }

    @Retention(RetentionPolicy.RUNTIME)
    @Target(ElementType.METHOD)
    public static @interface RequiresChecks {}

}
```

Edit 1: Added syntax highlighting in the example implementation

**Comment by Spasi** [comment]
Hey @TheMrMilchmann,

Unlike demos, tests are assumed to always run with both checks and debug enabled. The workaround looks simple enough though, I guess it can be used. Thanks!
