### ISSUE TITLE
glfwWindowShouldClose not responding to a closed window

### ISSUE THREAD

**Issue by stelar7** [LWJGL/lwjgl3#278]
It only happens 1/ 100 times, so I have no real idea what causes it..

See this video for how it acts: https://youtu.be/jKbNkffT2t4
Code here: https://git.io/vDc2l
LWJGL version: 3.1.0

**Comment by httpdigest** [comment]
I see you are using some sort of synchronization/lock. Are you calling _all_ GLFW.glfw*() methods _only_ on the main thread?
(the thread that the `public static void main(String[] args)` method is called in at the start of the JVM)

**Comment by stelar7** [comment]
glfwWindowShouldClose can be called from any thread according to the Javadocs, so that shouldnt be an issue..?

**Comment by httpdigest** [comment]
> glfwWindowShouldClose can be called from any thread according to the Javadocs, so that shouldnt be an issue..?

Oh yes, you're right.

What's strange is that in the video the window does close but the process does not end. The window only closes when either the JVM/process exits or the user application calls glfwDestroyWindow() explicitly itself. Neither happens with you, it seems.

**Comment by httpdigest** [comment]
I think I know what happens:
- the main thread sees that the window should be closed (Renderer:32 ends the loop)
- then the main thread destroys the window (Renderer:40) and afterwards also terminates GLFW
- now the spawned thread takes another turn at Renderer:141 but the window is already gone (and probably the memory freed), thus it works on garbage memory

**Comment by stelar7** [comment]
I changed the code to match the multithread example, so even if it would act on garbage, it now acts on a boolean. BUT, the issue is still there.

**Comment by httpdigest** [comment]
You mean, the `boolean destroyed` field will be set to `true` by the main thread once the window is being destroyed/closed, but the spawned thread still sees `true`?

**Comment by stelar7** [comment]
the main thread will set the `boolean destroyed` to true, but the spawned thread still sees it as false, yes.
