### ISSUE TITLE
Git revision information incomplete in nightly version

### ISSUE THREAD

**Issue by code-disaster** [LWJGL/lwjgl3#281]
This is a follow-up to #251. No urgent matter, but I was actually looking at *.dll.git files inside some nightly build JARs.

- lwjgl itself contains the correct Git hash
- for lwjgl-glfw, the .dll.git files contain just one character
- for lwjgl-bgfx, the .dll.git files are there, but empty

**Comment by Spasi** [comment]
Thanks! The next nightly (3.1.2 build 16) should contain correct revisions.
