### ISSUE TITLE
Artifact download failed: Please try again

### ISSUE THREAD

**Issue by Bobbyjoness** [LWJGL/lwjgl3#282]
I cant download a zip bundle. I do not know how to otherwise use LWJGL 3 with intellij 2016 edition. all tutorials are outdated and reference things which aren't in the release zip on github so im assuming it is different from the zip bundle. Which I cant download.

**Comment by httpdigest** [comment]
In the meantime you can switch to "Maven" or "Gradle" mode on the download site and simply create a Maven or Gradle project, which is also by far easier than configuring the individual module artifacts.
Instructions can be found here: https://github.com/LWJGL/lwjgl3-wiki/wiki/1.2.-Install#gradle-or-maven

**Comment by apostolos** [comment]
@Bobbyjoness Please try again, you should now be able to download the ZIP bundles.
