### ISSUE TITLE
No aiGetPredefinedLogStream function in assimp

### ISSUE THREAD

**Issue by Immueggpain** [LWJGL/lwjgl3#283]
I'm trying to follow https://github.com/assimp/assimp/blob/master/samples/SimpleOpenGL/Sample_SimpleOpenGL.c
but I can't find function `aiGetPredefinedLogStream` at line 341. What am I missing?

**Comment by Spasi** [comment]
Hey @Immueggpain,

`aiGetPredefinedLogStream` is the only function in Assimp that returns a struct by value. That's not a problem for LWJGL, but it would require an additional native binary to support. I didn't want to introduce an entire shared library (per platform) just for one function, which does not provide critical functionality anyway and can easily be emulated (with a custom `AILogStreamCallback`).

I have this in my todo list though and eventually will be supported.

**Comment by Immueggpain** [comment]
@Spasi Oh I see. That totally makes sense. I will use `AILogStreamCallback` instead. Also thank you for your reply!
P.S. It seems to me that beta has less bugs and is more stable than the current 3.1.1 release, is it just my illusion? LOL

**Comment by kenzierocks** [comment]
Is there plans to implement this now that the Assimp binding has a shared library?

**Comment by kenzierocks** [comment]
Sounds good, thank you for explaining.

**Comment by octylFractal** [comment]
Requesting another look at this since it seems you suggested libffi 3.3 would fix this, and it appears to be out since Nov. 16 2019.

**Comment by Spasi** [comment]
LWJGL has replaced dyncall with libffi which, among other nice things, made it possible to implement `aiGetPredefinedLogStream`. Sorry that it took so long!
