### ISSUE TITLE
Buffers in LWJGL

### ISSUE THREAD

**Issue by Immueggpain** [LWJGL/lwjgl3#285]
I have a few questions about buffers in LWJGL 3.
1. Can I specify offset and length of an `nio.Buffer`? `glBufferData` simply accepts a buffer object but there is no offset and length parameter.
2. I found out that `glBufferData` can also accept a java array, but still, no offset and length parameter.

So what should I do to reuse a big block of data with different offsets and lengths? Do I have to recopy them out? That sounds quite inefficient!

**Comment by HackeurD** [comment]
1. The method put of direct buffers is really fast. So it shouldn't be an issue. The best way to do is to use them directly. You can allocate them with BufferUtils.create<Float|Int|Byte|Char|Double|Int|Long|Pointer|Short>Buffer(int capacity);

2. For the offset, you have to use glBufferSubData.

**Comment by Immueggpain** [comment]
@HackeurD Hi, thank you for your reply. But there are still some problems.
1. The `put` method may be fast, but why should I incur unnecessary copy at all? Also I have to allocate new buffers, which is also a problem.
2. The wiki says that we should use `MemoryUtil` class to allocate buffers, are you suggesting me to use `BufferUtils` instead?
3. I think `glBufferSubData` is used to modify part of the server-side buffer, not client-side buffer? Am I wrong?

**Comment by Spasi** [comment]
> Can I specify offset and length of an nio.Buffer? glBufferData simply accepts a buffer object but there is no offset and length parameter.

You set the buffer's `position()` and `limit()`, just like in any API that consumes NIO buffers. The only difference is that LWJGL only reads and never mutates the current position, which reduces the need for additional `flip()` and `rewind()` calls. This is all covered in the [Bindings FAQ](https://github.com/LWJGL/lwjgl3-wiki/wiki/1.4.-Bindings-FAQ).

> The put method may be fast, but why should I incur unnecessary copy at all? Also I have to allocate new buffers, which is also a problem.

You can do anything in LWJGL with zero copies. You don't even have to allocate that much, most short allocations can be replaced with stack allocations (see the `MemoryStack` class).

> The wiki says that we should use `MemoryUtil` class to allocate buffers. Are you suggesting me to use `BufferUtils` instead?

`BufferUtils` should be your last option. The [Memory FAQ](https://github.com/LWJGL/lwjgl3-wiki/wiki/1.3.-Memory-FAQ) contains more information.

> I think `glBufferSubData` is used to modify part of the server-side buffer, not client-side buffer. Am I wrong?

You are correct.

> I found out that `glBufferData` can also accept a java array, but still, no offset and length parameter.

That's true, array overloads do not support the equivalent of position/limit. One reason is that it would require introducing synthetic parameters to JNI functions, which is against LWJGL's design. Another reason is that using array overloads for functions like `glBufferData` is not recommended. This has to do with how Hotspot Critical Natives work (you generally don't call `glBufferData` enough times for it to be JIT compiled, which means additional copies anyway). Array overloads should only be used with small arrays and such functions either don't require custom offsets/lengths or the overhead from copying such short arrays is negligible.

Using a custom position for array parameters is out of the question, but if you really want to use a custom length, you can do it by having a look at LWJGL's source code. For example, `glBufferData(int target, float[] data, int usage)` is implemented with a call to `JNI.callPPV(__functionAddress, target, (long)(data.length << 2), data, usage)`. You can see that there's an explicit size parameter (in bytes). Parameters like `data` are called "auto-sized" parameters in LWJGL and the corresponding size/length/count parameter is calculated automatically. This protects against crashing the JVM with illegal memory accesses.

**Comment by Immueggpain** [comment]
@Spasi Oh thank you very much for the info. `position()` and `limit()` are exactly what I am looking for. 
And the binding FAQ is quite informative. I have read the Memory FAQ but not the binding one, should've done that.
But I really don't think that offset and length are synthetic. The native C APIs have such parameters and almost every java method which operates arrays has them too.
Another problem. Though that I see `Hotspot Critical Natives` will block GC when calling in the JNI function. But does that mean that the array may still get moved after the function returns? And since OpenGL is highly asynchronous, wouldn't that be a problem?

**Comment by Spasi** [comment]
> But I really don't think that offset and length are synthetic. The native C APIs have such parameters and almost every java method which operates arrays has them too.

Most have a length parameter, but not an offset (pointer arithmetic in C does the job just fine). As I said above, for rare cases where you need to use the length parameter explicitly, LWJGL provides access to it via the "unsafe" overloads (methods with an `n` prefix) or via the `JNI` class.

> But does that mean that the array may still get moved after the function returns? And since OpenGL is highly asynchronous, wouldn't that be a problem?

Most OpenGL functions, including `glBufferData`, consume the data specified before returning. If the actual work is done later (asynchronously), the driver copies the data internally. The buffer may be deallocated by the user or moved by the GC and nothing bad will happen.

This is a problem only for functions that store the pointer to the data, such as `glVertexAttribPointer`. Which means such functions should not have array overloads. I'm reopening this issue until they are removed. If anyone can compile a list of similar functions, I would appreciate it.
