### ISSUE TITLE
glDrawElements bindings

### ISSUE THREAD

**Issue by Immueggpain** [LWJGL/lwjgl3#286]
Hey! For `glDrawElements`, there are bindings that group `count` and `indices` into an `IntBuffer` or similar things. But it doesn't make any sense. The `indices` parameter is an offset, not a real pointer!
I was banging my head why I got nothing drawn until I found this LOL.

**Comment by httpdigest** [comment]
No need for further head-banging All overloads of that method have their uses. But you should use [this overload](https://javadoc.lwjgl.org/org/lwjgl/opengl/GL11.html#glDrawElements-int-int-int-long-) instead when you are using buffer objects and not client-side arrays.

**Comment by Immueggpain** [comment]
Oh, wait... Does the `indices` mean different things whether there is a `GL_ELEMENT_ARRAY_BUFFER` or not?

**Comment by Immueggpain** [comment]
@httpdigest Okay, I googled the client-side arrays things and found out what's going on. I guess there are still some old hidden deprecated secrets in OpenGL LOL.

**Comment by Immueggpain** [comment]
Thanks for the help!
