### ISSUE TITLE
Problem on running an application using LWJGL

### ISSUE THREAD

**Issue by NatanielBR** [LWJGL/lwjgl3#287]
![e65f2ba9b5244f9072bc4a443fcf6815c305d179](https://cloud.githubusercontent.com/assets/22733502/23359290/5b4ebac4-fcc4-11e6-87fa-5d77c6f6ad85.png)

![650e48cfc34af7484892330dbd6db84ee76db3dd](https://cloud.githubusercontent.com/assets/22733502/23359306/6fbdc6d0-fcc4-11e6-85ce-82b0d74ae418.png)

**Comment by ShchAlexander** [comment]
Check if it the same issue as https://github.com/LWJGL/lwjgl3/issues/271?

**Comment by NatanielBR** [comment]
![image](https://cloud.githubusercontent.com/assets/22733502/23371227/27f7a4a6-fcf6-11e6-8ac7-8dcf4bbfeb20.png)

same problem.

**Comment by Spasi** [comment]
Have you tried other OpenGL applications?

**Comment by NatanielBR** [comment]
Yes, i test the Minecraft and Blender. All works well.

**Comment by NatanielBR** [comment]
Yes, i tested the Minecraft and Blender, all works well.
