### ISSUE TITLE
Calls to glBufferData with a FloatBuffer made with .wrap() fails

### ISSUE THREAD

**Issue by stelar7** [LWJGL/lwjgl3#289]
I'm not sure how this works behind the scenes, but if you produce a FloatBuffer with FloatBuffer.wrap(floatArray), then try to call glBufferData with it, it turns out as gibberish.

It works as expected if you create a FloatBuffer with BufferUtils then put() and flip()

Seeing as the method took a FloatBuffer, i expected to be able to use wrap(), is that not allowed?

(The buffer produced by .wrap() is a nio.HeapFloatBuffer, the one by .create() is a nio.DirectFloatBuffer)

**Comment by Spasi** [comment]
Buffers backed by heap arrays are not supported. Read the [Memory FAQ](https://github.com/LWJGL/lwjgl3-wiki/wiki/1.3.-Memory-FAQ) for more information.
