### ISSUE TITLE
Extension NV_vertex_buffer_unified_memory crashes on unloaded, deprecated function glEnableClientState

### ISSUE THREAD

**Issue by philipguin** [LWJGL/lwjgl3#290]
So I've been attempting to get some basic NV_command_list functionality working, and in so doing, was attempting to debug things via NV_vertex_buffer_unified_memory (using calls to glBufferAddressRangeNv specifically), when I ran into the following:

NV_vertex_buffer_unified_memory specifically 'un-deprecates' functions glEnableClientState and glDisableClientState for several inputs, in order to affect the state of the currently bound VAO (wonkily enough). However, LWJGL doesn't appear to load the pointers associated with these functions in core mode, thus failing basic sanity checks and crashing, making the API effectively unusable (as far as I'm aware - I'm still learning these extensions.) From NV_vertex_buffer_unified_memory, it needs to accept VERTEX_ATTRIB_ARRAY_UNIFIED_NV and ELEMENT_ARRAY_UNIFIED_NV, and from NV_uniform_buffer_unified_memory, it needs to accept UNIFORM_BUFFER_UNIFIED_NV. There could be other values as well, but I have yet to see any perusing the docs.

Also, I have no idea how 'un-deprecating' should work regarding the GLCapabilities object, but it sounds like it could be a headache?

Thank you to whoever integrated these extensions, I'm finding them immensely useful, if not only fun :)

Relevant extensions:
[NV_vertex_buffer_unified_memory](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_vertex_buffer_unified_memory.txt)
[NV_uniform_buffer_unified_memory](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_uniform_buffer_unified_memory.txt)
[NV_shader_buffer_load](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_shader_buffer_load.txt)

LWJGL Version: 3.0.0.90
GPU: GTX 860M.
Other (excessive) details: [system.txt](https://github.com/LWJGL/lwjgl3/files/816012/system.txt)

**Comment by attilanyers** [comment]
I just met this issue. The posted workaround works. Thank you.
