### ISSUE TITLE
CPU/GPU profiler - Might be of interest

### ISSUE THREAD

**Issue by dustContributor** [LWJGL/lwjgl3#292]
https://github.com/Celtoys/Remotery

I have no use for it right now but other people might be interested in bindings for it.

**Comment by RUSshy** [comment]
@code-disaster Already ported it for libGDX, since it use LWLJGL it would make sense to implement it directly in it so everyone will be able to use it easily :) 

https://github.com/code-disaster/libgdx-snippets/tree/master/src/main/java/com/badlogic/gdx/profiler

**Comment by code-disaster** [comment]
My JNI wrapper does some book-keeping which may not be required when used properly with LWJGL 3 (MemoryStack et al). One more item on my "would be nice to look into" backlog.

**Comment by dustContributor** [comment]
Sweet :smile:

**Comment by ShchAlexander** [comment]
Is there some usage examples in java?
