### ISSUE TITLE
Can I define my own struct by extending org.lwjgl.system.Struct?

### ISSUE THREAD

**Issue by dustContributor** [LWJGL/lwjgl3#293]
Well, I got these RenderTasks and it'd be lovely if they were structs rather than heap allocated objects. It'd be nice to have a sequentially allocated array of them. 

It can be done through Struct? Or some other util from LWJGL?

**Comment by Spasi** [comment]
Yes, you can extend `org.lwjgl.system.Struct` and implement your own struct types. The code that needs to be written in `Struct`/`StructBuffer` subclasses is simple, but overly verbose. It's not meant to be written by hand. So:

- If there are only a few types, you can write struct classes for them manually.
- If there are too many, you can use the LWJGL generator to generate them for you. Add your types to any of the existing bindings, then copy the generated code to your project and change the `package` only.

There's also a more powerful alternative: [LibStruct](https://github.com/riven8192/LibStruct). It should work nicely with LWJGL.

**Comment by dustContributor** [comment]
Sweet. I'll look into the generator in the future. Thanks!
