### ISSUE TITLE
YGMeasureFunc - returned width & height values are swapped

### ISSUE THREAD

**Issue by raniejade** [LWJGL/lwjgl3#294]
Been playing around with the `Yoga` binding and I've encountered a bug with `YGMeasureFunc`.

I have this node hierarchy:

```kotlin
override fun content() = FlexBox().apply {
    layoutHeight = FILL_PARENT
    layoutWidth = FILL_PARENT
    background.setBackgroundColors(BackgroundFill(Color(1.0f, 0.8f, 0.6f, 1.0f), Insets(), CornerRadii()))

    addChild(FlexBox().apply {
        background.setBackgroundColors(BackgroundFill(Color(1.0f, 0.0f, 0.0f, 1.0f), Insets(), CornerRadii(5)))

        addChild(FlexBox().apply {
            layoutHeight = 100
            layoutWidth = 200
            background.setBackgroundColors(BackgroundFill(Color(1.0f, 1.0f, 0.0f, 1.0f), Insets(), CornerRadii(5)))
        })
    })
}
```

The `YGMeasureFunc` is only applied on a leaf node, this is how I implemented it.

```kotlin
    private fun measureFunc(ygNode: Long, width: Float, widthMode: Int, height: Float, heightMode: Int): Long {
        val node = if (ygNode == ygRootNode) {
            this
        } else {
            requireNotNull(ygToNodeMap[ygNode])
        }

        val ygSize = YGSize.malloc()

        try {
            node.measure(width.toInt(), fromYGMeasureMode(widthMode), height.toInt(), fromYGMeasureMode(heightMode))
            ygSize.set(
                node.getMeasuredWidth().toFloat(),
                node.getMeasuredHeight().toFloat()
            )
            return YGMeasureFunc.toLong(ygSize)
        } finally {
            ygSize.free()
        }
    }
```

`node.measure(...)` will consider the `layoutWidth` and `layoutHeight` values so in the example above, `node.getMeasuredWidth()` and `node.getMeasuredHeight()` will return 200 and 100, respectively.

With the code above I get this:
![screenshot from 2017-03-18 19-37-12](https://cloud.githubusercontent.com/assets/1041919/24071641/6c732aee-0c12-11e7-8a78-f84d73a23657.png)

`YGMeasureFunc.toLong(ygSize)` since the actual c code the return value is a `YGSize`.  

```java
public static long toLong(YGSize size) {
    return ((long)floatToRawIntBits(size.width()) << 32) | floatToRawIntBits(size.height());
}
```

I guess this gets mapped directly to the "memory layout" of the `YGSize` struct? Anyway swapping `width` and `height`

```kotlin
fun toLong(size: YGSize): Long {
    return floatToRawIntBits(size.height()).toLong() shl 32 or floatToRawIntBits(size.width()).toLong()
}
```

gives the correct result.

![screenshot from 2017-03-18 19-37-56](https://cloud.githubusercontent.com/assets/1041919/24071690/22ba1b1e-0c13-11e7-9ec1-08232b379701.png)

**Comment by Spasi** [comment]
Thank you! All `YGMeasureFunc` tests used the same value for width/height, so this bug was missed.
