### ISSUE TITLE
Add bindings for FMOD

### ISSUE THREAD

**Issue by voidburn** [LWJGL/lwjgl3#295]
Since now it's free for indies and small teams (anything that has a butdged < $500k), it would be an amazing tool to have!

http://www.fmod.com/licensing

**Comment by raniejade** [comment]
Does this matter?

http://www.fmod.com/licensing#faq
```
Q. Can I distribute FMOD as a standalone library or as part of a game engine or toolset.
A. No, you are not permitted to distribute FMOD in that way. Contact us if you would like to discuss a special arrangement.
```

**Comment by voidburn** [comment]
It sure does, this should start by inquiring about the intent to provide
the bindings and seeing how the respond to it.

I'd be willing to contact them and push it forward if there's interest for
these bindings.

**Comment by Spasi** [comment]
It's not a problem, LWJGL can include the bindings without distributing the FMOD binaries. Similar to how bindings like Vulkan, OpenCL and EGL do not have any natives. FMOD provides binaries for all platforms, they can be added to an LWJGL application and the bindings will work.

**Comment by Illithidek** [comment]
I would also be interested, I work on a new project and the only thing that I'm worried about is bindigns for fmod. I don't know JNI well but if I can help somehow please let me know.

**Comment by Spasi** [comment]
The next 3.3.2 snapshot is going to include bindings for FMOD (core, studio and fsbank APIs). As mentioned above, the native libraries will be included, they'll have to be downloaded and distributed separately.

**Comment by Illithidek** [comment]
@Spasi that's so cool, I can't wait to try it out :>!

**Comment by soundasleep** [comment]
Thank you for the FMOD support!

I couldn't find any docs on how to integrate FMOD and lwjgl (or in my case, libgdx) so I hope I did everything right: https://stormcloak.games/2023/10/25/libgdx-and-fmod
