### ISSUE TITLE
Prefered method for copying memory?

### ISSUE THREAD

**Issue by stelar7** [LWJGL/lwjgl3#297]
What is the prefered method for putting stuff into memory in vulkan?
The examples in lwjgl3 uses one, and the lwjgl3-demos uses another

pointer.getFloatBuffer() then put?
memAlloc then memCopy?

EDIT: ignore the title change, i was thinking of something else at the same time

**Comment by httpdigest** [comment]
It of course depends on the exact usecase:
1. if you have an off-heap source memory address and an off-heap destination memory address and want to copy contiguous arrays of memory to copy, then MemoryUtil.memCopy() is probably fastest
2. if you have an on-heap source Java array and an off-heap destination memory address then using Buffer.put(array) is probably fastest (maybe MemoryUtil has other methods accepting Java source arrays)
3. if you have an off-heap source memory address and an on-heap destination Java array then using MemoryUtil to create a NIO Buffer and then using method 2 is probably fastest.
4. if you have an on-heap source Java array and an on-heap destination Java array then probably System.arraycopy is fastest
5. if you cannot copy contiguous ranges of memory from source to destination but must put individual values into an off-heap destination address, then using MemoryUtil.memPut\*(offset, value) is probably fastest.

There are probably other cases I missed.

**Comment by stelar7** [comment]
Whats the difference in performance? ns? ms?
