### ISSUE TITLE
VkDeviceQueueCreateInfo.queueCount() is locked at 0

### ISSUE THREAD

**Issue by LordC777** [LWJGL/lwjgl3#298]
When using the VkDeviceQueueCreateInfo struct in LWJGL you are unable to set the queueCount varible, usually count variables are automatically allocated by LWJGL but VkDeviceQueueCreateInfo it is stuck at 0 and with no way of changing it.

It's simple to reproduce, just call the vkCreateDevice with a filled out createInfo struct and you'll see the error in question.

Here's what the validation layers output...
```
ERROR [ParameterValidation] (4): vkCreateDevice: parameter pCreateInfo->pQueueCreateInfos[0].queueCount must be greater than 0 
ERROR [ParameterValidation] (61): vkGetDeviceQueue() parameter, uint32_t queueIndex 0, must be less than the number of queues given when the device was created. For more information refer to Vulkan Spec Section '4.3.2. Queue Creation' which states 'queueIndex must be less than the number of queues created for the specified queue family index when device was created, via the queueCount member of the VkDeviceQueueCreateInfo structure' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/xhtml/vkspec.html#vkGetDeviceQueue) 
```

... and here's the code in question:
```
VkDeviceQueueCreateInfo.Buffer qCreateInfo = VkDeviceQueueCreateInfo.malloc(1);
qCreateInfo.sType(VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO);
qCreateInfo.queueFamilyIndex(inds.getGfxFamily());
qCreateInfo.pQueuePriorities(BufferUtils.createFloatBuffer(1).put(1.0f));
```
...
		`createInfo.pQueueCreateInfos(qCreateInfo);`

**Comment by httpdigest** [comment]
`BufferUtils.createFloatBuffer(1).put(1.0f)`
This is wrong. You must `.flip()` the buffer so that it has a remaining() of 1.

**Comment by LordC777** [comment]
Well, I'm an idiot.

**Comment by Spasi** [comment]
You also risk a JVM crash (or worse, a silent bug) using `BufferUtils` there. The struct does not store a strong reference to the `FloatBuffer` instance, only its memory address. After `pQueuePriorities` returns, there's nothing stopping the GC from freeing the buffer instance and the associated offheap memory.

**Comment by LordC777** [comment]
Is using struct.create okay though or should I use malloc for it?

**Comment by Spasi** [comment]
There's no single answer. It depends on the use case and expected life-cycle of a given allocation. The ideal choice may be different for the different instances of the same struct type or for different invocations of the same function. It's up to you to make the right trade-offs between performance and ease-of-use.

You can read more information in the [Memory FAQ](https://github.com/LWJGL/lwjgl3-wiki/wiki/1.3.-Memory-FAQ).
