### ISSUE TITLE
Malformed API version string [OpenGL ES-CM 1.1 Mesa 17.0.3]

### ISSUE THREAD

**Issue by elect86** [LWJGL/lwjgl3#300]
I get that error with `glfwWindowHint(GLFW_CLIENT_API, GLFW_OPENGL_ES_API)`

Specs:

- Ubuntu 17.04

OpenGL vendor string: X.Org
OpenGL renderer string: Gallium 0.4 on AMD RV610 (DRM 2.49.0 / 4.10.0-19-generic, LLVM 4.0.0)
OpenGL core profile version string: 3.3 (Core Profile) Mesa 17.0.3

**Comment by Spasi** [comment]
LWJGL does not support OpenGL ES 1.x.
