### ISSUE TITLE
Future OpenXR Support (Question)

### ISSUE THREAD

**Issue by nickclark2016** [LWJGL/lwjgl3#301]
The Khronos group is currently working on the development of OpenXR, a cross platform VR API.  Once released, will this be included into the LWJGL libraries?

[OpenXR](https://www.khronos.org/openxr)

**Comment by Spasi** [comment]
Yes, that's the plan. We'll then deprecate and eventually remove the existing LibOVR & OpenVR bindings.

**Comment by sriharshachilakapati** [comment]
What's the point in removing existing bindings when they are not officially deprecated on their own? Even when OpenXR came, someone might want to use OpenVR or LibOVR directly. Since LWJGL 3 is modular, I don't think keeping them available will not raise any problems.

**Comment by dragonslayer0531** [comment]
In my opinion, the bindings should be kept for several releases as deprecated, then eventually they should be removed from further releases.  Thanks @Spasi for your response!

**Comment by Spasi** [comment]
There's no problem with keeping the current bindings, except maintenance overhead. I'm just being hopeful, given the companies involved in OpenXR, that the existing VR libraries will become obsolete. In any case, if deprecation/removal happens, there will be enough time for users to migrate their code.

**Comment by knokko** [comment]
The first version of OpenXR has been released. So... how far are you with the bindings for it? Are you working on this? Or do other things have more priority? I do not want to sound impatient (sorry if I do), I'm just curious about this.
