### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by attilanyers** [LWJGL/lwjgl3#303]
With the usage of Multi OS Engine I think LWJGL could support iOS platform too.

[https://doc.multi-os-engine.org/multi-os-engine/9_game/2_opengl/opengl.html](https://doc.multi-os-engine.org/multi-os-engine/9_game/2_opengl/opengl.html)
[https://multi-os-engine.org/](https://multi-os-engine.org/)

What do you think about it?

**Comment by nickdbush** [comment]
LWJGL is written in Java, and iOS is Swift / Objective C based. So, unless I'm missing something, you'd need to get Java working on iOS if you wanted the LWJGL library specifically.

Note "library", as LWJGL is not a game or graphics engine - it just exposes the raw OpenGL (and other) bindings and makes them easy to consume in Java. You can use OpenGL bindings on iOS too, but you'll need to use the ones Apple provide. LWJGL would not be required there then.

**Comment by sriharshachilakapati** [comment]
@nickdbush Yes iOS is Swift / Objective C based, but Multi OS Engine is an AOT transpiler that translates Java code to ARM binary code ahead of time. So if proper efforts are made, LWJGL could run on both Android and iOS with the same code.

I do however doubt the amount of boilerplate code that MOE adds and whether LWJGL port on iOS is necessary at all. IMO LWJGL is a low-level bindings library, and porting it to iOS requires quite a good amount of abstractions which doesn't fit the goal of LWJGL.

**Comment by elect86** [comment]
https://blog.kotlin-academy.com/multiplatform-native-development-in-kotlin-now-with-ios-a8546f436eec

**Comment by kosbar** [comment]
This could be the way?
https://github.com/digitalgust/miniJVM
