### ISSUE TITLE
Failed to load library - error code = 193

### ISSUE THREAD

**Issue by EmpsThomy** [LWJGL/lwjgl3#309]
Hi,

One of our users is having a problem starting game using the lwjgl 3 library. It has taken quite a while, but we've now found the issue. The lwjgl 3 library is unable to unpack itself. I've asked the user to run the application with debugging flags and this is what we got:

> C:\Users\AwVzZhH>java -jar -Dorg.lwjgl.util.Debug=true %HOMEPATH%/.emps_world/em
ps-world-client.jar
[LWJGL] Version: 3.1.1 SNAPSHOT
[LWJGL]          OS: Windows 8.1 v6.3
[LWJGL]         JRE: 1.8.0_131 amd64
[LWJGL]         JVM: Java HotSpot(TM) 64-Bit Server VM v25.131-b11 by Oracle Corporation
[LWJGL] Loading library (system): lwjgl
[LWJGL]         Found at: C:\Users\AwVzZhH\AppData\Local\Temp\lwjglAwVzZhH\3.1.1-SNAPSHOT\lwjgl.dll
[LWJGL]         Loaded from org.lwjgl.librarypath: C:\Users\AwVzZhH\AppData\Local\Temp\lwjglAwVzZhH\3.1.1-SNAPSHOT\lwjgl.dll
[LWJGL] MemoryUtil accessor: MemoryAccess$MemoryAccessorUnsafe
[LWJGL] Warning: Failed to instantiate memory allocator: org.lwjgl.system.jemall
oc.JEmallocAllocator. Using the system default.
[LWJGL] MemoryUtil allocator: MemoryManage$StdlibAllocator
[LWJGL] Loading library: glfw
[LWJGL]         Found at: C:\Users\AwVzZhH\AppData\Local\Temp\lwjglAwVzZhH\3.1.1-SNAPSHOT\glfw.dll
[LWJGL]         Loaded from org.lwjgl.librarypath: C:\Users\AwVzZhH\AppData\Loca
l\Temp\lwjglAwVzZhH\3.1.1-SNAPSHOT\glfw.dll
[LWJGL] Loading library (system): lwjgl_opengl
[LWJGL]         Found at: C:\Users\AwVzZhH\AppData\Local\Temp\lwjglAwVzZhH\3.1.1
-SNAPSHOT\lwjgl_opengl.dll
[LWJGL]         Loaded from org.lwjgl.librarypath: C:\Users\AwVzZhH\AppData\Loca
l\Temp\lwjglAwVzZhH\3.1.1-SNAPSHOT\lwjgl_opengl.dll
[LWJGL] Loading library: opengl32
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to load library: C:\Users\AwVzZhH\AppData\Local\Temp\lwjglAwVzZhH\3.1.1-SNAPSHOT\opengl32.dll
(error code = 193)
        at org.lwjgl.system.windows.WindowsLibrary.<init>(Unknown Source)
        at org.lwjgl.system.APIUtil.apiCreateLibrary(Unknown Source)
        at org.lwjgl.system.Library.loadNative(Unknown Source)
        at org.lwjgl.system.Library.loadNative(Unknown Source)
        at org.lwjgl.system.Library.loadNative(Unknown Source)
        at org.lwjgl.system.Library.loadNative(Unknown Source)
        at org.lwjgl.opengl.GL.create(Unknown Source)
        at org.lwjgl.opengl.GL.<clinit>(Unknown Source)
        at net.emps.client.f.b.a.a(Unknown Source)
        at net.emps.client.f.b.run(Unknown Source)
        at net.emps.client.model.Client.run(Unknown Source)
        at net.emps.client.f.b.a(Unknown Source)
        at net.emps.client.model.Client.main(Unknown Source)

I've already tried Googling this, but I couldn't find anything regarding error code 193. So what is the issue and what does error code 193 stand for?

Thanks,
Thomy

**Comment by Spasi** [comment]
Error 193 on Windows happens when `LoadLibrary` tries to load a 32-bit library in a 64-bit process.

This error shouldn't happen though. There shouldn't be an `opengl32.dll` in the temp `3.1.1-SNAPSHOT` folder. The OpenGL library is not bundled with LWJGL, it comes with the GPU drivers on user systems.

Note that `opengl32` is the official name of the OpenGL client library on Windows and it's the same even on x64 systems. It's not related to the `32` suffix LWJGL adds to the x86 shared libraries it bundles.

**Comment by EmpsThomy** [comment]
Okay, thanks! Is this related to the user trying to run the game with a 64bit jvm? What Could I do to avoid that from happening? Could it be a faulty driver installation on the user's end?

**Comment by Spasi** [comment]
LWJGL runs fine (better actually) on 64bit JVMs. And as you can see in the debug output, `lwjgl.dll`, `glfw.dll` and `lwjgl_opengl.dll` load successfully. The question is how can there be an `opengl32.dll` in the classpath. I don't have an explanation for that. But the shared library loader wouldn't try to extract and load it if it wasn't there.

A few things to try:

- Ask the user to reinstall their GPU drivers.
- Ask the user to delete the `C:\Users\AwVzZhH\AppData\Local\Temp\lwjglAwVzZhH\` folder and relaunch your game.
- You may want to update to `3.1.2-SNAPSHOT`. Or wait for `3.1.2`, it's going to be released tonight if all goes well.

**Comment by EmpsThomy** [comment]
Deleting the `C:\Users\AwVzZhH\AppData\Local\Temp\lwjglAwVzZhH\` folder has worked. I will keep this in mind and recommend it to users in the future. Cheers!
