### ISSUE TITLE
Add binding to OpenGL Mathematics (GLM)

### ISSUE THREAD

**Issue by renannprado** [LWJGL/lwjgl3#31]
I've seen that a lot of guides using this extension math lib, it seems to me that it would be pretty useful to have binding of that.
The website:
https://www.opengl.org/sdk/libs/GLM/

**Comment by httpdigest** [comment]
You might want to have a look at JOML: https://github.com/JOML-CI/Java-OpenGL-Math-Library
It does however not (yet) reflect the design of GLM, but rather that of Sun's javax.vecmath, due to being allocation-free.

**Comment by Spasi** [comment]
LWJGL is not yet able to create C++ bindings. Especially to libraries that are template heavy like GLM.

Native math libraries in general will suffer from JNI overhead (too many calls, doing too little work) and don't offer much over what you can do in Java. A solution like JOML is a better option.
