### ISSUE TITLE
org.lwjgl.opengl.GL11.nglDrawArrays crashing

### ISSUE THREAD

**Issue by notcdk** [LWJGL/lwjgl3#315]
Sorry for not detailed information, i've reported it there
https://bugs.mojang.com/browse/MC-117881
look at attachements for hs_err_pid
seems like its happening only for me, and yes i have latest drivers

**Comment by BinarSkugga** [comment]
As said in the Minecraft issue report site, this is a nvidia crash not a LWJGL's. Either bad drivers or your graphic card is too old.
