### ISSUE TITLE
GL11.glPixelStoref Takes int Instead of float

### ISSUE THREAD

**Issue by gudenau** [LWJGL/lwjgl3#316]
In LWJGL 3.1.2 build 29 org.lwjgl.opengl.GL11.glPixelStoref takes an int for param instead of a float.

`    // --- [ glPixelStoref ] ---

    /**
     * <p><a target="_blank" href="http://docs.gl/gl4/glPixelStoref">Reference Page</a></p>
     * 
     * Float version of {@link #glPixelStorei PixelStorei}.
     *
     * @param pname the pixel store parameter to set
     * @param param the parameter value
     */
    public static native void glPixelStoref(int pname, int param);`

**Comment by Spasi** [comment]
Good catch, thanks!

**Comment by gudenau** [comment]
In the meantime Float.floatToRawIntBits would work the same correct?

**Comment by Spasi** [comment]
It should work, yes.

Btw, what use do you have for `glPixelStoref`? Afaik, all pixel store state variables are either boolean or integer.

**Comment by gudenau** [comment]
Oh, making a compatibility layer and found that mistake.
