### ISSUE TITLE
Error using Vulkan binding with build.gradle

### ISSUE THREAD

**Issue by jfelrod1960** [LWJGL/lwjgl3#317]
@spasi I'm having trouble executing the Vulkan demos using gradle.  Here is the error I'm getting ...

"C:\Program Files\Java\jdk1.8.0_121\bin\java" -Didea.launcher.port=7533 "-Didea.launcher.bin.path=C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.2.4\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_121\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_121\jre\lib\rt.jar;C:\Users\jfe.CAMPUS\Documents\AIDev\VulkanExamples\build\classes\main;C:\Users\jfe.CAMPUS\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl\3.1.2\af9c28e4cc38f58ef34131ca3d300b985b2e265\lwjgl-3.1.2-natives-windows.jar;C:\Users\jfe.CAMPUS\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-glfw\3.1.2\987e3151840ee1ed028f242dfd0894ceb0ab1073\lwjgl-glfw-3.1.2-natives-windows.jar;C:\Users\jfe.CAMPUS\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-jemalloc\3.1.2\4dfc918bf703180493e2fb113c9ba2256bcc80e2\lwjgl-jemalloc-3.1.2-natives-windows.jar;C:\Users\jfe.CAMPUS\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-openal\3.1.2\c0781595de8dbc3df03f7abae00e86e6a8c2a32b\lwjgl-openal-3.1.2-natives-windows.jar;C:\Users\jfe.CAMPUS\.gradle\caches\modules-2\files-2.1\org.lwjgl\lwjgl-stb\3.1.2\376b97a7cabe1ff5f46ff9f30da9361f25ba529f\lwjgl-stb-3.1.2-natives-windows.jar;C:\Program Files (x86)\JetBrains\IntelliJ IDEA 2016.2.4\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain org.lwjgl.demo.vulkan.InstancedSpheresDemo
Exception in thread "main" java.lang.NoClassDefFoundError: org/lwjgl/vulkan/VkDebugReportCallbackEXT
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:123)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.vulkan.VkDebugReportCallbackEXT
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more

I created a gradle project and copied all of the Vulkan demos from org.lwjgl.demo.vulkan into my gradle project using the same package name.  In addition I copied org.lwjgl.demo.opengl.util.DemoUtils into my project.

Also here is the build.gradle file ...

apply plugin: 'java'

version = '1.0'

targetCompatibility = 1.8
sourceCompatibility = 1.8

repositories {
    mavenCentral()
    mavenLocal()
}

project.ext.lwjglNatives = "natives-windows"
project.ext.lwjglVersion = "3.1.2"
project.ext.jomlVersion = "1.9.3"

dependencies {
	compile "org.lwjgl:lwjgl:${lwjglVersion}"
	compile "org.lwjgl:lwjgl-glfw:${lwjglVersion}"
	compile "org.lwjgl:lwjgl-jemalloc:${lwjglVersion}"
	compile "org.lwjgl:lwjgl-openal:${lwjglVersion}"
	compile "org.lwjgl:lwjgl-stb:${lwjglVersion}"
	compile "org.lwjgl:lwjgl-vulkan:${lwjglVersion}"
	runtime "org.lwjgl:lwjgl:${lwjglVersion}:${lwjglNatives}"
	runtime "org.lwjgl:lwjgl-glfw:${lwjglVersion}:${lwjglNatives}"
	runtime "org.lwjgl:lwjgl-jemalloc:${lwjglVersion}:${lwjglNatives}"
	runtime "org.lwjgl:lwjgl-openal:${lwjglVersion}:${lwjglNatives}"
	runtime "org.lwjgl:lwjgl-stb:${lwjglVersion}:${lwjglNatives}"
	compile "org.joml:joml:${jomlVersion}"
}

I'm using gradle version 3.5

I'm sure I did something wrong.  Appreciate your help
Jeff

**Comment by httpdigest** [comment]
I cannot reproduce this.
For some reason, your IntelliJ is not putting the "compile"-scoped dependencies in the runtime classpath, which it _must do_ (only 'compileOnly'-scoped dependencies are not put into the runtime classpath).
Open _View_ -> _Tool Windows_ -> _Gradle_ in the menu and in the now visible "Gradle projects" view hit the "blue rotating arrows" button to reimport/refresh the Gradle project. And then try again.

**Comment by jfelrod1960** [comment]
@httpdigest I had to rebuild the project.  Now it is working.  Thank you for your help.  I must have done something wrong when I first built the project.
