### ISSUE TITLE
Potential Nuklear issue with Intel Integrated Graphics

### ISSUE THREAD

**Issue by nickclark2016** [LWJGL/lwjgl3#318]
I have been working on adding Nuklear bindings to my engine.  I usually work on it on a computer with nVidia graphics, but have recently been using my laptop with a Intel 530.  When I use the nVidia card, it renders everything correctly.  However, when I use the Intel chip, it renders the scene 2 times, then stops updating the screen.  I am using the same process as outlined in the demos.  My window's update method looks as follows (https://pastebin.com/VmRL2pYV)

Has anyone experienced this issue or know a fix?

Update: My card renders Nuklear UIs by themselves correctly, as it renders my own OpenGL graphics correctly by themselves. It is just when they are mixed on my intel integrated graphics that it does not work.

Update 2: Here is a link to my runnable JAR.  I have found that it seems only NVidia architecture seems to work: [Dropbox](https://www.dropbox.com/sh/e2z69w817nik0k8/AAArzMVnIkxNozbzBvaUUD3qa?dl=0)

**Comment by nickclark2016** [comment]
Update: My card renders Nuklear UIs by themselves correctly, as it renders my own OpenGL graphics correctly by themselves.  It is just when they are mixed on my intel integrated graphics that it does not work.

**Comment by Spasi** [comment]
Nuklear itself does not render anything, it only provides data buffers and draw commands. How these are used depends on the application and the rendering API. Are you sure there are no OpenGL or shader compilation errors when running on the Intel GPU?

**Comment by nickclark2016** [comment]
No compilation issues, no OpenGL errors or notifications.  It runs, renders everything, but it doesn't update the screen after the first glfwSwapBuffers call by the looks of it.
