### ISSUE TITLE
MemoryStack.UTF8 out of a partial CharSequence?

### ISSUE THREAD

**Issue by dustContributor** [LWJGL/lwjgl3#319]
Hi! I'm trying to make the text wrap thingy I talked about in #313 

My idea is to accumulate all the text into a single StringBuilder, and later hand out slices of that to Nuklear to draw after I compute the line lengths.

The issue is that I noticed it doesn't seems I can do that, Nuklear nk_text calls are like:
```java
// Inside this does the stack.UTF8(str) call
public static void nk_text(NkContext ctx, CharSequence str, int alignment); 
// This hands the address of the str buffer assuming it's already UTF8
public static void nk_text(NkContext ctx, ByteBuffer str, int alignment)
// Native call to Nuklear (sort of)
public static native void nnk_text(long ctx, long str, int len, int alignment)
```

So I can only hand out an entire string or nothing. The simplest solution is to create a CharSequence implementation that works with offsets inside. Using a heap CharBuffer *could* work since it handles position/offsets just fine, but it isn't dynamically resizable like a StringBuilder, so I'd need to make the realloc myself. 

An LWJGL side solution could be:

```java
try(MemoryStack mem = MemoryStack.push()) {
  ByteBuffer buffer = mem.UTF8(someString, startOffset, endOffset);
  nk_text(ctx, buffer, 0);
  startOffset += someStride;
  endOffset += someOtherStride;
}
```
ie, adding a new MemoryStack.UTF8 overload that receives start/end offsets to read from the CharSequence. Makes sense?

It is just a suggestion since I can make it work with a thin CharSequence implementation anyway.

**Comment by Spasi** [comment]
I'd like to keep the raw `CharSequence` encoding implementations in LWJGL simple and avoid adding start/end offsets.

> I can make it work with a thin CharSequence implementation anyway.

That's the expected way to do it. It's why string encoding in LWJGL accepts `CharSequence`, for cases like this. Building a `CharSequence` view on top of another implementation (e.g. `StringBuilder`) should be trivial.

With that said, I would avoid a `StringBuilder` and a UTF-8 encoding loop altogether. Why pay the encoding overhead every frame? You could encode the entire text once, to a single buffer. If we're talking about something like a chat box, you should already have a rough idea of how much text is going to be in there (a chat history limit?) and pre-allocate a buffer with the appropriate size. You'd still probably need to reallocate sometimes, but it should be minimal. Then, for each line, you can call `nk_text` by either manipulating the buffer's `position/limit` or by using `nnk_text` and manual `str/len` offsets.

**Comment by dustContributor** [comment]
> With that said, I would avoid a StringBuilder and a UTF-8 encoding loop altogether. Why pay the encoding overhead every frame?

One step at a time :smile: I'll see about optimizing it like you suggested once I have it working.

Anyway, yeah, it makes sense, I'll just use a CharSequence implementation. Thanks for the feedback! .
