### ISSUE TITLE
OpenGL create context

### ISSUE THREAD

**Issue by piegamesde** [LWJGL/lwjgl3#321]
Is there a way to create an OpenGL context in a specific thread without having a window and to use GLFW? I posted a more detailed question about this [on stackoverflow](https://computergraphics.stackexchange.com/questions/5245/lwjgl-3-render-to-texture-offscreen-without-display), but apparently nobody had to deal with this kind of situation before.

**Comment by Spasi** [comment]
Creating a hidden GLFW window is the recommended way to do off-screen rendering.

I don't see how the window visibility state is related to getting a `GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT` status from your FBO. Could you share a minimal code sample that reproduces this? Also some information about your OS and hardware would be useful.

**Comment by piegamesde** [comment]
That's weird. I tried to remove the `glfwShowWindow(window);` line again and this time, no errors. I sadly don't have the broken code anymore so maybe I had an error somewhere else that just got triggered when the window was closed and it was thrown at the wrong place for different reasons.
