### ISSUE TITLE
Nuklear Issues

### ISSUE THREAD

**Issue by nickclark2016** [LWJGL/lwjgl3#322]
I am testing the Nuklear bindings in my game engine and have found a weird "bug" when I am using my Surface Pro 4. I have been using the calculator example provided, but when I try to use the calculator's buttons, it attempts to press the button above it (e.g. hovering over "6" will display "9" as being hovered over). When I use my desktop or another laptop I do not experience this issue. I have verified that the mouse coordinates as received by Nuklear are correct.  It works neither in the code example or in my own application. 

I can post screen captures and code if there is a need.

**Comment by Spasi** [comment]
Could you please try the `org.lwjgl.demo.nanovg.ExampleGL3` or `org.lwjgl.demo.stb.Vorbis` demos and check whether mouse interaction works as expected?

Is there a difference if you change the DPI settings on the Surface Pro?

**Comment by nickclark2016** [comment]
They do as far as I can tell, but the change in DPI does not help my problem.

**Comment by Spasi** [comment]
LWJGL 3.1.3 build 5 is now available and it includes updated GLFW and Nuklear. Could you please try it?

**Comment by nickclark2016** [comment]
I will in a few.  I have found that there is an issue with OpenGL based applications on the device, as I experience similar issues with Blender.  This may be driver related.
