### ISSUE TITLE
glAlphaFunc Program Crash

### ISSUE THREAD

**Issue by oreon3D** [LWJGL/lwjgl3#323]
When I call the functions glEnable(GL_ALPHA_TEST) and glAlphaFunc ( _some function_, _some value_) the program crashes at the glAlphaFunc call with the error message:

[LWJGL] A function that is not available in the current context was called. The JVM will abort execution. Inspect the crash log to find the responsible Java frames.

I am wondering why exactly the same configuration was executable with lwjgl 2, it's just simple alpha testing...
The error message "A function that is not available in the current context was called." doesn't help me that much.

**Comment by Spasi** [comment]
It sounds like you're using a core/forward-compatible context, which does not expose the `glAlphaFunc` function. Alpha test is legacy OpenGL functionality that has been deprecated in modern OpenGL. It can be replaced with `discard` in the fragment shader.

**Comment by oreon3D** [comment]
Alright, that helps me, thank you!

**Comment by oreon3D** [comment]
But the I have to implement GL_SAMPLE_ALPHA_TO_COVERAGE by myself right? GL_SAMPLE_ALPHA_TO_COVERAGE isn't applied to textures with Alpha Test in Fragment Shader with discard.

**Comment by Spasi** [comment]
`GL_SAMPLE_ALPHA_TO_COVERAGE` works with the `alpha` value that the fragment shader outputs. If the shader is expensive, you can still use `discard` to early-out when `alpha` is `0.0`. For all other fragments, the `alpha` value will be translated correctly to a coverage mask.

Also note that the alpha test and `discard` can always be used, but `GL_SAMPLE_ALPHA_TO_COVERAGE` requires multi-sampling to work.

An expensive alternative to `GL_SAMPLE_ALPHA_TO_COVERAGE` is `GL_SAMPLE_SHADING`/`glMinSampleShading`/`gl_SampleID`. You can make your fragment shader run for each sample, in which case `discard` will produce the correct coverage.
