### ISSUE TITLE
GLFW.glfwInit() take 10s to complete

### ISSUE THREAD

**Issue by malobre** [LWJGL/lwjgl3#325]
Measured with:
```java
long start = System.currentTimeMillis();
if (!GLFW.glfwInit()) throw new IllegalStateException("Unable to initialize GLFW");
long stop = System.currentTimeMillis();
System.out.println("GLFW.glfwInit() took " + (stop - start) + "ms");
```

Output:
```
GLFW.glfwInit() took 10071ms
GLFW.glfwInit() took 10073ms
GLFW.glfwInit() took 10060ms
GLFW.glfwInit() took 10070ms
GLFW.glfwInit() took 10058ms
GLFW.glfwInit() took 10068ms
GLFW.glfwInit() took 10075ms
GLFW.glfwInit() took 10077ms
GLFW.glfwInit() took 10070ms
GLFW.glfwInit() took 10076ms
```

The measuring code is the only thing that is in the main method.

Is this normal behavior ? Ten seconds is awfully long.

I can provide more info on my setup if needed.

**Comment by httpdigest** [comment]
> I can provide more info on my setup if needed.

It certainly is needed. What OS, what CPU arch, etc. However, this seems more like a GLFW issue than one of LWJGL 3. You should instead clone the GLFW repo, build their native examples and see whether running them also takes seconds. If so, open an issue with GLFW and detail exactly your system specs and the exact steps to reproduce the behaviour.

**Comment by malobre** [comment]
I ran the GLFW example and it also take 10s to launch.
I will open an issue on the GLFW repo asap.
I'm also closing this issue as everything is fine with lwjgl.
