### ISSUE TITLE
GL11 | glEnable- / glDisableClientState doc wrong

### ISSUE THREAD

**Issue by dotSp0T** [LWJGL/lwjgl3#327]
The documentation on the current version of the generated class [GL11](https://github.com/LWJGL/lwjgl3-generated/blob/master/java/org/lwjgl/opengl/GL11.java) is wrong for the functions [glEnableClientState](https://github.com/LWJGL/lwjgl3-generated/blob/master/java/org/lwjgl/opengl/GL11.java#L2094) and [glDisableClientState](https://github.com/LWJGL/lwjgl3-generated/blob/master/java/org/lwjgl/opengl/GL11.java#L1821).

Both functions have been deprecated in version 3.0 and removed in version 3.1.

I understand that they have been wrongly un-deprecated as of Issue #290 ([commit](https://github.com/LWJGL/lwjgl3-generated/commit/52432522e9e84859670d4fd4005aa361e8ed5d41)).

**Comment by Spasi** [comment]
Documentation could be better (unlike Vulkan, OpenGL docs are written by hand, contributions are welcome), but technically LWJGL is doing the right thing here. From the [NV_vertex_buffer_unified_memory](https://www.khronos.org/registry/OpenGL/extensions/NV/NV_vertex_buffer_unified_memory.txt) spec:

> If the context version is greater than 3.0 and does not include ARB_compatibility functionality, then EnableClientState and DisableClientState have been deprecated and removed. This extension adds back those commands, but only requires that they accept the VERTEX_ATTRIB_ARRAY_UNIFIED_NV and ELEMENT_ARRAY_UNIFIED_NV tokens.

Currently LWJGL will load the function pointers for `EnableClientState` and `DisableClientState`, but it won't check whether they're available or not. This will work in any combination of compatibility profile, core profile and presence of `NV_vertex_buffer_unified_memory`. A strict check could be added, but honestly it would be a waste of effort, this is the only occurrence of a deprecated function being undeprecated.

**Comment by Spasi** [comment]
Nevermind, it was simple enough. Generated code diff: LWJGL/lwjgl3-generated@8cfd34369928fa36096018fed4e12b2c841880b2.

Thanks!

**Comment by dotSp0T** [comment]
Sweet! I assumed the doc to be generated and didn't really look for the generator code...

If you can link me to it I'll go through it and make sure deprecated methods link to the correct doc/spec versions? (making a pullrequest for it in the end)

**Comment by Spasi** [comment]
The OpenGL templates used by the generator are [here](https://github.com/LWJGL/lwjgl3/tree/master/modules/templates/src/main/kotlin/org/lwjgl/opengl/templates). They are written in Kotlin.
