### ISSUE TITLE
OpenGL 4.6 support?

### ISSUE THREAD

**Issue by LordC777** [LWJGL/lwjgl3#328]
Khronos released the GL4.6 spec yesterday, which brought SPIR-V support and other things, will there be 4.6 support?

**Comment by Meronat** [comment]
https://github.com/LWJGL/lwjgl3/commit/fee37bac713ed9a0c14c97b9ed21accc1ee1c633

**Comment by LordC777** [comment]
Wow, that was quick.

**Comment by Spasi** [comment]
The latest snapshot (3.1.3 build 9) includes OpenGL 4.6 and latest extensions.
