### ISSUE TITLE
GPU Affinity

### ISSUE THREAD

**Issue by EmpsThomy** [LWJGL/lwjgl3#330]
Hi!

Is there a way to get the GPU affinity of my program through lwjgl? I'd like to automate this process for laptops that have 2 graphic cards and select the high performance card. I'm using Java 8, lwjgl 3.1.1 and aim to achieve this task on Windows.

I've already read about Nvidia Optimus and found following stackoverflow topic: https://stackoverflow.com/questions/6036292/select-a-graphic-device-in-windows-opengl
However, they set a C flag and that's tedious to do through Java for mac, linux and windows when the rest of my application stack is all written in Java.

I've also found following lwjgl package:
>org.lwjgl.opengl.WGLNVGPUAffinity

However trying to loop through EnumGpusNV crashes the JVM:
>			PointerBuffer gbuf = MemoryUtil.memAllocPointer(1024);
>			for (int i = 0; i < 5; i++) {
>				WGLNVGPUAffinity.wglEnumGpusNV(i, gbuf);
>				//System.out.println("gpu["+i+"]: "+gbuf.getStringASCII());
>			}

Are there examples on how to auto-select a GPU through lwjgl?

Thanks,
Thomy

**Comment by httpdigest** [comment]
There are no ways to do this other than what is described here: http://developer.download.nvidia.com/devzone/devcenter/gamegraphics/files/OptimusRenderingPolicies.pdf

Also, the Stackoverflow answer you are referring to about WGL_NV_gpu_affinity mentions this: **But it is only supported on QUADRO series.** and hardly anyone has a Quadro card in their Laptops.

However, I do, and I've tested WGL_NV_gpu_affinity on my Laptop, and funny enough, that extension is only exposed/exported by the driver iff you are already running on the dedicated Quadro card.
So, WGL_NV_gpu_affinity is really only meant to be used on workstations that have multiple Quadro cards installed.

**Comment by EmpsThomy** [comment]
Thanks for the quick reply! In that case I have to add a native binding. Will there be support in the future by the lwjgl library to enable that behavior by default?

**Comment by httpdigest** [comment]
Please note that even a native shared library will not help. The process module file must export that symbol. Even if lwjgl.dll did export it, it would not work. Your _only_ option in that regard is to provide a custom java.exe/javaw.exe launcher, which is quite simple to do. Have a look at the JNI Invocation API.

**Comment by kdunee** [comment]
> Please note that even a native shared library will not help. The process module file must export that symbol. Even if lwjgl.dll did export it, it would not work. Your only option in that regard is to provide a custom java.exe/javaw.exe launcher, which is quite simple to do. Have a look at the JNI Invocation API.

For future reference, I wrote a blog post on this subject with code examples: https://www.dunikovsky.online/posts/nvidia-optimus-jvm/
