### ISSUE TITLE
Crashing on threads?

### ISSUE THREAD

**Issue by BlakeBarnes00** [LWJGL/lwjgl3#332]
I am fairly new to using LWJGL, and I keep getting this error. From what I can tell from reading under the THREAD section in the log, it seems to crash on Thread.run()

Here is the log file IntelliJ spits out at me: [hs_err_pid18639.log ](https://gist.github.com/BlakeBarnes00/fe7508820a735b39b2e3477aeb5651af)

**Comment by httpdigest** [comment]
[glfwCreateWindow](http://www.glfw.org/docs/latest/group__window.html#ga5c336fddf2cbb5b92f65f10fb6043344) (read the section "Thread safety") as well as a lot of other GLFW functions may _only_ be called in the _main_ thread (which is the thread that initially calls your main method).
Also make sure you call glfwInit before doing anything with GLFW (except setting its error callback via glfwSetErrorCallback).

**Comment by BlakeBarnes00** [comment]
I still get the same error for when I completely go away from starting on another thread. 

Here is my recent push: https://github.com/BlakeBarnes00/Sandbox/commit/42c7571690ae3b77487c982df873aa894804ff58 it shows that I have removed the thread, and went straight to calling ```run()```. Still getting the same error from within the inside of the function.

**Comment by sriharshachilakapati** [comment]
Thinking from the docs, I assume that main thread in that context means the thread that called the `glfwInit()` function right? Even after the change, it should work if that was the cause. He also do seem to set the GLFW error callback.

@BlakeBarnes00 Could you delete all the error logs and retry? Upload the new log after the rerun.

**Comment by BlakeBarnes00** [comment]
@sriharshachilakapati 

[new log](https://gist.github.com/BlakeBarnes00/b93b0b76b9967d2385e7f1ce9a13d836)
[most recent commit](https://github.com/blakebarnes00/sandbox/commit/da807c8a73aaa21698b2b57c3de7c4ff15e3bd17)

**Comment by sriharshachilakapati** [comment]
Remove the call to `init()` in the Window class constructor, it's already being initialized by the game engine. Did you try the native GLFW to verify if this is a problem of your system instead?

Can you run my game (self running fat jar) http://downloads.goharsha.com/ld38/PlanetDefenseDesktop.jar ?

**Comment by sriharshachilakapati** [comment]
I guess that [line 49 of Window.java](https://github.com/BlakeBarnes00/Sandbox/blob/OpenGL/src/com/ellisbarnes/OpenGL/engine/Window.java#L49) is your error. You had this:

~~~java
this.windowHandle = glfwCreateWindow(this.width, this.height, this.title, 1, 0);
~~~

The fourth parameter is the monitor to use, and that is only used to make your window fullscreen on start. For other windows, it should be `MemoryUtil.NULL` or 0.

The error you are having is a SIGSEGV, which means that something got a segmentation fault, like accessing un-owned memory location, and that might be the unknown monitor handle.

To get the correct monitor handle, you have to use `glfwGetPrimaryMonitor()` function to get the ID of the primary monitor. Hope this helps.

**Comment by BlakeBarnes00** [comment]
That was the fix! I can't believe I overlooked that this entire time. Thank you so much @sriharshachilakapati

**Comment by sriharshachilakapati** [comment]
Now try to get your threading code back into place. I'm sure running with thread is fine on non-mac machines which your initial code does in the `gameEngine.start()` method. I'm curious about this.

**Comment by BlakeBarnes00** [comment]
With ```gameEngine.start()``` it works now! Funny how one number can ruin an entire program, eh?

**Comment by sriharshachilakapati** [comment]
Good, as I believed, the main thread in this context is the thread that invoked `glfwInit()` and not the thread that ran your main method. This becomes the later on MacOS, because Cocoa doesn't allow two application event loops in a single application and that contradicts with the EDT of Swing/JavaFX. Congrats on getting this solved, and I guess we both learned a new thing.

**Comment by BlakeBarnes00** [comment]
I am still new to threading, so this did help me out a lot. Thank you so much!

**Comment by httpdigest** [comment]
Thanks @sriharshachilakapati for inspecting and solving this!
I've added a check for this potential error to https://github.com/LWJGLX/debug.
