### ISSUE TITLE
eglMakeCurrent with EGL_NO_SURFACE does not work

### ISSUE THREAD

**Issue by Jochen0x90h** [LWJGL/lwjgl3#335]
for off-screen rendering I use eglMakeCurrent(display, EGL_NO_SURFACE, EGL_NO_SURFACE, context); which throws a nullpointer exception. This should be allowed (and works when copy/pasting eglMakeCurrent and removing checks for draw and read). Is it possible to fix this? (Class is org.lwjgl.egl.EGL10)

**Comment by Spasi** [comment]
This will be fixed in the first 3.1.4 snapshot. Thanks!
