### ISSUE TITLE
How to create list of EGLConfig for eglChooseConfig?

### ISSUE THREAD

**Issue by Jochen0x90h** [LWJGL/lwjgl3#336]
eglChooseConfig is used in C like this:
`EGLint numConfigs;
EGLConfig config;
eglChooseConfig(display, configAttribs, &config, 1, &numConfigs);`

How does this translate to lwjgl? As I don't know the size of EGLConfig I created a buffer of size 1024. This works but looks like a hack:
`PointerBuffer configs = stack.mallocPointer(1);
ByteBuffer b = stack.malloc(1024);
configs.put(0, b);
int[] numConfigs = new int[1];
eglChooseConfig(display, configAttribs, configs, numConfigs);`

What is the correct way to do this?

**Comment by Spasi** [comment]
`EGLConfig`  is an opaque pointer type. There is no way to know the size of the data structure behind it and it doesn't matter (you query it with `eglGetConfigAttrib`).

The standard way to use `eglChooseConfig` is to first call it with `configs == NULL`. Example code:

```java
try (MemoryStack stack = stackPush()) {
    IntBuffer attribList = stack.ints(
        EGL_SURFACE_TYPE, EGL_WINDOW_BIT,
        EGL_RENDERABLE_TYPE, EGL_OPENGL_ES2_BIT,
        EGL_COLOR_BUFFER_TYPE, EGL_RGB_BUFFER,
        EGL_RED_SIZE, 8,
        // ...more here...
        EGL_NONE
    );

    IntBuffer numConfig = stack.mallocInt(1);

    if (!eglChooseConfig(glfwGetEGLDisplay(), attribList, null, numConfig)) {
        throw new IllegalStateException(String.format("eglChooseConfig failed [0x%X]", eglGetError()));
    }

    PointerBuffer configs = stack.mallocPointer(numConfig.get(0));

    eglChooseConfig(dpy, attribList, configs, numConfig);

    // ...query the returned configs and choose one...
}
```

The first call returns the number of available configs (based on the specified attribute list) to `numConfig`. Then you know how big the `configs` buffer must be.
