### ISSUE TITLE
GL43 glDebugMessageControl issue

### ISSUE THREAD

**Issue by johnnic431** [LWJGL/lwjgl3#337]
When manually creating a GL Debug callback, the method `GL43.glDebugMessageControl(GL11.GL_DONT_CARE,GL11.GL_DONT_CARE,GL11.GL_DONT_CARE,BufferUtils.createIntBuffer(0),false);` does not disable any debug messages. Flipping the intbuffer does not change anything. In the javadoc, settinf the last argument to false should disable all messages, as the buffer is effectively null. I have also tested this with only specific id's disabled (`GL43.glDebugMessageControl(GL11.GL_DONT_CARE,GL11.GL_DONT_CARE,GL11.GL_DONT_CARE,BufferUtils.createIntBuffer(1),put(131185)[.flip()],false);`) and there is no change in behavior.

**Comment by Spasi** [comment]
> does not disable any debug messages

I was able to reproduce this on Windows with the latest Nvidia drivers. However, this works (and doesn't do a redundant allocation):

```glDebugMessageControl(GL_DONT_CARE, GL_DONT_CARE, GL_DONT_CARE, (IntBuffer)null, false);```

In both cases `0` is passed to the native `count` parameter, only the `ids` parameter is different (null vs not-null). This is probably a driver bug, according to the spec: *if count is zero, the value if `ids` is ignored*.

> I have also tested this with only specific id's disabled

This is not allowed, when `count` is not zero then: *if source or type is `DONT_CARE`, or severity is not `DONT_CARE`, the error `INVALID_OPERATION` is generated*.

**Comment by johnnic431** [comment]
Correct me if I am wrong, but from that I gether that this should disable the error ID 131185, which produces the output
`ID 131185: OTHER of NOTIFICATION severity, raised from API: Buffer detailed info: Buffer object 12 (bound to GL_ELEMENT_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations.`

This is the new code I tried:

`GL43.glDebugMessageControl(GL43.GL_DEBUG_SOURCE_API,GL43.GL_DEBUG_TYPE_OTHER,GL43.GL_DEBUG_SEVERITY_NOTIFICATION,BufferUtils.createIntBuffer(1).put(131185)[.flip()],false);`

It still shows all notifications, even 131185 as detailed above. Am I still doing it incorrectly? I have the correct source, debug type, and severity level, which are not DONT_CARE, along with the correct ID.

Changing that line to `GL43.glDebugMessageControl(GL43.GL_DEBUG_SOURCE_API,GL43.GL_DEBUG_TYPE_OTHER,GL43.GL_DEBUG_SEVERITY_NOTIFICATION,(IntBuffer)null,false);`
fixes it, but obviously kills all other notifications in that level. Minor issue, and I know i could just return on bad ID's in my callback (which I'm currently doing), but this just doesn't seem right.

**Comment by Spasi** [comment]
> `GL43.glDebugMessageControl(GL43.GL_DEBUG_SOURCE_API,GL43.GL_DEBUG_TYPE_OTHER,GL43.GL_DEBUG_SEVERITY_NOTIFICATION,BufferUtils.createIntBuffer(1).put(131185)[.flip()],false);`
> 
> It still shows all notifications, even 131185 as detailed above. Am I still doing it incorrectly? 

Yes, see the end of my previous reply. When `ids` are specified, severity must be `GL_DONT_CARE`.
