### ISSUE TITLE
LWJGL supporting Java 9 automatic modules not possible?

### ISSUE THREAD

**Issue by blobjim** [LWJGL/lwjgl3#338]
Eclipse gives this error when putting lwjgl libraries on the module path:  `The package org.lwjgl is accessible from more than one module: lwjgl, lwjgl.glfw, lwjgl.openal, lwjgl.opengl`. This shows that even attempting to use lwjgl as a set of modules will not work, since the same package name cannot be in multiple modules (as specified by the module system). This issue can probably just be closed since it sounds like modules wont be dealt with until LWJGL 4 (I assume that will be after things like value types, project panama, etc.?). I'm still confused by the module system sometimes so I may be wrong about a lot of this. For now, the workaround seems to be to only use the classpath.

**Comment by Spasi** [comment]
Sounds like a bug in Eclipse. Which version do you use? I'm not familiar with the state of module support in Eclipse, but updating to a newer version (possibly beta) may fix the issue.

First issue I notice is that Eclipse doesn't recognize `Automatic-Module-Name` in the LWJGL manifests. The modules `lwjgl`, `lwjgl.glfw`, ..., should be `org.lwjgl`, `org.lwjgl.glfw`, etc.

The `org.lwjgl.glfw` module contains only the `org.lwjgl.glfw` package with the GLFW classes. It shouldn't trigger the `The package org.lwjgl is accessible from more than one module` error. It's probably an issue with how Eclipse treats automatic modules.

You could verify that this isn't an LWJGL issue with: `java -p <path_to_LWJGL_jars> --add-modules ALL-MODULE-PATH --validate-modules` with LWJGL `3.1.4 build 3` or newer.

**Comment by blobjim** [comment]
The module validation worked. I'm using the latest Eclipse Oxygen with the updated Java 9 support. I also wasn't using LWJGL 3.1.4 so that's definitely my mistake. I'll try the library on the module path again and see how it goes.
