### ISSUE TITLE
NanoVG: Why does `nvgImageSize` take arrays as parameters?

### ISSUE THREAD

**Issue by otoomey** [LWJGL/lwjgl3#342]
The signature for the generated binding for `NanoVG.nvgImageSize()` is as follows:

```(java)
public static void nvgImageSize(long ctx, int image, int[] w, int[] h)
```

However, NanoVG (original, not binding) [simply takes two ints](https://github.com/memononen/nanovg/blob/master/src/nanovg.h#L386). Why does the binding take two arrays?

**Comment by kenzierocks** [comment]
It looks like it takes two `int*`, aka pointers to `int`s, which in Java is either `int[]` or `IntBuffer`, so this signature is correct.

**Comment by otoomey** [comment]
That makes much more sense.
