### ISSUE TITLE
Usage of glfwUpdateGamepadMappings

### ISSUE THREAD

**Issue by virtuoushub** [LWJGL/lwjgl3#343]
I am attempting to update the gamepad mappings. So far, without any luck. 

I have tried using both methods: 
- [`org.lwjgl.glfw.GLFW#glfwUpdateGamepadMappings(java.nio.ByteBuffer)`](https://javadoc.lwjgl.org/org/lwjgl/glfw/GLFW.html#glfwUpdateGamepadMappings-java.nio.ByteBuffer-)
- [`org.lwjgl.glfw.GLFW#glfwUpdateGamepadMappings(java.lang.CharSequence)`](https://javadoc.lwjgl.org/org/lwjgl/glfw/GLFW.html#glfwUpdateGamepadMappings-java.lang.CharSequence-)

Here is an example of what I have tried using `glfwUpdateGamepadMappings(java.lang.CharSequence)`
```java
final String string = "030000004c050000c405000000010000,PS4 Controller,a:b1,b:b2,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b12,leftshoulder:b4,leftstick:b10,lefttrigger:a3,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b11,righttrigger:a4,rightx:a2,righty:a5,start:b9,x:b0,y:b3,platform:Mac OS X,";
assert glfwUpdateGamepadMappings(string);
```

The code above results in a `Exception in thread "main" java.lang.AssertionError` in my environment. From the documentation `glfwUpdateGamepadMappings` 

> Returns:
true, or false if an error occurred

Not sure what is causing the error.

See also:
- http://www.glfw.org/docs/3.3/input_guide.html#gamepad_mapping
- https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt
- https://github.com/gabomdq/SDL_GameControllerDB/issues/110

**Comment by Sylvyrfysh** [comment]
Have you tried GLFW error callbacks? This would be my go-to.

http://www.glfw.org/docs/3.0/group__error.html

**Comment by virtuoushub** [comment]
@Sylvyrfysh, I had not yet. I just did and now.
```java
glfwSetErrorCallback((error, description) -> {
    System.out.println("error " + error);
    System.out.println("description " + GLFWErrorCallback.getDescription(description));
});
```
Resulted in.
```
error 65537
description The GLFW library is not initialized
```
I was attempting to call `glfwUpdateGamepadMappings` before [org.lwjgl.glfw.GLFW#glfwInit](https://javadoc.lwjgl.org/org/lwjgl/glfw/GLFW.html#glfwInit--)... :man_facepalming:

I made sure to call it after and now I am all set.

Thank you for the quick reply.
