### ISSUE TITLE
Raw OpenGL context pointer

### ISSUE THREAD

**Issue by olegchir** [LWJGL/lwjgl3#350]
I don't know where to write such questions, so put it here (sorry for that)

I want to integrate my swing app (plugin for IntelliJ IDEA Community Edition) with Servo (rendering engine for Firefox)

So I decided to embed somehow lwjgl into Swing, and then get a raw opengl context pointer to pass it to the Servo. Servo have Rust API, but I'll try to wrap it with C++ and attach it via JNI.

Two questions: 
1) is it a good idea?
2) how to obtain a raw pointer?

I'm a complete beginner, but maybe you'll point me the direction.

Now I'm trying to compile the following:
1) create a swing app
2) connect jpane with a canvas
3) implement mouseadapters and prepare to send events to Servo
4) Display.setParent(java.awt.Canvas) to put the LWJGL display on a canvas
5) Get raw pointer to opengl context
6) Wrap Rust with C++
7) Wrap C++ with JNI
8) Pass raw pointer to JNI API
9) Send mouse events to JNI API

So far I am very afraid of the sudden complexity of the task, especially for cross-platform solution (Winodws, GNU/Linux - must have, MacOS/OSX - very very desirable) :(

**Comment by Spasi** [comment]
LWJGL contains bindings to WGL, GLX, etc. You can use them to create, manage or access OpenGL contexts. GLFW also exposes the native window/context, with the platform-specific classes (`GLFWNativeWGL`, `GLFWNativeGLX`, etc).

What you're trying to do sounds hard, unless Servo has a decent embedding API. You may want to start with https://github.com/paulrouget/servo-embedding-example.

Btw, `Display.setParent(java.awt.Canvas)` does not exist in `lwjgl3`, it's an [lwjgl2](https://github.com/LWJGL/lwjgl) API. In `lwjgl3`, see the JAWT bindings.
