### ISSUE TITLE
GLFW generated | clipboard get/set | remove check for window handle

### ISSUE THREAD

**Issue by dotSp0T** [LWJGL/lwjgl3#357]
The current version of the generated GLFW bindings do a check on window `window-handle` parameter for the `glfwGetClipboardString` / `glfwSetClipboardString` methods.

As I understand it LWJGL mirrors the GLFW development branch, not the stable one, thus the clipboard methods should allow NULL handles as specified in [this commit that deprecates window handles in clipboard functions](https://github.com/glfw/glfw/commit/31cbb20ba276af45f7d5dffcb91fd231e597f6ce)

**Comment by Spasi** [comment]
Thanks!
