### ISSUE TITLE
Can Not Build on Windows 10 x64: LNK2001

### ISSUE THREAD

**Issue by gudenau** [LWJGL/lwjgl3#362]
### Environment

* LWJGL version: `e2e54e94821cfe41a8f0e1f7e7ad5bea8fd46c9b` 
* LWJGL build #: `X`
* Java version: `9.0.1`
* Platform: `Windows 10 x64`
* Module: `DynCall, maybe others`

### Description
Building LWJGL3 on Windows 10 x64 fails on `ant compile-native` with several unresolved symbols.

These are the missing symbols as reported by ant:

- `_dcArgFloat`
- `_dcCallChar`
- `_dcStructSize`
- `_dcArgChar`
- `_dcDefineStruct`
- `_dcArgLongLong`
- `_dcCallLong`
- `_dcStructField`
- `_dcMode`
- `_dcFree`
- `_dcArgLong`
- `_dcCallVoid`
- `_dcArgShort`
- `_dcCallStruct`
- `_dcCallBool`
- `_dcCallShort`
- `_dcSubStruct`
- `_dcCloseStruct`
- `_dcFreeStruct`
- `_dcArgPointer`
- `_dcNewStruct`
- `_dcArgBool`
- `_dcCallLongLong`
- `_dcStructAlignment`
- `_dcArgDouble`
- `_dcCallDouble`
- `_dcReset`
- `_dcArgStruct`
- `_dcCallPointer`
- `_dcCallFloat`
- `_dcGetError`
- `_dcArgInt`
- `_dcCallInt`
- `_dcNewCallVM`
- `_dcbArgUChar`
- `_dcbArgBool`
- `_dcbArgUShort`
- `_dcbArgShort`
- `_dcbArgDouble`
- `_dcbArgLong`
- `_dcbArgLongLong`
- `_dcbNewCallback`
- `_dcbArgUInt`
- `_dcbArgPointer`
- `_dcbInitCallback`
- `_dcbGetUserData`
- `_dcbArgInt`
- `_dcbArgULong`
- `_dcbFreeCallback`
- `_dcbArgFloat`
- `_dcbArgChar`
- `_dcbArgULongLong`
- `_dlSymsNameFromValue`
- `_dlSymsName`
- `_dlFreeLibrary`
- `_dlSymsCleanup`
- `_dlFindSymbol`
- `_dlLoadLibrary`
- `_dlSymsInit`
- `_dlSymsCount`

### Steps to Reproduce:
1. `mkdir test`
2. `cd test`
3. `pushd .`
4. `call "D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"`
5. `popd`
6. `git clone https://github.com/LWJGL/lwjgl3.git .`
7. `ant init`
8. `ant init-generated`
9. `ant init-wiki`
10. `ant compile-templates`
11. `ant generate`
12. `ant compile`
13. `ant compile-native`

### Environment

* LWJGL version: `M.m.r` 
* LWJGL build #: `X`
* Java version: `java.version`
* Platform: `Linux|macOS|Windows`
* Module: `core|binding name`

**Comment by httpdigest** [comment]
The msvc environment defaults to 32-bit/x86.
In order to switch to 64-bit/x86-64/amd64 use `VsDevCmd.bat -arch=amd64`

**Comment by gudenau** [comment]
Oh my god I'm an idiot.
