### ISSUE TITLE
Kotlin Library

### ISSUE THREAD

**Issue by sgwerder** [LWJGL/lwjgl3#376]
LWJGL3 is clearly a Kotlin library - with a Java API. This should be reflected on the site and the description.

**Comment by kenzierocks** [comment]
Unless things have changed, LWJGL is still 100% Java at compile time, and only uses Kotlin for generation of sources. It's not really a Kotlin library.

**Comment by sgwerder** [comment]
Can you also generate Kotlin sources?

**Comment by Spasi** [comment]
> Can you also generate Kotlin sources?

Not at the moment, but you can use LWJGL in Kotlin, just like any other Java library. Also, nullability annotations have been added recently which improves Kotlin interop.

Generating Kotlin sources could be beneficial for certain things. E.g. making struct access syntax look like C, with Kotlin properties. However, Kotlin/Native is maturing quickly and I'm waiting to see what options open there, before committing to anything.
