### ISSUE TITLE
crash, exit code -2

### ISSUE THREAD

**Issue by jsdeveloper97** [LWJGL/lwjgl3#379]
### Environment

* LWJGL version: 3.1.0
* LWJGL build #: 0
* Java version: 8
* Platform: Windows
* Module: core

### Description

I copied hello world example from the website and it works good, but when I close window it crashes and I get error

```
ERROR: JDWP Unable to get JNI 1.2 environment, jvm->GetEnv() return code = -2
       JDWP exit error AGENT_ERROR_NO_JNI_ENV(183): [util.c:840]
```

Is this a lwjgl issue, or is something wrong with my java binaries?

**Comment by Spasi** [comment]
> LWJGL version: 3.1.0

Could you please try with `3.1.6` instead? Also, could you post the full output of `java -version`?

**Comment by jsdeveloper97** [comment]
Ah sorry, my version is actually 3.1.6, build 14, I was looking at wrong numbers. And here is output of java version

```
java version "1.8.0_162"
Java SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot 64-Bit Server VM (build 25.162-b12, mixed mode)
```

BTW, I am using Eclipse to build project

**Comment by Spasi** [comment]
Are you running your application in a debugger? Does it happen if not?

**Comment by jsdeveloper97** [comment]
It is hard to tell, since the error dosn't display always. I had to test it multiple times and here are the results (numbers represent number of times tested):

|             | No crash | Crash |
|:-----------:|:--------:|:-----:|
| Debugger    | 92       | 3     |
| No debugger | 88       | 0     |

**Comment by Spasi** [comment]
Apparently it's a known low-priority issue marked as _won't fix_:

[JDK-6476706](https://bugs.openjdk.java.net/browse/JDK-6476706)

There's a call to [GetEnv](https://docs.oracle.com/javase/8/docs/technotes/guides/jni/spec/invocation.html#GetEnv) somewhere, probably a race condition when exiting the debugging session makes it return `NULL`.

IMHO it's harmless and can be ignored. It's not related to LWJGL and won't happen in non-debugging runs.

**Comment by jsdeveloper97** [comment]
Ok, I'm closing this issue.
