### ISSUE TITLE
GLFW Window Hint missing

### ISSUE THREAD

**Issue by DesertCookie** [LWJGL/lwjgl3#381]
I couldn't find an LWJGL-GLFW issues page and therefore will post this here.
The _GLFW_COCOA_FRAME_AUTOSAVE_ window hint is missing and thus cannot be set with _GLFW.setWindowHint(hint,value)_.
It would be nice to see that added.

**Comment by TheMrMilchmann** [comment]
The `COCOA_FRAME_AUTOSAVE` hint has been replaced with the string hint `COCOA_FRAME_NAME` back in December last year. (See [here](https://github.com/glfw/glfw/commit/9da2285b140ba054875906159cd63f739dbaf448) for the relevant commit to GLFW and [here](https://github.com/LWJGL/lwjgl3/commit/7906bf6a5c35e1d82b522e10b5b13aba30faed99) for relevant commit to LWJGL.)

Keep in mind that LWJGL releases may ship with pre-release versions of libraries which means that there can be (minor) breaking changes.
