### ISSUE TITLE
Missing CL_DEVICE_PREFERRED_VECTOR_WIDTH constant in OpenCL bindings

### ISSUE THREAD

**Issue by apemanzilla** [LWJGL/lwjgl3#384]
### Environment

* LWJGL version: `3.1.6` 
* LWJGL build #: `14`
* Java version: `1.8u162`
* Platform: `Linux`
* Module: `OpenCL`

### Description

Pretty straightforward, the `CL_DEVICE_PREFERRED_VECTOR_WIDTH_INT` constant is missing from `CL10`. The other types have the appropriate constants (`CHAR`, `LONG`, etc). [Relevant reference page](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clGetDeviceInfo.html). There isn't much else to say...

**Comment by Spasi** [comment]
Thanks!
