### ISSUE TITLE
JOML - 'mallocInt' - Out of stack space.

### ISSUE THREAD

**Issue by AwfulMint** [LWJGL/lwjgl3#387]
### Environment

* LWJGL version: 3.1.6
* LWJGL build #: 14
* Java version: JDK 9
* Platform: Windows
* Module: `JOML`

### Description

I'm trying to read the stanford dragon.obj model into my engine and I get this error: java.lang.OutOfMemoryError: Out of stack space.

And It's point exactly to my createBuffer method where I use mallocInt to store indices VBO. I'm using the recommended allocation method described in JOML wiki.

Here's the allocation code:
`
public IntBuffer createBuffer(int[] data) {
    IntBuffer buffer = null;

    try (MemoryStack stack = MemoryStack.stackPush()) {
        buffer = stack.mallocInt(data.length);
        buffer.put(data).flip();

        return buffer;

    }
}
`

I don't know what's causing this, the stack have a data limit? I can't find any information about this.

**Comment by Spasi** [comment]
Yes, the stack has a fixed capacity. It defaults to `64kb`, can be changed programmatically with `Configuration.STACK_SIZE` or via the command line with `-Dorg.lwjgl.system.stackSize=<value in kb>`.

Note that `MemoryStack` is supposed to be used for local/short-lived/small allocations. Model data do not qualify (it's typically large) and heap allocation (e.g. via `MemoryUtil`) is more appropriate.

**Comment by httpdigest** [comment]
@AwfulMint I wonder how you got this information from JOML's wiki. There is not a single reference in JOML's wiki to LWJGL's MemoryStack or MemoryStack.stackPush() and nowhere is there a mention that this is "the recommended allocation method" (though it might be for small matrices).

**Comment by AwfulMint** [comment]
Thanks @Spasi for the tips, and to @httpdigest to tell me this important info about small matrices, I fixed the "bug" :D

**Comment by goofyseeker311** [comment]
if you use a stored instance of MemoryStack clStack = MemoryStack.stackPush(); then you continue to push on the same stack without anything getting freed. so instead of using a stored stack, get a new stack local instance for each class method that needs to temporarily store stack variables.
