### ISSUE TITLE
ERROR using EXTDescriptorIndexing

### ISSUE THREAD

**Issue by oreonengine** [LWJGL/lwjgl3#388]
### Environment

* LWJGL version: 3.1.7-SNAPSHOT 
* LWJGL build : 20180419.175343-4
* Java version: 1.8.0_161
* Platform: Windows
* Module: vulkan

### Description

when I try to use the flag EXTDescriptorIndexing.VK_DESCRIPTOR_POOL_CREATE_UPDATE_AFTER_BIND_BIT_EXT for creating a command pool with VkDescriptorPoolCreateInfo I get the error

vkCreateDescriptorPool: value of pCreateInfo->flags contains flag bits that are not recognized members of VkDescriptorPoolCreateFlagBits

is the extension EXTDescriptorIndexing not yet fully supported (in 3.1.7-SNAPSHOT)?

**Comment by httpdigest** [comment]
There is nothing on the LWJGL3 side to "support" there.
The question is really only whether the version of your installed Vulkan validation layer supports this extension and whether your graphics card driver supports it.
Since that error message seems to be generated by the validation layer, check the version of your validation layer.

**Comment by oreonengine** [comment]
Alright, I forgot to add the extension name VkInstanceCreateInfo.
I have another issue, since I updated LunarG Vulkan SDK to 1.1.73 on my device, I get a NullPointerException by calling vkCreateDebugReportCallbackEXT. The Exception occurs at 
nvkCreateDebugReportCallbackEXT.check(__functionAddress) where __functionAddress = instance.getCapabilities().vkCreateDebugReportCallbackEXT. So the vkCreateDebugReportCallbackEXT of the instance seems to be null. However, I never got that error before, so it's strange to me

**Comment by Spasi** [comment]
`EXT_descriptor_indexing` is available in the developer beta driver version `397.40`. See [Vulkan Driver Support](https://developer.nvidia.com/vulkan-driver).
