### ISSUE TITLE
Windows resize themselves

### ISSUE THREAD

**Issue by LordMonoxide** [LWJGL/lwjgl3#393]
### Environment

* LWJGL version: `3.1.6` 
* LWJGL build #: `14`
* Java version: `1.10`
* Platform: `Windows 10 17672`
* Module: `core`

### Description

Windows are getting automatically resized slightly larger than the requested size upon creation.  I think it's fairly likely to be due to Sets (a beta feature) in the latest Insider builds of Windows 10, but may still be worth looking in to.  I'm creating a window at `1280x720`.  I have a resize event bound that simply prints out the window size.  It fires once with the proper size, then immediately again with a larger size.
```
1280, 720
1294, 727
```
Note: I am not resizing the window, this happens immediately after creation.  I just started this project a few minutes ago and don't even have a call to the resize method in my code.

**Comment by Guerra24** [comment]
This is a Sets bug, GLFW has nothing to do about it. If the resize is the issue I suggest you add Java to the exclusion list until they fix it.

**Comment by CorruptComputer** [comment]
This probably isn't an issue anymore, as Microsoft has removed the sets feature entirely because of how many issues it caused.
