### ISSUE TITLE
Setting window icon from png file using glfwSetWindowIcon

### ISSUE THREAD

**Issue by Jldevictoria** [LWJGL/lwjgl3#394]
### Environment

* LWJGL version: **3.1.6**
* LWJGL build #: **14**
* Java version: **10.0.1**
* Platform: Linux|macOS|**Windows**
* Module: **org.lwjgl.glfw**

### Description

I have seen several posts about this issue across many forums and issues, but I never saw any resolution to actually solving the implementation issues with adding a window icon.

I am just starting out with LWJGL, and one of the first things I wanted to do was set a custom icon for the game window and taskbar.

I have tried about 15 different methods to get this to at least show something upon running, but it continues to have this error every time I try to call the glfwSetWindowIcon() function:

```java
Exception in thread "main" java.lang.NullPointerException
	at org.lwjgl.system.Checks.check(Checks.java:99)
	at org.lwjgl.glfw.GLFW.nglfwSetWindowIcon(GLFW.java:1962)
	at org.lwjgl.glfw.GLFW.glfwSetWindowIcon(GLFW.java:1997)
	at project.Main.init(Main.java:56)
	at project.Main.run(Main.java:29)
	at project.Main.main(Main.java:25)
```

---

#### Function to extract a ByteBuffer from png image.

```java
import static org.lwjgl.BufferUtils.*;

public class Importer {
    public static ByteBuffer ExtractByteBufferFromImagePath(String s) {
        try {
            BufferedImage bi = ImageIO.read(new java.io.File(s));
            byte[] iconData = ((DataBufferByte) bi.getRaster().getDataBuffer()).getData();
            ByteBuffer ib = createByteBuffer(iconData.length);
            ib.order(ByteOrder.nativeOrder());
            ib.put(iconData, 0, iconData.length);
            ib.flip();
            return ib;
        }
        catch (Exception e){
            System.out.println("Couldn't open icon image..." + e.toString());
            return null;
        }
    }
}
```

#### My simple execution in Main.

```java
// ----------------------------------------------
        // Configure GLFW.
        // ----------------------------------------------
        glfwDefaultWindowHints(); // optional, the current window hints are already the default.
        glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE); // the window will stay visible after creation.
        glfwWindowHint(GLFW_RESIZABLE, GLFW_TRUE); // the window will be resizable.
        ByteBuffer icon = Importer.ExtractByteBufferFromImagePath("logo_icon_32.png");
        GLFWImage.Buffer gb = new GLFWImage.Buffer(icon);
        glfwSetWindowIcon(window, gb);
```

#### Verified that my Importer is at least getting raw png data into ByteBuffer.

```java
        ByteBuffer icon = 
        Importer.ExtractByteBufferFromImagePath("logo_icon_32.png");
        String builder = "";
        for (int i = 0; i < 32*32*4; i++) {
            builder += icon.get(i) + " ";
            if ((i + 1) % 128 == 0) {
                builder += "\n";
            }
        }
        System.out.println(builder);
```

Output:

>0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 58 0 0 0 -121 0 0 0 -36 0 0 0 -1 0 22 30 -1 0 15 21 -54 0 0 0 -114 0 0 0 76 0 0 0 15 0 0 0 0 0 0 0 0 0 0 0 25 0 0 0 85 0 0 0 -111 0 0 0 -45 0 0 0 -1 0 20 28 -1 0 15 20 -50 0 0 0 125 0 0 0 47 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 25 0 0 0 107 0 0 0 -71 0 0 0 -1 0 1 2 -1 0 36 49 -1 0 83 114 -1 0 -126 -78 -1 0 -115 -63 -1 0 -114 -62 -1 0 -124 -75 -1 0 98 -122 -1 0 62 85 -1 0 27 37 -14 0 0 0 -7 0 0 0 -1 0 31 43 -1 0 67 91 -1 0 103 -116 -1 0 -120 -70 -1 0 -115 -63 -1 0 -114 -61 -1 0 125 -84 -1 0 76 104 -1 0 31 43 -2 0 0 0 -79 0 0 0 95 0 0 0 16 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 18 33 33 33 -1 0 0 0 -1 0 0 0 -1 0 0 0 -1 0 33 46 -1 0 71 97 -1 0 103 -115 -1 0 -118 -68 -1 0 -115 -63 -1 0 -119 -68 -1 0 -120 -70 -1 0 -120 -70 -1 0 -119 -69 -1 0 -116 -64 -1 0 -116 -66 -1 0 -115 -63 -1 0 -116 -65 -1 0 -120 -69 -1 0 -120 -70 -1 0 -120 -70 -1 0 -118 -68 -1 0 -114 -62 -1 0 -122 -73 -1 0 99 -121 -1 0 68 93 -1 0 27 37 -1 0 0 0 -1 0 0 0 -1 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 20 0 0 0 -1 0 0 0 -1 0 75 103 -1 0 30 41 -1 0 0 0 -1 0 0 0 -1 0 0 0 -1 0 0 0 -1 0 22 30 -1 0 57 78 -1 0 94 -127 -1 0 -127 -80 -1 0 -113 -60 -1 0 -118 -67 -1 0 -120 -70 -1 0 -120 -70 -1 0 -117 -66 -1 0 -113 -60 -1 0 125 -85 -1 0 90 122 -1 0 52 72 -1 0 17 23 -1 0 0 0 -1 0 0 0 -1 0 0 0 -1 0 0 0 -1 0 34 48 -1 0 68 93 -1 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 20 0 0 0 -1 0 0 0 -1 0 -111 -57 -1 0 -116 -64 -1 0 -115 -63 -1 0 107 -110 -1 0 69 94 -1 0 30 42 -1 0 0 0 -1 0 0 0 -1 0 0 0 -1 0 0 0 -1 0 11 15 -1 0 46 63 -1 0 85 116 -1 0 80 109 -1 0 42 58 -1 0 6 9 -1 0 0 0 -1 0 0 0 -1 0 0 0 -1 0 0 0 -1 0 35 48 -1 0 74 100 -1 0 111 -104 -1 0 -113 -61 -1 0 -116 -65 -1 0 126 -84 -1 0 0 0 0 0 0 0 0 0 0 0 
..
x16
..
0 0 0 0 20 0 0 0 -1 0 0 0 -1 0 -104 -48 -1 0 -118 -68 -1 0 -120 -70 -1 0 -120 -70 -1 0 -120 -70 -1 0 68 93 -1 0 0 0 -1 0 0 0 -1 0 -127 -80 -1 0 -115 -64 -1 0 26 35 -96 0 0 0 0 0 0 0 0 0 0 0 -60 0 0 0 -1 0 45 62 -1 0 -117 -66 -1 0 110 -106 -1 0 0 0 -1 0 0 0 -1 0 87 119 -1 0 -120 -70 -1 0 -120 -70 -1 0 -120 -70 -1 0 -118 -67 -1 0 -124 -75 -1 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 19 0 0 0 -1 0 0 0 -1 0 13 18 -1 0 51 71 -1 0 88 120 -1 0 124 -86 -1 0 -112 -59 -1 0 70 95 -1 0 0 0 -1 0 0 0 -1 0 -120 -71 -1 0 122 -89 -1 0 16 22 -96 0 0 0 0 0 0 0 0 0 0 0 -60 0 0 0 -1 0 31 42 -1 0 124 -86 -1 0 116 -98 -1 0 0 0 -1 0 0 0 -1 0 90 123 -1 0 -112 -59 -1 0 120 -92 -1 0 83 114 -1 0 47 64 -1 0 10 13 -1 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 15 0 0 0 96 0 0 0 -76 0 0 0 -3 0 0 0 -1 0 0 0 -1 0 6 8 -1 0 19 27 -1 0 0 0 -1 0 0 0 -1 0 1 1 -1 0 0 0 -1 0 0 0 -102 0 0 0 0 0 0 0 0 0 0 0 -64 0 0 0 -1 0 0 0 -1 0 0 0 -1 0 4 6 -1 0 0 0 -1 0 0 0 -1 0 22 29 -1 0 3 4 -1 0 0 0 -9 0 0 0 -88 0 0 0 87 0 0 0 6 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 44 0 0 0 127 0 0 0 -50 0 0 0 -1 0 0 0 -16 0 0 0 -89 0 0 0 95 0 0 0 21 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 31 0 0 0 104 0 0 0 -81 0 0 0 -8 0 0 0 -1 0 0 0 -60 0 0 0 114 0 0 0 36 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### Tried every single way I could imagine to create a GLFWImage.Buffer

```java
GLFWImage.Buffer iconGB = new GLFWImage.Buffer;
```

```java
GLFWImage.Buffer iconGB = GLFWImage.malloc(1);
```

```java
GLFWImage iconGI = new GLFWImage(icon);
iconGB.put(0, iconGI);
```

 (icon is ByteBuffer, iconGB is as shown previously)

```java
iconGB.put(iconGI);
```

And many many many more iterations of trying things like this, trying to get the icon to show up to no avail.

See these forums where I have tried to go for help:

* https://stackoverflow.com/questions/4791654/taskbar-icon-with-lwjgl
* https://stackoverflow.com/questions/42322382/glfw-window-icon
* https://stackoverflow.com/questions/25466586/changing-lwjgl-icons-taskbar-and-program
* http://forum.lwjgl.org/index.php?topic=6684.msg35331#msg35331
* http://forum.lwjgl.org/index.php?topic=5602.msg32977#msg32977
* http://forum.lwjgl.org/index.php?topic=6218.msg33237#msg33237

+ around 10 more

**Comment by kenzierocks** [comment]
```java
GLFWImage.Buffer gb = new GLFWImage.Buffer(icon);
GLFWImage iconGI = new GLFWImage(icon);
```
This treats your image data as the specified struct, which is not what you want. You want to store your data in the structs, like so:
```java
GLFWImage.Buffer gb = GLFWImage.create(1);
GLFWImage iconGI = GLFWImage.create().set(<width>, <height>, icon);
gb.put(0, iconGI);
```
(I used `#create` because the memory will be automatically freed for you, if you know how to manage memory then you can use `#malloc`.)
You'll need to pass the `width` and `height` from the `BufferedImage` as well.

As an aside, your buffer copy code can be simplified, as there's no need to specify native order (it's already done for you):
```java
            ByteBuffer ib = createByteBuffer(iconData.length);
            ib.put(iconData);
            ib.flip();
```

**Comment by Jldevictoria** [comment]
@kenzierocks thanks for the quick response.

I tried what you recommended, as well as using malloc with the appropriate size.
However, it looks like the GLFWImage.Buffer object is going out of scope and being deleted as I enter the glfwSetWindowIcon(long window, Buffer images) function.

This is what I see as I step through the debugger:

![image](https://user-images.githubusercontent.com/6485853/40572486-a084bf46-6062-11e8-88cb-de765c73f81f.png)

![image](https://user-images.githubusercontent.com/6485853/40572491-b364e62c-6062-11e8-97c2-c04a698fa17f.png)

perhaps GLFW.java is losing access to this variable somehow?

maybe Java is cleaning it up too early?

**Comment by kenzierocks** [comment]
Why do you think your buffer is deleted? It looks just fine.
Your window, however, is a null pointer. You have an error in your window creation, so you won't be able to call `glfwSetWindowIcon`.

**Comment by Jldevictoria** [comment]
@kenzierocks doh!  Yes. I can't believe I have been spending so much time on this and all I needed to do was move the glfeSetWindowIcon below the window creation.  Sorry to submit this silly issue!

You can mark this resolved or closed, I'm back on track!

![image](https://user-images.githubusercontent.com/6485853/40572598-00eb17c0-6065-11e8-8140-a831aeeaaac2.png)
