### ISSUE TITLE
Add SBT as new mode for package customization

### ISSUE THREAD

**Issue by MarkusA380** [LWJGL/lwjgl3#395]
Currently, LWJGL.org gives you four modes for customization: ZIP Bundle, Maven, Ivy and Gradle.
I would like to propose adding a fifth mode: SBT.

SBT is the most common tool used for compiling Scala code to JVM bytecode, and because of that supports any and all JAR dependencies.

I got a simple LWJGL program running using that method, and I would love to see this library available for everyone using Scala.

To use LWJGL with SBT the `build.sbt` needs to include the following snippet:

```scala
libraryDependencies ++= {
  val version = "3.1.6"

  Seq(
    "lwjgl",
    "lwjgl-glfw",
    "lwjgl-opengl"
    //Add other modules here
  ).flatMap {
    module => {
      Seq(
        "org.lwjgl" % module % version,
        "org.lwjgl" % module % version classifier "natives-windows" //Change to linux/mac
      )
    }
  }
}
```

**Comment by Spasi** [comment]
Sure, but could you reopen this issue in the [lwjgl3-www](https://github.com/LWJGL/lwjgl3-www) repository please?

> To use LWJGL with SBT the build.sbt needs to include the following snippet:

Thanks. If you'd like to submit a PR, the script generation source is in [BuildScript.jsx](https://github.com/LWJGL/lwjgl3-www/blob/master/client/routes/customize/BuildConfigurator/components/BuildScript.jsx). Note that a `flatMap` cannot be used like that, e.g. not all modules have natives and whether a module has natives or not may depend on the LWJGL version. The details are reasonably abstracted though and you only have to worry about generating the proper syntax/formatting. For reference, see the functions `generateMaven`, `generateGradle` and `generateIvy`.
