### ISSUE TITLE
Some CL10.clSetKernelArg methods set an incorrect arg_size value

### ISSUE THREAD

**Issue by Nerogar** [LWJGL/lwjgl3#396]
### Environment

* LWJGL version: `3.1.6` 
* LWJGL build #: `14`
* Java version: `1.8.0_162`
* Platform: `Windows`
* Module: `opencl`

### Description

Some of the CL10.clSetKernelArg methods set an incorrect arg_size value.
I have tested this for the following methods, but others might have the same problem:

| method           | expected     | actual       |
| ---------------- | ------------ | ------------ |
| clSetKernelArg3i | (1 << 2) * 4 | (1 << 2) * 3 |
| clSetKernelArg3f | (1 << 2) * 4 | (1 << 2) * 3 |
| clSetKernelArg3l | (1 << 3) * 4 | (1 << 3) * 3 |

https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/dataTypes.html
specifies that 3-component vector types are aligned to 4*sizeof(component)

**Comment by Spasi** [comment]
I think I'll just remove the `clSetKernelArg3x` overloads. Any objections?

**Comment by Nerogar** [comment]
>I think I'll just remove the clSetKernelArg3x overloads. Any objections?

Using the ```clSetKernelArg4x``` overloads with ```0``` as the last parameter works fine.
Removing methods could potentially be a breaking change though.
Apart from that I don't think this would be a problem.
Maybe add a line to the javadoc telling the user to use the ```clSetKernelArg4x``` overloads for 3 component vectors.

**Comment by Spasi** [comment]
My thinking is that removing them is not a breaking change in practice, since there's no kernel argument type for which they could have worked without an error.
