### ISSUE TITLE
OpenVR problems

### ISSUE THREAD

**Issue by Zamundaaa** [LWJGL/lwjgl3#403]
### Environment

* LWJGL version: 3.2.0
* LWJGL build #: 12
* Java version: 8
* Platform: Linux, Windows
* Module: OpenVR

### Description

When using LWJGL 3.1.5, VRSystem_GetDeviceToAbsoluteTrackingPose would still kind of work (in that it only gave me the HMDs position, and I then have to use VRSystem_GetControllerStateWithPose to get the controllers pose and state), but in LWJGL 3.2.0 it crashes. The work-around is to use VRCompositor_WaitGetPoses, but that's a bit less convenient. Also it seems like the same thing happened on Windows even with LWJGL 3.1.5. The error log from Linux, LWJGL 3.2.0 is here:
[hs_err_pid26152.log](https://github.com/LWJGL/lwjgl3/files/2259563/hs_err_pid26152.log)
The error log from Windows, LWJGL 3.1.5 is here. I'll try again with LWJGL 3.2.0 when I have time.
[hs_err_pid1448.log](https://github.com/LWJGL/lwjgl3/files/2259579/hs_err_pid1448.log)

VRSystem_CaptureInputFocus seems to be gone now ... wonder why? It's still there in OpenVR

Controller input doesn't work. Events for them do, but I can't get, what button was pressed or where I touched etc. This is not a new thing since my upgrade to 3.2.0, but it never worked. I've created an issue for OpenVR, but as other programs work just fine it seems like this could be an issue with the transfer from C++ to Java. The issue is here: https://github.com/ValveSoftware/openvr/issues/835
I'd probably need some help debugging this, as I have no clue to how I'd do it

**Comment by Spasi** [comment]
Hey @Zamundaaa,

I do not have access to a HMD yet, so I've personally never tested the OVR and OpenVR bindings. I depend on users reporting issues with enough information to fix them. I'm afraid the crash logs you shared do not indicate anything obvious. Maybe posting a minimal code sample that reproduces the issue would help.

I don't know why `GetControllerStateWithPose` crashes, but in `1.0.16` is has been deprecated in favor of the new `IVRInput` system (introduced in `1.0.15`).

> VRSystem_CaptureInputFocus seems to be gone now ... wonder why? It's still there in OpenVR

It's not, it was completely removed in `1.0.12`. Note that the LWJGL bindings follow the latest OpenVR C API header exactly.

> I've created an issue for OpenVR, but as other programs work just fine it seems like this could be an issue with the transfer from C++ to Java.

A good method to identify if that's the case, is to port an existing native demo to Java/LWJGL. You can then easily validate if there are issues with the bindings. We could also use a decent OpenVR sample in the repository, if you'd like to contribute.

**Comment by Zamundaaa** [comment]
I think I may have found out why the Controller State was always 0... https://github.com/ValveSoftware/SteamVR-for-Linux/issues/35#issuecomment-411257729.
Yet I've still not succeeded using the IVRInput system as SteamVR just shows a dark blue background at some point when trying to create bindings. I guess that's an error on their side but didn't get a response yet on it

**Comment by Zamundaaa** [comment]
So all problems I had with OpenVR that may be related to LWJGL are gone or just resolved to be Valve's fault and have been fixed, so I'll close this now
