### ISSUE TITLE
Opus binding

### ISSUE THREAD

**Issue by Alex-----** [LWJGL/lwjgl3#405]
Hi, I'd like to request an [Opus](http://opus-codec.org/) binding.

Describe why you need it and how you're going to use it. 
I'm going to use it to encode/decode speech to allow players to talk to each other. It could also be used for a game's sound effects, but stbvorbis is working fine for me right now so I don't really need it for that.

Include a link to the project's website and/or source repository. 
http://opus-codec.org/
https://github.com/xiph/opus

Do you need it on all platforms?
yes.

Are you going to use the entire project or only a subset of it?
Looking at the different moduls here: http://opus-codec.org/docs/opus_api-1.2/modules.html
I don't think I will need the multistream part of it and probably not the custom part or the repacketizer.

If you tell me the best way to do it (or other binding to copy) I could try and make the binding myself.

**Comment by Ealrann** [comment]
By chance, is there any demo code somewhere about using Opus with LWJGL?

**Comment by kohr8664** [comment]
> By chance, is there any demo code somewhere about using Opus with LWJGL?

Also searching for it...

**Comment by stodge** [comment]
> > By chance, is there any demo code somewhere about using Opus with LWJGL?
> 
> Also searching for it...

Did you find any?

**Comment by Ealrann** [comment]
Nope sorry
I used ogg finally
