### ISSUE TITLE
CLDemo still requires InfoUtil

### ISSUE THREAD

**Issue by piegamesde** [LWJGL/lwjgl3#406]
### Environment

* LWJGL version: `3.2.0` 
* LWJGL build #: `?`
* Java version: `openjdk 10.0.2 2018-07-17`
* Platform: `Arch Linux`
* Module: `opencl`

### Description

According to #263, the class `InfoUtil` has been removed in LWJGL 3. However, the demo class `CLDemo` still references it (a lot). Apparently, `InfoUtil` still exists in a test package for some reason (https://github.com/LWJGL/lwjgl3/blob/master/modules/lwjgl/opencl/src/test/java/org/lwjgl/opencl/InfoUtil.java), but I expect from a demo class to be able to copy-paste it into my project for testing without problems. However this won't work since it will be missing that specific class.

**Comment by intrigus** [comment]
So what do you expect the maintainer to do?

Why don't you simply copy the InfoUtil class to your project?

**Comment by intrigus** [comment]
Sorry, I thought that you meant the included tests when you said "demos".
