### ISSUE TITLE
scrollCallBack full screen issue.

### ISSUE THREAD

**Issue by maxbryarsmansell** [LWJGL/lwjgl3#407]
### Environment

* LWJGL version: `3.1.7` 
* LWJGL build #: `8`
* Java version: `Version 1.8, Update 151`
* Platform: `Windows`

### Description

I have set up a scroll callback as you can see in this image.

![image](https://user-images.githubusercontent.com/18558188/44620257-deb19a00-a888-11e8-92c4-58a76af99fbd.png)
This works fine when my program is not in full screen. However, in full screen, the callback is only triggered when the mouse is not positioned around the centre of the screen.

![image](https://user-images.githubusercontent.com/18558188/44620284-5da6d280-a889-11e8-9b87-ea491e26120a.png)
The width and height passed to the "glfwCreateWindow" method is 800x600, and the resolution of my monitor is 1920x1080. 

I am wondering whether I have done something wrong, or whether this is a bug.

**Comment by Spasi** [comment]
Cannot reproduce on Windows 10, latest nvidia drivers. Please post more details and an [MCVE](https://stackoverflow.com/help/mcve) if possible.

**Comment by maxbryarsmansell** [comment]
I have filled in the area that is effected with the red colour.
![image](https://user-images.githubusercontent.com/18558188/44622064-1f211000-a8a9-11e8-8e0f-62af26b174aa.png)
Unfortunately I don't have time to put together an MCVE at the moment, sorry. But I can give you the link to the repository containing the project that I am having this problem with - see if it happens for you. 
[Repository](https://github.com/maxbryarsmansell/Java-OpenGL-Engine)
