### ISSUE TITLE
Add V-EZ bindings

### ISSUE THREAD

**Issue by DrinkyBird** [LWJGL/lwjgl3#410]
[V-EZ](https://github.com/GPUOpen-LibrariesAndSDKs/V-EZ) is a recently open-sourced cross platform Vulkan wrapper by AMD GPUOpen that's meant to bridge the gap between traditional APIs and Vulkan by providing all the power of Vulkan with an easier to use API.

It would be great to have this in LWJGL as it would allow easier and faster development of Vulkan applications.

Only possible issue is that it doesn't officially support macOS, [due to MoltenVK limitaitons](https://github.com/GPUOpen-LibrariesAndSDKs/V-EZ/issues/4#issuecomment-385784204).

**Comment by httpdigest** [comment]
@Spasi V-EZ is pretty much discontinued. Do we still want bindings for it?

**Comment by Spasi** [comment]
I think we've eased some of the difficulties with the extensive javadoc that comes with the Vulkan bindings and [VMA](https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator) for memory management. Closing this for now, may reconsider if V-EZ (or something similar) becomes active/popular in the future.
