### ISSUE TITLE
Missing Vulkan natives in Maven Central for 3.2.0

### ISSUE THREAD

**Issue by Bawbby** [LWJGL/lwjgl3#412]
While I was using gradle to pull down dependencies it said that it could not find the `lwjgl-vulkan-natives-windows.jar` at this [link](https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-vulkan/3.2.0/lwjgl-vulkan-3.2.0-natives-windows.jar) 
but further checking [here](https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-vulkan/3.2.0/) shows that there are no vulkan natives for both windows or linux.

Sorry if this is the wrong place for asking this question.

**Comment by Spasi** [comment]
There is no `lwjgl-vulkan-natives` for Linux/Windows. On macOS it contains the [MoltenVK](https://github.com/KhronosGroup/MoltenVK) binary, which emulates Vulkan over Metal.

It is recommended to use the official [build customizer](https://www.lwjgl.org/customize) to generate Maven dependency scripts, etc. It knows which platforms are supported by each module and whether natives are necessary, saves a lot of time.

**Comment by Bawbby** [comment]
Im just wondering for when building an LWJGL game for mac, sorry for the silly issue.
