### ISSUE TITLE
Linux x64 OpenVR - throws NullPointerException

### ISSUE THREAD

**Issue by DavidYKay** [LWJGL/lwjgl3#415]
### Environment

* LWJGL version: `3.2.0` 
* LWJGL build #: `12`
* Java version: `1.8.0_151`
* Platform: `Linux 4.4.0-134-generic x86_64`
* Module: `openvr`

#### Issue:

Calls to either:

* VRSystem_GetStringTrackedDeviceProperty
* VRSystem_GetRecommendedRenderTargetSize

both throw java.lang.NullPointerException.

I suspect that all calls to OpenVR may also fail, as I've closely scrutinized my parameters and can't find fault.

FYI: I've gotten the [C++ hello world](https://gist.github.com/DavidYKay/b01fc8cf1bc682671e0ad6000b8e7c5a) working by running the following command:

`~/.steam/steam/ubuntu12_32/steam-runtime/run.sh ./cpphellovr`

So I know that OpenVR, my headset, and my runtime are working.

The issue seems to be somewhere in the LWJGL-OpenVR chain.

Steps to reproduce:

* [Download gist](https://gist.github.com/DavidYKay/639760f4f3be8ca77658a076fdf55916) (Kotlin)
* Build JAR (I use IntelliJ's "Build Artifacts")
* `~/.steam/steam/ubuntu12_32/steam-runtime/run.sh java -jar out/artifacts/kotlinviz_jar/kotlinviz.jar`

Thank you very much for the library!

**Comment by Spasi** [comment]
Hey @DavidYKay,

I cannot test your code without a HMD. Could you please post the NPE stacktrace? Also, try printing the value of `OpenVR.VRSystem.GetStringTrackedDeviceProperty` & `OpenVR.VRSystem.GetRecommendedRenderTargetSize`, they should not be `0`. If they are, it means that LWJGL failed to retrieve function pointers from your OpenVR runtime. Which version do you have installed? Another thing you could try is running the program with `-Dorg.lwjgl.util.Debug=true -Dorg.lwjgl.util.DebugLoader=true` and seeing if there's any useful output.

One thing that's definitely wrong with your code is this line: `return String(stringBuffer.array())`. LWJGL buffers are never backed by a Java array on the heap, they are always direct. Try returning `MemoryUtil.memUTF8(stringBuffer, unRequiredBufferLen - 1)` instead.

**Comment by DavidYKay** [comment]
First, thank you SO much for the prompt reply. I am hugely in your debt. :)

Second, it looks like it was user error. I followed your instructions and found that VRSystem wasn't being initialized properly. Because I was missing a call to it. I am so sorry for sending you on a goose chase!

Here's a working Hello World for any future OpenVR devs: https://gist.github.com/DavidYKay/639760f4f3be8ca77658a076fdf55916

Thanks again!
