### ISSUE TITLE
NPE when calling VRCompositor.WaitGetPoses without "gamePoseArray"

### ISSUE THREAD

**Issue by neph1** [LWJGL/lwjgl3#418]
### Environment

* LWJGL version: `3.2.0` 
* LWJGL build #: `X`
* Java version: `java.version`
* Platform: `Windows`
* Module: `openvr`

### Description
Calling VRCompositor.waitGetPoses without a gamePoseArray yields an NPE due to accessing the object before passing it on to the native code:
`pGamePoseArray.address()`

It looks like the same would occur with getLastPoses.

According to documentation:

> Scene applications should call this function to get poses to render with (and **optionally poses predicted an additional frame out to use for gameplay**).

A work around would be to call the native code directly.

**Comment by Spasi** [comment]
Thanks!
