### ISSUE TITLE
Providing jmod format download

### ISSUE THREAD

**Issue by chengenzhao** [LWJGL/lwjgl3#419]
Hi:

Recently Java release [jmod format,](http://openjdk.java.net/jeps/261) so is it possible to provide jmod format release version along with jar format?
If so, we could use jlink to integrate lwjgl3.jmod into customized jre
like JavaFX which provides [jmod format download](https://gluonhq.com/products/javafx/)

**Comment by Spasi** [comment]
Hey @chengenzhao,

You don't need dependencies in `jmod` format to use `jlink`, normal jars work just fine. The only prerequisite is that all dependencies must be explicit modules (i.e. include `module-info.class`, simply adding an `Automatic-Module-Name` in the manifest is not enough).

**Comment by chengenzhao** [comment]
> Hey @chengenzhao,
> 
> You don't need dependencies in `jmod` format to use `jlink`, normal jars work just fine. The only prerequisite is that all dependencies must be explicit modules (i.e. include `module-info.class`, simply adding an `Automatic-Module-Name` in the manifest is not enough).

Thanks for reply, so basically we need to add module-info.class manually, and then use jlink to link this modified jar to generate jre right?
It looks feasible but if we could add module-info.class in the native jar, would it be more convenient for users?

**Comment by kenzierocks** [comment]
I believe it's already in there, check the `META-INF/versions/9` folder.

**Comment by chengenzhao** [comment]
> I believe it's already in there, check the `META-INF/versions/9` folder.

found it, cool, thanks

**Comment by Spasi** [comment]
Since LWJGL `3.1.4` artifacts are jlink-able without any changes. `module-info.class` was moved into `META-INF/versions/9` in `3.1.6` for compatibility with older software that tried to parse it and failed.

**Comment by chengenzhao** [comment]
> Since LWJGL `3.1.4` artifacts are jlink-able without any changes. `module-info.class` was moved into `META-INF/versions/9` in `3.1.6` for compatibility with older software that tried to parse it and failed.

thanks a lot, test it successfully
