### ISSUE TITLE
GL45.glEnableVertexArrayAttrib requires a bound VAO despite being DSA

### ISSUE THREAD

**Issue by tristandaniel** [LWJGL/lwjgl3#42]
[`GL45.glEnableVertexArrayAttrib(int vaobj, int index)`](https://github.com/LWJGL/lwjgl3-generated/blob/master/java/org/lwjgl/opengl/GL45.java#L3394) should be the direct state access version of [`GL20.glEnableVertexAttribArray(int index)`](https://github.com/LWJGL/lwjgl3-generated/blob/master/java/org/lwjgl/opengl/GL20.java#L3000) but returns `GL_INVALID_OPERATION` if there isn't a Vertex Array Object bound.
Also, the link to the OpenGL SDK Reference link is [broken](http://www.opengl.org/sdk/docs/man/html/glEnableVertexArrayAttrib.xhtml) : `glEnableVertexArrayAttrib` and `glEnableVertexAttribArray` share the same [page](https://www.opengl.org/sdk/docs/man/html/glEnableVertexAttribArray.xhtml).

**Comment by Spasi** [comment]
The docs say:

> `GL_INVALID_OPERATION` is generated by `glEnableVertexArrayAttrib` and
> `glDisableVertexArrayAttrib` if `vaobj` is not the name of an existing vertex array object.

If what you're saying is true, then it must be a driver bug. LWJGL does nothing special when you call that method.

There are several problems with the SDK reference links, including the one you described. It's a known issue that will be address at a later time.

**Comment by Toun2267** [comment]
Ok then, I don't really know how LWJGL implements OpenGL methods. I will make some more tests and see if I can get it working with another driver version.

**Comment by Toun2267** [comment]
Well, I finally figured out how to get it working: in fact, you need to bind a VAO or VBO at least one time before using it with a DSA function. So after calling `glGenVertexArrays()` or `glGenBuffers()`, I bind the object and unbind it once. I don't know if this behaviour is intended, but it is for sure not in the documentation (or I might be blind).

**Comment by Spasi** [comment]
See paragraph 2.6.1.1 of the OpenGL specification:

> Generated names **do not initially correspond to an instance of an object**. Objects
> with generated names are created by **binding a generated name to the context**.
> For example, a buffer object is created by calling the command BindBuffer with
> a name returned by GenBuffers, which allocates resources for the buffer object
> and its state, and associate the name with that object.

**Comment by Toun2267** [comment]
Well, thank you. Shame on me .. My mistake will maybe help someone else. Since this property is invisible when using non DSA functions, it's kind of easy to forget. And sorry for turning this issue into a forum thread.

**Comment by httpdigest** [comment]
There is the GL45.glCreateVertexArrays function creating the name of a VAO without the need to bind it in order to make it a VAO object.
Correspondingly, there are all those other glCreate* functions, such as GL45.glCreateBuffers (buffer creation without needing to bind it) as well as GL45.glCreateTextures for texture objects, GL45.glCreateFramebuffers for FBOs and GL45.glCreateRenderbuffers for render buffers.
