### ISSUE TITLE
Trojan:Java/Tisifi.C in 3.2.0 release

### ISSUE THREAD

**Issue by leduyquang753** [LWJGL/lwjgl3#420]
I am using CocCoc (a Chrome-based browser) running on Windows 10 ver 1803 (build 17134.165) to download LWJGL version 3.2.0 - the latest stable one. Right after the download completes, the browser reported: "Failed - Contains virus", and Windows Defender notified me about a threat. So I opened Defender up to see what was going wrong. It said that the file "lwjgl\lwjgl-javadoc.jar" in "lwjgl-3.2.0.zip" contained **Trojan:Java/Tisifi.C**:

![image](https://user-images.githubusercontent.com/26449060/46676754-5a825e80-cc0b-11e8-8f79-5bf5188938d5.png)

### Trojan:Java/Tisifi.C
- Severity: Severe.
- Status: Isolated.
- Date: 9/10/2018 (9 Oct 2018).
- Recommended action: Remove threat now.
- Type: Trojan.
- Detailed information: This program is dangerous and executes commands from an attacker.
- Affected items:
```
containerfile: C:\Users\Asus\Downloads\lwjgl-3.2.0.zip

file: C:\Users\Asus\Downloads\lwjgl-3.2.0.zip->lwjgl/lwjgl-javadoc.jar

webfile: C:\Users\Asus\Downloads\lwjgl-3.2.0.zip|https://github-production-release-asset-2e65be.s3.amazonaws.com/7xxxx44/efbxx0e2-9430-11e8-9906-cdxxxxx8962e?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAxxxxxxxxxxxVEH53A%2F20181009%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20181009T124031Z&X-Amz-Expires=300&X-Amz-Signature=d4c0b72d83xxxxxx27f66bc670869f48d2c85dca93fe615550c0f8139858574f&X-Amz-SignedHeaders=host&actor_id=264490xx&response-content-disposition=attachment%3B%20filename%3Dlwjgl-3.2.0.zip&response-content-type=application%2Foctet-stream|pid:460,ProcessStart:131835604370xxxxxx
```

Please review this as it may affect many people using this library or having a game that uses this.

Thanks.

**Comment by kenzierocks** [comment]
Looks like a false positive -- the Javadoc jar should contain no compiled classes, and therefore no Java code.

**Comment by scholza** [comment]
I wonder why you have a download from aws - if I go to releases I get a download from "github.com"

**Comment by Spasi** [comment]
It's a false positive. VirusTotal reports: [lwjgl-3.2.0.zip](https://www.virustotal.com/#/url/0b53e8f8f9907d5296e7ec6b51b54fc018ac5aa719838de8da33bcd14c4c247e/detection) & [lwjgl-javadoc.jar](https://www.virustotal.com/#/file/f8e1829c0a90aa6d8ff3907d290d9138dc5758f69b453c953f878ef0e8c84544/detection).
