### ISSUE TITLE
Become a contributor

### ISSUE THREAD

**Issue by nikialeksey** [LWJGL/lwjgl3#422]
### Environment

* LWJGL github master branch

### Description
![image](https://user-images.githubusercontent.com/5731084/47641115-cc5d2080-db97-11e8-9fcd-37ee6632677e.png)

May be, "become a contributor"?

**Comment by Spasi** [comment]
That is an image generated by Open Collective. You may want to open an issue with [them](https://github.com/opencollective) (probably in the `opencollective-images` repository).
