### ISSUE TITLE
[Bullet] Failing to read translation and orientation from a collision mesh

### ISSUE THREAD

**Issue by dustContributor** [LWJGL/lwjgl3#423]
### Environment

* LWJGL version: `3.2.1` 
* LWJGL build #: `7`
* Java version: `10`
* Platform: `Linux`
* Module: `Bullet`

### Description

Hi! I'm trying to read back Bullet's position and orientation for a given collision shape so I can update my rendering transforms after a simulation step, but I'm getting a VM crash after submitting the state command. Here is a repro:

```java
public static final void main ( final String[] args ) {
	// World transform that we want to refresh with Bullet's 
	var world = new Mat4f();
	var phy = b3ConnectPhysicsDirect();
	if ( phy == MemoryUtil.NULL ) {
		throw new IllegalStateException();
	}
	{
		long cmd = b3InitPhysicsParamCommand( phy );
		b3PhysicsParamSetGravity( cmd, 0, 0, -9.8 );
		b3PhysicsParamSetTimeStep( cmd, 1.0 / 60.0 );
		var status = b3SubmitClientCommandAndWaitStatus( phy, cmd );
		var type = b3GetStatusType( status );
		if ( type != CMD_CLIENT_COMMAND_COMPLETED ) {
			throw new IllegalStateException();
		}
	}
	int uid;
	{
		var cmd = b3CreateCollisionShapeCommandInit( phy );
		var index = b3CreateCollisionShapeAddCapsule( cmd, 1, 1 );
		try ( var mem = MemoryStack.stackPush() ) {
			var pos = new Vector3f( 1, 0, 0 );
			world.rotateLocalX( 45 );
			world.translate( pos );
			var quat = new Quaternionf().setFromNormalized( world );
			b3CreateCollisionShapeSetChildTransform( cmd, index,
					mem.mallocDouble( 3 )
							.put( 0, pos.x )
							.put( 1, pos.y )
							.put( 2, pos.z )
							.rewind(),
					mem.mallocDouble( 4 )
							.put( 0, quat.x )
							.put( 1, quat.y )
							.put( 2, quat.z )
							.put( 3, quat.w )
							.rewind() );
		}
		var handle = b3SubmitClientCommandAndWaitStatus( phy, cmd );
		var type = b3GetStatusType( handle );
		if ( type != CMD_CREATE_COLLISION_SHAPE_COMPLETED ) {
			throw new IllegalStateException();
		}
		uid = b3GetStatusCollisionShapeUniqueId( handle );
	}
	{
		var cmd = b3RequestActualStateCommandInit( phy, uid );
		var status = b3SubmitClientCommandAndWaitStatus( phy, cmd );
		var type = b3GetStatusType( status );
		// Here is where it fails.
		if ( type != CMD_ACTUAL_STATE_UPDATE_COMPLETED ) {
			throw new IllegalStateException();
		}
		try ( var mem = MemoryStack.stackPush() ) {
			var ptr = mem.mallocPointer( 1 );
			b3GetStatusActualState( status, null, null, null, null, ptr, null, null );
			// Size is 3 doubles for position + 4 for orientation.
			var data = ptr.getDoubleBuffer( 0, 7 );
			// If we ignore the status, these make the VM crash because ptr isn't valid.
			var pos = new Vec3f( 
					(float) data.get(), 
					(float) data.get(), 
					(float) data.get() );
			var or = new Quaternionf( 
					(float) data.get(), 
					(float) data.get(), 
					(float) data.get(), 
					(float) data.get() );
			// Read back Bullet's data into our world transform object.
			world.set( or ).setTranslation( pos );
		}
	}
	System.out.println( "Finished!" );
	System.out.println( world );
}
```

As I mention in the comments, b3GetStatusType returns status type 22 which is a failed status. If I let it continue it makes the VM crash because the later b3GetStatusActualState doesn't modifies the pointer argument at all so it's left pointing to a bogus address.

Any ideas? Should I ask in Bullet's repository?

**Comment by Spasi** [comment]
> As I mention in the comments, b3GetStatusType returns status type 22 which is a failed status.

I can reproduce this, but I don't see anything wrong with the bindings.

> If I let it continue it makes the VM crash because

If you change `var ptr = mem.mallocPointer( 1 );` to `callocPointer`, you'll get a `NPE` in the `ptr.getDoubleBuffer` call, instead of a crash.

> Any ideas? Should I ask in Bullet's repository?

Nope, sorry, I don't have any experience with Bullet. Before asking upstream, you could try reproducing the issue in C.

**Comment by dustContributor** [comment]
> I can reproduce this, but I don't see anything wrong with the bindings.

Well that's something at least :smile: 

> If you change var ptr = mem.mallocPointer( 1 ); to callocPointer, you'll get a NPE in the ptr.getDoubleBuffer call, instead of a crash.

Right! Good idea.

> Nope, sorry, I don't have any experience with Bullet. Before asking upstream, you could try reproducing the issue in C.

And I have no experience with C :smile: I can read C code just fine, but setting up a build environment is a different thing. I'll submit the issue to them, hopefully the Java code will be enough, otherwise I'll research how to do it in C and try again. Thanks!

**Comment by dustContributor** [comment]
I'm an idiot, I forgot that (even in normal C++ Bullet) you have to create collision shapes first, _then_ add them to a rigid body, and then you can do position/orientation stuff with them -_- So I'll probably have to go and use b3CreateMultiBody* functions for this, make a body, and then request the stuff.
