### ISSUE TITLE
LWJGLCanvas.java null pointer exception, glfwAttachWin32Window not found!

### ISSUE THREAD

**Issue by NgocLuu-Incepit** [LWJGL/lwjgl3#429]
### Environment

* LWJGL version: `3.2.1-SNAPSHOT` 
* LWJGL build #: `10`
* Java version: `8`
* Platform: `Windows`
* Module: `jawt`

### Description

When I run JAWTDemo, found exception : null pointer exception, glfwAttachWin32Window not found!
Maven setting "Everything" at https://www.lwjgl.org/customize
I saw lwjgl-3.2.1-20181109.113206-11-natives-windows.jar in Maven repo folder

**Comment by Spasi** [comment]
Hey @NgocLuu-Incepit. 3.2.1 build 11 is now available, `glfwAttachWin32Window` will be there.
