### ISSUE TITLE
what is GLFW_KEY_WORLD_1 and what is GLFW_KEY_WORLD_2?

### ISSUE THREAD

**Issue by XenoAmess** [LWJGL/lwjgl3#433]
Recently I'm using LWJGL making my game engine and when I write an input box class, I go to look at your **GLFW.java**, and under the **Printable keys** , I found **GLFW_KEY_WORLD_1       = 161** and **GLFW_KEY_WORLD_2       = 162** , and I just wonder what are these keys?
I will be very happy if you send a picture about which keys are them on the key board.

**Comment by dustContributor** [comment]
You should probably ask in GLFW's repo itself: https://github.com/glfw/glfw

**Comment by XenoAmess** [comment]
> You should probably ask in GLFW's repo itself: https://github.com/glfw/glfw

OK, that make sense.
