### ISSUE TITLE
[Question] ram leak when using nvgText?

### ISSUE THREAD

**Issue by Masy** [LWJGL/lwjgl3#434]
I'm currently working on a debug screen with lots of smaller text labels and i'v noticed that even when not updating any texts the ram usage still increases.

I have already posted this question on the nanoVG github page, but since the project is rather abandoned due to the fact that the dev had a child and didn't found any new maintainers and it could also be an issue with the lwjgl bindings i'm posting this question here aswell.

So this is my method to draw text:
```java
public static void drawText(int posX, int posY, ByteBuffer asciiBuffer, float fontSize, float fontBlur, Font font, NVGColor color, int alignment) {
	nvgFontSize(NVG_ID, fontSize);
	nvgFontFace(NVG_ID, font.getName());
	nvgFontBlur(NVG_ID, fontBlur);
	nvgFillColor(NVG_ID, color);
	nvgTextAlign(NVG_ID, alignment);
	nvgText(NVG_ID, posX, posY, asciiBuffer);
}
```

And here is a video showing the ram usage in the title of my window (i can't draw it as text since it would need updating, which would flaw the "evidence")
https://streamable.com/5dss2

As shown in the video, as soon as i start rendering text the ram starts increasing even though the ByteBuffers containing the chars for the texts never change. When i stop rendering, the ram usage stays the same.

Since i'm not very good at c++ and especially not very familiar with the nanoVG code i'm wondering if the ram leak is because i'm using nvgText() wrong or is the native method just messing something up.

**Comment by httpdigest** [comment]
You should first use a memory profiler (such as JProfiler or YourKit - both available as fully functional time-limited evaluation versions) to identify the source (call stack) of the memory allocations.

**Comment by Masy** [comment]
JProfiler says that there are 9 million nio DirectByteBuffers using 572 mb after a while.
As soon as i start rendering the debug screen, which consists of 18 text labels, therefore 18 ByteBuffers, there is an increase of about 400k byte buffers per second. I'm having around 20k fps, so i guess every time i call nvgText it copies all 18 ByteBuffers when calling nvgText()

**Comment by httpdigest** [comment]
[The binding of nvgText()](https://github.com/LWJGL/lwjgl3/blob/2359eb7b5a9e7e629beae95d3cdab8e997c59039/modules/lwjgl/nanovg/src/generated/c/org_lwjgl_nanovg_NanoVG.c#L586-L592) itself does not do anything, and what the implementation of nvgText() may do could not be picked up by any JVM profiler, so the assumption is that your own code is doing the ByteBuffer allocations. What is the exact callstack doing the ByteBuffer allocations?

**Comment by Masy** [comment]
I create a ByteBuffer using MemoryUtil.memASCII("Text") when creating a text label object and then passing it to nvgText() on every render call. Not sure where to look up where objects where created in JProfiler

**Comment by httpdigest** [comment]
If you call MemoryUtil.memASCII() indeed every frame, then that's the issue. You need to manually release the memory afterwards with MemoryUtil.memFree(). Or you may be better off using the MemoryStack. See https://blog.lwjgl.org/memory-management-in-lwjgl-3/ for more information.

**Comment by Masy** [comment]
I'm not calling it every frame. I once create the ByteBuffer when creating the object. I then store it as a private attribute in the TextLabel object and when calling the render method of the TextLabel it calls the nvgText() method with the ByteBuffer attribute of the TextLabel object as parameter

**Comment by httpdigest** [comment]
I see. Well, then I'm out of ideas. You should just check the callstack of the memory allocations. You need to enable CPU profiling to see that. Consult the JProfiler documentation about that.

**Comment by Masy** [comment]
Oh i see, it's in fact nvgFontFace creating the buffers. I would guess because i pass the fonts name as string which then gets converted to a byte buffer so the native method has access to the pointer of the char array

**Comment by Spasi** [comment]
There is an allocation happening in the above code: The `nvgFontFace(NVG_ID, font.getName());` call must serialize the font name string and LWJGL currently allocates a `ByteBuffer` via the `MemoryStack` internally. Assuming nothing else allocates, this would account for ~400k instances at 20k fps.

But, this would only happen when running inside a profiler which, ironically, screws up with escape analysis and you end up with useless measurements. Running `nvgFontFace` in a tight loop produces zero garbage normally, EA eliminates the `ByteBuffer` allocation.

So, two questions:

- Is it really a memory leak? Does memory usage continuously increase and never goes down after a GC?

**Comment by Masy** [comment]
Well, of course the GC clears them after a while.

I measure ram usage by calling this method every 50ms (20 times per second):
```java
public static void update() {
	usedMemory = allocatedMemory - (RUNTIME.freeMemory() / 1024 / 1024);
	allocatedMemory = RUNTIME.totalMemory() / 1024 / 1024;
	usedMemoryBuffer = LongUtil.toText(usedMemory, usedMemoryBuffer);
	allocatedMemoryBuffer = LongUtil.toText(allocatedMemory, allocatedMemoryBuffer);
}
```

The LongUtil.toText() is just a copy of the original Long.toString() method but instead of creating a string it just reallocates the memory of the given byte buffer and then writes the numbers of the long directly into the byte buffer.

When converting the name of the Font to a ByteBuffer instead of a string the ram "leak" is indeed fixed.

**Comment by Spasi** [comment]
> When converting the name of the Font to a ByteBuffer instead of a string the ram "leak" is indeed fixed.

This is odd. It sounds like EA is unable to eliminate the internal `ByteBuffer` allocation for some reason. Could you please share more information on how you run the application? What JVM do you use? Does `-XX:+/-DoEscapeAnalysis` make a difference? If you've got time to spare, you could try capturing a log and analyzing it in [JITWatch](https://github.com/AdoptOpenJDK/jitwatch), it will tell you exactly why the allocation isn't eliminated. E.g. a method might be too large, or the call hierarchy is too deep.

**Comment by Masy** [comment]
Java version:
```
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.18.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

I start the application via IntelliJ or, when i profiled, run the jar that was created by maven with JProfiler.
Starting the game with the ``-XX:+/-DoEscapeAnalysis`` does not make a difference.

**Comment by Spasi** [comment]
@Masy I think we're seeing different results because we are on different LWJGL versions. Could you please confirm that you're on `3.2.0` or earlier and that allocations (with the original `nvgFontFace` call, passing a `String`) are eliminated when running with the `3.2.1` snapshot build?

Btw, this is useful just to verify that the recent performance work that has gone into LWJGL helps in such cases. For performance-sensitive code, converting the string to a buffer ahead of time is preferable even with no allocations, it avoids the memory copy. Which can also be much more than a simple `memcpy` when dealing with UTF-8 encoding.

**Comment by Masy** [comment]
I am currently using 3.2.0, but when running the latest 3.2.1-SNAPSHOT the bug is fixed
