### ISSUE TITLE
A required function is missing: glfwGetWaylandDisplay

### ISSUE THREAD

**Issue by Ant01n3** [LWJGL/lwjgl3#436]
### Environment

* LWJGL version: `3.2.2` 
* LWJGL build #: `SNAPSHOT 2018-12-08`
* Java version: `openjdk version "1.8.0_172"`
* Platform: `Linux`
* Module: `glfw|glfwGetWaylandDisplay()`

### Description

Hi all !

When trying to use the `GLFWNativeWayland.glfwGetWaylandDisplay()` method, the program crashes with : 

```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.lwjgl.glfw.GLFWNativeWayland.glfwGetWaylandDisplay(GLFWNativeWayland.java:47)
	at ME.main(ME.java:30)
Caused by: java.lang.NullPointerException: A required function is missing: glfwGetWaylandDisplay
	at org.lwjgl.system.APIUtil.requiredFunctionMissing(APIUtil.java:142)
	at org.lwjgl.system.APIUtil.apiGetFunctionAddress(APIUtil.java:135)
	at org.lwjgl.glfw.GLFWNativeWayland$Functions.<clinit>(GLFWNativeWayland.java:28)
	... 2 more
```

Without it the program runs without problem. The GLFWNativeWin32 for example works perfectly. I do verified that I had the correct jars in the classpath (lwjgl-glfw-natives-linux.jar...), and by the way all of GLFW is available and working.

Here is a minimal program to reproduce the error : 

```
import org.lwjgl.*;
import org.lwjgl.glfw.*;
import org.lwjgl.system.*;

import java.nio.*;

import static org.lwjgl.glfw.Callbacks.*;
import static org.lwjgl.glfw.GLFW.*;
import static org.lwjgl.system.MemoryStack.*;
import static org.lwjgl.system.MemoryUtil.*;


public class ME {
	public static void main(String args[]) {
		GLFWErrorCallback.createPrint(System.err).set();

		if (!glfwInit())
			throw new IllegalStateException("Unable to initialize GLFW");

		glfwDefaultWindowHints();
		glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE);
		glfwWindowHint(GLFW_RESIZABLE, GLFW_TRUE);
		
		long window = glfwCreateWindow(300, 300, "Hello World!", NULL, NULL);
		long monitor = glfwGetWindowMonitor(window);
		
		if(window == NULL)
			throw new RuntimeException("Failed to create the GLFW window");

		long dpy = GLFWNativeWayland.glfwGetWaylandDisplay();
	}
}
```

Thanks for your help, and thanks for all the great work !

**Comment by Spasi** [comment]
Currently, the choice between X11 and Wayland cannot be made at runtime, GLFW must be built to support one or the other. That's why `lwjgl-glfw-natives-linux.jar` includes two binaries. LWJGL defaults to X11. You can use `-Dorg.lwjgl.glfw.libname=glfw_wayland` (or call `Configuration.GLFW_LIBRARY_NAME.set("glfw_wayland")` before initializing GLFW) to enable the shared library that supports Wayland.

**Comment by Ant01n3** [comment]
Thanks a lot for this answer !

May I suggest to point to these configurations options in the exception error message if possible ?

Thanks again
