### ISSUE TITLE
LWJGL 3.2.1 build 12 seem not compiled with Java 8

### ISSUE THREAD

**Issue by nathan818fr** [LWJGL/lwjgl3#437]
It seem that LWJGL version 3.2.1 build 12 distributed on the website (https://www.lwjgl.org/customize) is compiled using Java 10 (all classes files are bytecode version 54.0).
Is it an error or a choice ?

**Comment by httpdigest** [comment]
Cannot reproduce. The zip download contains only 52.0 class files as does the Maven Central download of the classes in the jar artifacts for version = 3.2.1.
