### ISSUE TITLE
NanoVG Stencil Test problems

### ISSUE THREAD

**Issue by Perso11** [LWJGL/lwjgl3#439]
### Environment

* LWJGL version: `3.2.1` 
* LWJGL build #: `12`
* Java version: `build 1.8.0_191-b12`
* Platform: `Windows`
* Module: `nanovg`

### Description

Hello, I am currently using nanovg to make my own gui library. To do that, i have look at the Demo gived, and with the colorwheel, i have a problem.
When the Stencil test is enable, the window become black, except for the colorwheel drawed. Since the Stencil Test is important, i don't know how and what to do.

From line 121 to 126: Preparing the rendering (before the rendering of the component)
From line 132 to 137: Finish the rendering (after the rendering of the component)

public void restoreState() {
    glEnable(GL_DEPTH_TEST);
    glEnable(GL_STENCIL_TEST);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);
    if (opts.cullFace) {
        glEnable(GL_CULL_FACE);
        glCullFace(GL_BACK);
    }
}

From line 1089 to 1191: Colorwheel rendering.
[nvgUtils.txt](https://github.com/LWJGL/lwjgl3/files/2718386/nvgUtils.txt)

Thanks you.
Perso11

With Stencil Test:
![with stencil test](https://user-images.githubusercontent.com/46230881/50561180-8d1e8d80-0d08-11e9-897c-66443c3195c0.png)

Without Stencil Test
![without stencil test](https://user-images.githubusercontent.com/46230881/50561193-a58ea800-0d08-11e9-8aa2-590129b84512.png)

**Comment by httpdigest** [comment]
> Since the Stencil Test is important

Important for what? Are you (not NanoVG) making active use of it in your own rendering?

Additionally, you haven't really given any hint to how the end result should look like. With the information given, I'd say the second image looks right. So just disable stencil testing. NanoVG enables stencil testing anyways for itself to work properly. See: https://github.com/memononen/nanovg#opengl-state-touched-by-the-backend

If you need stencil testing for your own rendering, then clear the stencil buffer and reset the stencil function and stencil operation accordingly for your own rendering.

**Comment by Perso11** [comment]
Thanks you, after some research, i think now then the stencil test is not necessarily required. I think then i am going to de without him.

Thanks you again.
Perso11
