### ISSUE TITLE
glfwUpdateGamepadMappings does not work

### ISSUE THREAD

**Issue by DesertCookie** [LWJGL/lwjgl3#441]
I'm trying to change my controller's mapping because several buttons aren't assigned correctly.
I tried modifying the default GLFW mapping for XInput controllers (Xbox 360 Controller by Logitec in my case) and applying it by using `glfwUpdateGamepadMappings(String)`.
My mapping is: `78696e70757401000000000000000000,XInput Gamepad (GLFW),platform:Windows,a:b0,
b:b1,x:b2,y:b3,leftshoulder:b4,rightshoulder:b5,back:b6,start:b7,leftstick:b8,
rightstick:b9,leftx:a0,lefty:a1~,rightx:a2,righty:a3,lefttrigger:a4,
righttrigger:a5,dpup:h0.1,dpright:h0.2,dpdown:h0.4,dpleft:h0.8` (for now I'm only trying to invert the left stick's y-axes.

I have verified that the specified name and GUID are the same as my controller; no changes made in the mapping string seem to be applied, my controller's behaviour doesn't change.

### Environment
* LWJGL version: `3.2.1` 
* LWJGL build #: `12`
* Java version: `11.0.1`
* Platform: `Windows 10`
* Module: `core|GLFW`

**Comment by dustContributor** [comment]
Shouldn't this be reported in GLFW's repo?

https://github.com/glfw/glfw

If it's a GLFW issue, there is nothing Spasi can do.

**Comment by DesertCookie** [comment]
> If it's a GLFW issue, there is nothing Spasi can do.

That's the question. Is it really or is it because of something to do with the Java binds...

**Comment by XenoAmess** [comment]
according to 

[release note](https://github.com/LWJGL/lwjgl3/blob/e27da7fe58ca824f09278d6deafc16bf4b98271e/doc/notes/3.2.2.md)

that function is removed.

A bug of that function is described at [issue](https://github.com/LWJGL/lwjgl3/issues/462).

I don't know if it is related to this but I suggest you use the other overload glfwUpdateGamepadMappings function and see if your issue still happens.

**Comment by XenoAmess** [comment]
Also, when you discover a new type of controller, do not forget to commit it at https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt

You are not likely the only one person who are using that kind of controller after all. You commit can make others less trouble.

**Comment by TheMrMilchmann** [comment]
> 
> 
> according to
> 
> [release note](https://github.com/LWJGL/lwjgl3/blob/e27da7fe58ca824f09278d6deafc16bf4b98271e/doc/notes/3.2.2.md)
> 
> that function is removed.
> 
> A bug of that function is described at [issue](https://github.com/LWJGL/lwjgl3/issues/462).
> 
> I don't know if it is related to this but I suggest you use the other overload glfwUpdateGamepadMappings function and see if your issue still happens.

The two issues are unrelated. The overload was removed since mapping data is usually quite large, thus the default mechanism used in these overloads failed (= allocating a buffer using the `MemoryStack` ran out of memory to - well - allocate on the stack). A method call that triggered this issue could never get to the actual native GLFW call.

This issue is about an entirely different problem: According to the reporter the Java call to `glfwUpdateMethodBindings` returns but the controls to not reflect the changes made. (This has also been reported upstream in https://github.com/glfw/glfw/issues/1422 but could not be reproduced yet.)

**Comment by Spasi** [comment]
Is this still a problem with the latest LWJGL snapshot?

**Comment by DesertCookie** [comment]
> Is this still a problem with the latest LWJGL snapshot?
With LWJGL 3.2.2 my gamepad's buttons are mapped correctly by default and changing button mappings works without a problem. Though the specific example used above still does not yield and results. The range modifiers `+` and `-` and the inversion modifer `~` seem to have no effect.

> Also, when you discover a new type of controller, do not forget to commit it at https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt
Searching this document for my gamepad (Logitech F310) I could find it, but using a different GUID and name. What should I make of this?

**Comment by Ali-RS** [comment]
I'm trying to update mappings but it results in a native crash. 
Using LWJGL 3.2.3, Linux Mint, OpenJDK 12

I use mappings from  https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt

My code: 

`updateMappings(new File("gamecontrollerdb.txt"));`


```
 private void updateMappings (File file) {

        if (!file.exists()) {
            throw new RuntimeException("File does not exist.");
        }

        byte[] bytes = new byte[0];

        try {
            bytes = Files.readAllBytes(file.toPath());
        } catch (IOException e) {
            e.printStackTrace();
        }

        // for some reason the loader wants a null char at the end of the file.
        byte[] newbytes = new byte[bytes.length + 1];
        System.arraycopy(bytes, 0, newbytes, 0, bytes.length);
        newbytes[newbytes.length - 1] = '\0';

        ByteBuffer byteBuffer = ByteBuffer.wrap(newbytes);
        byteBuffer.rewind();

        // always returns false if loaded before .start() or in constructor.
        // Crashes natively if loaded in simpleInit().
        boolean b = GLFW.glfwUpdateGamepadMappings(byteBuffer);

        // debugger breakpoint.
        String a = "b";
    }
```
Error log:

**Comment by octylFractal** [comment]
That is unrelated to this issue, you are allocating memory incorrectly for use with LWJGL. See https://github.com/LWJGL/lwjgl3-wiki/wiki/1.3.-Memory-FAQ for how to properly allocate.

**Comment by Ali-RS** [comment]
Ah, yep, it worked. 
@octylFractal  thanks so much for your help :)
