### ISSUE TITLE
LWJGL3 with RoboVM?

### ISSUE THREAD

**Issue by jleeson** [LWJGL/lwjgl3#446]
Would it be possible to use LWJGL3 OpenGL ES or Vulkan bindings with RoboVM?

I am aware RoboVM provides bindings for OpenGL ES but i am interested in building a game engine using LWJGL bindings.

I know the Vulkan bindings use MoltenVK on Mac OS, is there a way to use the MoltenVK build for ios?

**Comment by Spasi** [comment]
LWJGL probably won't play well with AOT compilation, but I haven't tried it.

The bundled MoltenVK is built for x64, a separate ARM build is required for iOS, which LWJGL does not provide.
