### ISSUE TITLE
Failed to locate library: libGLESv2.dylib

### ISSUE THREAD

**Issue by oakes** [LWJGL/lwjgl3#449]
### Environment

* LWJGL version: `3.2.1` 
* Java version: `11.0.2`
* Platform: `macOS`
* Module: `opengles`

### Description

I'm getting `java.lang.UnsatisfiedLinkError: Failed to locate library: libGLESv2.dylib` when I call `GLES.createCapabilities();`. I have the native dependency on the classpath, but when inspecting `lwjgl-opengles-3.2.1-natives-macos.jar` it appears to contain `liblwjgl_opengles.dylib`. Is this discrepancy in naming the cause of the problem?

**Comment by oakes** [comment]
I'm guessing this is because opengl ES isn't implemented in Mac OS?

**Comment by Spasi** [comment]
A good option for GLES on macOS is [MoltenGL](https://moltengl.com/moltengl/). I have tried it and works great with LWJGL.
