### ISSUE TITLE
Loading image from memory fails depending on ByteBuffer implementation used

### ISSUE THREAD

**Issue by Wasabi375** [LWJGL/lwjgl3#453]
### Environment

* LWJGL version: `3.2.1` 
* Java version: `1.8` - kotlin 1.3.21
* Platform: `MacOs` but also failing on `Linux (Travis: Linux (Trusty))`
* Module: `core | stb`

Loading image from memory fails depending on ByteBuffer implementation passed to `stbi__load_from_memory`

```kotlin
val buffer = BufferUtils.createByteBuffer(bytes.size).also { it.put(bytes); it.flip() } // DirectByteBuffer
val buffer2 = ByteBuffer.wrap(bytes)     // HeapByteBuffer

buffer.rem shouldBe buffer2.rem
for(i in 0 until buffer.rem){
    buffer[i] shouldBe buffer2[i]
}
buffer.equals(buffer2) shouldBe true

val stack = MemoryStack.stackGet()
stack.push()

val widthBuf = stack.ints(1)
val heightBuf = stack.ints(1)
val compCountBuf = stack.ints(1)

println("test loading from buffer 1")
stbi_load_from_memory(buffer, widthBuf, heightBuf, compCountBuf, 0)
        ?: throw IOException("Couldn't load image")

println("test loading from buffer 2")

stbi_load_from_memory(buffer2, widthBuf, heightBuf, compCountBuf, 0)
        ?: throw IOException("Couldn't load image")
stak.pop()
```
This code fails on the second invocation of `stbi_load_from_memory`. Both buffers contain exactly the same data. I have set up a test project here: https://github.com/Wasabi375/lwjglCrashSTBTest

**Comment by httpdigest** [comment]
You _must_ use only _direct_ NIO Buffers with LWJGL.

**Comment by kenzierocks** [comment]
You can't use heap-based byte buffers because they're not guaranteed to have a C-compatible representation, and have no easy way to access the address of the memory. Read https://blog.lwjgl.org/memory-management-in-lwjgl-3/ for more details.

**Comment by Wasabi375** [comment]
Mmmm. I must have missed that. Is there any reason why.
