### ISSUE TITLE
Possible spelling mistake in Assimp libary: "aiShadingMode_Fflat" instead of "aiShadingMode_Flat"

### ISSUE THREAD

**Issue by Destranix** [LWJGL/lwjgl3#454]
### Environment

* LWJGL version: `3.2.1` 
* LWJGL build #: `X`
* Java version: `java.version`
* Platform: `Linux|macOS|Windows`
* Module: `assimp`

### Description
See title

**Comment by Spasi** [comment]
Thanks!

**Comment by Destranix** [comment]
np
