### ISSUE TITLE
Build for Elbrus(e2k)

### ISSUE THREAD

**Issue by DJs3000** [LWJGL/lwjgl3#457]
[0001-Fix-some-compilation-errors-for-e2k.zip](https://github.com/LWJGL/lwjgl3/files/3089065/0001-Fix-some-compilation-errors-for-e2k.zip)

### Environment

* LWJGL version: `3.2.2` 
* LWJGL build #: `X`
* Java version: `1.8.0_152`
* Platform: `Linux`
* Module: `core|binding name`

**Comment by DJs3000** [comment]
I am trying to compile lwjgl for an alternative architecture processor. In Russia, there is a computer on its architecture, called Elbrus, code name "e2k". I optimized the code to build correctly, but at compile time the binaries are loaded and they certainly don't work on, not x86. What can be done? Your library is needed for minecraft ))))))

**Comment by Spasi** [comment]
LWJGL does not support architectures other than x86/x64 atm. Support for ARM is coming at a later time. I can't help with other architectures, unless you could provide specific information about what's not working as expected.

Btw, the above patch is trying to fix issues in bindings that Minecraft does not use. You can simply disable them in `build-bindings.xml`.

**Comment by Spasi** [comment]
Also see [this comment](https://github.com/LWJGL/lwjgl3/pull/469#issuecomment-511143529).
