### ISSUE TITLE
Calling GraphicsEnvironment.getLocalGraphicsEnvironment() blocks glfwPollEvents

### ISSUE THREAD

**Issue by Plericromon** [LWJGL/lwjgl3#459]
### Environment

* LWJGL version: `3.2.1` 
* LWJGL build #: `3.3.0 Cocoa NSGL dynamic`
* Java version: `OpenJDK 64-Bit Server VM Azul Systems, Inc. 12.0.1+12`
* Platform: `Mac OS X 10.14.4 x86_64`
* Module: `core`

### Description

I have been able to create a reproduce able minimal example that has the same error as my application:

First a working example where the offending line is commented out:
[https://gist.github.com/Plericromon/a169fbc76699d9492799329aced82d9b](https://gist.github.com/Plericromon/a169fbc76699d9492799329aced82d9b)

This example will work fine and render a dark blue window and printing "on frame" very regularly.

When you uncomment the following line:
`      //GraphicsEnvironment.getLocalGraphicsEnvironment();`

The window will remain black and "on frame" will never be printed. Using a debugger it can be seen that the application is blocked inside the call to `glfwPollEvents` and never returns.

**Comment by Plericromon** [comment]
Same as here:
https://github.com/LWJGL/lwjgl3/issues/68

**Comment by kenzierocks** [comment]
If you read that issue, you'll have your answer. It's not supported.

**Comment by Plericromon** [comment]
Yea, tried to close the issue, but I dont seem to be able to so i just added the link. Adding the headless property works good enough for me :)
