### ISSUE TITLE
[question] Is it possible to render text via nvgText() with trailing spaces?

### ISSUE THREAD

**Issue by Masy** [LWJGL/lwjgl3#464]
So i'm currently making a debug screen with a whole bunch of smaller textlabels because i splitted the information text into labels which need to be updated and which don't need updates. Because of that some labels have text that ends with spaces to ensure that the next label is not directly next to the previous label. Unfortunately nanoVG seems to ignore these trailing spaces.

```
ByteBuffer buffer = MemoryUtil.memUTF8("AbCd   ", false);
for (int n = 0; n < buffer.limit(); n++) {
	System.out.print((char) buffer.get(n));
}
System.out.print("\n");
```

prints
```AbCd   ``` 
so i'm 100% sure that the spaces are in the buffer.

This is how i render my text:
```
public static void drawText(int posX, int posY, ByteBuffer asciiBuffer, float fontSize, float fontBlur, Font font, NVGColor color, int alignment) {
	NanoVG.nvgFontSize(NVG_ID, fontSize);
	NanoVG.nvgFontFace(NVG_ID, font.getName());
	NanoVG.nvgFontBlur(NVG_ID, fontBlur);
	NanoVG.nvgFillColor(NVG_ID, color);
	NanoVG.nvgTextAlign(NVG_ID, alignment);
	NanoVG.nvgText(NVG_ID, (float)posX, (float)posY, asciiBuffer);
}
```

**Comment by kenzierocks** [comment]
NVG is rendering trailing spaces for me, on LWJGL 3.2.1 build 12, Ubuntu 18.10. Project: https://github.com/kenzierocks/nvgtext-trailing-spaces
Image: ![](https://i.imgur.com/SomeHpP.png)

You should provide:
- an [MCVE](https://stackoverflow.com/help/mcve) so we can try to reproduce the issue
- your LWJGL version & build number
- your platform / OS

**Comment by Masy** [comment]
Well, i kinda now realize that is probably rendering. The issue is the nvgTextBounds method not adding the trailing spaces to the text width

**Comment by kenzierocks** [comment]
That looks like it is intended behavior: https://github.com/memononen/nanovg/issues/225.

**Comment by Masy** [comment]
Yes, it is. But is there a way to get the width of a text with the spaces? They are talking about the difference between bound and advance, but i don't think there is method to get the position on where the next character will start (advance), only the width of the characters bounding box (bounds)

**Comment by Masy** [comment]
Ok, so now i have the problem, that i can't render the text when i need to know the advance of the text.
Because i have 2 texts next to each other i have to move the second text before the first text has been rendered, otherwise i would have to move the second text everytime it is rendered, even though the position can only change 20 times per second
