### ISSUE TITLE
Failed to locate library when using modules

### ISSUE THREAD

**Issue by Icedude907** [LWJGL/lwjgl3#468]
### Environment

* LWJGL version: `3.2.2` 
* LWJGL build #: `10`
* Java version: `12.0.1 amd64`
* Platform: `Windows`
* Module: `core`
* IDE: `Eclipse Java 2019-03`

### Description

Hey. I'm probably doing something incredibly stupid but I couldn't find any help on the interwebs.
My module-info file is as such:
```
module example.jigsaw.error {
	exports example;
	
	requires org.lwjgl;
	requires org.lwjgl.natives;
	requires org.lwjgl.glfw;
	requires org.lwjgl.glfw.natives;
	requires org.lwjgl.opengl;
	requires org.lwjgl.opengl.natives;
        requires org.lwjgl.jemalloc;
	requires org.lwjgl.jemalloc.natives;
}
```
And I copied the code from https://www.lwjgl.org/guide into the example package, adding the `package example;` on the top.
Then, I added the entire LWJGL library onto my modulepath and, enabling debug mode, hit run, this being the output.
```
Hello LWJGL 3.2.2 build 10!
[LWJGL] Version: 3.2.2 build 10
[LWJGL] 	 OS: Windows 10 v10.0
[LWJGL] 	JRE: 12.0.1 amd64
[LWJGL] 	JVM: OpenJDK 64-Bit Server VM v12.0.1+12 by Oracle Corporation
[LWJGL] Loading library (system): lwjgl
[LWJGL] 	lwjgl.dll not found in java.library.path
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: lwjgl.dll
	at org.lwjgl/org.lwjgl.system.Library.loadSystem(Library.java:147)
	at org.lwjgl/org.lwjgl.system.Library.loadSystem(Library.java:67)
	at org.lwjgl/org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl/org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:97)
	at org.lwjgl/org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
	at org.lwjgl/org.lwjgl.system.Callback.<clinit>(Callback.java:40)
	at example.jigsaw.error/example.HelloWorld.init(HelloWorld.java:39)
	at example.jigsaw.error/example.HelloWorld.run(HelloWorld.java:24)
	at example.jigsaw.error/example.HelloWorld.main(HelloWorld.java:114)
```
Whats interesting about this is that if I delete the module-info file and switch LWJGL onto the classpath instead of the modulepath I get no errors whatsoever and the application runs as it should.

Thanks in advance for any assistance.

**Comment by Spasi** [comment]
The issue is likely related to:

> IDE: Eclipse Java 2019-03

Module support in Eclipse has been problematic. You can search for similar issues here or on the JGO forums. Afaict, no user has been able to get Eclipse to build modular projects properly.

You could verify that it's not an LWJGL issue by building and running your project from the command line.

**Comment by Icedude907** [comment]
Yes, your right, thanks.
Ran it with the exact same dependencies that I used in eclipse via the command line and it ran just fine. Interesting...
Anyway, I'll close the issue now.

**Comment by Icedude907** [comment]
Out of curiosity... has anyone been able to build it with Intellij or Netbeans?

**Comment by Spasi** [comment]
IntelliJ has great module support, even before Java 9 was officially released. Netbeans supports modules since mid-2018 and works fine afaict.
