### ISSUE TITLE
Eclipse update site down

### ISSUE THREAD

**Issue by C-Otto** [LWJGL/lwjgl3#47]
The Eclipse update site mentioned on https://wiki.eclipse.org/LWJGL_Plugin is down (404).

**Comment by SilverTiger** [comment]
That's because there is a new homepage for LWJGL3.
The old homepage is available at http://legacy.lwjgl.org/ and the update site should be http://legacy.lwjgl.org/update/

**Comment by C-Otto** [comment]
Thank you!
