### ISSUE TITLE
Assimp FBX loading problem.

### ISSUE THREAD

**Issue by MrManiacc** [LWJGL/lwjgl3#470]
### Environment

* LWJGL version: `3.2.2` 
* LWJGL build #: `latest`
* Java version: `1.8`
* Platform: `macOS`
* Module: `org.lwjgl.assimp`

### Description

  I'm having trouble loading FBX models using assimp with lwjgl. I have no problem loading in obj files, but as soon as I pass in a FBX file, the  AIScene is null.

When passing in an obj, the null check doesn't get called, and the model is valid. When passing in a FBX file type however, the AIScene is null, and throws the exception I'm catching. I'm not sure if it's just some flags i'm not passing or what, but I'd like to be able to load all file types, and I can't seem to find anything on loading anything other than objs with lwjgl's assimp binding. I hope i'm overlooking something simple and this can be resolved quickly, thanks!

<img width="1053" alt="Screen Shot 2019-05-29 at 1 21 12 PM" src="https://user-images.githubusercontent.com/4280960/58577912-91969600-8215-11e9-8d6b-642330f6833f.png">

**Comment by Spasi** [comment]
What's the output of `aiGetErrorString()` when it fails? Also, could you share the problematic FBX file?

**Comment by MrManiacc** [comment]
> What's the output of `aiGetErrorString()` when it fails? Also, could you share the problematic FBX file?

Thanks for this. Realized that i'm an idiot and  can't rename model files. I think that when I was renaming the files, it wasn't reading properly because the files have some sort of link  between the file name, and the file name inside the actual file. Anyways  I've corrected the issue and can properly load any model.
