### ISSUE TITLE
Can't render on transparent window

### ISSUE THREAD

**Issue by EnderWings** [LWJGL/lwjgl3#471]
I tried creating a transparent window using:
GLFW.glfwWindowHint(GLFW.GLFW_TRANSPARENT_FRAMEBUFFER, GLFW.GLFW_TRUE);
The window appears to be transparent but I can't render anything on it.

I won't send source code but I'll provide two images of when my program enables transparent framebuffer and when it doesn't.
![image](https://user-images.githubusercontent.com/38600771/58715906-0a524980-83f2-11e9-831b-29e6960feab6.png)
![image](https://user-images.githubusercontent.com/38600771/58715974-41285f80-83f2-11e9-8c4e-a306d89afd4d.png)
* LWJGL version: `3.2.1` 
* Java version: `jdk 1.8.0_191`
* Platform: `Windows 10`

**Comment by httpdigest** [comment]
The output of your render will be blended with the background behind the window based on the alpha channel you render to. You likely render alpha=0.0 (the fourth component of the framebuffer color output channel).

**Comment by XenoAmess** [comment]
if you dont wanna show your real source code you can still show your idea with writing a runable demo with 100- lines...
That will  always save lots of time...

**Comment by httpdigest** [comment]
Closing, because there is no real issue here. It works fine when taking care of which value is written to the alpha/w channel of the color buffer (including: glClearColor, glColor4f, output of fragment shader).
