### ISSUE TITLE
I wondered, if there be some way to render a svg file?

### ISSUE THREAD

**Issue by XenoAmess** [LWJGL/lwjgl3#473]
As title.
Just an ask, not mean I really need it.
We are now using a tool to render svg to png then load the texture from png, it runs fair good.
While I guess there might be more elegant way to do this.

**Comment by Spasi** [comment]
Yes, the nanovg bindings include [NanoSVG](https://github.com/memononen/nanosvg).

Sample code available in [SVGDemo](https://github.com/LWJGL/lwjgl3/blob/master/modules/samples/src/test/java/org/lwjgl/demo/nanovg/SVGDemo.java).
