### ISSUE TITLE
glfwSetCursorPos not working on windows

### ISSUE THREAD

**Issue by Masy** [LWJGL/lwjgl3#475]
I'm setting the cursorPosition to 0,  0 and immediately getting it, but it's still the same as before.

On linux this method works fine, but on windows the setCursorPos() is completely ignored (and charCallback aswell on a side note).

This is the code:
```
GLFW.glfwSetCursorPos(this.windowHandle, 0, 0);
GLFW.glfwGetCursorPos(this.windowHandle, this.mouseX, this.mouseY);
System.out.println("Mouse Pos: " + this.mouseX.get(0) + ", " + this.mouseY.get(0));
```

and this is the result: `Mouse Pos: 551.0, 397.0`, which completley breaks my camera movement because the player is constantly rotating because i can't set the cursor to the center of the window.

I'm using lwjgl-3.2.1 but on 3.2.2 it's the same issue.

EDIT: This seems to be completely unrelated to the version, because i downgraded to 3.1.6 where i had a project months ago where this was definitely working, but it's still not working in this project.

**Comment by Spasi** [comment]
Hey @Masy, I cannot reproduce this. Tried this code in LWJGL's Gears demo:

```java
case GLFW_KEY_C:
    glfwSetCursorPos(window, 100, 100);
    try (MemoryStack s = stackPush()) {
        DoubleBuffer x = s.callocDouble(1);
        DoubleBuffer y = s.callocDouble(1);
        glfwGetCursorPos(window, x, y);
        System.out.println("Mouse Pos: " + x.get(0) + ", " + y.get(0)); // getting 100, 100
    }
    break;
```

and it works fine. Are you calling `glfwSetCursorPos` from the main thread?

**Comment by Masy** [comment]
No, i have an OpenGL thread and an Input thread, the input thread calls the setCursorPos() method. I've made a completely new project using the sample code from the website and it works fine aswell on windows, so I'm guessing it's some other problem. If it's really a thread thing i'm wondering why it would work on linux and not on windows

**Comment by Rossledge** [comment]
Wouldn't it make more sense for the cursor position to be allowed to be updated on a separate thread? If it is a common practice to update input on a separate thread, than it would make sense to put your cursor methods there. It also is common to have your update and render loops on different threads meaning that if you wanted to update your cursor position in the update thread it is not possible. Just some observations.

**Comment by Spasi** [comment]
This is an OS-level limitation that GLFW has to respect. There is no way around it. Even if it may work fine on Linux for example, GLFW is a cross-platform library and is designed so that it works properly on all target platforms.

Splitting input and rendering on different threads is indeed a common practice and is fully supported under these constraints. You simply have to handle input on the **main** thread and move rendering to a secondary thread, not the other way around.
