### ISSUE TITLE
Customizing doesn't work

### ISSUE THREAD

**Issue by Zamundaaa** [LWJGL/lwjgl3#478]
I'm on Firefox.
It generates the zip and then nothing happens. Apparently with & without arm(64) selected.

**Comment by httpdigest** [comment]
Please share the config of the selected options (click on "Save config" and paste the resulting json in a code block here). Also check Ctrl+J or your downloads folder that it might not just have generated a download in the background.
And what exactly do you mean with "nothing happens"? What did you expect to happen other than generating the zip file?

**Comment by Zamundaaa** [comment]
Ok thanks. It happens to me with every single config I tried. Never occurred to me it could be joml

**Comment by httpdigest** [comment]
Looking into the F12 / developer tools always helps when diagnosing web page issues. :)

**Comment by apostolos** [comment]
`joml-1.9.15.jar` was missing from the build server.

I've uploaded both `joml-1.9.15.jar` and `joml-1.9.15-sources.jar` but I'm not sure where I'm supposed to find `joml-1.9.15-javadoc.jar`...

Pinging @Spasi

**Comment by httpdigest** [comment]
If in doubt, then repo.maven.apache.org is always right: https://repo.maven.apache.org/maven2/org/joml/joml/1.9.15/
But I am very sure that the download did work at one point with 1.9.15, as I immediately verified it myself when the PR was deployed.

**Comment by apostolos** [comment]
Thanks, I've updated the javadoc jar as well. Everything should be working now.

I've opened an issue for downloading addons directly from Maven. It's a good idea.
https://github.com/LWJGL/lwjgl3-www/issues/68
