### ISSUE TITLE
GLFW.glfwCreateWindow error

### ISSUE THREAD

**Issue by DanielCoreOfficial** [LWJGL/lwjgl3#487]
### Environment

* LWJGL version: `3.2.2` 
* LWJGL build #: `10`
* Java version: `JDK-11`
* Platform: `macOS`
* Module: `Don't know.`

### Description

Describe your question in detail and include example code if applicable.
So I'm programming a window and apparently when I tried to create the window, it'll appear it as an error. I have GLFW and such which needs to have to create the window.

window = GLFW.glfwCreateWindow(width, height, title, 0, 0);

**Comment by httpdigest** [comment]
You haven't given _any_ useful information about the error you are getting and which code produces the error. Best would be to provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example).
`window = GLFW.glfwCreateWindow(width, height, title, 0, 0);` is not a useful code example. What was called before that?

**Comment by DanielCoreOfficial** [comment]
> You haven't given _any_ useful information about the error you are getting and which code produces the error. Best would be to provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example).
> `window = GLFW.glfwCreateWindow(width, height, title, 0, 0);` is not a useful code example. What was called before that?

I was dumb and I added an s on accident.

Can you help me with this other problem though?

https://sourceb.in/e0dda5c1b4.java

(PS. The problem I had above is working, yet this one is something wrong with my code when I try and run it.)

**Comment by httpdigest** [comment]
If you run GLFW applications on Mac OS, you need to take care of two things:
1. run the JVM with the JVM argument [-XstartOnFirstThread](https://stackoverflow.com/questions/28149634/what-does-the-xstartonfirstthread-vm-argument-do-mean)
2. certain GLFW functions must _only_ be called by the main thread (not by a spawned thread). Such GLFW functions include `glfwInit`, `glfwCreateWindow`, `glfwPollEvents`. See the GLFW documentation for information about thread-safety of the functions you call.

**Comment by DanielCoreOfficial** [comment]
> If you run GLFW applications on Mac OS, you need to take care of two things:
> 
> 1. run the JVM with the JVM argument [-XstartOnFirstThread](https://stackoverflow.com/questions/28149634/what-does-the-xstartonfirstthread-vm-argument-do-mean)
> 2. certain GLFW functions must _only_ be called by the main thread (not by a spawned thread). Such GLFW functions include `glfwInit`, `glfwCreateWindow`, `glfwPollEvents`. See the GLFW documentation for information about thread-safety of the functions you call.

So what do I do?
