### ISSUE TITLE
MacOS isn't running, even with VM Arguments.

### ISSUE THREAD

**Issue by DanielCoreOfficial** [LWJGL/lwjgl3#488]
* LWJGL version: `3.2.2` 
* LWJGL build #: `10`
* Java version: `java 11`
* Platform: `macOS`
* Module: `Don't know.`

I'm learning about how LWJGL works and openGL, everything is great like there are no errors.
Yet I can't run it because an error pops up.
I read about this a little bit, and a comment said this about the situation.
"Remove the start() function and change "new Main().start()" to "new Main.run". "

**
 public void start() {
		game = new Thread(this, "game");
		game.start();
	}
	
	public static void init() {
		System.out.println("Initializing game.");
		window = new Window(WIDTH, HEIGHT, "game");
		window.create();
	}
	
	public void run() {
		init();
		while (true) {
			update();
			render();
		}
	}
	
	private void update() {
		System.out.println("Updating the game libraries, sorry.");
	}
	
	private void render() {
		System.out.println("Rendering the game.");
	}
	
	public static void main(String[] args) {
		new Main().start();
	}**

In what part of that code do they mean? (Sorry if this is probably not a good question, I'm just wondering so I can get back to doing the Window. :D )

**Comment by kappaOne** [comment]
It would help if you can state what the error is that pops up? Further the code you have pasted doesn't show any LWJGL code in it, so it'll be hard to say what it does and where any problem lies.

**Comment by DanielCoreOfficial** [comment]
> It would help if you can state what the error is that pops up? Further the code you have pasted doesn't show any LWJGL code in it, so it'll be hard to say what it does and where any problem lies.

Hello! I've fixed the problem.
