### ISSUE TITLE
OpenPOWER Support

### ISSUE THREAD

**Issue by llebout** [LWJGL/lwjgl3#495]
Hello,
Currently only ARM and x86 is supported, but it would be nice to support the OpenPOWER platform that's high performance and gaming capable. An OpenPOWER compliant CPU would be the [IBM POWER9](https://en.wikipedia.org/wiki/POWER9).

I don't exactly know what's really architecture specific into lwjgl3 but hopefully you can tell me that so I can go straight to the point if I want to solve that issue myself.

Thanks

**Comment by Spasi** [comment]
LWJGL artifacts are built on Travis CI (Linux & macOS) and AppVeyor (Windows). Support for a new architecture like POWER must start here: [LWJGL-CI](https://github.com/LWJGL-CI?tab=repositories). In each repository there's a `.travis.yml` file that builds the corresponding library for the supported architectures. A new target must be added to the build matrix, that cross-compiles for POWER.

You can start by forking the repositories and removing the AWS S3 stuff. You can also skip libraries that are irrelevant on POWER9 or support specific architectures only (e.g. Meow and Tootle). When you have working builds, update this issue and we'll talk about next steps.

**Comment by PineconesUpMyButthole** [comment]
i'll see if i can get it to compile next weekend. it looks like POWER9 has similar AES instructions to x86, so making something that replicates meow might be possible. Do many games use meow though? it might be unnecessary for now.

https://wiki.raptorcs.com/w/images/c/cb/PowerISA_public.v3.0B.pdf (page 333)
https://www.intel.com/content/dam/doc/white-paper/advanced-encryption-standard-new-instructions-set-paper.pdf
https://en.wikipedia.org/wiki/AES_instruction_set

**Comment by Matthew-Bradley** [comment]
Neato! This'd be really cool to have, and I'd be willing to post/contribute to a bounty on it at https://www.bountysource.com/ similar to some other POWER porting work.

I just kinda want to run minecraft :P but with the work going in right now for Radeon Open Compute (https://www.phoronix.com/scan.php?page=news_item&px=AMDGPU-Linux-5.5-KFD-PPC) this would be pretty timely. :D

**Comment by runlevel5** [comment]
I believe the CI has now been migrated to hosted Github Action which does not offer ppc64le workers. I am more than happy to host Github Action worker on my ppc64le box.

**Comment by runlevel5** [comment]
The first PR to get libffi lib compiled with ppc64le https://github.com/LWJGL-CI/libffi/pull/3

**Comment by runlevel5** [comment]
Great thanks @Spasi
