### ISSUE TITLE
Failed to initialize GLFW, errors: GLFW error during init

### ISSUE THREAD

**Issue by Bryophyllum** [LWJGL/lwjgl3#499]
### Environment

* LWJGL version: `3.2.2` 
* LWJGL build #: `10`
* Java version: `OpenJDK 11.0.4`
* Platform: `Linux`
* Module: `core`

### Description
I'm trying to find a way around the issue of Minecraft failing to initialize GLFW when the latter's Wayland backend is enabled via the argument `-Dorg.lwjgl.glfw.libname=glfw_wayland`. 
According to the comment: https://bugs.mojang.com/browse/MC-92393?focusedCommentId=554000&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-554000, using a version of GLFW newer than the one bundled in LWJGL =<3.1.6 fixed the problem at the time. 

Fast forward to the present day and the latest release 1.14.4 of the game now uses LWJGL 3.2.2, which ships with GLFW 3.3, and yet that's still an issue, which leads me to believe that LWJGL is to blame in this particular case.

```
Description: Initializing game

java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init: [0x10008]139935606292560
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:75)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:602)
	at czq.c(SourceFile:448)
	at net.minecraft.client.main.Main.main(SourceFile:162)

A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX._initGlfw(SourceFile:75)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(SourceFile:602)
	at czq.c(SourceFile:448)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:162)
```

I can't tell if this crash log actually indicates that LWJGL's GLFW causes the problem, as I know nothing about Java, and the underlying libraries used in the game. But, if the author of that comment is right, and given the fact that my game doesn't crash with GLFW complaining that "Focusing a window requires user interaction", I assume that there's a linkage between LWJGL and this issue.

**Comment by kenzierocks** [comment]
It's likely that your game _does_ crash with "Focusing a window requires user interaction", but the Minecraft code for printing errors appears to have a bug where it prints the _address_ of the error string, rather than the actual string:

```java
      GLFWErrorCallback var1 = GLFW.glfwSetErrorCallback((var1x, var2x) -> {
         var0.add(String.format("GLFW error during init: [0x%X]%s", var1x, var2x));
      });
```

So I suspect you're still experiencing the linked issue, because this isn't a problem for GLFW to solve, it's a problem for Minecraft to solve.

**Comment by Bryophyllum** [comment]
That's a shrewd observation. In this case, I'm closing this issue. Thanks~
