### ISSUE TITLE
stbtt does not work in ubuntu?

### ISSUE THREAD

**Issue by XenoAmess** [LWJGL/lwjgl3#500]
----------------
### Environment

* LWJGL version: 3.2.2 / 3.2.3
* Java version: adopt openjdk12
* Platform: ubuntu 19(linux)
* Module: stbtt

### Description

My engine works fine in windows and I'm trying to port it to linux.
And I just find out that the texts drawing using stbtt is not right.
on Windows:
![java_2019-08-11_13-31-06](https://user-images.githubusercontent.com/17455337/64094582-cecb7080-cd8e-11e9-931b-788c0045772b.png)
on Ubuntu:
![vmconnect_2019-08-11_13-26-08](https://user-images.githubusercontent.com/17455337/64094586-d1c66100-cd8e-11e9-94a4-6b0fda789239.png)

(focus on the DEMO text in left top corner.)
I just don't know why it happened...

If you wanna reproduce:
the codes can be found in https://github.com/cyanpotion/cyan_potion,
just run com.xenoamess.cyan_potion.cyan_potion_demo.ForceEntrance.main() to enter the demo.

Thanks for reading. :)

**Comment by Spasi** [comment]
Hey @XenoAmess,

The font texture size is 16k*16k, which may be over the `GL_MAX_TEXTURE_SIZE` limit of the VM's OpenGL driver. Or there might not be enough virtual GPU memory available, that texture alone needs 256MB. Have you checked if you're getting OpenGL errors?

You could also verify that stb_truetype works correctly, by enabling `TEST_PRINT_FONT_BMP` and inspecting the output.

**Comment by XenoAmess** [comment]
My bad.
Due to my poor knowledge about hyper-v, I wrongly get that machine's GL_MAX_TEXTURE_SIZE 3379,
far smaller than it need.
I will test it on a real machine next time.
