### ISSUE TITLE
sigsev on minecraft rpi4

### ISSUE THREAD

**Issue by Askmewho** [LWJGL/lwjgl3#504]
HI guys!

Ive tried the libraries for arm32 of the official website and doing LD_LIBRARY_PATH=
for the JRE 11 lib location (because I dont know why it doesnt use them anyway)
Ive had renamed them whit a "32" at the end because minecraft ask them to be like that (I know, not very clean)

the thing its than now it load them but with a sigseg as result 

[hs_err_pid21145.log](https://github.com/LWJGL/lwjgl3/files/3618744/hs_err_pid21145.log)

hope you gave me a clue of what should I do. thanks on advance

**Comment by Spasi** [comment]
Hey @Askmewho,

I don't see a way this code could crash in libjvm like that, unless there's a version mismatch between liblwjgl and lwjgl.jar. I.e. the 3.2.3 shared library is not compatible with the 3.2.2 classes. Could you verify please?

**Comment by Askmewho** [comment]
Many thanks for the answer @Spasi , I will!!

**Comment by Askmewho** [comment]
indeed,it seems than minecraft 1.14.4 uses 3.2.2 version, could I force it to use the newer versions with preload or should I wait for a newer release? or could I compile 3.2.2 for arm32? thanks!

**Comment by Spasi** [comment]
Afaik, it is not allowed to tamper with the libraries Minecraft uses. Compiling 3.2.2 for arm32 would be a lot of backporting work. I think waiting for Minecraft to upgrade to 3.2.3 would be wiser.

**Comment by Askmewho** [comment]
Thanks @Spasi . Closed for now!
