### ISSUE TITLE
double free occuring randomly with OpenVR

### ISSUE THREAD

**Issue by Zamundaaa** [LWJGL/lwjgl3#505]
### Environment
* LWJGL version: 3.2.3 as well as 3.2.4 tested
* LWJGL build #: 13; 1 in the case of 3.2.4
* Java version: openjdk 12.0.2 2019-07-16, also tried openjdk 8.
* Platform: Linux
* Module: OpenVR

This is a question and maybe a bug report, too. If I'm using OpenVR then everything works as expected (ignoring the faults in my own system of course) but it just suddenly exits the VM with the message in System.err
> free(): double free detected in tcache 2

It seems to happen at random times, sometimes a minute in, sometimes it takes a few minutes, and possibly not even in my own code. I tried finding out where the message comes from but it doesn't appear to lead anywhere, it sometimes seems to appear in one method (that only has 3 joml calls in it and nothing else) and sometimes in another.
Other (non-java) applications works just fine though, and if I let my app just render to the screen and not use VR then it doesn't crash, too.
My question would be: how do I find out where this comes from?

**Comment by Spasi** [comment]
You could try running with `-Dorg.lwjgl.util.Debug=true -Dorg.lwjgl.util.DebugAllocator=true`. Unless the crash triggers inside OpenVR, the debug allocator should be able to detect a double free and get you a usable stacktrace.

**Comment by Zamundaaa** [comment]
Thanks.
Problem is now that I can't get my app to run now... It throws an IllegalStateException.
> Exception in thread "main" java.lang.IllegalStateException: The memory address specified is not being tracked: 0x7FD765E831E0
	at org.lwjgl.system.MemoryManage$DebugAllocator.untrack(MemoryManage.java:259)
	at org.lwjgl.system.MemoryManage$DebugAllocator.free(MemoryManage.java:220)
	at org.lwjgl.system.MemoryUtil.nmemFree(MemoryUtil.java:336)
	at org.lwjgl.system.Struct.free(Struct.java:57)
	at org.lwjgl.system.NativeResource.close(NativeResource.java:20)
	at vr.actions.VRAction_Pose.cleanUp(VRAction_Pose.java:68)
	at vr.VRController.reloadActions(VRController.java:351)
        ...

The native resource that's closed here is a InputPoseActionData that got created with InputPoseActionData.create(), so with BufferUtils. I made sure that this resource can only be closed once (I set it to null after closing) but the error persists. Is one simply not supposed to close it at all?

**Comment by kenzierocks** [comment]
Correct, LWJGL memory is not supposed to be explicitly freed if you use `create()`. If you wish to manage that memory directly, use `malloc` or `calloc` (depending on your use case, `calloc` is more analogous to `create`), otherwise GC will clean it up for you.

**Comment by Zamundaaa** [comment]
Does LWJGL also throw an exception if I don't enable debugging? Because if not then that explains my issue. I explicitly free()d something that the GC then later tried to free as well, a second time. That also explains the random timing of the problem.

**Comment by Zamundaaa** [comment]
Great! Thanks you for your help!
