### ISSUE TITLE
How to actively trigger the key of the gamepad #24

### ISSUE THREAD

**Issue by chensiweipsp** [LWJGL/lwjgl3#506]
I don't need to listen to the user's operational behavior
, I just want to actively trigger the buttons in the game handle through the program.
How to do it
??

**Comment by XenoAmess** [comment]
@chensiweipsp lwjgl have glfw binding so you can use it. 
But as for gamepad I suggest you using Jamepad.
GLFW's gamepad lib is just...awful.

**Comment by chensiweipsp** [comment]
> @chensiweipsp lwjgl有glfw绑定，所以你可以使用它。
> 但至于游戏手柄，我建议你使用[Jamepad](https://github.com/williamahartman/Jamepad)。
> GLFW的游戏手柄只是......太糟糕了。

Thank you very much for your reply. I only found that jamepad can listener the operation of the user's game handle. But I haven't found that jamepad can actively trigger the button of the game handle.

**Comment by XenoAmess** [comment]
@chensiweipsp you can add a detect for every keys in the main loop of your engine.
once a button press is detected then you can create an event into your event system.
I know glfw have several function called setxxxcallback to setup a CallbackI into it and trigger it but I don't know if there be such function to deal with gamepad.
If you really want to use glfw's gamepad lib then you should go to there site for documents first.

**Comment by chensiweipsp** [comment]
@XenoAmess  Thank you for your answer. Let me try.
