### ISSUE TITLE
GLFW/GLES cant create window with GLES30 support on Raspberry PI4 with Mesa 19.2.0-rc1

### ISSUE THREAD

**Issue by rsahlin** [LWJGL/lwjgl3#512]
* LWJGL version: `3.2.3` 
* LWJGL build #: `SNAPSHOT Build 13`
* Java version: `openjdk 11.0.3 2019-04-16`
OpenJDK Runtime Environment (build 11.0.3+7-post-Raspbian-5)
* Platform: `Linux` (Raspberry PI 4 with Mesa 19.2.0-rc1)
* Module: `GLFW|GLES`

Running a program using GLFW / GLES and fetching GLCapabilites from GLES will only show support for GLES20 and not GLES30 as expected.
Below is a snippet that will reproduce the error.

 
    if (!GLFW.glfwInit()) {
        throw new IllegalStateException("Unable to initialize glfw");
    }
    GLFW.glfwDefaultWindowHints();
    GLFW.glfwWindowHint(GLFW.GLFW_VISIBLE, GLFW.GLFW_FALSE);
    GLFW.glfwWindowHint(GLFW.GLFW_RESIZABLE, GLFW.GLFW_TRUE);
    GLFW.glfwWindowHint(GLFW.GLFW_SAMPLES, 4);
    window = GLFW.glfwCreateWindow(width , height, "", MemoryUtil.NULL, MemoryUtil.NULL);
    if (window == MemoryUtil.NULL) {
        throw new RuntimeException("Failed to create the GLFW window");
    }
    GLFW.glfwMakeContextCurrent(window);
    org.lwjgl.system.Configuration.OPENGLES_EXPLICIT_INIT.set(true);
    GLES.create(GL.getFunctionProvider());
    GLESCapabilities caps = GLES.createCapabilities();

The created caps will only have caps.GLES20 set to true - although the Mesa driver clearly reports GLES 3.0.

Update
Requesting hard version of:

    GLFW.glfwWindowHint(GLFW.GLFW_CONTEXT_VERSION_MAJOR, 3);
    GLFW.glfwWindowHint(GLFW.GLFW_CONTEXT_VERSION_MINOR, 0);

Results in:
[LWJGL] GLFW_VERSION_UNAVAILABLE error
Description : GLX: Failed to create context: GLXBadFBConfig

**Comment by intrigus** [comment]
Why do you think that the caps should support GLES 3.0?
You never create a GLES 3.0 context using glfw.
Have a look at this https://www.glfw.org/docs/latest/window_guide.html#window_hints_ctx and try to set the necessary hints.

**Comment by rsahlin** [comment]
Why I think that the caps should support GLES 3.0?
- Because the underlying hardware and Mesa driver supports it.
- Because running the same code on Windows returns GLCapabilities that support GLES up to 3.2 both on Nvidia and AMD hw/drivers.
- If I don't create the GLES 3.0 context with glfw - then how do I get one?
I don't understand could you please elaborate?

I'm not sure what section of the docs you are referring to, but this is one of the sections I looked at:

_While there is no way to ask the driver for a context of the highest supported version, GLFW will attempt to provide this when you ask for a version 1.0 context, which is the default for these hints._

_OpenGL ES: These hints are not hard constraints, but creation will fail if the OpenGL ES version of the created context is less than the one requested. Additionally, OpenGL ES 1.x cannot be returned if 2.0 or later was requested, and vice versa. This is because OpenGL ES 3.x is backward compatible with 2.0, but OpenGL ES 2.0 is not backward compatible with 1.x._

This is why I do not request a hard version, but instead use the default to get the highest supported version.

Could you please clarify what hint you are referring to?

**Comment by Spasi** [comment]
When you do not specify a context version, the driver is free to make that choice for you. Many drivers will return the maximum supported version, but this is in no way specified or required. Try setting `GLFW_CONTEXT_VERSION_MAJOR` and `GLFW_CONTEXT_VERSION_MINOR` explicitly.

**Comment by rsahlin** [comment]
I guess I should  rename the issue since it is not only the reporting of the gles version to GLCapabilities that does not work.
Adding the following 2 lines before glfwCreateWindow:

    GLFW.glfwWindowHint(GLFW.GLFW_CONTEXT_VERSION_MAJOR, 3);
    GLFW.glfwWindowHint(GLFW.GLFW_CONTEXT_VERSION_MINOR, 0);

Results in failure to create window:

[LWJGL] GLFW_VERSION_UNAVAILABLE error
	Description : GLX: Failed to create context: GLXBadFBConfig
	Stacktrace  :
		org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714)
		org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897)

**Comment by rsahlin** [comment]
It seems that a workaround is to just ignore the boolean values of GLCapabilities.GLES3X.

Although GLFW is unable to create GLES with a hard version higher than 2.0 when using default values the resulting GLES compiles GLSL #version 300 es without any problem.

It seems to me that it's a bug when the GLESXX bolean fields are se in the GLCapabilites.

**Comment by Spasi** [comment]
> It seems to me that it's a bug when the GLESXX bolean fields are se in the GLCapabilites.

The above `GLFW_VERSION_UNAVAILABLE error` you're seeing has nothing to do with `GLESCapabilities` or LWJGL itself. It is an error reported by GLFW.

Try running your program with `-Dorg.lwjgl.util.Debug=true -Dorg.lwjgl.util.DebugLoader=true -Dorg.lwjgl.util.DebugFunctions=true" and paste the output here.

**Comment by rsahlin** [comment]
Thanks for your reply @Spasi 
I have abandoned my GL based project in favor of Vulkan. This is no longer an issue for me.
