### ISSUE TITLE
How does LWJGL generate Javadoc for Vulkan bindings?

### ISSUE THREAD

**Issue by YaaZ** [LWJGL/lwjgl3#515]
LWJGL has such a cool (auto-generated from specs I guess) javadoc for Vulkan, which I miss very much when I have to work with Vulkan in C++
So I think it would be cool to bring there some doxygen-style documentation and would love to know, where can I find classes, related to javadoc generation/few words about how does it work in general. Thanks!

**Comment by Spasi** [comment]
Hey @YaaZ,

There is a separate repository, [lwjgl3-vulkangen](https://github.com/LWJGL/lwjgl3-vulkangen), that parses the Vulkan specification/documentation/registry from [Vulkan-Docs](https://github.com/KhronosGroup/Vulkan-Docs) and generates the Kotlin templates that lwjgl3 uses for its code generation.

The templates contain a Kotlin DSL that you'll probably find weird. It's not been designed to be particularly beautiful/enjoyable, just something that is somewhat type-safe and usable inside IntelliJ IDEA. Example: [KHR_surface.kt](https://github.com/LWJGL/lwjgl3/blob/master/modules/lwjgl/vulkan/src/templates/kotlin/vulkan/templates/KHR_surface.kt). Modifying lwjgl3-vulkangen to output what you need would definitely be easier than modifying the lwjgl3 generator.

**Comment by YaaZ** [comment]
Thank you, @Spasi ! I will take a look at vulkangen repository
