### ISSUE TITLE
Status of DriftFX integration

### ISSUE THREAD

**Issue by mipastgt** [LWJGL/lwjgl3#522]
Hi,

I just tried how far I could get with the new DriftFX integration using the nightly build via Maven on my MacBook Pro Retina macOS 10.14.6. As an example I used the application HelloDriftFX from the demos.

I first tried it with OpenJDK 11 and OpenJFX 13.0.1. That compiled but failed at run-time. I then tried it with Oracle JDK 8 (built-in JavaFX) and the example worked, giving me roughly 3000 FPS on my old MacBook (from 2012) but Java crashes unexpectedly each time when I try to terminate the application via ESC.

To my knowledge OpenJDK 11 cannot work because you would have to build DriftFX from the specific Java 11 branch, which seems to be a little bit outdated too. Do you have any plans to support OpenJDK 11?

The crash when terminating on Java 8 is not nice. Is this a known bug or can anything be done against it? The line `libc++abi.dylib: Pure virtual function called!` is in red, so I assume it is an error.

```
GLContext name: drift-3/surface1-4
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: NVIDIA GeForce GT 650M OpenGL Engine
GL_VERSION: 4.1 NVIDIA-12.0.24 355.11.10.50.10.103
1800 fps
3273 fps
2682 fps
3037 fps
3310 fps
3245 fps
3225 fps
3051 fps
3062 fps
2772 fps
2926 fps
3138 fps
3106 fps
2905 fps
2402 fps
libc++abi.dylib: Pure virtual function called!
[C] [ INFO] TransferModeManager.cpp: 87 - RegisterTransferMode Registering TransferMode Instance 'IOSurface' as 0
[C] [ INFO] TransferModeManager.cpp: 87 - RegisterTransferMode Registering TransferMode Instance 'MainMemory' as 1
[C] [ INFO] TransferModeManager.cpp: 87 - RegisterTransferMode Registering TransferMode Instance 'NoOp' as 2
[C] [ INFO] Configuration.cpp: 59 - Initialize Loaded native driftfx configuration:
[C] [ INFO] Configuration.cpp: 60 - Initialize debug = 0
[C] [ INFO] Configuration.cpp: 61 - Initialize logLevel = 1
[C] [ INFO] Configuration.cpp: 62 - Initialize useWinFallback = 0
```

**Comment by Spasi** [comment]
Hey @mipastgt,

I've made a comment about the current status of the DriftFX bindings [here](https://github.com/LWJGL/lwjgl3/issues/101#issuecomment-569344734). Indeed, only JavaFX 8 is supported and there are obvious stability/performance issues. These issues must be resolved upstream, so please report your findings to [efxclipse-drift](https://github.com/eclipse-efx/efxclipse-drift).

**Comment by mipastgt** [comment]
I did that. See https://github.com/eclipse-efx/efxclipse-drift/issues/17

**Comment by Spasi** [comment]
DriftFX has been updated in LWJGL and now supports JavaFX 11 (as well as JavaFX 8, via the multi-release JAR functionality). However, the current implementation is still slow, outputs random stuff on stdout and crashes for me on OpenJFX 11.

I'm now waiting for the 2.x version mentioned in the above issue.

**Comment by soarteam** [comment]
Hope to support Java15
