### ISSUE TITLE
OpenAL.dll doesn't load in the latest snapshot

### ISSUE THREAD

**Issue by Alex-----** [LWJGL/lwjgl3#523]
### Environment

* LWJGL version: `3.2.4` 
* LWJGL build #: `SNAPSHOT build 4`
* Java version: `13`
* Platform: `Windows`
* Module: `OpenAL`

I built lwjgl locally with my bullet changes rebased on top of the latest commit, but OpenAL.dll is downloaded anyway so I'm not sure if that makes a difference.

### Description

Initializing the class ALC throws this error in the latest snapshot:

[LWJGL] Loading library: OpenAL
[LWJGL] 	Module: org.lwjgl.openal
java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.openal.ALC
	at org.lwjgl.openal/org.lwjgl.openal.ALC10.nalcGetString(ALC10.java:426)

I stepped through the class initialization and found that it throws an UnsatisfiedLinkError in org.lwjgl.system.windows.WindowsLibrary.loadLibrary(String name) with the message 
Failed to load library: C:\Users\Alex\Desktop\projects\lwjgl3\bin\libs\native\windows\x64\org\lwjgl\openal\OpenAL.dll (error code = 126)

If I replace the dll with a previous version then it works.

**Comment by Alex-----** [comment]
I tried on my other pc (also windows) and its working there, Just not on my laptop.

**Comment by Alex-----** [comment]
Using process monitor it looks like its trying to load VCRUNTIME140_1.dll after loading OpenAL.dll which is not found on my laptop.

**Comment by Spasi** [comment]
It seems that OpenAL-Soft's CMake configuration for the static MSVC runtime is broken since the migration from C to C++. OpenAL.dll will not have external dependencies in the next 3.2.4 snapshot.

Thank you @Alex-----!
