### ISSUE TITLE
usage about steamworks4j in lwjgl?

### ISSUE THREAD

**Issue by XenoAmess** [LWJGL/lwjgl3#529]
I checked your pom on lwjgl.org again today.
and there be 2 things confusing me.

1. if I chose [everything] in your pom generator, the pom I get will include lwjgl-ovr, thus fall build progress on travis-ci(in a linux machine).
[https://travis-ci.org/cyanpotion/cyan_potion/builds/644707517](travis-ci fail report)

should we fix it? at least, we can create an ampty ovr-linux-native or something, atleast we must make it can build, right?

2.how and where did we use steamworks4j in lwjgl?
I know this might be a boring question but I really cannot find anywhere you use steamworks4j in lwjgl.
Neither don't I know why we generate it in the lwjgl.org's page.
Although usually most developers DO need steamworks4j (who can ignore steam, after all?), I still think they shall add it into their pom by themself, because it is their game that use steamworks4j, not lwjgl use steamworks4j.
And I think that be better if they go maven or github and getting the steamworks4j they need by themselfs.

**Comment by httpdigest** [comment]
steamworks4j is listed under "Addons", which provides convenience for developers to add useful third-party libraries (not maintained by the LWJGL project itself) to the pom/gradle/zip if they want to use it. All addons are disabled/excluded by default, even if you select the "Everything" preset under "Presets". So you would not accidentally include it if you are not selecting it explicitly when you want it.

**Comment by Spasi** [comment]
Hey @XenoAmess,

> if I chose [everything] in your pom generator, the pom I get will include lwjgl-ovr

Actually, the bindings selected depend on the platforms/architectures you choose under `Natives`. If you uncheck the two Windows options, you'll find that the OVR bindings are not selected (disabled actually), even with the `Everything` preset.

This may not be very intuitive, but we've tried to take care of such details when possible. However, the generated script is meant to be a simple convenience. It should be correct in the majority of cases, but users should review it before copying it into their build script. The `Everything` preset in particular is almost always a bad idea, no application is going to need all bindings. It's there for testing if all artifacts have been deployed properly.

**Comment by XenoAmess** [comment]
got it,thx.
