### ISSUE TITLE
Taskbar Icon Support

### ISSUE THREAD

**Issue by adoxian** [LWJGL/lwjgl3#53]
As far as I have seen, there is no feature in LWJGL 3 for setting taskbar icons in Windows for an application (previously accomplished through Display.setIcons(ByteBuffer[])).

**Comment by sriharshachilakapati** [comment]
@adoxian 

LWJGL3 just wraps the GLFW library for windowing, and it is not supported to set the icon at runtime with GLFW. However, this is planned with the next release of GLFW. For more information, see these issues in the GLFW Repository.

https://github.com/glfw/glfw/issues/453
https://github.com/glfw/glfw/pull/467

According to the comments in the above mentioned pull-request, it is known that the feature is implemented in Windows and X11, but no Cocoa support till now. I think it is going to be introduced with GLFW 3.2 release. I'm also hoping to see it as early as possible.

**Comment by adoxian** [comment]
Thanks for the reply. I'm hoping so as well.
