### ISSUE TITLE
GLFW callbacks not invoking

### ISSUE THREAD

**Issue by nbilyk** [LWJGL/lwjgl3#530]
### Environment

* LWJGL version: `3.2.3`, `3.2.2`
* LWJGL build #: `13`
* Java version: `11.0.2`, `10`, `11.0.3`, `1.8`
* Platform: `Windows 10`
* Module: `glfw`

### Description

GLFW callbacks are sometimes not invoked (around 5% of launches).  The window, gl context, and frame buffers all create normally, but the callbacks such as event handling, window resizing, window closing, etc aren't being invoked.

This is reproducible with the hello world from the guide (https://www.lwjgl.org/guide)
Rapidly relaunch the hello world application, closing via clicking the close button. The window will always close but on some launches the close button will not invoke the close handler, and therefore the process will remain active. 
It doesn't matter if you're launching from Gradle, IDEA, or a fat jar.

I have not yet tried on other operating systems.

[lwjgl3hello.zip](https://github.com/LWJGL/lwjgl3/files/4167351/lwjgl3hello.zip)

**Comment by octylFractal** [comment]
I don't see a close callback in the source code, only a `glfwSetKeyCallback` and a `GLFWErrorCallback.createPrint`. I wouldn't expect either of those to be called. What part are you referring to?

**Comment by nbilyk** [comment]
Ah, you're right, I've probably mislabeled the issue. 
When clicking the close button, the close callback (if there was one, but you're right, not in the hello world example) is never called, and glfwWindowShouldClose(window) never returns true and therefore the application never closes. 
The window closes, but the process never terminates. 
And again, this happens about 5% of the time

**Comment by nbilyk** [comment]
@octylFractal were you able to reproduce it?

**Comment by octylFractal** [comment]
I'm on Arch Linux, so I didn't attempt to reproduce it. Nevertheless, I tried just now, and I can't. Might be a Windows-only bug, and probably in GLFW itself. I would try out a GLFW example to see if it has the same issue for you.

**Comment by nbilyk** [comment]
I can try on other platforms, I'm pretty sure this didn't happen in lwjgl 2.9.+ It seems to happen less often when running from a standalone jar than running via class files in the IDE so I suspect it's possibly a race condition.

**Comment by octylFractal** [comment]
Not happening in LWJGL 2 isn't surprising considering it used a completely different window library.
