### ISSUE TITLE
I want to play a video in my game but I don't know how to get started.

### ISSUE THREAD

**Issue by XenoAmess** [LWJGL/lwjgl3#531]
IMO I neede to : 1.decode the videos into frames. 2.let opengl renew texture about the frames, and draw it.
Now I think I know how to do 2. but I wanna ask, if there already be some video decoding bindings in lwjgl? or I shall go find something like ffmpeg by myself?
Or if there already be a better solution in lwjgl3?

**Comment by Spasi** [comment]
Hey @XenoAmess,

There are 3rd-party bindings that you could use (e.g. for ffmpeg or libvlc). There haven't been many requests for video playback support in LWJGL, but my plan is to add [AV1](https://aomedia.org/) bindings eventually.

**Comment by XenoAmess** [comment]
got it, thx.
