### ISSUE TITLE
Problem using stb_tt (segfault)

### ISSUE THREAD

**Issue by edwinRNDR** [LWJGL/lwjgl3#535]
* LWJGL version: `3.2.3`, `3.2.4-SNAPSHOT`
* Java version: `11`, `14`
* Platform: `macOS|Windows`
* Module: `stb`

### Description

I am loading and rasterizing an amount of fonts but run into segfaults after processing +/- 10 fonts. The segfaults appear whenever I create largish containers inside the function that uses stbtt to load and rasterize. 

I have tried running adding `-Dorg.lwjgl.util.Debug=true` and `-Dorg.lwjgl.system.allocator=system` but segfaults persist and there are no additional debug messages of relevance.

Further error reports look like this:
```
---------------  S U M M A R Y ------------

Command Line: -Dorg.lwjgl.util.Debug=true -javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=49251:/Applications/IntelliJ IDEA CE.app/Contents/bin -Dfile.encoding=UTF-8 BugIsolationKt

Host: iMac14,2 x86_64 3500 MHz, 8 cores, 16G, Darwin 18.7.0
Time: Tue Feb 25 12:06:10 2020 CET elapsed time: 3 seconds (0d 0h 0m 3s)

---------------  T H R E A D  ---------------

Current thread (0x00007faf6b000000):  JavaThread "main" [_thread_in_native, id=8707, stack(0x000070000d726000,0x000070000d826000)]

Stack: [0x000070000d726000,0x000070000d826000],  sp=0x000070000d825868,  free space=1022k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [liblwjgl_stb.dylib+0x39da4]
[error occurred during error reporting (printing native stack), id 0xe0000000, Internal Error (/scratch/mesos/slaves/fcf4c0c4-d73e-4321-860c-6613427db92b-S1400/frameworks/1735e8a2-a1db-478c-8104-60c8b0af87dd-0196/executors/daacdadf-a1b9-40bc-9978-e61e217c02bb/runs/8ae9fce2-2d0e-4b1f-b6c6-d913bc747292/workspace/open/src/hotspot/os/bsd/decoder_machO.hpp:43)]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 633  org.lwjgl.stb.STBTruetype.nstbtt_FindGlyphIndex(JI)I (0 bytes) @ 0x000000011c6bcdf4 [0x000000011c6bcda0+0x0000000000000054]
J 717 c2 org.lwjgl.stb.STBTruetype.stbtt_FindGlyphIndex(Lorg/lwjgl/stb/STBTTFontinfo;I)I (9 bytes) @ 0x000000011c6cf938 [0x000000011c6cf920+0x0000000000000018]
J 632% c2 BugIsolationKt.main()V (1290 bytes) @ 0x000000011c6c6cec [0x000000011c6c66c0+0x000000000000062c]
j  BugIsolationKt.main([Ljava/lang/String;)V+0
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x000000012b37d16c
```
I have added a small program that demonstrates the problem:
[BugIsolation.kt.zip](https://github.com/LWJGL/lwjgl3/files/4249596/BugIsolation.kt.zip)

**Comment by Spasi** [comment]
You need to ensure that the `ByteBuffer` passed to `stbtt_InitFont` is not garbage collected (or not freed when using explicit memory management APIs) while the font is in active use. This is a common mistake when dealing with stb_truetype. Read [this](http://forum.lwjgl.org/index.php?topic=6917.msg36395#msg36395) post for more info.

**Comment by edwinRNDR** [comment]
@Spasi a-ha! that does seem to fit just right in with the behavior I encounter. Will rework the code to prevent the bytebuffer from being freed, thank you so much!

**Comment by edwinRNDR** [comment]
That fixes it!
