### ISSUE TITLE
Null Pointer Exception When Binding Framebuffer to '0' (the window)

### ISSUE THREAD

**Issue by neon64** [LWJGL/lwjgl3#54]
Hello, I'm porting my LWJGL 2 game to version 3 and I've came across this annoying issue.

Calling `glBindFramebuffer(GL_FRAMEBUFFER, 0);` will cause a null pointer exception like so:

	Exception in thread "main" java.lang.NullPointerException
	at org.lwjgl.opengl.GL30.glBindFramebuffer(GL30.java:2308)
	at test.TestFail.loop(TestFail.java:98)
	at test.TestFail.run(TestFail.java:29)
	at test.TestFail.main(TestFail.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

It's reproducible with the following test code copied and pasted from the getting started guide. (save for the one call to `glBindFramebuffer`):

    package test;
    
    import org.lwjgl.Sys;
    import org.lwjgl.glfw.*;
    import org.lwjgl.opengl.*;
     
    import java.nio.ByteBuffer;
     
    import static org.lwjgl.glfw.Callbacks.*;
    import static org.lwjgl.glfw.GLFW.*;
    import static org.lwjgl.opengl.GL11.*;
    import static org.lwjgl.opengl.GL30.*;
    import static org.lwjgl.system.MemoryUtil.*;
    
    public class TestFail {
         
                    // We need to strongly reference callback instances.
                    private GLFWErrorCallback errorCallback;
            private GLFWKeyCallback   keyCallback;
         
                    // The window handle
                    private long window;
         
                    public void run() {
                    System.out.println("Hello LWJGL " + Sys.getVersion() + "!");
             
                    try {
                            init();
                            loop();
                 
                            // Release window and window callbacks
                            glfwDestroyWindow(window);
                            keyCallback.release();
                        } finally {
                            // Terminate GLFW and release the GLFWerrorfun
                            glfwTerminate();
                            errorCallback.release();
                        }
                }
         
                    private void init() {
                    // Setup an error callback. The default implementation
                    // will print the error message in System.err.
                    glfwSetErrorCallback(errorCallback = errorCallbackPrint(System.err));
             
                    // Initialize GLFW. Most GLFW functions will not work before doing this.
                    if ( glfwInit() != GL11.GL_TRUE )
                        throw new IllegalStateException("Unable to initialize GLFW");
             
                    // Configure our window
                    glfwDefaultWindowHints(); // optional, the current window hints are already the default
                    glfwWindowHint(GLFW_VISIBLE, GL_FALSE); // the window will stay hidden after creation
                    glfwWindowHint(GLFW_RESIZABLE, GL_TRUE); // the window will be resizable
             
                    int WIDTH = 300;
                    int HEIGHT = 300;
             
                    // Create the window
                    window = glfwCreateWindow(WIDTH, HEIGHT, "Hello World!", NULL, NULL);
                    if ( window == NULL )
                        throw new RuntimeException("Failed to create the GLFW window");
             
                    // Setup a key callback. It will be called every time a key is pressed, repeated or released.
                    glfwSetKeyCallback(window, keyCallback = new GLFWKeyCallback() {
                            @Override
                            public void invoke(long window, int key, int scancode, int action, int mods) {
                                    if ( key == GLFW_KEY_ESCAPE && action == GLFW_RELEASE )
                                        glfwSetWindowShouldClose(window, GL_TRUE); // We will detect this in our rendering loop
                                }
                        });
             
                    // Get the resolution of the primary monitor
                    ByteBuffer vidmode = glfwGetVideoMode(glfwGetPrimaryMonitor());
                    // Center our window
                    glfwSetWindowPos(
                                window,
                                (GLFWvidmode.width(vidmode) - WIDTH) / 2,
                        (GLFWvidmode.height(vidmode) - HEIGHT) / 2
                    );
             
                    // Make the OpenGL context current
                    glfwMakeContextCurrent(window);
                    // Enable v-sync
                    glfwSwapInterval(1);
             
                    // Make the window visible
                    glfwShowWindow(window);
                }
         
                    private void loop() {
                    // This line is critical for LWJGL's interoperation with GLFW's
                    // OpenGL context, or any context that is managed externally.
                    // LWJGL detects the context that is current in the current thread,
                    // creates the ContextCapabilities instance and makes the OpenGL
            // bindings available for use.
            GLContext.createFromCurrent();
    
**glBindFramebuffer(GL_FRAMEBUFFER, 0);**
    
                    // Set the clear color
                    glClearColor(1.0f, 0.0f, 0.0f, 0.0f);
             
                    // Run the rendering loop until the user has attempted to close
                    // the window or has pressed the ESCAPE key.
                    while ( glfwWindowShouldClose(window) == GL_FALSE ) {
                            glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT); // clear the framebuffer
                 
                            glfwSwapBuffers(window); // swap the color buffers
                 
                            // Poll for window events. The key callback above will only be
                            // invoked during this call.
                            glfwPollEvents();
                        }
                }
         
                    public static void main(String[] args) {
                    new TestFail().run();
                }
         
    }

Thanks very much if you can help, or let me know if this is already a recognised issue.

**Comment by Spasi** [comment]
Have you checked if the context supports OpenGL 3.0? Note that if you're on OS X, you need to explicitly ask for a 3.2+ forward compatible context (see the `glfwWindowHint` documentation or [this](http://www.glfw.org/faq.html#how-do-i-create-an-opengl-30-context) on how to do that).

**Comment by neon64** [comment]
Yes I just realised I needed to do that :)
After asking for a 3,2 context with core profile etc it works fine.
Perhaps it could help to have a bit better error message though?

**Comment by Spasi** [comment]
Yes, good point.
