### ISSUE TITLE
How will implemented `VK_KHR_ray_tracing` in bindings?

### ISSUE THREAD

**Issue by helixd-2k18** [LWJGL/lwjgl3#541]
### Environment

* LWJGL version: `21.01.2020` 
* LWJGL build #: `3.2.4`
* Java version: `13.0.2`
* Platform: `Windows`
* Module: `vulkan`

### Description

I want ask some questions about `VK_KHR_ray_tracing` implementation. How it will implemented in general? How will implemented `VkDeviceOrHostAddressKHR` and `VkDeviceOrHostAddressConstKHR` unions? Will or not confusions with `long` types? Bit same issues may have with `VK_KHR_buffer_device_address` extension.

**Comment by Yugen42** [comment]
Well, according to http://forum.lwjgl.org/index.php?topic=7030.0 it should be in the latest snapshot at least, however I can't find any reference to VkPhysicalDeviceRayTracingFeaturesKHR so I'd guess it's not yet supported in general.

**Comment by helixd-2k18** [comment]
Too late...

**Comment by Spasi** [comment]
LWJGL 3.3.0 snapshot 8 is now available and includes Vulkan 1.2.172 with all extensions, including the KHR ray tracing extensions.

There is nothing special about types like `VkDeviceOrHostAddressKHR`, they're simple C unions and have been implemented accordingly.
