### ISSUE TITLE
opus module bug in version 3.2.3

### ISSUE THREAD

**Issue by Hossam-FQY** [LWJGL/lwjgl3#543]
### Environment

* LWJGL version: latest 
* LWJGL build #: latest
* Java version: 8
* Platform: `Linux|macOS|Windows`
* Module: `opus`

### Description
When calling function "Opus.opus_encoder_create" the following error appears 
"symbol lookup error: /libopus.so: undefined symbol: __wrap_memcpy"

**Comment by DarkWeird** [comment]
Environment:
    * LWJGL version: latest
    * LWJGL build #: latest
    * Java version: 8|11(librica)
    * Platform: Linux
    * Module: glfw_wayland

Catch same problem for `libglfw_wayland`:
symbol lookup error: .../libglfw_wayland.so: undefined symbol: __wrap_memcpy

**Comment by Spasi** [comment]
Thanks! This should be fixed in `LWJGL 3.2.4 build 6`.
