### ISSUE TITLE
Assimp | aiProcess_GlobalScale flag does not work on loading collada files

### ISSUE THREAD

**Issue by barisdoga2** [LWJGL/lwjgl3#549]
LWJGL version: 3.2.3
Java version: 1.8
Platform: Windows
Module: Assimp (Latest 04/12/2020)

While loading 3D collada models global scale of object does not applied on vertices. It is accomplished by aiProcess_GlobalScale flag passed to aiImportFile function.

Maybe Related With; https://github.com/assimp/assimp/issues/1836

**Comment by Spasi** [comment]
Hey @barisdoga2, could you please try the latest `3.3.0` snapshot and see if it works now?

**Comment by SWinxy** [comment]
@barisdoga2, is this an issue you'd like to be kept open?
