### ISSUE TITLE
Function postfixes

### ISSUE THREAD

**Issue by dustContributor** [LWJGL/lwjgl3#55]
Eh, I think this should be discussed with users here too:

http://forum.lwjgl.org/index.php?topic=5746.0

Personally I'm not entirely sold on the "No postfixes confuses users!" side of this. Then again, these days I'm using less and less typed calls, usually its more of fill a byte buffer and send it over the bus. So it wouldn't affect me too much, I dunno about other users.

**Comment by Spasi** [comment]
LWJGL 3.0a has been released without postfix stripping and there were no complains.
