### ISSUE TITLE
Import BGFX API 106

### ISSUE THREAD

**Issue by mcslee** [LWJGL/lwjgl3#555]
The BGFX API has been updated to restore the presence of "bgfx_reset_view" in the API.
https://github.com/bkaradzic/bgfx/commit/f2e79bbe41d8a069db04979ff91ed15c3343ea8d

Can this be imported into the next release of LWJGL3? The method disappeared when an earlier BGFX API change was imported, to API 99:
https://github.com/LWJGL/lwjgl3/commit/611047611c3c167129848c59f89dfd7ca2831e5f

I'm not familiar with the process to update BGFX API, figure I would cause more trouble trying to make a PR than just requesting this get incorporated. Thanks!

**Comment by mcslee** [comment]
Super quick, thank you - much appreciated!

**Comment by mcslee** [comment]
Was just curious - are there plans for an official release of LWJGL3 anytime soon? This is not an urgent need, I am fine using the nightly builds or the changes via GitHub, but seems a safer practice for shipping software to use an official release.

Just noticed it had been over a year since the last official release, so I was curious if there are any plans. Thanks!

**Comment by Spasi** [comment]
Yes, 3.2.4 will be released soon. Binding updates are currently on hold, while I'm migrating our CI infrastructure from Travis CI to Github Actions.
