### ISSUE TITLE
libopus.so: undefined symbol: __wrap_memcpy

### ISSUE THREAD

**Issue by jobfeikens** [LWJGL/lwjgl3#557]
### Environment

* LWJGL version: `3.2.3` 
* LWJGL build #: `13`
* Java version: `1.8.0_242 amd64`
* Platform: `Linux (Debian 10)`
* Module: `Opus binding`

### Description

Got the following error while using the opus binding (during the opus_encode() method):

```/usr/lib/jvm/adoptopenjdk-8-hotspot-amd64/bin/java: symbol lookup error: /tmp/lwjgljob/3.2.3-build-13/libopus.so: undefined symbol: __wrap_memcpy```

### Minimal code example

[Min.txt](https://github.com/LWJGL/lwjgl3/files/4635101/Min.txt)

**Comment by jobfeikens** [comment]
Possibly the same issue as #543

**Comment by Spasi** [comment]
Thanks! This should be fixed in `LWJGL 3.2.4 build 6`.
