### ISSUE TITLE
Assimp loading embedded textures.

### ISSUE THREAD

**Issue by mcmacker4** [LWJGL/lwjgl3#558]
### Environment

* LWJGL version: `3.2.3` 
* LWJGL build #: `?`
* Java version: `11`
* Platform: `Windows`
* Module: `assimp`

### Description

Some 3D model formats (namely gltf's binary format: glb) have embedded textures and Assimp supports these textures.
As described in the [Textures section in their documentation](https://assimp-docs.readthedocs.io/en/latest/usage/use_the_lib.html#textures), to load an embedded texture you call `aiScene::GetEmbeddedTexture` and it returns an `aiTexture`. This struct contains the width, height, filename of the texture, and a pointer to the data.

In LWJGL that method is missing (as are the rest of methods in C++ Assimp's `aiScene`) but that's not that big of a problem given that this method is an easy implementation.

The real problem comes with reading the embedded texture:

The `aiTexture::pcData` pointer can be two things depending on the value of `aiTexture::height`. It can be a list of `aiTexel`s if the height is `>0`, or it can be a buffer of length `aiTexture::width` bytes that contains file-like data (like a png, or jpeg).

In LWJGL only the first of these options is possible (as far as I can tell). `AITexture.pcData()` returns an `AITexel.Buffer`, and in fact you need to give the `pcData` method a capacity (it is also not specified if that capacity is the number of bytes or the number of `AITexel`s).
So in the case of `AITexture.width()` being 0, the pointer cannot be requested as a ByteBuffer to be given to `stbi_load_from_memory()`, thus the embedded texture cannot be loaded.

We need a way of getting that buffer as a portable `ByteBuffer` of length `aiTexture::width` so we can use it in `STBImage`.

**Comment by mcmacker4** [comment]
I found a very sketchy workaround:
```kotlin
val address = aiTexture.pcData(0).address0()
val buffer = MemoryUtil.memByteBuffer(address, aiTexture.mWidth())
// Give buffer to stbi_load_from_memory
```
It works, but i don't know if that might cause issues with memory management.

**Comment by Spasi** [comment]
Thanks @mcmacker4!
