### ISSUE TITLE
Missing errcode_ret pararmeter for clLinkProgram.

### ISSUE THREAD

**Issue by kurtzmarc** [LWJGL/lwjgl3#561]
The Javadoc for LWJGL's clLinkProgram mentions a errcode_ret value for obtaining the error code when the program fails to link.

> Otherwise clLinkProgram returns a NULL program object with an appropriate error in errcode_ret.

However there is no parameter for `IntBuffer/int[] errcode_ret` in the LWJGL API call. The OpenCL specification for clLinkProgram shows that there is a parameter for obtaining the errcode but this isn't exposed in the API `clLinkProgram(..., cl_int *errcode_ret)`. A quick look through the javadoc and I also see `clCreateSubDevices` has this same issue.

**Comment by Spasi** [comment]
Duplicates #560. The fix is coming soon.
