### ISSUE TITLE
 Pixel format not accelerated

### ISSUE THREAD

**Issue by kebufu** [LWJGL/lwjgl3#562]
### Environment

* LWJGL version: `2.9.4` 
* LWJGL build #: `idk`
* Java version: `1.8`
* Platform: `Windows`
* Module: `core|binding name`

### Description

I hate windows 10.

**Comment by Sylvyrfysh** [comment]
This has no useful information. However, having this issue myself, my guess
is that your display is running in 10 or 12bpp more rather than 8bpp. If
changing that doesn't work, can you post some more info about what
caused the issue?

**Comment by Spasi** [comment]
This is not the place for LWJGL 2 support.

**Comment by XenoAmess** [comment]
@kebufu go here instead. https://github.com/LWJGL/lwjgl
