### ISSUE TITLE
usage of MemoryStack and Struct class

### ISSUE THREAD

**Issue by sadeghpro** [LWJGL/lwjgl3#563]
Hi all,
can any one give me a simple example of use MemoryStack and Struct class to map c struct with java class.
for example I have a c struct:
```
struct color {
    float r;
    float g;
    float b;
}
```
how to create a java class and send pointer of an object of it to c and get that struct in c?

**Comment by elect86** [comment]
> how to create a java class and send pointer of an object of it to c and get that struct in c?

Your code should do something else, like creating and managing the C struct on its own.

Which is your use case exactly?

**Comment by Spasi** [comment]
LWJGL does not support mapping of user-defined structs. Only structs defined in the public API of bindings are supported and those are generated offline, at build time.

However, you could inspect the code generated for structs and implement something similar for your custom types. You can make it compatible with `MemoryStack`.

This situation will probably improve when LWJGL adopts [Project Panama](https://openjdk.java.net/projects/panama/) (in LWJGL 4, with a very different API).

**Comment by sadeghpro** [comment]
tnx @Spasi 
Yes I see the `Layout` class of LWJGL is protected and I can use it. May be it's good to make it public to use it anywhere. I don't know may be there is other prerequisites but when I see `Layout` class is protected I don't use it anymore.

I see project panama and I think it's so cool but I don't find a good guide for it. Did you have a good tutorial for it's usage?
when you release LWJGL 4?
