### ISSUE TITLE
Missing javadocs for LLVM bindings

### ISSUE THREAD

**Issue by illessayano** [LWJGL/lwjgl3#564]
After looking through some of the source and recently finding out LWJGL has bindings for LLVM, I looked on the online Javadoc, at https://javadoc.lwjgl.org/, but could not find any mention on it. There are Javadoc annotations in the generated source and a downloadable Javadoc on the lwjgl.org website. Is there a reason it does not appear (licence or something) or is this a mistake?

**Comment by Spasi** [comment]
Thanks @illessayano, `javadoc.lwjgl.org` is now up-to-date.
