### ISSUE TITLE
How to use window handle of other application?

### ISSUE THREAD

**Issue by deeprobin** [LWJGL/lwjgl3#568]
I wrote a launcher for my LWJGL game in Rust. Is it possible to pass the window handle via the start arguments to draw the game into my launcher window or would I have to pass every single OpenGL function via JNI?

**Comment by httpdigest** [comment]
Please clarify what you mean by "launcher". If you mean a [JVM Invocation API client](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/invocation.html), which loads a JVM process and calls into your main class'es main(String[]) method (so essentially a replacement for the `java` executable), then you don't have to do anything, als GLFW when called inside your Java application will simply create the window.

**Comment by deeprobin** [comment]
I have written a program/launcher in Rust that uses OpenGL to open a window. This launcher starts the java.exe with the appropriate arguments. My question was if I can draw into this window from my program/launcher instead of creating a new window using LWJGL to make the transition a bit smoother?

**Comment by httpdigest** [comment]
Is there a particular reason why you create the window in another process and not inside of your Java application?
Regarding sharing window handles: There is a PR in GLFW to allow GLFW to manage external windows/contexts, but it hasn't been finished/integrated yet: https://github.com/glfw/glfw/issues/25

**Comment by deeprobin** [comment]
> 
> 
> Is there a particular reason why you create the window in another process and not inside of your Java application?
> Regarding sharing window handles: There is a PR in GLFW to allow GLFW to manage external windows/contexts, but it hasn't been finished/integrated yet: [glfw/glfw#25](https://github.com/glfw/glfw/issues/25)

The reason is that in the future I want to run not only Java programs but also other applications.

**Comment by httpdigest** [comment]
Alright, then it seems this is not a question/issue towards LWJGL but rather towards the windowing/context library used. In LWJGL's case it is GLFW, which as of now, does not have this capability. I don't know about GLUT or SDL even being able to do this.

**Comment by httpdigest** [comment]
In the end, this question boils down to: "Can an OS process A render to a window from another process B using OpenGL." And so far the answer to this seems to be "no", at least on Windows. You might want to do more research in that area. Probably first try with simply two native (i.e. Rust or C) processes and try using the window handle of process in process B and make that context/window current and draw to it and swap buffers in process B.
