### ISSUE TITLE
Status of OpenXR

### ISSUE THREAD

**Issue by knokko** [LWJGL/lwjgl3#569]
According to the final comment at https://github.com/LWJGL/lwjgl3/issues/258, LWJGL would have OpenXR bindings in the near future. I have been trying to find out how this is going, but couldn't find anything. So... how is that going?

This question may seem a bit impatient, but that's not my intention. I only ask how far you are (if you started already), I am **not** asking you to hurry up. If it isn't ready anytime soon, I will just go with OpenVR or perhaps another programming language.

**Comment by Spasi** [comment]
I will start working on the OpenXR bindings after 3.2.4 is released (which is long overdue). There will be an `lwjgl3-openxrgen` repository for automatically generating the bindings and keeping them up-to-date, just like [lwjgl3-vulkangen](https://github.com/LWJGL/lwjgl3-vulkangen).

**Comment by knokko** [comment]
Thank you for the rapid answer!

**Comment by calvertdw** [comment]
Any status update on this? :smile: Sorry, I'm pretty excited about this one.

**Comment by knokko** [comment]
Lwjgl 3.2.4 doesn't seem to be released yet, so I guess something came up in Spasi's private/work life (or it is more work than expected). But, I can only guess.

**Comment by Spasi** [comment]
The next snapshot (3.3.1 build 3) will include OpenXR bindings! I haven't done any testing though, please let me know if you face any issues.

Will post more information in #627.
