### ISSUE TITLE
How to use STBImageWrite.stbi_write_bmp?

### ISSUE THREAD

**Issue by zhouhang95** [LWJGL/lwjgl3#570]
```
byte[] pixels = new byte[640 * 360 * 3];
STBImageWrite.stbi_write_bmp("a.bmp", 640, 360, 3, ByteBuffer.wrap(pixels));
```
I try to test this funciton, it crashed!

**Comment by octylFractal** [comment]
Please read https://github.com/LWJGL/lwjgl3-wiki/wiki/1.3.-Memory-FAQ#how-do-i-allocate-and-deallocate-buffers. It's an important part of using LWJGL.

**Comment by XenoAmess** [comment]
Hi.
If you are looking for a demo or something, this might be helpful. https://github.com/cyanpotion/cyan_potion/blob/b2a52d14cad47c8c7253944a633b576d1f60cd7a/src/base/src/main/lombok/com/xenoamess/cyan_potion/base/visual/Font.java

**Comment by zhouhang95** [comment]
Thank you!

**Comment by zhouhang95** [comment]
```
glReadBuffer(GL_FRONT);
ByteBuffer pixels = memAlloc(w * h * 3);
glReadPixels(0, 0, w, h, GL_RGB, GL_BYTE, pixels);
STBImageWrite.stbi_flip_vertically_on_write(true);
STBImageWrite.stbi_write_png("a.png", w, h, 3, pixels, 0);
memFree(pixels);
```
Find a new issue, how to modify data in it?
I must use gammar correct, chang every byte in buffer.
