### ISSUE TITLE
suggestion : consider using SDL_GameControllerDB_Util

### ISSUE THREAD

**Issue by XenoAmess** [LWJGL/lwjgl3#571]
Hi.
https://github.com/cyanpotion/SDL_GameControllerDB_Util
This repo is for updating SDL_GameControllerDB.
I've been maintaining it for 1-year long, and will update it at least every month(if there be update in original SDL_GameControllerDB), so I think it be stable.
You can add a dependency for glfw module like:

```
<dependency>
    <groupId>com.xenoamess.cyan_potion</groupId>
    <artifactId>SDL_GameControllerDB_Util</artifactId>
    <version>[1.1.0,)</version>
</dependency>
```

and add function `public static boolean glfwUpdateGamepadMappings()` into your class GLFW.

Any ideas?

@Spasi

**Comment by XenoAmess** [comment]
@TheMrMilchmann 
Hi.
I see you put a confused emoji here, thus I wanna know about you confusion.
A confused feedback with no explains is confusing.

**Comment by TheMrMilchmann** [comment]
Hey,
I don't think adding such a utility to LWJGL is the right approach and out of scope for this project for a couple of reasons. In my opinion, it violates the idea of LWJGL being a lightweight library that just provides bindings for native libraries. Additionally, keeping a utility like this in a separate library looks perfectly fine to me and gives users* the choice to opt-in into using it.

Obviously I'm not the one making this decision and if Spasi decides to go ahead with this, there are a few other (less opinionated) things to keep in mind:
1. LWJGL currently does not have any library dependencies and adding a dependency on your library would require users to respect another license's terms.
2. Your library would need to fully support the Java module system (via explicit module descriptor) to keep LWJGL working with jlink.
3. When LWJGL users would want to update to more recent mappings, they would either need to roll a solution by themselves or wait until you have updated your library.

(* When I'm referring to users, I'm talking about authors of software depending on LWJGL, not end-users.)

**Comment by Spasi** [comment]
What @TheMrMilchmann said, plus I don't see why a dependency is needed to download a single file from `gabomdq/SDL_GameControllerDB` and call one function (`glfwUpdateGamepadMappings`). An application may also want to update the db at runtime, without deploying a new build.

**Comment by XenoAmess** [comment]
> I don't see why a dependency is needed to download a single file from `gabomdq/SDL_GameControllerDB`

The meaning is the download process happened when compile, but not when runtime.
And the game engine developers need not rebuild/re-release their repo for upgrade SDL_GameControllerDB.

> An application may also want to update the db at runtime, without deploying a new build.

That is bandwidth costing.
Besides github is not well connected in many places of the world. means download a single file like that can cost several seconds. Which is usually unacceptable.

> LWJGL currently does not have any library dependencies

That is a point. I'll close this issue. Maybe it is better to persuade some controller lib or game engine dev use it, instead of put it to lwjgl.

> Your library would need to fully support the Java module system

Done .(at least I think so)

> When LWJGL users would want to update to more recent mappings, they would either need to roll a solution by themselves or wait until you have updated your library.

I havn't seen such user exist, who watch SDL_GameControllerDB and upgrade everytime it upgrades.
I assume myself making upgrades fast enough.
