### ISSUE TITLE
GL_TEXTURE

### ISSUE THREAD

**Issue by theagentd** [LWJGL/lwjgl3#573]
### Environment

* LWJGL version: 3.2.1
* LWJGL build #: Not sure... 
* Java version: 13
* Platform: Windows
* Module: opengl

### Description

The enum GL_TEXTURE is an accepted parameter in glObjectLabel(), but it is not part of GL43C. 

It was originally only used glMatrixMode(), which is not available in the Core profile. However, it got "resurrected" with OpenGL 4.3 due to its use in glObjectLabel(). As such, it should be defined in GL43C.

**Comment by Spasi** [comment]
Thanks @theagentd!

`GL_TEXTURE` has been added to `GL11C`, not `GL43C`. We want the core and compatibility profiles to be source-compatible.

**Comment by theagentd** [comment]
Thanks!
