### ISSUE TITLE
[macOS] Setting the input mode to GLFW_CURSOR_NORMAL has a small delay between when the cursor shows up and when the cursor can actually be moved

### ISSUE THREAD

**Issue by Ghalid** [LWJGL/lwjgl3#576]
### Environment

* LWJGL version: `3.2.4`, also occurs in stable build `3.2.2`
* LWJGL build #: `5`
* Java version: `1.8.0_242`
* Platform: `macOS`
* Module: `GLFW`

### Description

When the input mode is set to `GLFW_CURSOR_DISABLED`, setting it to `GLFW_CURSOR_NORMAL` causes the cursor to show immediately, but it remains frozen for a small amount of time (for a little less than a second). The expected behavior is for the cursor to be immediately "moveable" once it shows up.

Steps to reproduce:
1. Hide the cursor with something like `GLFW.glfwSetInputMode(window, GLFW.GLFW_CURSOR, GLFW.GLFW_CURSOR_DISABLED);`
2. While moving the mouse (while the cursor is hidden, so you don't see any movement), turn the input mode back to `CURSOR_NORMAL`, such as by: `GLFW.glfwSetInputMode(window, GLFW.GLFW_CURSOR, GLFW.GLFW_CURSOR_NORMAL);`
Once you do, you'll notice that the cursor is still for a moment, before it moves as normal.

For a real world example of this bug, see long-standing Minecraft bug [MC-134546](https://bugs.mojang.com/browse/MC-134546). This specific bug report leads me to believe that this bug only affects macOS.

You can reproduce this issue on a Mac with the code below (press SPACE while the window is in focus to toggle the cursor's hidden/normal state):

```Java
import org.lwjgl.glfw.GLFW;
import org.lwjgl.opengl.GL;
import org.lwjgl.opengl.GL11C;

import static org.lwjgl.system.MemoryUtil.NULL;

public class MouseTest {
    long window;

    boolean cursorIsFrozen = false;

    public static void main(String[] args) {
        new MouseTest().run();
    }

    public void run() {
        createWindow();
        loop();
    }

    private void createWindow() {
        GLFW.glfwInit();
        window = GLFW.glfwCreateWindow(1000, 300, "Press space to toggle cursor frozen/unfrozen state", NULL, NULL);
        if (window == NULL) {
            throw new RuntimeException("Failed to create window");
        }

        GLFW.glfwSetKeyCallback(window, (window, key, scancode, action, mods) -> {
            if (key == GLFW.GLFW_KEY_SPACE && action == GLFW.GLFW_PRESS)
                toggleCursor();
        });

        GLFW.glfwMakeContextCurrent(window);
        GLFW.glfwShowWindow(window);
    }

    private void toggleCursor() {
        if (cursorIsFrozen) {
            GLFW.glfwSetInputMode(window, GLFW.GLFW_CURSOR, GLFW.GLFW_CURSOR_NORMAL);
            cursorIsFrozen = false;
        } else {
            GLFW.glfwSetInputMode(window, GLFW.GLFW_CURSOR, GLFW.GLFW_CURSOR_DISABLED);
            cursorIsFrozen = true;
        }
    }

    private void loop() {
        GL.createCapabilities();
        while (!(GLFW.glfwWindowShouldClose(window))) {
            GL11C.glClear(GL11C.GL_COLOR_BUFFER_BIT | GL11C.GL_DEPTH_BUFFER_BIT);
            GLFW.glfwSwapBuffers(window);
            GLFW.glfwPollEvents();
        }
    }
}
```

**Comment by Spasi** [comment]
Hey @Ghalid, thanks for reporting this issue.

I've been able to reproduce the delay and found a fix that eliminates it. I've submitted a PR to GLFW for evaluation. In the meantime, you may download a GLFW build that includes the fix here: https://build.lwjgl.org/nightly/macosx/x64/libglfw.dylib. The next LWJGL 3.3.0 snapshot will also include this build.

**Comment by Ghalid** [comment]
Sorry for the delayed response. I can confirm that the issue is fixed when forcing the latest version of Minecraft to use LWJGL 3.3.0 - thank you very much!
