### ISSUE TITLE
FATAL ERROR when GL33C.glCreateProgram been called

### ISSUE THREAD

**Issue by scaventz** [LWJGL/lwjgl3#577]
`package net.toughdays.lwjgl;

import org.lwjgl.glfw.GLFW;
import org.lwjgl.opengl.GL33C;

public class Issue {
    public static void main(String[] args) {
        new Issue().run();
    }

    public void run() {
        GLFW.glfwInit();
        GLFW.glfwWindowHint(GLFW.GLFW_CONTEXT_VERSION_MAJOR, 3);
        GLFW.glfwWindowHint(GLFW.GLFW_CONTEXT_VERSION_MINOR, 3);
        GLFW.glfwWindowHint(GLFW.GLFW_OPENGL_PROFILE, GLFW.GLFW_OPENGL_CORE_PROFILE);

        long window = GLFW.glfwCreateWindow(800, 600, "Hello OpenGL", 0, 0);
        GLFW.glfwMakeContextCurrent(window);

        int shaderProgram = GL33C.glCreateProgram();
    }
}`

the last line of my code cause the Following fatal error:

FATAL ERROR in native method: Thread[main,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL20C.glCreateProgram(Native Method)
	at net.toughdays.lwjgl.Issue.run(Issue.java:31)
	at net.toughdays.lwjgl.Issue.main(Issue.java:12)

I'm new to lwjgl3 and I'm studying modern opengl at learnopengl.com,  so I was trying to rewrite the triangle demo with lwjgl3

**Comment by httpdigest** [comment]
You have to call `GL.createCapabilities();`.
See the example code on: https://www.lwjgl.org/guide

**Comment by scaventz** [comment]
> You have to call `GL.createCapabilities();`.
> See the example code on: https://www.lwjgl.org/guide

thanks a lot
