### ISSUE TITLE
[Question] which math lib I should use in lwjgl3 to handle matrices

### ISSUE THREAD

**Issue by scaventz** [LWJGL/lwjgl3#578]
I'm new to lwjgl3, I learnd that GLM is available in c++.
but what lib should I use in lwjgl?

**Comment by lwjglgamedev** [comment]
You should use the [JOML](https://github.com/JOML-CI/JOMLurl) library. It provides vectors, matrices, quaternions, etc. It also plays nice with LWJGL.

**Comment by scaventz** [comment]
> You should use the [JOML](https://github.com/JOML-CI/JOMLurl) library. It provides vectors, matrices, quaternions, etc. It also plays nice with LWJGL.

thanks a lot
