### ISSUE TITLE
Driver quirk on Creative's OpenAL does not allow LWJGL to be used

### ISSUE THREAD

**Issue by LAGonauta** [LWJGL/lwjgl3#581]
### Environment

* LWJGL version: `3.2.2` 
* LWJGL build #: `unknown`
* Java version: `1.8.0_261 amd64`
* Platform: `Windows 10 64-bit`
* Module: `openal`

### Description

Creative's hardware OpenAL drivers do not fully meet the `OpenAL 1.1` specification when returning the `AL_VERSION` string. It returns `OpenAL version 1.1` instead of `<version>.<version><optionalText>` as required by the spec.
This causes and exception while parsing the version string:
https://github.com/LWJGL/lwjgl3/blob/330c01908605ac1b87194b36c2902d605a45e182/modules/lwjgl/openal/src/main/java/org/lwjgl/openal/AL.java#L162

OpenAL works as expected if the driver is forced to return "1.1" through a native shim.

**Comment by Spasi** [comment]
I cannot reproduce this with Creative's OpenAL implementation (https://openal.org/downloads/). Which driver do you use exactly?

**Comment by LAGonauta** [comment]
Hardware OpenAL on a Creative X-Fi Titanium running on Windows 10

**Comment by Spasi** [comment]
Thanks @LAGonauta!
