### ISSUE TITLE
Some Constants need to be added from glext.h

### ISSUE THREAD

**Issue by abinash18** [LWJGL/lwjgl3#588]
Hi, I develop mainly using lwjgl3 and wanted to port a cpp lib into java and found that some constants that are in cpp in glext.h are not supported in lwjgl3.
Here they are:
GL_RGB2_EXT
--S3TC--
GL_RGB_S3TC
GL_RGB4_S3TC
GL_RGBA_S3TC
GL_RGBA4_S3TC
GL_RGBA_DXT5_S3TC
GL_RGBA4_DXT5_S3TC
--SUN--
GL_R1UI_V3F_SUN
GL_R1UI_C4UB_V3F_SUN
GL_R1UI_C3F_V3F_SUN
GL_R1UI_N3F_V3F_SUN
GL_R1UI_C4F_N3F_V3F_SUN
GL_R1UI_T2F_V3F_SUN
GL_R1UI_T2F_N3F_V3F_SUN
GL_R1UI_T2F_C4F_N3F_V3F_SUN
--SGIX--
GL_RGB_SIGNED_SGIX
GL_RGBA_SIGNED_SGIX
GL_RGB16_SIGNED_SGIX
GL_RGBA16_SIGNED_SGIX
GL_RGB_EXTENDED_RANGE_SGIX
GL_RGBA_EXTENDED_RANGE_SGIX
GL_RGB16_EXTENDED_RANGE_SGIX
GL_RGBA16_EXTENDED_RANGE_SGIX
--3DFX--
GL_COMPRESSED_RGB_FXT1_3DFX
GL_COMPRESSED_RGBA_FXT1_3DFX
--NV--
GL_RGBA_UNSIGNED_DOT_PRODUCT_MAPPING_NV

And yes i need this on all platforms.

**Comment by Spasi** [comment]
Hey @abinash18!

> GL_RGB2_EXT

Will not add. Introduced in the `EXT_texture` extension, promoted to core in OpenGL 1.1, which is the minimum version LWJGL supports. The promotion dropped this specific texture type and the extension doesn't ship on any relevant drivers.

> --S3TC--
> GL_RGB_S3TC
> GL_RGB4_S3TC
> GL_RGBA_S3TC
> GL_RGBA4_S3TC
> GL_RGBA_DXT5_S3TC
> GL_RGBA4_DXT5_S3TC

Added.

> --SUN--
> GL_R1UI_V3F_SUN
> GL_R1UI_C4UB_V3F_SUN
> GL_R1UI_C3F_V3F_SUN
> GL_R1UI_N3F_V3F_SUN
> GL_R1UI_C4F_N3F_V3F_SUN
> GL_R1UI_T2F_V3F_SUN
> GL_R1UI_T2F_N3F_V3F_SUN
> GL_R1UI_T2F_C4F_N3F_V3F_SUN

Will not add. Obsolete hardware, obsolete extension.

> --SGIX--
> GL_RGB_SIGNED_SGIX
> GL_RGBA_SIGNED_SGIX
> GL_RGB16_SIGNED_SGIX
> GL_RGBA16_SIGNED_SGIX
> GL_RGB_EXTENDED_RANGE_SGIX
> GL_RGBA_EXTENDED_RANGE_SGIX
> GL_RGB16_EXTENDED_RANGE_SGIX
> GL_RGBA16_EXTENDED_RANGE_SGIX

Will not add. Incomplete extension `SGIX_texture_range`, doesn't ship on anything.

> --3DFX--
> GL_COMPRESSED_RGB_FXT1_3DFX
> GL_COMPRESSED_RGBA_FXT1_3DFX

Added.

> --NV--
> GL_RGBA_UNSIGNED_DOT_PRODUCT_MAPPING_NV

Added the `NV_texture_shader/2/3` extensions.
