### ISSUE TITLE
Suggestion: Add FreeType Binding

### ISSUE THREAD

**Issue by neon64** [LWJGL/lwjgl3#59]
My humble suggestion is to add bindings for FreeType. It is pretty much the industry standard library for font loading/rasterisation and I'd love to be able to use it with LWJGL. To be honest I have little experience with C++/JNI but I might be able to help implement it.

Thanks very much if you could consider this.

**Comment by sriharshachilakapati** [comment]
@Spasi said that he is looking at STB (which is great because it does fonts, images and also ogg sounds) on the forums. At the same time, a friend of mine is working on a JNI library to Freetype. You can find his repository here: https://github.com/gamingchris3/jfreetype/

**Comment by Spasi** [comment]
The stb bindings have been [added](https://github.com/LWJGL/lwjgl3/commit/caaa82675506c7aa783e144a799e74f09d17c335). See [this post](http://www.java-gaming.org/topics/lwjgl-stb-bindings/36153/view.html) for details.

If you think there's an important font rendering feature that stb does not provide, please reply here.

**Comment by neon64** [comment]
Thanks for the info. I think stb is what I (and probably many others) require. Shall I close the issue?

**Comment by SilverTiger** [comment]
The first thing that would spring to my mind is that FreeType would support the OpenType format and stb only supports the TrueType format.
But on the other hand FreeType is a huge library.

**Comment by Tetramputechture** [comment]
How about writing some examples that don't use deprecated OpenGL? It would be helpful.

**Comment by Tetramputechture** [comment]
I wish the STB test demos were writting with non-deprecated OpenGL.

**Comment by Tetramputechture** [comment]
@Spasi I don't see a way change the font size in OverSample demo.

**Comment by Spasi** [comment]
Did you try pressing 'S'? If you mean arbitrary zoom in/out like the other two demos, this demo doesn't support it.

**Comment by Tetramputechture** [comment]
@Spasi I mean change  the font size directly, like specifying a point size for it to use, like in the previous demo (not Oversample, just TrueType)

**Comment by Spasi** [comment]
Change the values in [this array](https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/test/java/org/lwjgl/demo/stb/TruetypeOversample.java#L41). They are used in `PackFontRange`, [here](https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/test/java/org/lwjgl/demo/stb/TruetypeOversample.java#L173).

**Comment by Tetramputechture** [comment]
@Spasi Right, but that gives odd results, and it's questionable how to change that. Why are there two values?

**Comment by Spasi** [comment]
There are two values because there are two font sizes that you can toggle by pressing 'S'. Both sizes are packed in the same texture and the initial texture size is 512x512. It's quite possible that if you increase the font sizes then they won't fit, that's why you might be seeing odd results. Try to increase the font size as well.

Note that I didn't write this demo. It's a Java port of the [same demo](https://github.com/nothings/stb/blob/master/tests/oversample/main.c) in the stb repository.

**Comment by Spasi** [comment]
LWJGL `3.2.2-snapshot+8` is now available with FreeType bindings.

**Comment by palexdev** [comment]
Is there an example on how to use it, 'cause it's pretty difficult and I can't get it right
