### ISSUE TITLE
Fatal Error (SIGSEGV) while hashing (xxhash128)

### ISSUE THREAD

**Issue by ghost** [LWJGL/lwjgl3#591]
### Environment

* LWJGL version: `3.2.3` 
* Java version: `11`
* Platform: `Linux`
* Module: `xxhash`

### Description

I have a maven project (IntelliJ IDEA) with XXHASH.
While runtime following error appears:
`A fatal error has been detected by the Java Runtime Environment:`
`SIGSEGV (0xb) at pc=0x00007fa0f2e75724, pid=17837, tid=17841`
`JRE version: OpenJDK Runtime Environment (11.0.8+10) (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)`
`Java VM: OpenJDK 64-Bit Server VM (11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)`
`Problematic frame:`
`V  [libjvm.so+0xd55724]`

This are the relevant parts of my pom.xml:
`<properties>`
        `<lwjgl.version>3.2.3</lwjgl.version>`
        `<lwjgl.natives>natives-linux</lwjgl.natives>`
   `</properties>`
    `<dependencyManagement>`
        `<dependencies>`
            `<dependency>`
              `  <groupId>org.lwjgl</groupId>`
                `<artifactId>lwjgl-bom</artifactId>`
              `  <version>${lwjgl.version}</version>`
              `  <scope>import</scope>`
            `    <type>pom</type>`
            `</dependency>`
        `</dependencies>`
   ` </dependencyManagement>`
`<dependencies>`
  `<dependency>`
           ` <groupId>org.lwjgl</groupId>`
          `  <artifactId>lwjgl</artifactId>`
       ` </dependency>`
      `  <dependency>`
         `   <groupId>org.lwjgl</groupId>`
         `   <artifactId>lwjgl-xxhash</artifactId>`
       ` </dependency>`
     `   <dependency>`
          `  <groupId>org.lwjgl</groupId>`
         `   <artifactId>lwjgl</artifactId>`
         `   <classifier>${lwjgl.natives}</classifier>`
      `  </dependency>`
       ` <dependency>`
      `      <groupId>org.lwjgl</groupId>`
      `      <artifactId>lwjgl-xxhash</artifactId>`
        `    <classifier>${lwjgl.natives}</classifier>`
      `  </dependency>`
`</dependencies>`

This is my code:
`XXH128Hash hash5 = new XXH128Hash(byteArrayToBuffer(bytes));`
       ` long a = hash5.high64();`
       ` long b = hash5.low64();`
     `   System.out.println(a);`
        `System.out.println(b);`
        
What can be the reason of this error/bug?
Am i doing it wrong?

Thank you for any help.

Greetings
Mark

**Comment by octylFractal** [comment]
What does `byteArrayToBuffer` look like?

**Comment by tomatenmark** [comment]
`private static ByteBuffer byteArrayToBuffer(byte[] bytes){`
      `    return ByteBuffer.wrap(bytes);`
   `}`

**Comment by octylFractal** [comment]
That would be your problem. I suggest reading the [Memory FAQ](https://github.com/LWJGL/lwjgl3-wiki/wiki/1.3.-Memory-FAQ).

**Comment by tomatenmark** [comment]
Thanks so far.

If i chage code to
`ByteBuffer buffer = memAlloc(512*1024*1024);`
        `buffer.put(bytes);`
        `XXH128Hash hash5 = new XXH128Hash(buffer); //this is line 41`
        `long a = hash5.high64();`
        `long b = hash5.low64();`
        `System.out.println(a);`
        `System.out.println(b);`
        `memFree(buffer);`
it throws following exception:
`Exception in thread "main" java.lang.IllegalArgumentException: Number of remaining elements is 0, must be at least 16`
	`at org.lwjgl.system.Checks.throwIAE(Checks.java:457)`
	`at org.lwjgl.system.Checks.checkBuffer(Checks.java:259)`
	`at org.lwjgl.system.Checks.check(Checks.java:356)`
	`at org.lwjgl.system.Struct.__checkContainer(Struct.java:130)`
	`at org.lwjgl.util.xxhash.XXH128Hash.<init>(XXH128Hash.java:61)`
	`at d.m.t.Main.main(Main.java:41)`

What does it mean?

Thank you for helping.

**Comment by octylFractal** [comment]
You should also read the Buffer javadocs, `put` is a relative operation so it adjusts the internal index. How to account for this is described in the javadoc.

**Comment by tomatenmark** [comment]
Sorry for late answer.
I changed my code as follows:

`ByteBuffer buffer = memAlloc(16);`
`buffer.putInt(0, 1094795585);`
`buffer.putInt(4, 1094795585);`
`buffer.putInt(8, 1094795585);`
`buffer.putInt(12,1094795585);`
`XXH128Hash hash5 = new XXH128Hash(buffer);`
`long a = hash5.high64();`
`long b = hash5.low64();`
`System.out.printf("%X%X\n", a, b);`
`memFree(buffer);`

It outputs: 41414141414141414141414141414141
Which is the hexadecimal represantation of the original bytes.

What am i doing wrong? Do i forget a required step?

Thank you for your help.

Greetings
Mark

**Comment by octylFractal** [comment]
`XXH128Hash` is a simple result struct, not any sort of input. You want to use the methods in `XXHash` to actual perform computations.

LWJGL does not make many changes to how the C APIs are used, so it is not a very object-oriented API.

**Comment by octylFractal** [comment]
I don't really have time to explain how to use LWJGL myself, but https://github.com/LWJGL/lwjgl3-wiki/wiki/1.4.-Bindings-FAQ should be a decent starting point.

If you don't need to use this low-level API, I highly suggest using one of the other Java XXHash bindings (though they don't seem to support the 128 bit methods), or using something like https://guava.dev/releases/28.1-jre/api/docs/com/google/common/hash/Hashing.html. It'll be much easier to learn and more Java-like.

**Comment by tomatenmark** [comment]
I can not find xxhash in the linked wiki.
I finally was able to bring it to work :-)

For everyone who needs a working example in the future:
`ByteBuffer hashBuffer = memAlloc(16);`
`ByteBuffer inputBuffer = memAlloc(16);`
`inputBuffer.put(new byte[]{1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16});`
`inputBuffer.rewind();`
`XXH128Hash hash = new XXH128Hash(hashBuffer);`
`XXHash.XXH3_128bits(inputBuffer, hash);`
`long a = hash.high64();`
`long b = hash.low64();`
`System.out.printf("%016X%016X\n", a, b);`
`memFree(hashBuffer);`
`memFree(inputBuffer);`
Output is: 53D245F57C714D4283A23E62E9D85A04

Thanks for helping

Greetings
Mark

Edit: A check with xxhashsum -H2 outputs the hash a32c6f55b80b5f449f1a957522431b91 for the string "Nobody inspects the spammish repetition". For the same string the result of the code above is 4A1F7D4393633CA97A0578C9E16572FA.
Do you know where the difference comes from?

Thanks for all your help

**Comment by tomatenmark** [comment]
Maybe there is a hash result difference between the versions of xxhash (see comment above)?
-> Used in xxhsum: 0.73
-> Used in liblwjgl:  0.71
Could this be the reason?

When liblwjgl will be updated to xxhash 0.8.x?

Thanks

**Comment by Spasi** [comment]
The LWJGL 3.3.0 snapshot includes xxhash 0.8.0 and hashing the string `Nobody inspects the spammish repetition` produces the exact same output as `xxhsum` with all bit sizes.
