### ISSUE TITLE
Negative compressed size when using LWJGL LZ4

### ISSUE THREAD

**Issue by Katikatikou** [LWJGL/lwjgl3#592]
Hello, 

I tried to use the lwjgl lz4 dependency, and I am drawing black on an issue, I tried to compress and decompress a simple String, and I have some weird output : 

```
    private static final int BUFFER_SIZE = 64 * 1024;

    public static void main(String[] args) {

        String input = "String to encode";
        long stream_t =  org.lwjgl.util.lz4.LZ4.LZ4_createStream();
        long streamDecode_t =  org.lwjgl.util.lz4.LZ4.LZ4_createStreamDecode();
        ByteBuffer initialData = BufferUtils.createByteBuffer(BUFFER_SIZE); // initial data
        ByteBuffer compressedData = BufferUtils.createByteBuffer(org.lwjgl.util.lz4.LZ4.LZ4_COMPRESSBOUND(BUFFER_SIZE)); // compressed data
        ByteBuffer expandedData = BufferUtils.createByteBuffer(BUFFER_SIZE); // expanded compressed data
        for(byte b : input.getBytes()) {
            initialData.put(b);
        }

        initialData.position(0);
        int compressedSize = org.lwjgl.util.lz4.LZ4.LZ4_compress_fast_continue(stream_t, initialData, compressedData, 1);
        System.out.println("Compressed size = " + compressedSize);
        int expandedSize = org.lwjgl.util.lz4.LZ4.LZ4_decompress_safe_continue(streamDecode_t, compressedData, expandedData);
        System.out.println("Expanded size = " + expandedSize);
        byte[] bytes = new byte[BUFFER_SIZE];
        expandedData.get(bytes);
        System.out.println("Output value : " + new String(bytes));

    }
```

As an output I am getting the following : 

```
Compressed size = 284
Expanded size = -280
Output value : String to encode
```

According to the documentation, a negative value returned by the LZ4_decompress_safe_continue means that something went wrong, and I don't see what I did wrong. Is there a way for you to help on this please ? 

Thanks a lot and regards
Salah

**Comment by Spasi** [comment]
LWJGL functions that accept buffers pass the buffer's current `.remaining()` value to the corresponding size/length/capacity parameter, implicitly. Such parameters are hidden from the standard API, but they exist in the "unsafe" version (e.g. see `nLZ4_compress_fast_continue`). It is done this way to avoid a very common source of JVM crashes when writing LWJGL programs.

The code above does not appropriately `.flip()` or `.limit()` the buffers used. It tries to compress/decompress the entirety of the buffers, instead of only the bytes necessary for the input string.

**Comment by httpdigest** [comment]
What @Spasi said.
You (at the very least) have to add a `compressedData.position(compressedSize).flip();` after compressing.
However, you are still compressing the whole buffer, and not just the bytes you put into it in the loop.

**Comment by Katikatikou** [comment]
Oh I see, really sorry to bother you guys, I didn't understand it that way. I fixed my code, and it seems to work much better

Thanks a lot for your help. 
Salah
