### ISSUE TITLE
OpenGL ES 2 support - Version string OpenGL ES 2.0 Mesa 20.0.8 not parsed

### ISSUE THREAD

**Issue by OndrejSpanel** [LWJGL/lwjgl3#593]
* LWJGL version: `3.2.3` 
* Java version: `8`
* Platform: `Linux`
* Module: `core`

### Description

I try to use OpenGL ES on my Linux virtual machine, as the only OpenGL I have available there is a Mesa library and it seems to support only OpenGL 2.1 as a desktop OpenGL and also OpenGL ES 2.0.

I create the OpenGL ES using following parameters:

GLFW_CONTEXT_VERSION_MAJOR = 2
GLFW_CONTEXT_VERSION_MINOR = 0
GLFW_CLIENT_API = GLFW_OPENGL_ES_API

The creation is successful, but when I try to initialize LWJGL, I get following exception:

```text
Exception in thread "main" java.lang.IllegalArgumentException: Malformed API version string [OpenGL ES 2.0 Mesa 20.0.8]
	at org.lwjgl.system.APIUtil.apiParseVersion(APIUtil.java:300)
	at org.lwjgl.system.APIUtil.apiParseVersion(APIUtil.java:279)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:381)
	at org.lwjgl.opengl.GL.createCapabilities(GL.java:322)
```

I have read #96 but I think this issue is different - I already use the context selection from the recent GLFW, but the LWJGL is unable to handle the version.

Is there any way to get support for OpenGL ES 2 in LWJGL in this scenario?

**Comment by Spasi** [comment]
Hey @OndrejSpanel,

The LWJGL bindings for OpenGL ES are different from OpenGL. You need to use `org.lwjgl.opengles.GLES.createCapabilities` and the binding classes in `org.lwjgl.opengles`.

**Comment by OndrejSpanel** [comment]
I see now - I even need to add a different library as a dependency (https://mvnrepository.com/artifact/org.lwjgl/lwjgl-opengles). I admit it is a bit surprise by this, but I guess there are some reasons for that. For my curiosity, are the reasons explained in some document, discussion, issue ... whatever?

I already use an abstraction layer, therefore I should be able to use the same code with both paths (if anyone is interested, I have ported text renderer and also GLG2D from Jogl to LWJGL).

- abstraction layer: https://github.com/OpenGrabeso/jaagl
- text renderer (supports both fixed function and shaders, both Jogl and LWJGL): https://github.com/OpenGrabeso/text-renderer
- GLG2D (again fixed/shader pipeline, Jogl/LWJGL APIs): https://github.com/OpenGrabeso/glg2d

BTW: Thanks for your LWJGL work, I like the library a lot.

**Comment by Spasi** [comment]
There is a significant subset of OpenGL and OpenGL ES that is identical, but there are also important differences between the two APIs. LWJGL strives to provide lightweight bindings and any attempt to create an abstraction over GL/GLES would introduce complexity (and some performance overhead). I don't think it would be worth the effort. Much cleaner and efficient abstractions can be built at the application level.

There is a level of source compatibility though. For the common subset, most code would probably work as is by simply changing static imports (e.g. from `org.lwjgl.opengl.GL11.*` to `org.lwjgl.opengles.GLES20.*`).
