### ISSUE TITLE
AIMaterial missing GetTexture and GetTextureCount methods

### ISSUE THREAD

**Issue by Pinkolik** [LWJGL/lwjgl3#594]
### Environment

* LWJGL version: `3.2.3` 
* LWJGL build #: `X`
* Java version: `1.8`
* Platform: `Windows`
* Module: `lwjgl-assimp`

### Description

Hello!
I am studying OpenGL wtih learnopengl site and I'm stuck on chapter about loading models with [Assimp.](https://learnopengl.com/Model-Loading/Model)
And to be exact I'm stuck at this particular snippet.
```C++
vector<Texture> loadMaterialTextures(aiMaterial *mat, aiTextureType type, string typeName)
{
    vector<Texture> textures;
    for(unsigned int i = 0; i < mat->GetTextureCount(type); i++)
    {
        aiString str;
        mat->GetTexture(type, i, &str);
        Texture texture;
        texture.id = TextureFromFile(str.C_Str(), directory);
        texture.type = typeName;
        texture.path = str;
        textures.push_back(texture);
    }
    return textures;
}  
```
I couldn't find GetTextureCount and GetTexure methods in AIMaterial struct in your implementation of Assimp wrapper.
I also checked this Assimp [demo](https://github.com/LWJGL/lwjgl3-demos/blob/main/src/org/lwjgl/demo/opengl/assimp/WavefrontObjDemo.java)
But it doesn't follow parent-child mesh loading model as it is recommended by LearnOpenGL. So I don't know what to do now. Could you please give me an advice?

**Comment by Spasi** [comment]
Hey @Pinkolik,

LWJGL provides bindings to C APIs only, it does not expose C++ APIs. The corresponding functions are `aiGetMaterialTextureCount` and `aiGetMaterialTexture` in the `Assimp` class. These functions take an `AIMaterial` struct as their first parameter.
