### ISSUE TITLE
stb_vorbis_decode_memory returns null with LWJGL 3.2.4-SNAPSHOT

### ISSUE THREAD

**Issue by Ealrann** [LWJGL/lwjgl3#596]
Hello,

### Description
I tried the last LWJGL snapshot (3.2.4-SNAPSHOT build 6), and I got a different behavior when decoding vorbis files:
`stb_vorbis_decode_memory` and `stb_vorbis_open_memory` return null. 

I made a little test project here to reproduce the error: 
```
git clone https://github.com/Ealrann/testVorbis.git
cd testVorbis
./gradlew run
```

If I change the version of LWJGL in the build.gradle to `3.2.3`, the `./gradlew run` works again.

Maybe something changed in the stb library?

### Environment

* LWJGL version: `3.2.4-SNAPSHOT` 
* LWJGL build #: `6`
* Java version: `11` (OpenJDK 15)
* Platform: `Linux`
* Module: `stb`

**Comment by Ealrann** [comment]
I added a test with `stb_vorbis_open_memory` in the test project. It allows to get an error code (which is 3).

So, I'm not sure, but maybe it's related to this issue: https://github.com/nothings/stb/issues/1021

**Comment by Spasi** [comment]
Thanks @Ealrann, it's indeed the same issue. Will be fixed in the next snapshot.
