### ISSUE TITLE
MacOS MoltenVK native libraries should be updated  to 1.1.0

### ISSUE THREAD

**Issue by jessegit** [LWJGL/lwjgl3#599]
MoltenVK 1.1.0 has been released on Oct 2 that adds [Vulkan 1.1 Support and Vulkan SDK 1.2.154](https://github.com/KhronosGroup/MoltenVK/releases).

I'm assuming that the update would be just a bump of libraries in the -natives-macos artifact as lwjgl already supports VK11 on other platforms.

**Comment by Spasi** [comment]
Hey @jessegit, LWJGL 3.3.0 snapshot 8 is now available. It includes Vulkan `1.2.172` and MoltenVK `1.1.2`.
