### ISSUE TITLE
GL12.GL_TEXTURE_BINDING_3D missing?

### ISSUE THREAD

**Issue by SmashMaster** [LWJGL/lwjgl3#60]
I'm converting my library to use LWJGL 3.0.0a, and GL_TEXTURE_BINDING_3D appears to be missing from org.lwjgl.opengl.GL12. It should have a value of 0x806A.

Also, how did you guys generate this code?

**Comment by Spasi** [comment]
Thanks, it has been added with 053f8758a52e5188da17e43bb1c8d9c85fadc30c.

We use a custom code generator, written in [Kotlin](http://kotlinlang.org/). The source is [here](https://github.com/LWJGL/lwjgl3/tree/master/src/templates/org/lwjgl) and documentation [here](https://github.com/LWJGL/lwjgl3-wiki/wiki/4.5.-The-Generator).
