### ISSUE TITLE
Are they any options to do Software rendering with LWJGL3?

### ISSUE THREAD

**Issue by Coder246** [LWJGL/lwjgl3#600]
Especially on older PCs LWJGL3 wont't run...
So my Question is can we render the game with the cpu?
I know that the performance won't be so good. But it is better than nothing.

**Comment by octylFractal** [comment]
I'm pretty sure that LWJGL will use whatever OpenGL or Vulkan API is provided, so if there is a CPU-based API (which I'm pretty sure there always is for OpenGL), LWJGL can render on the CPU.

**Comment by Coder246** [comment]
And how can I provide an api for lwjgl like swiftshader fron Google

**Comment by Coder246** [comment]
Has no one an Idea?

**Comment by httpdigest** [comment]
Did you try the instructions on https://github.com/google/swiftshader#usage ?

**Comment by Coder246** [comment]
_"On Windows, most applications can be made to use SwiftShader's DLLs by placing them in the same folder as the executable. On Linux, the LD_LIBRARY_PATH environment variable or -rpath linker option can be used to direct applications to search for shared libraries in the indicated directory first."_

Is this working with LWJGL3?

**Comment by httpdigest** [comment]
> Is this working with LWJGL3?

You could simply try it. LWJGL tries to load `vulkan-1.dll` first from `org.lwjgl.librarypath`, then from `org.lwjgl.librarypath` and if that did not work, from a system-specific path (such as Windows/System32).

**Comment by Coder246** [comment]
Thanks i will try it!

**Comment by Coder246** [comment]
With Swiftshader Libary pressent there is also the Error:

[LWJGL] GLFW_API_UNAVAILABLE error
        Description : WGL: The driver does not appear to support OpenGL

**Comment by httpdigest** [comment]
Have you read what SwiftShader actually is and that I always mentioned Vulkan above? Of course it does not support OpenGL, as it says so clearly on the repo readme:
> Introduction
SwiftShader is a high-performance CPU-based implementation of the **Vulkan graphics API**

**Comment by Coder246** [comment]
Can you tell me an other option to do it, when SwiftShader isn't the right way?

**Comment by Coder246** [comment]
I tried to put the Mesa3D libary to `java.library.path` but lwjgl didn't recognize it?
The file is named `opengl32.dll`.
Is it the right way?

**Comment by Spasi** [comment]
Closing this as out-of-scope for LWJGL. LWJGL does not do rendering, it simply provides bindings to rendering APIs, that may or may not support software rendering.

The correct way to override the OpenGL library used is to set `Configuration.OPENGL_LIBRARY_NAME` (or the equivalent JVM parameter `-Dorg.lwjgl.opengl.libname=<path>`). The specified library will be used by both the OpenGL bindings and GLFW (which is the one creating/managing the OpenGL context).

**Comment by SWinxy** [comment]
There may exist some software-based implementation of OpenGL or Vulkan, but as Spasi mentioned, this is out of the scope of LWJGL.
