### ISSUE TITLE
glEnableClientState/glDisableClientState missing in compat profile

### ISSUE THREAD

**Issue by unascribed** [LWJGL/lwjgl3#602]
### Environment

* LWJGL version: `3.2.4` 
* LWJGL build #: `6`
* Java version: `11.0.9` (OpenJ9)
* Platform: `Linux`
* Module: `opengl`

### Description

glEnableClientState and glDisableClientState are completely missing. I assume this is because my driver does not support GL_NV_vertex_buffer_unified_memory, and it seems these two methods are now [guarded behind that extension](https://github.com/LWJGL/lwjgl3/blob/02934555dad9d0a69d076cbfc2aee37e2d2b71d4/modules/lwjgl/opengl/src/templates/kotlin/opengl/templates/GL11.kt#L1112) even in a compat profile. An untagged fork that fixes this seems to exist which [removes the DependsOn declaration from the templates](https://github.com/CosineMath/lwjgl3-boat/commit/87e3e0fb0151777902f2228483857f0584e33b58#diff-94a1f8cd5236cc1436f08e52f1b7dc3cd121629d4f48585d8a4b63b9a01c2546).

I'm unsure why this only came up recently; I've been using LWJGL nightlies forever and this change was made 3 years ago. Maybe Mesa dropped this extension in the AMD driver recently? No idea.

Oddly, this can be worked around by using glEnable/glDisable instead of glEnableClientState/glDisableClientState. Probably a driver compatibility quirk.

**Comment by Spasi** [comment]
@unascribed Thanks!
