### ISSUE TITLE
Allow setting pointer addresses for struct fields via fluent-interface Struct instance methods

### ISSUE THREAD

**Issue by httpdigest** [LWJGL/lwjgl3#604]
Currently, when working with structs - as is typical with the Vulkan bindings - and using the fluent-interface style of setting struct fields/members, you are supposed to set members that represent indirections/pointers via an actual NIO buffer (IntBuffer, LongBuffer, PointerBuffer, ...).

This brings two problems with it:
1. you actually need to allocate those NIO buffers (which you can of course do via `MemoryStack`, if they are short-lived)
2. if you want to simply alias the allocated buffer into two sections for two field/members, then you need to splice an additional NIO buffer object for that, since LWJGL methods always take the current position() and remaining() of the buffers

In most cases, short-lived buffers won't even be escape-analyzed-away, because most setup code is only ever interpreted and not even C1'ed, much less C2'ed.

So, when wanting to avoid having to allocate those NIO buffer instances, there is a possibility to simply use the `n`-methods. However, those methods are static and thus return `void`.

It'd be nice if we had `n`-style methods taking actual addresses as `long` which are instance methods of struct classes.

**Comment by Spasi** [comment]
Hmm, could you please post some example code?

I think I understand the idea, but my feeling is that it's not worth polluting the instance API. I can't imagine how an application would have trouble with a few extra instances being allocated+GCed during setup/init. The static API is supposed to be useful only for those rare cases that you have struct construction in tight loops and scalar replacement via EA is failing.

**Comment by httpdigest** [comment]
> it's not worth polluting the instance API

Yeah, you're right. Agreed.
