### ISSUE TITLE
STBImageResize: stbir_resize_uint8_generic Bad null Check

### ISSUE THREAD

**Issue by gudenau** [LWJGL/lwjgl3#605]
### Environment

* LWJGL version: `3.2.2`, checked in Master as well 
* LWJGL build #: `Unknown`
* Java version: `15`
* Platform: `Linux`
* Module: `stb`

### Description

The `alloc_context` pointer for `stbir_resize_uint8_generic` is being checked for null, even though the library itself passes `NULL` to the underlying function calls in `stbir_resize_uint8`.

stbir_resize_uint8: https://github.com/nothings/stb/blob/master/stb_image_resize.h#L2463
stbir_resize_uint8_generic: https://github.com/nothings/stb/blob/master/stb_image_resize.h#L2506

**Comment by Spasi** [comment]
Thank you @gudenau! The overloads with an explicit `alloc_context` parameter were generated by mistake. Removed now with 15cc62b5f853c14070aa0f75aee309c4df4c7b0f.

Note that stb is already configured to use the LWJGL memory allocator internally, so a user-specified allocation context is not necessary.
