### ISSUE TITLE
Compiler error

### ISSUE THREAD

**Issue by ElectronicsBoy** [LWJGL/lwjgl3#612]
### Environment

* LWJGL version: `3.2.3` 
* LWJGL build #: `3`
* Java version: `14`
* Platform: `Windows`
* Module: `core`

### Description

I'm trying to compile in eclipse but this error :
Exception in thread "main" java.lang.NoClassDefFoundError: org/lwjgl/Version
	at me.Electronics_boy.Main.run(Main.java:22)
	at me.Electronics_boy.Main.main(Main.java:114)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.Version
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)

anyone knows why????

**Comment by httpdigest** [comment]
First of all, this is _not_ a compile error. This is a _runtime_ exception.
Second: Make sure that the lwjgl-3.1.1.jar is in your runtime classpath or (if you use the Java 9+ Module System) it is in your module path and you have an automatic module dependency on the jar (such as "lwjgl") in your module-info.java file. The version 3.1.1 of LWJGL is not yet aware of the Java Module System (i.e. it does not bring its module-info.class).
On top of that: You probably shouldn't use an LWJGL version from 2016. If you can, you should upgrade to at least the current release version 3.2.3. See: https://mvnrepository.com/artifact/org.lwjgl/lwjgl

**Comment by NikunjChiluvuri** [comment]
I'm using the latest one but i thought i was using the 3.1.1 one.

**Comment by NikunjChiluvuri** [comment]
and I'm not using Marvel. And my ide is Eclipse if you need it.

**Comment by httpdigest** [comment]
Make sure that the lwjgl jar is in your runtime classpath or (if you use the Java 9+ Module System) it is in your module path and you have an automatic module dependency on the jar (such as "lwjgl") in your module-info.java file.

**Comment by ElectronicsBoy** [comment]
it is there

**Comment by ElectronicsBoy** [comment]
but still I'm getting the error

**Comment by ElectronicsBoy** [comment]
> Make sure that the lwjgl jar is in your runtime classpath or (if you use the Java 9+ Module System) it is in your module path and you have an automatic module dependency on the jar (such as "lwjgl") in your module-info.java file.


ok thx. it worked. i thought i added them. 

### _**CLOSING**_
