### ISSUE TITLE
Gradle Could Not Find lwjgl-nfd-3.2.3-natives-linux-arm64.jar in Maven Repo

### ISSUE THREAD

**Issue by CuriousTommy** [LWJGL/lwjgl3#616]
### Environment

* LWJGL version: `3.2.3` 
* LWJGL build #: `Not sure...`
* Java version: `OpenJDK Runtime Environment (build 15+36-Ubuntu-1)`
* Platform: `Linux/ARM64`
* Module: `Not sure...`

### Description

I'm currently trying to set up a gradle project to use the LWJGL libraries on my Raspberry Pi 4 (Ubuntu 20.10). When I try run the project, I get the following error message:

```
Could not find lwjgl-nfd-3.2.3-natives-linux-arm64.jar (org.lwjgl:lwjgl-nfd:3.2.3).
Searched in the following locations:
    https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-nfd/3.2.3/lwjgl-nfd-3.2.3-natives-linux-arm64.jar
```

Looking in https://repo.maven.apache.org/maven2/org/lwjgl/lwjgl-nfd/3.2.3/, I can see that the `lwjgl-nfd-3.2.3-natives-linux-arm64.jar` file in indeed not there.

I attached the [build.gradle.txt](https://github.com/LWJGL/lwjgl3/files/5760940/build.gradle.txt), in case you need to look at it.

**Comment by SWinxy** [comment]
[nfd](https://github.com/mlabbe/nativefiledialog) doesn't support Linux arm64/32. There's no issues or pr's on the GitHub page asking for an ARM port, so maybe you should ask about it if you really need it. Otherwise you will have to find something else.

**Comment by CuriousTommy** [comment]
Ah, so that is what nfd stands of.

I got nfd to compile on my Pinebook Pro after a few changes, I'm going to try and work with upstream dev to merge my change.

**Comment by SWinxy** [comment]
Ah cool. If you want, you may want to consider doing arm32 just to round things out. Wink wink.

**Comment by Spasi** [comment]
The LWJGL 3.3.0 snapshot now includes nfd builds for arm32/64.
