### ISSUE TITLE
AWTGLCanvas cannot hide or removed 

### ISSUE THREAD

**Issue by hubert-hy** [LWJGL/lwjgl3#618]
### Environment

* LWJGL version: `3.0` 
* LWJGL build #: `X`
* Java version: `12`
* Platform: `macOS`
* Module: `org.lwjgl.opengl.awt`

### Description

Here are two java files: 
CanvasTest.java 

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

package org.lwjgl.opengl.awt;

import static org.lwjgl.opengl.GL.*;
import static org.lwjgl.opengl.GL11.*;
import org.lwjgl.opengl.awt.AWTGLCanvas;
import org.lwjgl.opengl.awt.GLData;

 
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

import org.lwjgl.opengl.awt.GLData;
 
public class CanvasTest {
 
  public static class CustomAWTGLCanvas extends AWTGLCanvas {
 
	public static GLData data; 
	public static void create()
	{
		data = new GLData();
	  	data.samples = 4;
	    data.swapInterval = 0;
	}
    public CustomAWTGLCanvas() {
      
      super(data);
    }
 
    public void paintGL() {
     
    	int w = getWidth();
        int h = getHeight();
        float aspect = (float) w / h;
        double now = System.currentTimeMillis() * 0.001;
        float width = (float) Math.abs(Math.sin(now * 0.3));
        glClear(GL_COLOR_BUFFER_BIT);
        glViewport(0, 0, w, h);
        glBegin(GL_QUADS);
        glColor3f(0.4f, 0.6f, 0.8f);
        glVertex2f(-0.75f * width / aspect, 0.0f);
        glVertex2f(0, -0.75f);
        glVertex2f(+0.75f * width/ aspect, 0);
        glVertex2f(0, +0.75f);
        glEnd();
        swapBuffers();
      
    }

	@Override
	public void initGL() {
		// TODO Auto-generated method stub
		System.out.println("OpenGL version: " + effective.majorVersion + "." + effective.minorVersion + " (Profile: " + effective.profile + ")");
        createCapabilities();
        glClearColor(0.3f, 0.4f, 0.5f, 1);
	}
  }
 
  public static void main(String[] args) {
 
	CustomAWTGLCanvas.create();
    CustomAWTGLCanvas canvas = new CustomAWTGLCanvas();
 
    JPanel panel = new LwjglPanel(new BorderLayout())	    		
    {
            /**
      *
      */
      private static final long serialVersionUID = 1L;

      
   
   };
    panel.setMinimumSize(new Dimension(100, 100));
    ((LwjglPanel) panel).init(canvas);
 
    JDialog frame = new JDialog();
    frame.setPreferredSize(new Dimension(640, 480));
    JPanel panels = new JPanel(new CardLayout());
    
    JButton switcher = new JButton("Switch Active Panel!");
    JPanel another = new JPanel(); 
    switcher.addActionListener(new ActionListener()
	{

		@Override
		public void actionPerformed(ActionEvent e) {
			// TODO Auto-generated method stub
			if(panel.isVisible())
	    	{
	    		panel.setVisible(false);
	    		another.setVisible(true);
	    	}
	    	else 
	    	{
	    		panel.setVisible(true);
	    		another.setVisible(false);
	    	}
		}

	});

    
    panels.add(panel);
    
   
    another.setPreferredSize(new Dimension(640, 480));
    another.setBackground(Color.GREEN);
    another.add(new JLabel("Yeah, this is another panel."));
    another.setVisible(false);
    panels.add(another);
    
    frame.add(switcher, BorderLayout.PAGE_START);
    frame.add(panels);
    frame.pack();
 
    frame.setVisible(true);
  }
}

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
LwjglPanel.java
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

package org.lwjgl.opengl.awt;

import java.awt.BorderLayout;
import java.awt.Canvas;
import java.awt.Graphics;

import javax.swing.JPanel;

public class LwjglPanel extends JPanel{
	
	public LwjglPanel(BorderLayout borderLayout) {
		// TODO Auto-generated constructor stub
		super(borderLayout); 
	}

    public LwjglPanel()
    {
    	super(); 
    }
    

    public void paint(Graphics g)
    {
    	//super(g); 
    	if(m_canvas != null)
    	m_canvas.render(); 
    }
	
    
    @Override 
    public void setVisible(boolean v)
    {
    	super.setVisible(v);
    	if(!v && m_canvas != null)
    	{
    		this.remove(m_canvas);
    		this.m_canvas.disposeCanvas();
    		this.m_canvas = null; 
    		this.repaint(); 
    	}
    }
	
	public void init(AWTGLCanvas canvas)
	{
		this.m_canvas = canvas; 
		this.add(m_canvas); 
	}

	AWTGLCanvas m_canvas; 
}

**Comment by httpdigest** [comment]
LWJGL3 itself does not feature a AWTGLCanvas class. Do you mean https://github.com/LWJGLX/lwjgl3-awt ? Probably the issue should be posted there instead.

**Comment by hubert-hy** [comment]
ok, I will post it there. 

Thanks
