### ISSUE TITLE
Failed to run example on mac

### ISSUE THREAD

**Issue by recursivetree** [LWJGL/lwjgl3#620]
### Environment

* LWJGL version: `3.2.3` 
* LWJGL build: idk, from gradle
* Java version: `1.8`
* Platform: `macOS`

### Description

I tried to run the example from [https://www.lwjgl.org/guide](https://www.lwjgl.org/guide), but it fails when calling `glfwCreateWindow` with a native crash:
```
2021-01-22 15:31:07.688 java[36639:10414788] *** Assertion failure in +[NSUndoManager _endTopLevelGroupings], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1575.300/Foundation/Misc.subproj/NSUndoManager.m:361
2021-01-22 15:31:07.688 java[36639:10414788] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '+[NSUndoManager(NSInternal) _endTopLevelGroupings] is only safe to invoke on the main thread.'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff5206e9ad __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff7c78ea17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff520896ca +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff5432b741 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   Foundation                          0x00007fff5425e7be +[NSUndoManager(NSPrivate) _endTopLevelGroupings] + 473
	5   AppKit                              0x00007fff4f5a6661 -[NSApplication run] + 916
	6   libglfw.dylib                       0x000000011f21aa85 libglfw.dylib + 68229
	7   libglfw.dylib                       0x000000011f214416 libglfw.dylib + 42006
	8   ???                                 0x00000001081a47e8 0x0 + 4430907368
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by httpdigest** [comment]
Please also read the info "**MacOS users should start their application passing "-XstartOnFirstThread" as a VM option.**" on said LWJGL page.

**Comment by recursivetree** [comment]
That's what I did, and it didn't use anything. I use gradle, it is most likely related to it in this case.

**Comment by httpdigest** [comment]
If by "I use gradle" you mean that you invoke your application via the Gradle Application Plugin's `run` task, then "Option 2" of this answer is probably what you are looking for: https://stackoverflow.com/questions/35244961/how-do-i-add-default-jvm-arguments-with-gradle#answer-35248056
Else, simply google something like "Gradle how to add JVM argument to run".

**Comment by httpdigest** [comment]
Next question: You aren't actually doing something like `new Thread(...).start();` as the first thing in your main() method, do you?
Or put another way: Does the glfwCreateWindow() call _actually_ happen in the main thread (which invoked your main() method) or do you do everything in a spawned thread?

**Comment by recursivetree** [comment]
As I stated above, I use the official code from the getting started page on  https://www.lwjgl.org/guide. No, this code doesn't start it in a separate thread

**Comment by httpdigest** [comment]
Then, I'm sorry, this is simply a tooling issue that you need to solve. It has nothing to do with LWJGL itself and is not an issue related to it. It simply means: Whatever you use to run the Java application, it _must_ use the `-XstartOnFirstThread` JVM argument (not program argument).

**Comment by recursivetree** [comment]
True, it is not directly related, but somehow it is related, because I used the official instruction on how to setup a project with gradle
