### ISSUE TITLE
Can't load native x86-64 libraries running on x86-64 JVM via Rosetta 2 on Apple Silicon

### ISSUE THREAD

**Issue by badlogic** [LWJGL/lwjgl3#628]
### Environment

* LWJGL version: `3.3.0-SNAPSHOT` 
* LWJGL build #: `7`
* Java version: `13`
* Platform: `macOS`
* Module: `core`

### Description
Consider this simple mavenized `HelloWorld` app straight from your website. https://github.com/badlogic/lwjgl3-test/tree/a524629f428296c72440b6e4d81c32676029fd82

The x86-64 macOS natives are selected, the app is run via Azul JDK 13 x86-64 on macOS Big Sur running on a MacBook Pro Apple Silicon via Rosetta 2.

The native library loader insists on trying to find the ARM64 native libraries and refuses to load the x86-64 native libraries:

```
Hello LWJGL 3.3.0 build 7!
[LWJGL] Platform/architecture mismatch detected for module: org.lwjgl
	JVM platform:
		macOS aarch64 13.0.6
		OpenJDK 64-Bit Server VM v13.0.6+5-MTS by Azul Systems, Inc.
	Platform available on classpath:
		macos/x64
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib
	at org.lwjgl.system.Library.loadSystem(Library.java:164)
	at org.lwjgl.system.Library.loadSystem(Library.java:63)
	at org.lwjgl.system.Library.<clinit>(Library.java:51)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:99)
	at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:67)
	at org.lwjgl.system.Callback.<clinit>(Callback.java:39)
	at HelloWorld.init(HelloWorld.java:37)
	at HelloWorld.run(HelloWorld.java:22)
	at HelloWorld.main(HelloWorld.java:112)

Process finished with exit code 1
```

The loader correctly evaluates the CPU arch, but fails to take into account the JVM arch, which is x86-64 under Rosetta 2.

The loader should likely check the JVM arch instead of the CPU arch on macOS, so apps running under Rosetta 2 on a x86-64 JVM load the correct native libraries.

**Comment by Spasi** [comment]
Hmm, using `System.getProperty("os.arch")` for this. Not sure what a good alternative would be.

**Comment by badlogic** [comment]
Terribly sorry, I had a Maven hiccup and pulled in the ARM natives instead of the x86 natives. Works as intended!
