### ISSUE TITLE
Invalid window hint 0x00050002 when using the GLFW_ANGLE_PLATFORM_TYPE enum

### ISSUE THREAD

**Issue by LAX1DUDE** [LWJGL/lwjgl3#633]
### Environment

* LWJGL version: `3.3.0` 
* LWJGL build #: `X`
* Java version: `1.8`
* Platform: `Windows`
* Module: `glfw`

### Description

GLFW added window hints for selecting a platform type when using ANGLE to create an opengl es context. The window hint is GLFW_ANGLE_PLATFORM_TYPE and when it is used GLFW returns "Invalid window hint 0x00050002". The enum is available in the GLFW.java class but the GLFW DLL itself has clearly not been updated to support it

To reproduce, call glfwWindowHint with GLFW_ANGLE_PLATFORM_TYPE as the hint with any value

**Comment by Spasi** [comment]
Using `GLFW_ANGLE_PLATFORM_TYPE ` with `glfwWindowHint` is wrong. It should be set with `glfwInitHint` before calling `glfwInit`.

**Comment by LAX1DUDE** [comment]
sorry about that
