### ISSUE TITLE
OpusFile Bindings

### ISSUE THREAD

**Issue by ghost** [LWJGL/lwjgl3#634]
Hello dear community, I noticed the Opus binding provided by LWJGL3 is missing an important part of it! It's the "opusfile" support library.

### OPUSFILE _IS NOT_ LIBOPUS!!!

The actual Opus binding only include the encoder and decoder but not the library to actually deal with opus files.

The actual description of opusfile is "Opusfile is a easy to use library that encapsulates everything you need beyond libopus to correctly and completely support the playback of .opus (OggOpus) files.". 

Project on GH: https://github.com/xiph/opusfile
Opusfile documentation: https://www.opus-codec.org/docs/opusfile_api-0.7/index.html

Do I need it in all platforms? No, but having it in Win_x86-64 and Linux_x86-64 is a must.
Do you need the entire project? Yes

**Comment by Spasi** [comment]
The https://github.com/xiph/opusfile and https://github.com/xiph/libopusenc libraries are now part of the Opus bindings. Will be available in the next 3.3.0 snapshot.
