### ISSUE TITLE
Missing demo/footsteps.ogg

### ISSUE THREAD

**Issue by adiantek** [LWJGL/lwjgl3#637]
https://github.com/LWJGL/lwjgl3/blob/master/modules/samples/src/test/java/org/lwjgl/demo/openal/ALCDemo.java#L105
Where is the demo/footsteps.ogg?

**Comment by Spasi** [comment]
Hey @adiantek, the Ant build downloads demo resources automatically. Try `ant demo -Dclass=org.lwjgl.demo.openal.ALCDemo`.

**Comment by adiantek** [comment]
Ok, thanks
