### ISSUE TITLE
Wrong ELF class: ELFCLASS32

### ISSUE THREAD

**Issue by creepinson** [LWJGL/lwjgl3#641]
### Environment

* LWJGL version: `3.2.3`
* Java version: `11.0.10`
* Platform: `Linux (Ubuntu 20.04)`

### Description

I set up a lwjgl project using gradle on Ubuntu 20.04. Yes, I do have 64 bit java, as seen below

## The Error

```
OpenJDK 64-Bit Server VM warning: You have loaded library /home/theo/lwjgl/3.2.3-SNAPSHOT/liblwjgl.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
Exception in thread "Thread-1" java.lang.UnsatisfiedLinkError: /home/theo/lwjgl/3.2.3-SNAPSHOT/liblwjgl.so: /home/theo/lwjgl/3.2.3-SNAPSHOT/liblwjgl.so: wrong ELF class: ELFCLASS32 (Possible cause: architecture word width mismatch)
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at
```

## Java Version Proof

![image](https://user-images.githubusercontent.com/11761863/112916735-fe9b4100-90b5-11eb-8435-16d1c3b59755.png)

## File Command Output
```
❯ file 3.2.3-SNAPSHOT/liblwjgl.so 
3.2.3-SNAPSHOT/liblwjgl.so: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, BuildID[sha1]=9ef3fe71bdc1625ae5e589f417b770c1e50a2a6f, stripped
```

**Comment by SWinxy** [comment]
It looks like you're using the snapshot of 3.2.3. 3.2.3 is already released, and 3.3.0 is in its snapshot stage. The link error might be because you selected the wrong natives type (ARM32, rather than ARM64 or x64) on the customize page, or that you switched profiles with Maven.
