### ISSUE TITLE
libassimp.so: undefined symbol: __wrap_memcpy

### ISSUE THREAD

**Issue by dustContributor** [LWJGL/lwjgl3#642]
### Environment

* LWJGL version: `3.3.0` snapshot
* LWJGL build #: `11` 
* Java version: `15` Zulu 15 +51, 2020-09-15
* Platform: `Linux` debian x64 testing, libc 2.31-2
* Module: `assimp`

### Description

I can't seem to launch the hello assimp example. It fails with this error:
> /usr/lib/jvm/zulu-15-amd64/bin/java: symbol lookup error: /tmp/lwjgluser/3.3.0-build-11/libassimp.so: undefined symbol: __wrap_memcpy

A bunch of other bindings work fine though (opengl, nuklear, stb font, jemalloc, glfw).

**Comment by mudlee** [comment]
Same happens for me :(

**Comment by mudlee** [comment]
<img width="1133" alt="Screenshot 2021-05-25 at 18 56 46" src="https://user-images.githubusercontent.com/1439334/119538043-fa746280-bd8a-11eb-8f0b-1a561cf4a350.png">

**Comment by dustContributor** [comment]
@mudlee Thanks for adding this info in this issue, otherwise I wouldn't have known.
