### ISSUE TITLE
Javadoc typo in description to 'Package org.lwjgl.util.xxhash'

### ISSUE THREAD

**Issue by Sad-H** [LWJGL/lwjgl3#643]
Hello all, really small typo in the description to org.lwjgl.util.xxhash package (overview: https://javadoc.lwjgl.org/overview-summary.html and package summary: https://javadoc.lwjgl.org/org/lwjgl/util/xxhash/package-summary.html).

Currently:
"Contains bindings to xxHash, an extremely **fash** non-cryptographic hash algorithm."

Should be:
"Contains bindings to xxHash, an extremely **fast** non-cryptographic hash algorithm."

**Comment by SWinxy** [comment]
We don't want fascist algorithms here.

I also found some formatting error in [CallbackI](https://github.com/LWJGL/lwjgl3/blob/master/modules/lwjgl/core/src/main/java/org/lwjgl/system/CallbackI.java) that cuts off code styling mid-word:

><p>If the function is declared as returning {@code v}oid, then this value is garbage and should not be used.</p>
to
><p>If the function is declared as returning {@code void}, then this value is garbage and should not be used.</p>

**Comment by Spasi** [comment]
Thank you @Sad-H and @SWinxy!
