### ISSUE TITLE
Mouse position seems to have variable offset on kubuntu

### ISSUE THREAD

**Issue by Shadowblitz16** [LWJGL/lwjgl3#646]
### Environment

* LWJGL version: `3.2.3` 
* LWJGL build #: `not sure`
* Java version: `java 11 (jet brains run time/corretto)`
* Platform: `Kubuntu Linux 20.10`
* Module: `not sure`

### Description
I seem to be having issues other people don't have with the mouse position callback
It seems my mouse has a variable offset which grows or shrinks depending on where my mouse is on the screen.

I have reproduced it on the guys end doing the tutorial and he seems to not have the issue or anybody else.
![image](https://user-images.githubusercontent.com/2453707/116006376-c822ea00-a5bf-11eb-8dd6-00e490be0659.png)

 here is the code..
https://github.com/Shadowblitz16/Jade

**Comment by octylFractal** [comment]
Your repository does not contain any code, and it would be helpful if you could reduce it to a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) instead of just posting the full application.

**Comment by Shadowblitz16** [comment]
@octylFractal sorry you have to switch to the master branch instead of main

**Comment by Shadowblitz16** [comment]
@octylFractal ok so I got a example project working..
https://github.com/Shadowblitz16/lwjgl-mouse-pos-bug

**Comment by Shadowblitz16** [comment]
I can also reproduce this on kubuntu 20.04

**Comment by Spasi** [comment]
Hey @Shadowblitz16, thanks for the test project.

The problem you're seeing is a simple rendering bug and has nothing to do with mouse input. The code is missing a call to `glViewport`, which usually happens within a callback passed to `glfwSetFramebufferSizeCallback`. Everything is fine when it's added. You probably have a HiDPI monitor (with scale set to >100%) while other users don't.

**Comment by Shadowblitz16** [comment]
ok thankyou
