### ISSUE TITLE
glXGetVisualFromFBConfig returning null value

### ISSUE THREAD

**Issue by CalebCintary** [LWJGL/lwjgl3#649]
### Environment

* LWJGL version: `3.2.3` 
* LWJGL build #: `stable`
* Java version: `1.8.0_292 openjdk`, `11.0.11 openjdk`
* Platform: `Linux`
* OS: `ArchLinux`
* DE: `Gnome 40.0`
* Module: `GLX`

### Description
In LWJGLCanvas#createContextGLX method, glXGetVisualFromFBConfig method return null value and breaks app. Tested for wayland and Xorg.

**Comment by Spasi** [comment]
Hey @CalebCintary, I've fixed the NPE. Could you please try the new implementation and let me know how it goes?

**Comment by CalebCintary** [comment]
I'll try as soon as possible 

> 
> 
> Hey @CalebCintary, I've fixed the NPE. Could you please try the new implementation and let me know how it goes?
