### ISSUE TITLE
[MacOS] GLFW can only be used for offscreen rendering.

### ISSUE THREAD

**Issue by ajh123** [LWJGL/lwjgl3#650]
* LWJGL version: `3.2.3` 
* LWJGL build #: `13`
* Java version: `1.8.0_292"`
* Platform: `macOS`
* Module: `GLFW ?`

### Description

So when i run my [program](https://github.com/ajh123-development/HistorySurvival-Java-) when in my Window class where the [window is being created](https://github.com/ajh123-development/HistorySurvival-Java-/blame/main/src/main/java/HistorySurvival/net/ddns/minersonline/engine/io/Window.java#L33) as a debug error i get 

```
[LWJGL] Loading library: objc
[LWJGL]         Module: org.lwjgl
[LWJGL]         libobjc.dylib not found in org.lwjgl.librarypath=/var/folders/64/zpf4yy_17zq6y06hh5gfcch40000gn/T/lwjglsamuelhulme/3.2.3-SNAPSHOT
[LWJGL]         Loaded from system paths: /usr/lib/libobjc.A.dylib
[LWJGL] Loading library: com.apple.AppKit
[LWJGL]         Success
[LWJGL] GLFW can only be used for offscreen rendering.
```
Just before the create window call i do get my out message but i dont get the one after, probably because the [create window](https://github.com/ajh123-development/HistorySurvival-Java-/blame/main/src/main/java/HistorySurvival/net/ddns/minersonline/engine/io/Window.java#L33) dose not return.

How i run the code ```java -XstartOnFirstThread -Dorg.lwjgl.util.Debug=true -jar build/libs/History\ Survival-1.0-SNAPSHOT.jar```. Also i tried running it not in a thread aswel, but no different

So far my code is a fork of [this](https://github.com/CodingAP/lwjgl3-tutorial/blob/master/tutorial2/src/engine/io/Window.java) which works on windows

**Comment by ClaasJG** [comment]
I did not check your complete code, but it seems, that you call GLFW from an other Thread anyway ( [Main.java#L14](https://github.com/ajh123-development/HistorySurvival-Java-/blob/5ce4a77821de2e3e60bdac3f21e6b394c66f8341/src/main/java/HistorySurvival/net/ddns/minersonline/Main.java#L14) ). This somewhat bypasses  '-XstartOnFirstThread' . I dont know, if it fixes your problem, but try to issue GLFW calls from the first thread (i.e. the main).

**Comment by ajh123** [comment]
Ye I’ve tried it now but the window dose get created but then the program closes, but we are a bit further now

**Comment by ajh123** [comment]
Fixed now, calling the wrong function
