### ISSUE TITLE
Obtaining the lwjgl demo/samples jar?

### ISSUE THREAD

**Issue by gmseed** [LWJGL/lwjgl3#654]
I download the early release from lwjgl's website and the getting started pack including DriftFX as I'm interested in getting the HelloDriftFX example to work.

It references "org.lwjgl.demo.opengl.*" but don't see it as part of the downloaded lwjgl jars. It makes reference to GLXGears, and then learn that this makes use of joml, etc

Is there lwjgl samples jar on the website or github that can be downloaded or does all of this have to be built from source? I've already tried to build joml from source using the shipped pom and got a build failure and so a pre-built samples jar would be helpful.

**Comment by Spasi** [comment]
Hey @gmseed!

There is no samples jar available for download. These samples are only available in the LWJGL repository, which you can clone, build and experiment on locally. Assuming you have the required software installed/configured (C/C++ compiler, JDK 8+, Apache Ant), you can build LWJGL with:

```
ant compile-templates tests
```

> Note that `compile-templates` is separate because it takes very long. If it succeeds but you get a failure in subsequent tasks, you can skip `compile-templates` in your next attempts.

Then you can try one of the demos with:

```
ant demo -Dclass=<main class>
```

For example, you can run the DriftFX demo with `ant demo -Dclass=org.lwjgl.demo.driftfx.HelloDriftFX`. When trying new things, I usually also pass a couple of extra JVM parameters like `ant demo -Dclass=org.lwjgl.demo.driftfx.HelloDriftFX -Djvmargs="-Dorg.lwjgl.util.Debug=true -Dorg.lwjgl.util.DebugLoader=true"`.

Hope this helps.
