### ISSUE TITLE
VkSurfaceFormatKHR should be mutable

### ISSUE THREAD

**Issue by YvesBoyadjian** [LWJGL/lwjgl3#655]
In C code, VkSurfaceFormatKHR is a struct with public members, so it must be mutable:
We should have methods for setting format and colorspace
This can be useful for vk-bootstrap code, by example

**Comment by Spasi** [comment]
It is technically mutable, but it doesn't have to be. It's only used in `vkGetPhysicalDeviceSurfaceFormatsKHR` as an output parameter. `VkSwapchainCreateInfoKHR` takes a `VkFormat` and a `VkColorSpaceKHR` directly.

Note that the Vulkan bindings are automatically generated from [Vulkan-Docs](https://github.com/KhronosGroup/Vulkan-Docs) (source here: [lwjgl3-vulkangen](https://github.com/LWJGL/lwjgl3-vulkangen)). The Vulkan registry XML sets a `returnedonly` attribute on structs that don't need to be mutable (`VkSurfaceFormatKHR` has it) and the LWJGL binding generator uses that information to skip setters on such structs.

**Comment by YvesBoyadjian** [comment]
Thanks for your response. I managed it by coding:
`        VkSurfaceFormatKHR fmt1 = VkSurfaceFormatKHR.create();
        MemoryUtil.UNSAFE.putInt(null, fmt1.address() + VkSurfaceFormatKHR.FORMAT, VK_FORMAT_B8G8R8A8_SRGB);
        MemoryUtil.UNSAFE.putInt(null, fmt1.address() + VkSurfaceFormatKHR.COLORSPACE, VK_COLOR_SPACE_SRGB_NONLINEAR_KHR);
`
I close the issue
