### ISSUE TITLE
How to get Assimp AIMetadataEntry String value?

### ISSUE THREAD

**Issue by AntonioNoack** [LWJGL/lwjgl3#658]
### Environment

* LWJGL version: `3.2.3` 
* LWJGL build #: `13`
* Java version: `8`
* Platform: `Windows`
* Module: `assimp`

### Description

Hello, I am trying to read the metadata from fbx files using assimp, because I need to get their correct scale, and it's often incorrectly scaled by a factor of 100. In another issue on the assimp Github, I found that there is the "UnitScaleFactor" property, which should contain the value. In my currently inspecting file, it has type 4, so it should be a string.

How do I read in string values?

My current method (environment with the other types) is
```kotlin
        val metadata = aiScene.mMetaData()
        if (metadata != null) {
            // UnitScaleFactor
            val keys = metadata.mKeys()
            val values = metadata.mValues()
            for (i in 0 until metadata.mNumProperties()) {
                val key = keys[i].dataString()
                val valueRaw = values[i]
                val valueType = valueRaw.mType()
                val value = when (valueType) {
                    0 -> valueRaw.mData(1)[0] // bool
                    1 -> valueRaw.mData(4).int // int
                    2 -> valueRaw.mData(8).long // uint64
                    3 -> valueRaw.mData(4).float // float
                    4 -> { 0 }// todo how do we get a string?
                    5 -> {
                        // aivector3d
                        // todo doubles or floats?
                        val buffer = valueRaw.mData(12*8).asDoubleBuffer()
                        Vector3d(buffer[0], buffer[1], buffer[2])
                    }
                    else -> continue
                }
                println("metadata $key: $valueType, $value")
            }
        }
```

**Comment by Kerai** [comment]
I do it like this

			var buff = entry.mData(2048);
			int len = buff.getInt();
			buff.limit(buff.position() + len);
			return StandardCharsets.UTF_8.decode(buff).toString();

Don't worry about that 2048 value, it doesn't allocate anything, so you can put anything here (as long as it's longer than your potential strings)

**Comment by AntonioNoack** [comment]
Thank you :)
Now I just need to find out, why "UnitScaleFactor" is a string 😅. It's a double in the source file as well.

**Comment by Spasi** [comment]
Hey @AntonioNoack,

The supported `mType` values are these:

```java
public static final int
        AI_BOOL       = 0,
        AI_INT32      = 1,
        AI_UINT64     = 2,
        AI_FLOAT      = 3,
        AI_DOUBLE     = 4,
        AI_AISTRING   = 5,
        AI_AIVECTOR3D = 6,
        AI_AIMETADATA = 7,
        AI_META_MAX   = 8;
```

The value `4` corresponds to `AI_DOUBLE`, so `UnitScaleFactor` is correctly represented, it's not a string.
