### ISSUE TITLE
glEnableClientState does not work if not forward compatible context

### ISSUE THREAD

**Issue by YvesBoyadjian** [LWJGL/lwjgl3#659]
With 3.3.0-SNAPSHOT version, when using a non forward compatible context, I have the error:

"C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot\bin\java.exe" 
Hello LWJGL 3.3.0 build 11!
FATAL ERROR in native method: Thread[main,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11.glEnableClientState(Native Method)
	at HelloWorld.loop(HelloWorld.java:108)
	at HelloWorld.run(HelloWorld.java:25)
	at HelloWorld.main(HelloWorld.java:119)

Process finished with exit code 1

The code is:
`import java.nio.IntBuffer;

        import org.lwjgl.*;
        import org.lwjgl.glfw.*;
        import org.lwjgl.opengl.*;
        import org.lwjgl.system.*;

        import java.nio.*;

        import static org.lwjgl.glfw.Callbacks.*;
        import static org.lwjgl.glfw.GLFW.*;
        import static org.lwjgl.opengl.GL11.*;
        import static org.lwjgl.system.MemoryStack.*;
        import static org.lwjgl.system.MemoryUtil.*;

public class HelloWorld {

    // The window handle
    private long window;

    public void run() {
        System.out.println("Hello LWJGL " + Version.getVersion() + "!");

        init();
        loop();

        // Free the window callbacks and destroy the window
        glfwFreeCallbacks(window);
        glfwDestroyWindow(window);

        // Terminate GLFW and free the error callback
        glfwTerminate();
        glfwSetErrorCallback(null).free();
    }

    public void init() {
        // Setup an error callback. The default implementation
        // will print the error message in System.err.
        GLFWErrorCallback.createPrint(System.err).set();

        // Initialize GLFW. Most GLFW functions will not work before doing this.
        if ( !glfwInit() )
            throw new IllegalStateException("Unable to initialize GLFW");

        // Configure GLFW
        glfwDefaultWindowHints(); // optional, the current window hints are already the default
        glfwWindowHint(GLFW_VISIBLE, GLFW_FALSE); // the window will stay hidden after creation
        glfwWindowHint(GLFW_RESIZABLE, GLFW_TRUE); // the window will be resizable

        // Create the window
        window = glfwCreateWindow(300, 300, "Hello World!", NULL, NULL);
        if ( window == NULL )
            throw new RuntimeException("Failed to create the GLFW window");

        // Setup a key callback. It will be called every time a key is pressed, repeated or released.
        glfwSetKeyCallback(window, (window, key, scancode, action, mods) -> {
            if ( key == GLFW_KEY_ESCAPE && action == GLFW_RELEASE )
                glfwSetWindowShouldClose(window, true); // We will detect this in the rendering loop

            if(action == 1 || action == 0)
                System.out.println(window+" "+key+" "+scancode+" "+action+" "+mods);
        });

        // Get the thread stack and push a new frame
        try ( MemoryStack stack = stackPush() ) {
            IntBuffer pWidth = stack.mallocInt(1); // int*
            IntBuffer pHeight = stack.mallocInt(1); // int*

            // Get the window size passed to glfwCreateWindow
            glfwGetWindowSize(window, pWidth, pHeight);

            // Get the resolution of the primary monitor
            GLFWVidMode vidmode = glfwGetVideoMode(glfwGetPrimaryMonitor());

            // Center the window
            glfwSetWindowPos(
                    window,
                    (vidmode.width() - pWidth.get(0)) / 2,
                    (vidmode.height() - pHeight.get(0)) / 2
            );
        } // the stack frame is popped automatically

        // Make the OpenGL context current
        glfwMakeContextCurrent(window);
        // Enable v-sync
        glfwSwapInterval(1);

        // Make the window visible
        glfwShowWindow(window);
    }

    public void loop() {
        // This line is critical for LWJGL's interoperation with GLFW's
        // OpenGL context, or any context that is managed externally.
        // LWJGL detects the context that is current in the current thread,
        // creates the GLCapabilities instance and makes the OpenGL
        // bindings available for use.
        GL.createCapabilities();

        // Set the clear color
        glClearColor(1.0f, 0.0f, 0.0f, 0.0f);

        // Run the rendering loop until the user has attempted to close
        // the window or has pressed the ESCAPE key.
        while ( !glfwWindowShouldClose(window) ) {
            glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT); // clear the framebuffer

            org.lwjgl.opengl.GL11.glEnableClientState(/*32884*/GL_VERTEX_ARRAY);

            glfwSwapBuffers(window); // swap the color buffers

            // Poll for window events. The key callback above will only be
            // invoked during this call.
            glfwPollEvents();
        }
    }

    public static void main(String[] args) {
        new HelloWorld().run();
    }

    public long getWindow() {
        return window;
    }

}
`

With LWJGL 3.2.3, it works perfectly well

**Comment by Spasi** [comment]
See #327. The driver may be exposing the function, but passing `GL_VERTEX_ARRAY` is an error in a forward compatible context. That's why LWJGL doesn't expose the function unless `NV_vertex_buffer_unified_memory` is available (so that you can use it with `GL_VERTEX_ATTRIB_ARRAY_UNIFIED_NV` and `GL_ELEMENT_ARRAY_UNIFIED_NV`).

**Comment by YvesBoyadjian** [comment]
Thanks for your response, but in my case, I do not use a forward compatible context, so the function should be available

**Comment by YvesBoyadjian** [comment]
Please note that my graphics card is an AMD, so I think I do not have the extension NV_vertex_buffer_unified_memory

**Comment by YvesBoyadjian** [comment]
The bug must be at file "GLCapabilities", line 7421. The right code should be : 
`        int flag0 = !fc || ext.contains("GL_NV_vertex_buffer_unified_memory") ? 0 : Integer.MIN_VALUE;
`
