### ISSUE TITLE
NullPointerException when trying to access unsupported OpenGL-methods

### ISSUE THREAD

**Issue by looperhacks** [LWJGL/lwjgl3#66]
When trying to access a function that my graphic card doesn't support. Example:

    glVertexAttribDivisor(0, 0);

causes a NPE:

    Exception in thread "main" java.lang.NullPointerException
	at org.lwjgl.opengl.GL33.glVertexAttribDivisor(GL33.java:921)
        ...

The reason is that GL33.getInstance() returns null if GL33 is not supported.

Instead of throwing a NPE, an exception with a good description should be thrown. Maybe a good place to implement that would be the getInstance()-method of GLXX by checking for null – but that would introduce massive code duplication for every GLXX-class.

**Comment by Spasi** [comment]
This a known issue (see #54), it would indeed be better to throw a more descriptive exception.
