### ISSUE TITLE
How Do I Use the LWJGL STB to Compress Images in Java? The ByteBuffer After Compression Is Converted to ByteArrayInputStream?                                                                            My question is： After the stbir_resize_uint8 method is used, the output stream cannot be converted to byte[], or the converted byte[] is unavailable.

### ISSUE THREAD

**Issue by Ian-lin-max** [LWJGL/lwjgl3#666]
How Do I Use the LWJGL STB to Compress Images in Java? The ByteBuffer After Compression Is Converted to ByteArrayInputStream?

My question is：
After the stbir_resize_uint8 method is used, the output stream cannot be converted to byte[], or the converted byte[] is unavailable.

Please provide the code. Thank you.

**Comment by SWinxy** [comment]
Congrats on being issue #666!

I'm not sure what you're asking. One of LWJGL's STB package includes STBImage. It can load and save many formats, but it can't compress them. You could use Java's [ImageIO](https://docs.oracle.com/en/java/javase/16/docs/api/java.desktop/javax/imageio/package-summary.html) package to read and write and edit images. You could use STBImage to load the images. Example [here](https://stackoverflow.com/a/44566972).

Note that both ImageIO and STBImage both can read/write BMP, GIF, JPEG, and PNG, so you could do either.

**Comment by Ian-lin-max** [comment]
> Congrats on being issue #666!
> 
> I'm not sure what you're asking. One of LWJGL's STB package includes STBImage. It can load and save many formats, but it can't compress them. You could use Java's [ImageIO](https://docs.oracle.com/en/java/javase/16/docs/api/java.desktop/javax/imageio/package-summary.html) package to read and write and edit images. You could use STBImage to load the images. Example [here](https://stackoverflow.com/a/44566972).
> 
> Note that both ImageIO and STBImage both can read/write BMP, GIF, JPEG, and PNG, so you could do either.

1. The STB of the LWJGL can compress images. 
    use  STBImageResize.stbir_resize_uint8(originalImage, originalWidth, originalHeight, 0, outputStream, rw, rh, 0, channel); 
2. My question is：
    After the stbir_resize_uint8 method is used, the output stream cannot be converted to byte[], or the converted byte[] is unavailable.

**Comment by SWinxy** [comment]
> 1. The STB of the LWJGL can compress images.
It can't. It can resize images, but not compress them.
> 2. After the stbir_resize_uint8 method is used, the output stream cannot be converted to byte[], or the converted byte[] is unavailable.
Not sure I understand. What's your code? And what are you going to do with it (ie, save it using STBImage, or load it to memory)?

**Comment by Ian-lin-max** [comment]
> > 1. The STB of the LWJGL can compress images.
> 
> It can't. It can resize images, but not compress them.
> 
> > 1. After the stbir_resize_uint8 method is used, the output stream cannot be converted to byte[], or the converted byte[] is unavailable.
> 
> Not sure I understand. What's your code? And what are you going to do with it (ie, save it using STBImage, or load it to memory)?

   1.     ByteBuffer outputStream = BufferUtils.createByteBuffer(imageBuffer.capacity());
   2.       STBImageResize.stbir_resize_uint8(originalImage, originalWidth, originalHeight, 0, outputStream, rw, rh, 0, channel);
   3.     STBImage.stbi_image_free(originalImage);
   4.     STBImageWrite.stbi_write_png("E:\\stbi_write2222222222222.png", rw, rh, channel, outputStream, 0);

   5.     int len = outputStream.limit() - outputStream.position();
   6.     byte[] bytes = new byte[len];
   7.     outputStream.get(bytes);
   8.     ByteToFile(bytes, "E:\\", "stream11111111.png");
1、The fourth line of code can output the resize image.
2、The code in lines 5 to 8 cannot output resize images.
3、I want lines 5 through 8 to output the picture correctly.  Can you provide such a code?

**Comment by Ian-lin-max** [comment]
> > 1. The STB of the LWJGL can compress images.
> 
> It can't. It can resize images, but not compress them.
> 
> > 1. After the stbir_resize_uint8 method is used, the output stream cannot be converted to byte[], or the converted byte[] is unavailable.
> 
> Not sure I understand. What's your code? And what are you going to do with it (ie, save it using STBImage, or load it to memory)?

Any results?

**Comment by SWinxy** [comment]
Are you calling `toByteArray()` on the output stream? Please share your code. It's impossible to know what's going on.

**Comment by XenoAmess** [comment]
1. `resize` is not `compress`

2.  still don't understand why you compress the picture in java game runtime...

I mean, shouldn't you have it already on disk?

If you really want it then please go https://github.com/apache/commons-compress

If you want the compressed picture still be a picture, please go https://github.com/apache/commons-imaging
