### ISSUE TITLE
Shaders fail to compile with empty error log

### ISSUE THREAD

**Issue by TrevorCow** [LWJGL/lwjgl3#667]
I am currently developing a game using LWJGL and OpenGL. My main development and target are windows but I also would like support for m1 and other arm devices. My program runs fine on windows, however, on my m1 MacBook pro the shaders fail to compile. I am not sure if this is an LWJGL library problem, a macOS OpenGL problem or I am just missing something.

lwjgl debug jar says: "[error][1] Shader [0] did not compile successfully:"
and GL20.glGetShaderInfoLog(id) also returns an empty string.

I am using these GLFW hints also
```java
glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 1);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
```

### Environment
* LWJGL version: `3.3.0-SNAPSHOT` 
* LWJGL build #: `11`
* Java version: `16`
* Platform: `macOS (arm M1)` 

vert:
```glsl
#version 410 core

layout(location = 0) in vec3 inPosition;
layout(location = 1) in vec2 inTextureCoordinate;
layout(location = 2) in float inBasicLight;

out vec2 textureCoordinate;
out float basicLight;

uniform int frameCount;
uniform mat4 mvp;

void main() {
    textureCoordinate = inTextureCoordinate;
    basicLight = inBasicLight;
    gl_Position = mvp * vec4(inPosition, 1.0);
}
```

frag:
```glsl
#version 410 core

layout(location = 0) in vec2 textureCoordinate;
layout(location = 1) in float basicLight;

out vec4 fragColor;

uniform sampler2D texImage;

void main() {
    fragColor = basicLight * texture(texImage, textureCoordinate);
}
```

Any help or insight into why this is happening would be greatly appreciated. Thank you

**Comment by httpdigest** [comment]
The interface declaration between your vertex and fragment shader are not strictly correct according to GLSL spec.
You use explicit layout location qualifiers on the fragment shader _inputs_ while not declaring the appropriate matching layout location qualifiers on the vertex shader _outputs_. So, GLSL is not sure whether it should match by name (the default) or by layout location qualifiers.

See also https://www.khronos.org/opengl/wiki/Shader_Compilation#Interface_matching for a description of the shader interface matching:

> For loose variables, an output matches with an input if:
> - The two variables represent the same interface. This is determined by checking the following, in order (the first overrides the second):
>   - If both of the variables are given a layout(location) setting that is equivalent.
>   - If both variables have the same name (and neither variable has a layout(location) qualifier).

So, either remove the layout location qualifiers on your vertex shader _output_ variables (which is what people usually do when using OpenGL GLSL); or assign corresponding layout location qualifiers on the fragment shader _inputs_.

**Comment by TrevorCow** [comment]
Oh right, my bad I will remove them from the fragment shader. However, the problem still stands. There is no shader error code or message or I really don't even know where to look. The shaders work fine on my windows 10 machine.

**Comment by tlf30** [comment]
I have done several projects with OpenGL that attempted to target MacOS. You will find a variety of issues that pertain to how MacOS has implemented OpenGL.  With their latest M1 chips they have deprecated OpenGL support. I know it is a LOT of work, but I would recommend building a second backend in Metal for your application. If possible you could use the LWJGL bindings for BGFX which would give you multiple backend rendering options for different platforms. Otherwise you are going to be fighting MacOS and its poor OpenGL support for a very long time.

**Comment by SWinxy** [comment]
> With their latest M1 chips they have deprecated OpenGL support. I know it is a LOT of work, but I would recommend building a second backend in Metal for your application.
According to [this blog](https://unlimited3d.wordpress.com/2020/12/09/opengl-on-apple-m1/), OpenGL still works on M1 macs (and also OpenGL wasn't deprecated on these new macs, but back in 2017 iirc). Apple removing things out of the blue is not uncommon, but currently OpenGL is still a usable API.

**Comment by TrevorCow** [comment]
Just for future reference, this was not solved, I have switched to Vulkan for rendering and I could not get M1 to compile OpenGL shaders.

**Comment by httpdigest** [comment]
@TrevorCow that may be, but this question is out-of-scope/off-topic for LWJGL, since LWJGL does not control the platform's OpenGL driver. The reason why those shaders won't work on macOS is unrelated to LWJGL.
