### ISSUE TITLE
Getting Started example window does not appear (Mac)

### ISSUE THREAD

**Issue by swinshu** [LWJGL/lwjgl3#668]
### Environment

* LWJGL version: 3.2.3
* LWJGL build #: not sure, using IntelliJ IDEA?
* Java version: 11
* Platform: macOS
* Module: ?

### Description

I'm relatively new to programming and am following this [LWJGL Getting Started guide](https://www.lwjgl.org/guide) on IntelliJ. I've followed these instructions from the guide:

> 1. Go to our download page, select channel, select zip bundle, review the options and choose the bindings you're interested in, then click on Generate Bundle.
> 2. When the download is complete, extract its contents in your project.
> 3. In IntelliJ, go to Project Structure > Libraries > New Project Library. Add all LWJGL .jar files (classes+natives) to the library and add the library as a dependency to your project module(s). You do not need to extract the native libraries.
> 4. If you also downloaded the sources, add the corresponding .jar files as sources to the LWJGL library. You do not need to download and attach the javadoc .jar files, IntelliJ generates javadoc directly from sources.

and have set -XstartOnFirstThread in VM options (by adding it before all the other options?).

Something that seems a bit weird is that the library that I added with all the LWJGL jar files doesn't appear in my sidebar under 'External Libraries', but everything seems to import correctly so I'm not really sure.

I used the command line template when creating my IntelliJ project, and then added a class named HelloWorld.class into the same package as my Main.class. I then copied the code from the Getting Started guide into the HelloWorld class and ran it.  'Hello LWJGL 3.2.3 build 13!' is output in the console and a Java exec window shows in my dock, but the window doesn't actually appear. Can anybody tell me why this is happening and how to fix it? Thank you!

**Comment by Spasi** [comment]
Note that `-XstartOnFirstThread` needs to be added as a JVM option to the Run Configuration. With IntelliJ you can find it at:

```
Run -> Edit configurations -> <select your program> -> Modify options -> Add VM options
```

A new input field will appear in which you can pass JVM options.
