### ISSUE TITLE
Report a bug!

### ISSUE THREAD

**Issue by Sam-zhuang** [LWJGL/lwjgl3#669]
### Environment

* LWJGL version: `3.2.3` 
* LWJGL build #: `Don't know`
* Java version: `11.0.11`
* Platform: `Windows`
* Module: `core`
* IntelliJ IDEA version: `2021.1.3`

### Description
When I was studying using LWJGL, I wrote this code and run it in IDEA. It was so strange, desired result should be a windows with black background appears, a colorful triangle is spinning in it. But actual result was a window appears and disappears immediately. And it ALWAYS happens.
And then, this message printed on the console:

 `A fatal error has been detected by the Java Runtime Environment:`

  `EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000001d15c550000, pid=3608, tid=10536`

 `JRE version: Java(TM) SE Runtime Environment 18.9 (11.0.11+9) (build 11.0.11+9-LTS-194)`
` Java VM: Java HotSpot(TM) 64-Bit Server VM 18.9 (11.0.11+9-LTS-194, mixed mode, tiered, compressed oops, g1 gc, windows-md64)`
` Problematic frame:`
` C  0x000001d15c550000`

 `No core dump will be written. Minidumps are not enabled by default on client versions of Windows`

 `An error report file with more information is saved as:`
 `D:\Java\Worlder\hs_err_pid3608.log`

` If you would like to submit a bug report, please visit:`
`   https://bugreport.java.com/bugreport/crash.jsp`
 `The crash happened outside the Java Virtual Machine in native code.`
` See problematic frame for where to report the bug.`

I followed the file generate by JRE, I found out the problem is caused by org.lwjgl.system.JNI.invokePI(long param0, long __functionAddress), but I cannot find the source of the method.
I send this feedback to Oracle too, you can talk about this issue with them.
[hs_err_pid3608.log](https://github.com/LWJGL/lwjgl3/files/6900248/hs_err_pid3608.log)
The source code:
```
package net.worlder;

import org.lwjgl.glfw.GLFWErrorCallback;
import org.lwjgl.glfw.GLFWKeyCallback;
import org.lwjgl.glfw.GLFWVidMode;
import org.lwjgl.opengl.GL;

import java.nio.IntBuffer;

import static org.lwjgl.glfw.GLFW.*;
import static org.lwjgl.opengl.GL11.*;
import static org.lwjgl.system.MemoryUtil.*;

/**
 * LWJGL test.
 * @author shzbj
 */
public class Main {
    private final GLFWErrorCallback errorCallback =
            GLFWErrorCallback.createPrint(System.err);
    private final GLFWKeyCallback keyCallback = new GLFWKeyCallback() {
        @Override
        public void invoke(long window, int key, int scancode, int action, int mods) {
            if (key == GLFW_KEY_ESCAPE && action == GLFW_PRESS) {
                glfwSetWindowShouldClose(window, true);
            }
        }
    };
    private final IntBuffer width = memAllocInt(1);
    private final IntBuffer height = memAllocInt(1);
    private long window;

    public static void main(String[] args) {
        Main main = new Main();
        main.init();
        main.run();
    }

    private void init() {
        glfwSetErrorCallback(errorCallback);
        if (!glfwInit()) {
            throw new RuntimeException("Init GLFW failed");
        }
        window = glfwCreateWindow(600, 600, "Worlder", NULL, NULL);
        if (window == NULL) {
            glfwTerminate();
            throw new RuntimeException("Create window failed");
        }
    }

    private void run() {
        GLFWVidMode vidMode = glfwGetVideoMode(glfwGetPrimaryMonitor());
        glfwSetWindowPos(window, (vidMode.width() - 640) / 2, (vidMode.height() - 480) / 2);
        glfwMakeContextCurrent(window);
        GL.createCapabilities();

        glfwSwapInterval(1);
        glfwSetKeyCallback(window, keyCallback);

        while (!glfwWindowShouldClose(window)) {
            float ratio;
            
            glfwGetFramebufferSize(window, width, height);
            ratio = width.get() / (float) height.get();

            width.rewind();
            height.rewind();

            glViewport(0, 0, width.get(), height.get());
            glClear(GL_COLOR_BUFFER_BIT);

            glMatrixMode(GL_PROJECTION);
            glLoadIdentity();
            glOrtho(-ratio, ratio, -1f, 1f, 1f, -1f);
            glMatrixMode(GL_MODELVIEW);
            
            glLoadIdentity();
            glRotatef((float) glfwGetTime() * 50f, 0f, 0f, 1f);

            glBegin(GL_TRIANGLES);
            glColor3f(1f, 0f, 0f);
            glVertex3f(-0.6f, -0.4f, 0f);
            glColor3f(0f, 1f, 0f);
            glVertex3f(0.6f, -0.4f, 0f);
            glColor3f(0f, 0f, 1f);
            glVertex3f(0f, 0.6f, 0f);
            glEnd();

            
            glfwSwapBuffers(window);
            glfwPollEvents();
            
            width.flip();
            height.flip();

            memFree(width);
            memFree(height);
            
            glfwDestroyWindow(window);
            keyCallback.free();

            glfwTerminate();
            errorCallback.free();
        }
        destroy();
    }

    private void destroy() {
        memFree(width);
        memFree(height);

        glfwDestroyWindow(window);
        keyCallback.free();
        glfwTerminate();
        errorCallback.free();
    }
}
```

**Comment by elect86** [comment]
ps: give it a title

**Comment by ClaasJG** [comment]
You free your buffers (width / height) each iteration. You can either allocate them once on initialization and free them on destruction or you could take a look how the width / height buffers are handled at https://www.lwjgl.org/guide .

**Comment by SWinxy** [comment]
> You free your buffers (width / height) each iteration.

Not only that, but you're also telling GLFW to destroy itself as well as freeing other important pieces of memory. In agreement with @ClaasJG, you should check out the [getting started guide](https://www.lwjgl.org/guide) for clean code.

**Comment by httpdigest** [comment]
Closing this as there are _very_ obvious bugs in the user code itself and the chosen type of the issue (from the template) is wrong. It is _not_ a bug to report against LWJGL, but a "help me debug my code" kind of question.
For those kinds of questions, Stackoverflow _really_ is the better place to ask a question. GitHub issues are more like for _actual_ bugs in LWJGL itself or for questions about bindings or feature requests, etc.
