### ISSUE TITLE
Remotery bindings not working

### ISSUE THREAD

**Issue by kaphula** [LWJGL/lwjgl3#670]
### Environment

* LWJGL version: `3.2.3` 
* LWJGL build #: `Don't know what this means`
* Java version: `11.0.6`
* Platform: `Linux`
* Module: `lwjgl-remotery`

### Description

I am having hard time getting the Remotery bindings to work. My app connects to the web browser and I am able to send log messages to the browser window. However, I can't get any profiling information even though I am sampling pieces of code from my app using Remotery.

This is what I see in the browser view when my app is connected. I get the same results with Firefox and Chromium browsers.

![image](https://user-images.githubusercontent.com/36015558/127725770-1f5b1765-c02a-41cb-9331-fcf8778ddfae.png)

Here's the code I use for initializing and sampling:

```kotlin
import com.badlogic.gdx.utils.Disposable
import kotlinx.support.jdk7.use
import org.lwjgl.system.MemoryStack
import org.lwjgl.util.remotery.Remotery
import org.lwjgl.util.remotery.RemoteryGL

class RemoteryProfiler: Disposable {
    val globalInstance: Long
    init {
        var instance = 0L
        MemoryStack.stackPush().use { stack ->
            val pb = stack.callocPointer(1);
            Remotery.rmt_CreateGlobalInstance(pb);
            instance = pb.get(0);
            RemoteryGL.rmt_BindOpenGL();
            Remotery.rmt_SetCurrentThreadName("Render");
        }
        globalInstance = instance
    }


    inline fun sampleCPU(name: String, aggregate: Boolean, crossinline action: () -> Unit) {
        val flags = if (aggregate) Remotery.RMTSF_Aggregate else Remotery.RMTSF_None
        Remotery.rmt_LogText("Sampling CPU " + name)
        Remotery.rmt_BeginCPUSample(name, flags, null)
        action()
        Remotery.rmt_EndCPUSample()
    }

    inline fun sampleGPU(name: String, crossinline action: () -> Unit) {
        Remotery.rmt_LogText("Sampling GPU " + name)
        RemoteryGL.rmt_BeginOpenGLSample(name, null)
        action()
        RemoteryGL.rmt_EndOpenGLSample()
    }

    override fun dispose() {
        if (globalInstance != 0L) {
            RemoteryGL.rmt_UnbindOpenGL()
            Remotery.rmt_DestroyGlobalInstance(globalInstance)
        }
    }
}

```

I used this code as an example: https://github.com/code-disaster/libgdx-snippets/tree/master/src/main/java/com/badlogic/gdx/profiler

**Comment by Hayakhan1306** [comment]
> ### Environment
> * LWJGL version: `3.2.3`
> * LWJGL build #: `Don't know what this means`
> * Java version: `11.0.6`
> * Platform: `Linux`
> * Module: `lwjgl-remotery`
> 
> ### Description
> I am having hard time getting the Remotery bindings to work. My app connects to the web browser and I am able to send log messages to the browser window. However, I can't get any profiling information even though I am sampling pieces of code from my app using Remotery.
> 
> This is what I see in the browser view when my app is connected. I get the same results with Firefox and Chromium browsers.
> 
> ![image](https://user-images.githubusercontent.com/36015558/127725770-1f5b1765-c02a-41cb-9331-fcf8778ddfae.png)
> 
> Here's the code I use for initializing and sampling:
> 
> ```kotlin
> import com.badlogic.gdx.utils.Disposable
> import kotlinx.support.jdk7.use
> import org.lwjgl.system.MemoryStack
> import org.lwjgl.util.remotery.Remotery
> import org.lwjgl.util.remotery.RemoteryGL
> 
> class RemoteryProfiler: Disposable {
>     val globalInstance: Long
>     init {
>         var instance = 0L
>         MemoryStack.stackPush().use { stack ->
>             val pb = stack.callocPointer(1);
>             Remotery.rmt_CreateGlobalInstance(pb);
>             instance = pb.get(0);
>             RemoteryGL.rmt_BindOpenGL();
>             Remotery.rmt_SetCurrentThreadName("Render");
>         }
>         globalInstance = instance
>     }
> 
> 
>     inline fun sampleCPU(name: String, aggregate: Boolean, crossinline action: () -> Unit) {
>         val flags = if (aggregate) Remotery.RMTSF_Aggregate else Remotery.RMTSF_None
>         Remotery.rmt_LogText("Sampling CPU " + name)
>         Remotery.rmt_BeginCPUSample(name, flags, null)
>         action()
>         Remotery.rmt_EndCPUSample()
>     }
> 
>     inline fun sampleGPU(name: String, crossinline action: () -> Unit) {
>         Remotery.rmt_LogText("Sampling GPU " + name)
>         RemoteryGL.rmt_BeginOpenGLSample(name, null)
>         action()
>         RemoteryGL.rmt_EndOpenGLSample()
>     }
> 
>     override fun dispose() {
>         if (globalInstance != 0L) {
>             RemoteryGL.rmt_UnbindOpenGL()
>             Remotery.rmt_DestroyGlobalInstance(globalInstance)
>         }
>     }
> }
> ```
> 
> I used this code as an example: https://github.com/code-disaster/libgdx-snippets/tree/master/src/ main/java/com/badlogic/gdx/profiler

**Comment by Hayakhan1306** [comment]
https://github.com/code-disaster/libgdx-snippets/tree/master/src/

**Comment by Spasi** [comment]
The current viewer (i.e. `/vis/index.html` in the Remotery repository) is not compatible with the Remotery bindings in LWJGL 3.2.3. Since there are no Remotery releases available, you need to reset that repository to an older commit, that matches the source used by LWJGL 3.2.3.

The next 3.3.0 snapshot will include updated Remotery bindings that are compatible with the current viewer.
