### ISSUE TITLE
Release of 3.2.4?

### ISSUE THREAD

**Issue by davidgiga1993** [LWJGL/lwjgl3#671]
I just wanted to ask when will the next minor update `3.2.4` be released?

`3.2.3` causes some issues on certain macs (see #610) so I'm currently working off a snapshot version and a libgdx fork to make it work, which is not ideal

**Comment by SWinxy** [comment]
Contributions come in [spikes](https://github.com/LWJGL/lwjgl3/graphs/contributors?from=2019-01-01&to=2021-08-07&type=c) from Spasi. Most people I know on the discord work with the snapshot version. I would personally recommend LibGDX to go ahead and at least try with the snapshot, since it's surprisingly stable.

**Comment by davidgiga1993** [comment]
Yes I have my own libgdx fork anyways and I'm currently using the snapshot in production :) Just though I ask if there is a roadmap or something

**Comment by mpfaff** [comment]
> Contributions come in [spikes](https://github.com/LWJGL/lwjgl3/graphs/contributors?from=2019-01-01&to=2021-08-07&type=c) from Spasi. Most people I know on the discord work with the snapshot version. I would personally recommend LibGDX to go ahead and at least try with the snapshot, since it's surprisingly stable.

Where can I download the snapshot version? Or is there a maven repo for it?

**Comment by octylFractal** [comment]
https://www.lwjgl.org/customize shows you configuration for the SNAPSHOT. You'll need the Sonatype Snapshots repo.

**Comment by mpfaff** [comment]
Thanks!

**Comment by EwoutH** [comment]
I think LWJGL could benefit from more frequent (minor) releases. Not every project is comfortable with using snapshots or unstable releases, and the last release is now over 2 years old. The [milestones](https://github.com/LWJGL/lwjgl3/milestones) also aren’t updated anymore.
