### ISSUE TITLE
Crash application on mac os apple silicon m1

### ISSUE THREAD

**Issue by Saradey** [LWJGL/lwjgl3#672]
### Environment

* LWJGL version: `3.2.3` 
* LWJGL build #: `Don't know what this means`
* Java version: `java 8 or java 11`
* Platform: `macOS apple silicon m1`
* Module: `core`

### Description

I try run application, the application starts and crashes, stack trace:
```

Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/68/gp4rr8657qd3kl8fk78gb8fw0000gn/T/lwjglevgeny/3.2.3-build-13/liblwjgl.dylib: dlopen(/private/var/folders/68/gp4rr8657qd3kl8fk78gb8fw0000gn/T/lwjglevgeny/3.2.3-build-13/liblwjgl.dylib, 
1): no suitable image found.  Did find:
/private/var/folders/68/gp4rr8657qd3kl8fk78gb8fw0000gn/T/lwjglevgeny/3.2.3-build-13/liblwjgl.dylib: no matching architecture in universal wrapper
/private/var/folders/68/gp4rr8657qd3kl8fk78gb8fw0000gn/T/lwjglevgeny/3.2.3-build-13/liblwjgl.dylib: no matching architecture in universal wrapper
```

**Comment by TrevorCow** [comment]
I'm pretty sure that M1 (and windows ARM) require LWJGL version 3.3.0 or higher.

**Comment by mcendu** [comment]
Have you tried installing Rosetta? LWJGL 3.2.3 don't come with Mac ARM64 natives precompiled.
