### ISSUE TITLE
Vulkan: VkFramebufferCreateInfo doesnt allow for just passing the attachmentCount

### ISSUE THREAD

**Issue by hYdos** [LWJGL/lwjgl3#673]
### Environment

* LWJGL version: `3.3.0` 
* LWJGL build #: `SNAPSHOT`
* Java version: `java.version`
* Platform: `Linux`
* Module: `Vulkan`

### Description Of Issue

for ImagelessFramebuffers (A Core feature of vulkan 1.2), you need to be able to specify just the count of attachments. Specifying the attachments causes problems within Khronos Validation Layers. we have tried `VkFramebufferCreateInfo.nattachmentCount(framebufferInfo.address(), 2);` but this unfortunately doesn't work due to the checks causing a NullPointerException

**Comment by OroArmor** [comment]
The specific lines that cause the checks to fail are: https://github.com/LWJGL/lwjgl3/blob/e4a6cc863f469ea8acfe3c2158f2c77d0c0aa95d/modules/lwjgl/vulkan/src/generated/java/org/lwjgl/vulkan/VkFramebufferCreateInfo.java#L452-L461

**Comment by SWinxy** [comment]
The attachment counts are automatically generated when you pass in the `pAttachments` as a convenience I would guess.
https://github.com/LWJGL/lwjgl3/blob/f57d550298b8bcb607658ad0aa9f693caac1c136/modules/lwjgl/vulkan/src/generated/java/org/lwjgl/vulkan/VkFramebufferCreateInfo.java#L444

**Comment by OroArmor** [comment]
Yes, but the issue is that you cannot set the attachment count manually, and passing in a long buffer full of VK_NULL crashes the driver

**Comment by httpdigest** [comment]
As a work-around you can disable those consistency-checks in LWJGL in the meantime:
- https://github.com/LWJGL/lwjgl3/blob/master/modules/lwjgl/core/src/main/java/org/lwjgl/system/Checks.java#L37
- https://github.com/LWJGL/lwjgl3/blob/master/modules/lwjgl/core/src/main/java/org/lwjgl/system/Configuration.java#L186

by either calling `Configuration.DISABLE_CHECKS.set(true)` or by setting the system property `org.lwjgl.util.NoChecks` to `true`.

**Comment by Spasi** [comment]
@hYdos Thanks! This was a bug in [lwjgl3-vulkangen](https://github.com/LWJGL/lwjgl3-vulkangen) that has been fixed with https://github.com/LWJGL/lwjgl3-vulkangen/commit/f62d362c032a2216168b0ce9cf303c321f3fa4b0. The validation will be removed in the next 3.3.0 snapshot.
