### ISSUE TITLE
VkPipelineViewportStateCreateInfo exposes useless setters

### ISSUE THREAD

**Issue by TrevorCow** [LWJGL/lwjgl3#674]
### Environment

* LWJGL version: `3.3.0-SNAPSHOT` 
* LWJGL build #: `11`
* Java version: `16`
* Platform: `Windows`
* Module: `Vulkan`

### Description

When creating a `VkPipelineViewportStateCreateInfo` it seems that `viewportCount` and `scissorCount` are ignored and instead use the buffers length as the count. I assume this is intended as other Vulkan functions use the buffer size however I'm wondering if there is any reason that that `viewportCount` and `scissorCount` are kept visible if they do nothing.

**Comment by Spasi** [comment]
The Vulkan bindings are auto-generated from [Vulkan-Docs](https://github.com/KhronosGroup/Vulkan-Docs). This is how `VkPipelineViewportStateCreateInfo` is specified there:

```xml
<type category="struct" name="VkPipelineViewportStateCreateInfo">
    <member values="VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO"><type>VkStructureType</type> <name>sType</name></member>
    <member optional="true">const <type>void</type>*            <name>pNext</name></member>
    <member optional="true"><type>VkPipelineViewportStateCreateFlags</type>    <name>flags</name></member>
    <member optional="true"><type>uint32_t</type>               <name>viewportCount</name></member>
    <member noautovalidity="true" optional="true" len="viewportCount">const <type>VkViewport</type>*      <name>pViewports</name></member>
    <member optional="true"><type>uint32_t</type>               <name>scissorCount</name></member>
    <member noautovalidity="true" optional="true" len="scissorCount">const <type>VkRect2D</type>*        <name>pScissors</name></member>
</type>
```

The `noautovalidity` attribute in such cases basically decouples the array member from the corresponding length/count member, i.e. they may be set independently from each other. Normally LWJGL would hide the `viewportCount`/`scissorCount` setters, but `noautovalidity` overrides this behavior.

As for why `noautovalidity` is there, this is what I found in the Vulkan specification:

> `VK_DYNAMIC_STATE_VIEWPORT` specifies that the `pViewports` state in `VkPipelineViewportStateCreateInfo` will be ignored and must be set dynamically with `vkCmdSetViewport` before any drawing commands. The number of viewports used by a pipeline **is still specified** by the `viewportCount` member of `VkPipelineViewportStateCreateInfo`.

> `VK_DYNAMIC_STATE_SCISSOR` specifies that the `pScissors` state in `VkPipelineViewportStateCreateInfo` will be ignored and must be set dynamically with `vkCmdSetScissor` before any drawing commands. The number of scissor rectangles used by a pipeline **is still specified** by the `scissorCount` member of `VkPipelineViewportStateCreateInfo`.
