### ISSUE TITLE
meshoptimizer simplifySloppy does size checks with the wrong types and incorrectly reports bad parameters

### ISSUE THREAD

**Issue by javster101** [LWJGL/lwjgl3#675]
### Environment

* LWJGL version: 3.3.0-SNAPSHOT
* Java version: Java 16
* Platform: Windows
* Module: meshoptimizer

### Description

meshopt_SimplifySloppy does the following check to ensure that the vertex position buffer is the right size:
`check(vertex_positions, vertex_count * vertex_positions_stride);` (MeshOptimizer.java:meshopt_simplifySloppy());

The issue, from what I can tell, is that the vertex_positions argument must be a FloatBuffer and therefore returns
the amount of floats remaining when `.remaining()` is called, while the `vertex_positions_stride` argument is expected to be in bytes. Therefore, it thinks that there are four times less elements than are needed and it throws the following exception:

```
 java.lang.IllegalArgumentException: Number of remaining elements is 9723, must be at least 38892
 	at org.lwjgl/org.lwjgl.system.Checks.throwIAE(Checks.java:545)
 	at org.lwjgl/org.lwjgl.system.Checks.checkBuffer(Checks.java:347)
 	at org.lwjgl/org.lwjgl.system.Checks.check(Checks.java:449)
 	at org.lwjgl.meshoptimizer/org.lwjgl.util.meshoptimizer.MeshOptimizer.meshopt_simplifySloppy(MeshOptimizer.java:840)
 	at com.opengg.core/com.opengg.core.model.ModelUtil.autoSimplifyToTargetIndexCount(ModelUtil.java:46)

```

This is the relevant code in my codebase that reproduces it.

```
IntBuffer indices = mesh.getIndexBuffer();
FloatBuffer vertices = MemoryUtil.memAllocFloat(mesh.getVertices().size() * 3);
for(var vertex : mesh.getVertices()) {
  vertices.put(vertex.position.x).put(vertex.position.y).put(vertex.position.z);
}
vertices.rewind();

IntBuffer newIndices = MemoryUtil.memAllocInt(targetIndexCount);
var optimizedListSize = MeshOptimizer.meshopt_simplifySloppy(newIndices, indices, vertices, mesh.getVertices().size(), 12, targetIndexCount);
```

Am I doing something wrong here? I can make a PR to fix it if needed, but I'm not sure if I'm using this wrong.

**Comment by httpdigest** [comment]
From what I can see, this is a legitimate bug and you are doing everything correctly, yes.
When looking at the API usage on https://meshoptimizer.org/#simplification it becomes apparent that the `vertex_positions_stride` parameter is in units of bytes, so:
```java
check(vertex_positions, vertex_count * vertex_positions_stride);
```
in LWJGL's MeshOptimizer should probably read as:
```java
check(vertex_positions, vertex_count * (vertex_positions_stride >>> 2));
```
instead.
However, when doing that, we can _only_ have strides that are multiples of `4` bytes, which might be the case anyways when using a `FloatBuffer`, so it's probably fine.

**Comment by javster101** [comment]
I believe that meshoptimizer asserts that the stride is divisible by `sizeof(float)`, so only allowing strides with a multiple of four is fine.

**Comment by Spasi** [comment]
@javster101 Thanks!
