### ISSUE TITLE
GLFW doesn't return from glfwInit()

### ISSUE THREAD

**Issue by Trikzon** [LWJGL/lwjgl3#676]
### Environment

* LWJGL version: `3.0.0` 
* LWJGL build #: `11`
* Java version: `16`
* Platform: `macOS with m1 chip`

### Description

Running the Getting Started example doesn't create a window. The only console output (in debug mode) is:
```
18:57:03: Executing task ':HelloWorld.main()'...

Starting Gradle Daemon...
Connected to the target VM, address: '127.0.0.1:62784', transport: 'socket'
Gradle Daemon started in 1 s 733 ms
> Task :compileJava UP-TO-DATE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE
> Task :compileTestJava UP-TO-DATE
> Task :processTestResources UP-TO-DATE
> Task :testClasses UP-TO-DATE
Disconnected from the target VM, address: '127.0.0.1:62784', transport: 'socket'
Connected to the target VM, address: 'localhost:62789', transport: 'socket'

> Task :HelloWorld.main()
Hello LWJGL 3.3.0 build 11!
```

Using breakpoints, I found that the program enters the `GLFW.glfwInit()` function, invokes a native function, but doesn't return from it.
This causes the program to run forever (as far as I know. It's possible it will return for some reason in 500 hours) without executing any code after the init function.

**Comment by Spasi** [comment]
Is `-XstartOnFirstThread` passed as a JVM parameter?

**Comment by Trikzon** [comment]
It wasn't, but after trying with that JVM parameter nothing changes.
I know I'm not providing a lot of information to work with here, but there really isn't any

What's strange is that I also make Minecraft mods which requires a development environment with Minecraft which depends on LWJGL. That development environment works and creates a window when run

**Comment by Trikzon** [comment]
To simplify the environment, I made a simple java project and added the lwjgl jars as libraries.
This is the output (note with `-XstartOnFirstThread` at the end)

```
/Library/Java/JavaVirtualMachines/temurin-16.jdk/Contents/Home/bin/java -javaagent:/Users/trikzon/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5080.55/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=52446:/Users/trikzon/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/212.5080.55/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8 -classpath /Users/trikzon/Sources/untitled/out/production/untitled:/Users/trikzon/Sources/untitled/lwjgl-nightly-2021-08-29-custom/joml-1.10.1.jar:/Users/trikzon/Sources/untitled/lwjgl-nightly-2021-08-29-custom/lwjgl-assimp-natives-macos.jar:/Users/trikzon/Sources/untitled/lwjgl-nightly-2021-08-29-custom/lwjgl-assimp.jar:/Users/trikzon/Sources/untitled/lwjgl-nightly-2021-08-29-custom/lwjgl-glfw-natives-macos.jar:/Users/trikzon/Sources/untitled/lwjgl-nightly-2021-08-29-custom/lwjgl-glfw.jar:/Users/trikzon/Sources/untitled/lwjgl-nightly-2021-08-29-custom/lwjgl-natives-macos.jar:/Users/trikzon/Sources/untitled/lwjgl-nightly-2021-08-29-custom/lwjgl-openal-natives-macos.jar:/Users/trikzon/Sources/untitled/lwjgl-nightly-2021-08-29-custom/lwjgl-openal.jar:/Users/trikzon/Sources/untitled/lwjgl-nightly-2021-08-29-custom/lwjgl-opengl-natives-macos.jar:/Users/trikzon/Sources/untitled/lwjgl-nightly-2021-08-29-custom/lwjgl-opengl.jar:/Users/trikzon/Sources/untitled/lwjgl-nightly-2021-08-29-custom/lwjgl-stb-natives-macos.jar:/Users/trikzon/Sources/untitled/lwjgl-nightly-2021-08-29-custom/lwjgl-stb.jar:/Users/trikzon/Sources/untitled/lwjgl-nightly-2021-08-29-custom/lwjgl.jar HelloWorld -XstartOnFirstThread

Hello LWJGL 3.3.0 build 11!
```

The program still gets stuck in the native function in GLFW.glfwInit() and no window appears

**Comment by httpdigest** [comment]
This:
```
... -custom/lwjgl.jar HelloWorld -XstartOnFirstThread
```
is _not_ setting a **JVM argument** but setting a **program argument** (i.e. what gets passed in the `String[] args` argument to the main method). All JVM arguments must be specified _before_ the main class name or before the `-jar` argument (when using `-jar` - not your case). Everything specified _after_ the main class name is interpreted as a simple _program argument_ passed to the main method.

Use:
```
... -custom/lwjgl.jar -XstartOnFirstThread HelloWorld
```

**Comment by Trikzon** [comment]
Ah, thank you for the help. I thought something was off, but I wasn't sure. Last time I had to set jvm arguments, it was simply on the run configuration screen. I think in one of the updates since IntelliJ decided to hide that text box into the "Modify options" button.

With that added to the jvm options it works. Thanks again :)
