### ISSUE TITLE
Submodules can no longer find Native Bindings

### ISSUE THREAD

**Issue by Speiger** [LWJGL/lwjgl3#677]
### Environment

* LWJGL version: 3.3.0
* LWJGL build #: Shapshot-9?
* Java version: 1.8
* IDE: Eclipse Neon (Using Gradle)
* Platform: Windows
* Modules: Core/GL/AL/STB/Jemalloc

### Description
I very recently split my engine apart from game + engine in 1 project to have 2 projects.
And link the engine via a "GitModule".
Turns out Version 3.3.0 does not like that and can not find Natives anymore. The game starts up normal, but triggers breakpoints that LWJGL 3 couldn't find its natives and i have to manually let it skip these breakpoints to finish loading the setup.

The code that triggers this is:
```
GLFWErrorCallback.createPrint(System.err).set();
```
Which is exactly like this:
https://github.com/LWJGL/lwjgl3-demos/blob/main/src/org/lwjgl/demo/opengl/instancing/GrassDemo.java#L94

After testing around i found out that it is only 3.3.0 that has these issues the moment i switch back to 3.2.4 everything works without issues. Also trying only the submodule or the main project with 3.3.0 causes the same behavior. 

Not sure what causes this though.

**Comment by Spasi** [comment]
Please run the application with `-Dorg.lwjgl.util.Debug=true -Dorg.lwjgl.util.DebugLoader=true` and post the output here.

**Comment by Speiger** [comment]
```
[LWJGL] Version: 3.3.0 build 11
[LWJGL] 	 OS: Windows 10 v10.0
[LWJGL] 	JRE: Windows amd64 1.8.0_275
[LWJGL] 	JVM: OpenJDK 64-Bit Server VM v25.275-b01 by ojdkbuild
[LWJGL] Loading JNI library: lwjgl
[LWJGL] 	Module: org.lwjgl
[LWJGL] 	Using SharedLibraryLoader...
[LWJGL] 	Found at: C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.3.0-build-11\lwjgl.dll
[LWJGL] 	Found at: C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.3.0-build-11\lwjgl.dll
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.3.0-build-11\lwjgl.dll
[LWJGL] Closure Registry: simple
[LWJGL] Loading library: jemalloc
[LWJGL] 	Module: org.lwjgl.jemalloc
[LWJGL] 	Using SharedLibraryLoader...
[LWJGL] 	Found at: C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.3.0-build-11\jemalloc.dll
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.3.0-build-11\jemalloc.dll
[LWJGL] MemoryUtil allocator: JEmallocAllocator
[LWJGL] Loading library: glfw
[LWJGL] 	Module: org.lwjgl.glfw
[LWJGL] 	Using SharedLibraryLoader...
[LWJGL] 	Found at: C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.3.0-build-11\glfw.dll
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.3.0-build-11\glfw.dll
[LWJGL] Loading JNI library: lwjgl_opengl
[LWJGL] 	Module: org.lwjgl.opengl
[LWJGL] 	Using SharedLibraryLoader...
[LWJGL] 	Found at: C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.3.0-build-11\lwjgl_opengl.dll
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.3.0-build-11\lwjgl_opengl.dll
[LWJGL] Loading library: opengl32
[LWJGL] 	Module: org.lwjgl.opengl
[LWJGL] 	opengl32.dll not found in org.lwjgl.librarypath=C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.3.0-build-11
[LWJGL] 	Loaded from system paths: C:\Windows\SYSTEM32\opengl32.dll
```
This is all it outputs.

Here is a image of of the Stacktrace that gets automatically opened when i try to start my application.
The file from last time i checked exists.
![image](https://user-images.githubusercontent.com/2556269/131270891-bd648835-d784-4db9-b35d-d716119ed73d.png)

**Comment by Speiger** [comment]
Here is the log with 3.2.4:
```
[LWJGL] Version: 3.2.4 build 6
[LWJGL] 	 OS: Windows 10 v10.0
[LWJGL] 	JRE: Windows amd64 1.8.0_275
[LWJGL] 	JVM: OpenJDK 64-Bit Server VM v25.275-b01 by ojdkbuild
[LWJGL] Loading JNI library: lwjgl
[LWJGL] 	Module: org.lwjgl
[LWJGL] 	Using SharedLibraryLoader...
[LWJGL] 	Found at: C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.2.4-build-6\lwjgl.dll
[LWJGL] 	Found at: C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.2.4-build-6\lwjgl.dll
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.2.4-build-6\lwjgl.dll
[LWJGL] Loading library: jemalloc
[LWJGL] 	Module: org.lwjgl.jemalloc
[LWJGL] 	Using SharedLibraryLoader...
[LWJGL] 	Found at: C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.2.4-build-6\jemalloc.dll
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.2.4-build-6\jemalloc.dll
[LWJGL] MemoryUtil allocator: JEmallocAllocator
[LWJGL] Loading library: glfw
[LWJGL] 	Module: org.lwjgl.glfw
[LWJGL] 	Using SharedLibraryLoader...
[LWJGL] 	Found at: C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.2.4-build-6\glfw.dll
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.2.4-build-6\glfw.dll
[LWJGL] Loading JNI library: lwjgl_opengl
[LWJGL] 	Module: org.lwjgl.opengl
[LWJGL] 	Using SharedLibraryLoader...
[LWJGL] 	Found at: C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.2.4-build-6\lwjgl_opengl.dll
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.2.4-build-6\lwjgl_opengl.dll
[LWJGL] Loading library: opengl32
[LWJGL] 	Module: org.lwjgl.opengl
[LWJGL] 	opengl32.dll not found in org.lwjgl.librarypath=C:\Users\Speiger\AppData\Local\Temp\lwjglSpeiger\3.2.4-build-6
[LWJGL] 	Loaded from system paths: C:\Windows\SYSTEM32\opengl32.dll
```

**Comment by httpdigest** [comment]
Just to clarify:
- When you run the application _without_ the debugger, everything works fine
- When you enable the "All exceptions breakpoint" in the debugger, and run the app with the debugger attached, in LWJGL 3.3.0 the breakpoint in `URLClassLoader.JarLoader.getJarFile(URL)` on the `throw` statement is triggered, and in LWJGL 3.2.4 this breakpoint is _not_ triggered
- When you continue from that breakpoint, eventually everything is loaded and the app runs fine

So, the problem is not that the native shared libraries cannot be found (they will be found _eventually_) but that there is some class loader "issue" which leads to the exception being thrown as part of the process.

**Comment by Speiger** [comment]
> When you run the application without the debugger, everything works fine

No when i run the Application with Version 3.2.4 everything runs fine. If I run with 3.3.0 it basically forces me to skip the "forced" breakpoints every single time the software starts. I forgot to take out the debugger in 3.2.4 it just printed into the logs and I thought "huh maybe also add that because it could be useful"

> When you enable the "All exceptions breakpoint" in the debugger, and run the app with the debugger attached, in LWJGL 3.3.0 the breakpoint in URLClassLoader.JarLoader.getJarFile(URL) on the throw statement is triggered, and in LWJGL 3.2.4 this breakpoint is not triggered

I dunno even where to "enable" that feature. But trying to use "Skip All Breakpoints" does not work.

> When you continue from that breakpoint, eventually everything is loaded and the app runs fine

Yeah, this is correct. 

> So, the problem is not that the native shared libraries cannot be found (they will be found eventually) but that there is some class loader "issue" which leads to the exception being thrown as part of the process.

This sounds correct, but on the other hand also not. Because if that is a "Classloader" issue and the stuff that breaks is LWJGL3 Itself (and that does not add a classloader) then I kinda doubt its a Classloader issue. At least not the cause of it.

**Comment by httpdigest** [comment]
Can you provide your complete project setup? You seem to be using Gradle and also an Eclipse version (Neon) that is 5 years old. You also said something about "GitModule" which I don't know what that is supposed to be.
If you can, simply upload your project to GitHub so that we can have a look.

**Comment by Speiger** [comment]
@httpdigest its a normal Git SubModule. 
https://git-scm.com/book/de/v2/Git-Tools-Submodule

About the Project. Eh i can only show the "Engine" not the Project itself. The engine is added via submodule.

**Comment by httpdigest** [comment]
What I would like to have is a Minimal, Complete and Reproducible Example (MCVE) that can readily be executed and the issue reproduced with.
So, you could just include the engine and a single Main class with a main method having just `GLFWErrorCallback.createPrint(System.err).set();` (as you said that this would trigger the exception).

**Comment by Speiger** [comment]
Give me like 5-10 mins.

**Comment by Speiger** [comment]
@httpdigest https://github.com/Speiger/LWJGL3-SubModule-Issue
Here is a project. I made sure its useable and is causing this bug.

**Comment by httpdigest** [comment]
```
$ chmod +x gradlew
$ ./gradlew clean package
Downloading https://services.gradle.org/distributions/gradle-6.3-bin.zip
.........10%..........20%..........30%.........40%..........50%..........60%.........70%..........80%..........90%..........100%

Welcome to Gradle 6.3!

Here are the highlights of this release:
 - Java 14 support
 - Improved error messages for unexpected failures

For more details see https://docs.gradle.org/6.3/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Task 'package' not found in root project 'LWJGL3Issue'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s
```

**Comment by Speiger** [comment]
Yeah i forgot to add the JavaVersion give me a second.

**Comment by httpdigest** [comment]
That is not the issue. The issue is (and still is):
```
* What went wrong:
Task 'package' not found in root project 'LWJGL3Issue'.
```

**Comment by Speiger** [comment]
Yeah because you try to run "gradle package"
Package is not a default task. Also the "IDE" is having the issue. So you open the project with Eclipse Neon to try replicate it.

**Comment by httpdigest** [comment]
Okay, sorry. I was on the "Maven" track :D of course there is no "package" :)

**Comment by Speiger** [comment]
Make sure you also downloaded the submodules because git does not do that by default.

**Comment by httpdigest** [comment]
(I've just cleaned unnecessary issue comments here) :)

**Comment by httpdigest** [comment]
And thanks for providing the example! We'll have a look.

**Comment by Speiger** [comment]
No problem.
Also i might need to rework the engine a bit to also credit you more. (It was fully closed source until 2-3 days ago)
(I took a couple implementations from your matrix and vectors when i wasn't even planning on opensource stuff)

**Comment by httpdigest** [comment]
Sure, but is there a reason you simply don't use JOML?

**Comment by Speiger** [comment]
Eh the idea is i want to learn everything that i can. So Reinvent the wheel is the rule. As much as possible within java.
But outside of that preferences are just different of what i wanted to do.

**Comment by Spasi** [comment]
There's nothing here that indicates an issue with loading natives. The exception is thrown internally within a `ClassLoader::getResource` call, when LWJGL tries to locate the core jar to read its manifest. This happens automatically with `-Dorg.lwjgl.util.Debug=true`, when LWJGL prints the library version during its initialization.

**Comment by Speiger** [comment]
Yeah but Version 3.3.0 must have changed something that isn't a thing in 3.2.4 (Duh)
And killing debug mode is not a good idea...

**Comment by httpdigest** [comment]
I've now reproduced the "issue" and it is not related to any LWJGL 3 version, but simply to using a Java 8 JRE. The described issue happens _both_ with LWJGL 3.3.0-SNAPSHOT as well as with LWJGL 3.2.4-SNAPSHOT and 3.2.3 release.
So, it is _not_ an issue about LWJGL 3 but simply about how the JRE 8 handles class/resource loading internally.
When I configure the debugger to trap on _all_ IOExceptions (or FileNotFoundExceptions in this case), then it always traps in `URLClassPath$JarLoader.getJarFile(URL) line: 938` in JRE 8.
You should be able to observe the same.
To reproduce this, I've just used the Maven project https://github.com/LWJGL/lwjgl3-demos also in the latest Eclipse (but it's not relevant to the Eclipse version).

Once I upgraded to JRE 11, the "issue" is gone completely.

**Comment by Speiger** [comment]
Ok, but I am not trapping any exceptions on my own. So 3.3.0 must be enabling that somehow?
Because 3.2.4 does not enable that?

**Comment by httpdigest** [comment]
No, you just configured the debugger (whenever and however) to trap on such exceptions. Explore/look at the "Breakpoints" view in Eclipse. It will tell you which breakpoints exist and whether any of them is a Java exception breakpoint.

**Comment by Speiger** [comment]
![image](https://user-images.githubusercontent.com/2556269/131338990-b86d3c04-a634-48ed-8b02-cd26f101b6a7.png)

**Comment by httpdigest** [comment]
And when you run the app with a debugger, it halts at `URLClassPath$JarLoader.getJarFile(URL) line: 938` on its own? Very weird.

**Comment by Speiger** [comment]
Especially how easy i can fix/cause it.
I am only changing the version number https://github.com/Speiger/LWJGL3-SubModule-Issue/blob/master/gradle.properties and refresh gradle its that simple to fix/cause

**Comment by httpdigest** [comment]
I'll conclude with that you probably have a broken project/Eclipse setup.
Both in Eclipse _as well as_ in IntelliJ IDEA with a JRE 8 exceptions are being raised on `URLClassPath$JarLoader.getJarFile(URL) line: 938` (which is _fine_ - as it just seems to be how JRE 8 handles class/resource loading and control flow internally).
So: Regardless of LWJGL version or IDE used: The exceptions are _always_ being thrown at that point for various jars and classpath folders (which is _fine_).
Upgrading to JRE 11 solves this completely.

Why it does what it does for you (halting on exceptions when there is no exception breakpoint configured and doing so with LWJGL 3.3.0-SNAPSHOT but not with LWJGL 3.2.4-SNAPSHOT) is currently inexplicable and not worth pursuing.

I'd strongly recommend you to at least use a recent Eclipse version (not Neon!).

**Comment by httpdigest** [comment]
Closing as it is _not_ an issue with LWJGL 3 and can also not be reproduced the way it was described.

**Comment by Speiger** [comment]
@httpdigest long term goal anyways. But right now 99% of my project force me to use Java8, but that should change soon.
But thanks for the help and showing me that i am right now fine with 3.2.4 until i am ready to upgrade. I can live with that.

I assume @Spasi 3.2.4 is unofficially stable? so no surprises there i hope.

Thanks for the time anyways. And for the Heart attack httpdigest xD (your location and projects did that xD)

**Comment by Spasi** [comment]
There will not be another `3.2.4` build, so yeah I guess. The next official release after `3.2.3` will be `3.3.0` because of important changes that may break applications on `3.2.x`.
