### ISSUE TITLE
Compilation path for macOS SDK is not set correctly on Big Sur 11.4

### ISSUE THREAD

**Issue by Spuriosity1** [LWJGL/lwjgl3#681]
### Version

3.3.0 (nightly)

### Platform

macOS arm64

### JDK

N/A

### Module

N/A

### Bug description

When following the instructions to build from source on my M1 macbook air, running
`ant init` 
fails due to `ant` not being able to locate the macOS SDK. This was presumably caused by Apple moving the SDK location.

The fix is straightforward for me: I changed lines 19-30 in `config/macos/build.xml` to:

   
    <macrodef name="find-sdkroot">
        <attribute name="version"/>

        <sequential>
            <condition property="sdkroot" value="${developer_path}/SDKs/MacOSX@{version}.sdk">
                <and>
                    <not><isset property="sdkroot"/></not>
                    <available file="${developer_path}/SDKs/MacOSX@{version}.sdk" type="dir"/>
                </and>
            </condition>
        </sequential>
    </macrodef>

Build now succeeds. 
It's quite a small thing, but didn't want to submit a  PR since I don't have any experience using `ant,` and didn't know how to implement the fix without breaking someone else's configuration.

**Comment by Spasi** [comment]
Hey @Spuriosity1,

Could you please paste the output of these two commands on your system?

```
xcrun --show-sdk-path
xcrun --show-sdk-path --sdk macosx
```

**Comment by Spuriosity1** [comment]
```
xcrun --show-sdk-path
xcrun --show-sdk-path --sdk macosx
> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
> /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
```

**Comment by Spuriosity1** [comment]
Only command line tools. For completeness,  the version of `ant` I have installed comes from Homebrew, and the output of  `brew list` is 
```
❯ brew list
==> Formulae
ant			libffi			numpy
aom			libidn			open-mpi
armadillo		libidn2			openblas
arpack			libmpc			opencore-amr
bdw-gc			libogg			openjdk
brotli			libpng			openjpeg
c-ares			libpthread-stubs	openssl@1.1
cairo			libsamplerate		opus
dav1d			libsndfile		p11-kit
eigen			libsodium		pcre
ffmpeg			libsoxr			pixman
flac			libtasn1		pkg-config
fontconfig		libtermkey		pybind11
freetype		libtiff			python@3.8
frei0r			libtool			python@3.9
fribidi			libunistring		rav1e
gcc			libuv			readline
gdbm			libvidstab		rubberband
gettext			libvorbis		scipy
ghostscript		libvpx			sdl2
giflib			libvterm		snappy
glib			libx11			speex
gmp			libxau			sqlite
gnutls			libxcb			srt
gobject-introspection	libxdmcp		superlu
graphite2		libxext			szip
guile			libxrender		tcl-tk
harfbuzz		little-cms2		tesseract
hdf5			llvm			theora
hwloc			llvm@11			tree-sitter
icu4c			luajit-openresty	unbound
isl			luv			unibilium
jbig2dec		lzo			webp
jemalloc		m4			x264
jpeg			minicom			x265
lame			mpdecimal		xorgproto
lapack			mpfr			xvid
leptonica		msgpack			xz
libass			neovim			zeromq
libbluray		nettle			zimg
libev			nghttp2			zstd
libevent		node
```
