### ISSUE TITLE
Usage of JEP-412 MemorySegments only sometimes works

### ISSUE THREAD

**Issue by javster101** [LWJGL/lwjgl3#682]
### Question

I've been experiment replacing certain usages of MemoryUtil.memAlloc with MemorySegments from JDK17, mostly to see if I can benefit from memory scopes. However, it seems almost 50/50 if certain LWJGL functions work with it. For example, allocating OpenGL GPU memory seems to work, but MeshOptimizer has some functions that do (like meshopt_unstripify) and others that don't (like meshopt_simplifySloppy and meshopt_stripify). All of these are confirmed to work if I use MemoryUtil.memAlloc(...) instead of MemorySegment.allocateNative(...).asByteBuffer(). 

Specifically, a piece of code like this:

```
var size = MeshOptimizer.meshopt_stripifyBound(optimizedListSize);
var simpifiedStripIndices =  MemoryUtil.memAlloc((int) (size * Integer.BYTES)).asIntBuffer();
var simplifiedStripSize = MeshOptimizer.meshopt_stripify(simpifiedStripIndices,
       resizedNewIndices, mesh.getVertices().size(), 0);
```
works while
```
var size = MeshOptimizer.meshopt_stripifyBound(optimizedListSize);
var simpifiedStripIndices = MemorySegment.allocateNative(size * Integer.BYTES, scope)
                                                      .asByteBuffer().asIntBuffer();
var simplifiedStripSize = MeshOptimizer.meshopt_stripify(simpifiedStripIndices,
          resizedNewIndices, mesh.getVertices().size(), 0);
```
returns invalid indices.

I don't expect LWJGL to explicitly support a preview feature so its fine if I can't do that, but I'm confused as to a. why it works on some functions and not others and b. why it would fail if it's still a direct ByteBuffer that you can get a memory address from.

**Comment by octylFractal** [comment]
I suspect this is due to the byte order of `MemorySegment#asByteBuffer`, which is [documented](https://docs.oracle.com/en/java/javase/16/docs/api/jdk.incubator.foreign/jdk/incubator/foreign/MemorySegment.html#asByteBuffer()) as giving back a big endian buffer in all cases. `MemoryUtil`, on the other hand, always gives a native-order buffer, which on most modern systems is _little_ endian.

**Comment by javster101** [comment]
Oh that makes sense, thank you!
