### ISSUE TITLE
On Linux, the native library cannot be loaded if the path contains non ASCII characters

### ISSUE THREAD

**Issue by Glavo** [LWJGL/lwjgl3#691]
### Version

3.3.0 (nightly)

### Platform

Linux x64, Linux arm64, Linux arm32

### JDK

Any

### Module

LWJGL Core

### Bug description

On Linux, the native library cannot be loaded if the path contains non ASCII characters. The reason is that in the Linux library, ASCII is used to encode the path:

https://github.com/LWJGL/lwjgl3/blob/e4a6cc863f469ea8acfe3c2158f2c77d0c0aa95d/modules/lwjgl/core/src/main/java/org/lwjgl/system/linux/LinuxLibrary.java#L30

I think the problem can be solved by changing it to 
```java
handle = dlopen(stack.UTF8(name), RTLD_LAZY | RTLD_LOCAL); 
```

I don't know why there is no such thing here. Is there any special reason?

**Comment by Glavo** [comment]
This caused https://github.com/huanghongxun/HMCL/issues/1141, we have to bypass this problem by creating temporary soft links as workaround.

**Comment by Spasi** [comment]
Thank you @Glavo!
