### ISSUE TITLE
ALC10.alcDestroyContext​ import issue

### ISSUE THREAD

**Issue by AustinHoover** [LWJGL/lwjgl3#692]
### Version

3.2.3

### Platform

Windows x64

### JDK

Eclipse Temurin 17

### Module

OpenAL

### Bug description

Hello! I'm having issues importing ALC10.alcDestroyContext and a few other functions from that class. Importing ALC10 itself works, and I can create a context fine. I made an example project to demonstrate what I'm trying to accomplish:
https://github.com/AustinHoover/LWJGLOpenALImportDemo
When I clone this, cd into it, and try `mvn package` it fails to resolve ALC10.alcDestroyContext.

Of note: I changed the artifact id and it succeeded to build. The name I used for the artifact was "DemoProblem". This only works sometimes. Fiddling with the artifact id does seem to have some influence on build success.

I'm building with Maven 3.8.1 on Windows 10. I also tried it on a non-M1 Mac running java 17 and Maven 3.8.1. I've ruled out every configuration issue I think might have caused this, but in case I missed something obvious I apologize in advance!

### Stacktrace or crash log output

```shell
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /D:/p/LWJGLOpenALImportDemo/src/main/java/studiorailgun/openaltest/Main.java:[3,30] cannot find symbol
  symbol:   class alcDestroyContext
  location: class org.lwjgl.openal.ALC10
```

**Comment by Spasi** [comment]
Hey @AustinHoover,

You're trying to import a method from the `ALC10` class. This is only possible with a static import, i.e.:

`import static org.lwjgl.openal.ALC10.alcDestroyContext​;`
