### ISSUE TITLE
How to compile jar(s)?

### ISSUE THREAD

**Issue by ivxvm** [LWJGL/lwjgl3#694]
### Question

I'm trying to build nightly lwjgl3 from source on m1 arm64, doing exactly what is described here:
https://github.com/LWJGL/lwjgl3/tree/master/doc#build-process

Setting env as follows:
```
% echo $LWJGL_BUILD_TYPE                                   
nightly
% echo $LWJGL_BUILD_ARCH 
arm64
```
Everything seems to succeed, but inside the bin folder there are only classes, native dylibs and auxiliary jars (like testng and commons). Not sure if I'm missing anything.

**Comment by Spasi** [comment]
Hey @ivxvm, try this:

```
export LWJGL_BUILD_OFFLINE=true
ant release -Djavadoc.skip=true
```

The first line tells the build to not download natives from S3, but use the ones available locally. This means that only the `-macos-arm64` jars will be created.

The second line builds the LWJGL artifacts, under the `bin/RELEASE` folder. The `-Djavadoc.skip=true` flag makes the process much faster, but no `-javadoc` jars will be created.

**Comment by ivxvm** [comment]
@Spasi
Thank you, got it working
