### ISSUE TITLE
Could not find lwjgl-assimp-3.3.0-SNAPSHOT.jar (Grandle)

### ISSUE THREAD

**Issue by Snowiiii** [LWJGL/lwjgl3#698]
### Version

3.3.0 (nightly)

### Platform

Windows x64

### JDK

8

### Module

Core

### Bug description

repositories {
    mavenCentral()
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}

dependencies {
    implementation platform("org.lwjgl:lwjgl-bom:$lwjglVersion")

    implementation "org.lwjgl:lwjgl"
    implementation "org.lwjgl:lwjgl-assimp"
    implementation "org.lwjgl:lwjgl-bgfx"
    implementation "org.lwjgl:lwjgl-glfw"
    implementation "org.lwjgl:lwjgl-nanovg"
    implementation "org.lwjgl:lwjgl-nuklear"
    implementation "org.lwjgl:lwjgl-openal"
    implementation "org.lwjgl:lwjgl-opengl"
    implementation "org.lwjgl:lwjgl-par"
    implementation "org.lwjgl:lwjgl-stb"
    implementation "org.lwjgl:lwjgl-vulkan"
    runtimeOnly "org.lwjgl:lwjgl::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-assimp::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-bgfx::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-glfw::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-nanovg::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-nuklear::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-openal::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-opengl::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-par::$lwjglNatives"
    runtimeOnly "org.lwjgl:lwjgl-stb::$lwjglNatives"
    implementation "org.joml:joml:${jomlVersion}"
}

### Stacktrace or crash log output

```shell
Could not find lwjgl-assimp-3.3.0-SNAPSHOT.jar (org.lwjgl:lwjgl-assimp:3.3.0-SNAPSHOT:20211102.013639-14).
Searched in the following locations:
    https://oss.sonatype.org/content/repositories/snapshots/org/lwjgl/lwjgl-assimp/3.3.0-SNAPSHOT/lwjgl-assimp-3.3.0-20211102.013639-14.jar

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

**Comment by Spasi** [comment]
Hey @Snowiiii,

Try building with `--refresh-dependencies`. The `20211102.013639-14` snapshot has probably expired, the latest version is `20211115.155230-17`.

**Comment by Snowiiii** [comment]
okay thanks

**Comment by elect86** [comment]
You may find [this plugin](https://github.com/LWJGL/lwjgl3-gradle/) interesting though
