### ISSUE TITLE
TinyEXR loading from memory should use `DirectByteBuffer` instead of the more generic `ByteBuffer`

### ISSUE THREAD

**Issue by bartvangeneugden** [LWJGL/lwjgl3#699]
### Version

3.3.0 (nightly), 3.2.3, 3.2.2, 3.2.1, 3.2.0

### Platform

Linux x64, macOS x64

### JDK

OpenJDK 11

### Module

LWJGL TinyEXR

### Bug description

The API for loading EXR files from memory (as opposed to from a path on the filesystem) accepts a `ByteBuffer`. This should instead be a `DirectByteBuffer`. When creating a non-direct (`HeapByteBuffer`) the JVM crashes on a core dump.

Example reproducing the error:
```java
byte[] fileBytes = new ClassPathResource(pathOnClasspath).getInputStream().readAllBytes();
HeapByteBuffer heapByteBuffer =  ByteBuffer.wrap(fileBytes);
EXRVersion exrVersion = EXRVersion.calloc();
TinyEXR.ParseEXRVersionFromMemory(exrVersion, heapByteBuffer);
```

This will reproduce:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000010983efd6, pid=19042, tid=6147
#
# JRE version: OpenJDK Runtime Environment OpenJDK-11.0.12.7.1 (build 11.0.12+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM OpenJDK-11.0.12.7.1 (11.0.12+7-LTS, mixed mode, tiered, compressed oops, g1 gc, bsd-amd64)
# Problematic frame:
# C  [liblwjgl_tinyexr.dylib+0xfd6]
```

An example that does work:

```java
byte[] fileBytes = new ClassPathResource(pathOnClasspath).getInputStream().readAllBytes();
DirectByteBuffer directByteBuffer = ByteBuffer.allocateDirect(fileBytes.length).put(fileBytes)
EXRVersion exrVersion = EXRVersion.calloc();
TinyEXR.ParseEXRVersionFromMemory(exrVersion, directByteBuffer);
```

I suggest the signature of the `*FromMemory` methods to change from this:

```java
TinyEXR.ParseEXRVersionFromMemory(EXRVersion version, ByteBuffer memory)
```

to something like this:

```java
TinyEXR.ParseEXRVersionFromMemory(EXRVersion version, DirectByteBuffer memory)
```

**Comment by TheMrMilchmann** [comment]
> The API for loading EXR files from memory (as opposed to from a path on the filesystem) accepts a `ByteBuffer`.

This is the case for all LWJGL APIs that accept a buffer.

> This should instead be a `DirectByteBuffer`.

I assume that you are referring to `java.nio.DirectByteBuffer`. That class is not part of the API. It's an internal implementation class of the JDK and probably not even accessible anymore in Java >= 9. Therefore, publishing a library depending on it is not feasible as it will not just break on different JDK implementations but also on more recent versions.

This is non-ideal indeed and will probably be cleaned up once the new Java FFI is released. For now, I can only recommend reading up on the excellent [Memory management in LWJGL](https://blog.lwjgl.org/memory-management-in-lwjgl-3/) article. Note that using `ByteBuffer::allocateDirect` is already discouraged and that better alternatives are available in `org.lwjgl.system.MemoryUtil `. (More on that in the article).

**Comment by bartvangeneugden** [comment]
Thanks for the comprehensive answer 👍 Indeed a great article
