### ISSUE TITLE
vkCmdSetCheckpointNV should allow a value of 0 for the checkpoint marker

### ISSUE THREAD

**Issue by tlf30** [LWJGL/lwjgl3#702]
### Version

3.3.0 (nightly)

### Platform

Windows x64

### JDK

Adoptium 17

### Module

Vulkan

### Bug description

`NVDeviceDiagnosticCheckpoints.vkCmdSetCheckpointNV(VkCommandBuffer commandBuffer, @NativeType("void const *") long pCheckpointMarker)` should allow for the value `0L` as the `pCheckpointMarker` as this is a user provided pointer that is passed back to the user. It can be useful to pass a `0L` as the `pCheckpointMarker`, especially when the `pCheckpointMarker` is representing an index in a list of markers. 

See: https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/vkCmdSetCheckpointNV.html

Thanks,
Trevor

### Stacktrace or crash log output

```
java.lang.NullPointerException
	at org.lwjgl.system.Checks.check(Checks.java:188)
	at org.lwjgl.vulkan.NVDeviceDiagnosticCheckpoints.vkCmdSetCheckpointNV(NVDeviceDiagnosticCheckpoints.java:129)
	at io.tlf.outside.client.plugins.vk.renderer.vk12.Vk12Util.debugCommandBuffer(Vk12Util.java:64)
```

**Comment by Spasi** [comment]
Thanks @tlf30, will be fixed in the next snapshot!

**Comment by tlf30** [comment]
Thank you @Spasi, that fix has a wide impact, but I did not see anything that would cause an immediate issues. It is unfortunate that there are errors in the vulkan spec on things like this. 

Great job and thanks for all your hard work!
