### ISSUE TITLE
Mac M1 has OpenGL 4.1, Only 2.1 available in LWJGL

### ISSUE THREAD

**Issue by eeverman** [LWJGL/lwjgl3#729]
### Question

Despite OpenGL being deprecated on Mac, Open GL 4.1 is present:

<img width="730" alt="Screen Shot 2022-02-10 at 10 10 31 AM" src="https://user-images.githubusercontent.com/24287468/153448361-755a40fb-a8ab-4a3e-bc71-0ea80b47415d.png">

However, when I run a LWJGL application w/ Mac Arm natives, it only reports OpenGL 2.1:
  ```
GLCapabilities caps = GL.createCapabilities();
  System.out.println("1.5: " + caps.OpenGL15);
  System.out.println("2.1: " + caps.OpenGL21);
  System.out.println("3.0: " + caps.OpenGL30);
  System.out.println("4.0: " + caps.OpenGL40);
  System.out.println("4.1: " + caps.OpenGL41);
```
Output:
```
1.5: true
2.1: true
3.0: false
4.0: false
4.1: false
```

And, sure enough, a call like this fails:
```
GL30C.glGenVertexArrays();

>> No context is current or a function that is not available in the current context was called.
```

Any suggestions or ideas why this would be?  It seems like this should work.

Any help appreciated!

. . . .
System Info:
* MacOS 11.6 / MacBookAir10,1
* Java 17 with the '-XstartOnFirstThread' flag

Relavant Maven dependencies:
<img width="498" alt="Screen Shot 2022-02-10 at 10 16 02 AM" src="https://user-images.githubusercontent.com/24287468/153449441-a0f8f919-7ffc-434c-ab2f-ac53e3a38fc6.png">

Other info from GLView:
<img width="856" alt="Screen Shot 2022-02-10 at 10 21 35 AM" src="https://user-images.githubusercontent.com/24287468/153450563-5bdff178-2210-4cb0-91b3-c1479875a06f.png">

**Comment by eeverman** [comment]
Update:  The GLView app has a 'OpenGL Profile' selector.  When **Core** is selected, the capabilities in the above screenshot are reported (GL 4.1).  When **Compatibility** is selected, only GL 2.1 is available, as shown below.

Is there some way to make the native Mac arm libs detect and use the 'Core' profile?

<img width="812" alt="Screen Shot 2022-02-10 at 10 48 33 AM" src="https://user-images.githubusercontent.com/24287468/153455820-f0ab1d45-74e1-4688-ae35-9c6eadc0ecf0.png">

**Comment by octylFractal** [comment]
If you are using GLFW, you need to request OpenGL core + minimum version through GLFW -- see [the GLFW docs](https://www.glfw.org/docs/3.3/window_guide.html#GLFW_CONTEXT_VERSION_MAJOR_hint) for the requirement, and [here](https://github.com/LWJGL/lwjgl3/blob/e4a6cc863f469ea8acfe3c2158f2c77d0c0aa95d/modules/samples/src/test/java/org/lwjgl/demo/nanovg/ExampleGL3.java#L75-L78) for some LWJGL-specific example code.
