### ISSUE TITLE
libglfw_async for Linux

### ISSUE THREAD

**Issue by Ali-RS** [LWJGL/lwjgl3#732]
### Question

Hi

Is it possible to add a version of "libglfw_async" for Linux as well, please? For the GLFW + AWT/Swing issue on Linux Mesa drivers.

```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x4e0005b
  Serial number of failed request:  1332
  Current serial number in output stream:  1332
```

Kind Regards

**Comment by Spasi** [comment]
Hey @Ali-RS,

The `libglfw_async` implementation solves a very particular problem that exists in the macOS world, but does not affect Linux.

A first step would be identifying what exactly is causing the X error. Then we can discuss options, depending on whether it's a bug in GLFW or a weird interaction with AWT/Swing that may be fixable from our side.

**Comment by Ali-RS** [comment]
Hey @Spasi 

Sorry for making duplicate content. I think we can close this as it is related to https://github.com/LWJGL/lwjgl3/issues/742 which is resolved in the latest snapshot build.

Best Regards
