### ISSUE TITLE
Invalid CL_KERNEL_ARG_ADDRESS_* qualifiers

### ISSUE THREAD

**Issue by mflament** [LWJGL/lwjgl3#733]
### Version

3.3.0 (nightly)

### Platform

Linux x64, Linux arm64, Linux arm32, macOS x64, macOS arm64, Windows x64, Windows x86, Windows arm64

### JDK

any

### Module

OpenCL

### Bug description

The values of CL constants  CL_KERNEL_ARG_* differ from opencl header.
From [opencl header](https://github.com/KhronosGroup/OpenCL-Headers/blob/master/CL/cl.h) : 

```c
/* cl_kernel_arg_address_qualifier */
#define CL_KERNEL_ARG_ADDRESS_GLOBAL                0x119B
#define CL_KERNEL_ARG_ADDRESS_LOCAL                 0x119C
#define CL_KERNEL_ARG_ADDRESS_CONSTANT              0x119D
#define CL_KERNEL_ARG_ADDRESS_PRIVATE               0x119E
```

In [master](https://github.com/LWJGL/lwjgl3/blob/827dbbcec5cc12f4b6e25172bb3bfac6e989bba8/modules/lwjgl/opencl/src/generated/java/org/lwjgl/opencl/CL12.java#L22)
```java
/** cl_kernel_arg_address_qualifier */
public static final int
    CL_KERNEL_ARG_ADDRESS_GLOBAL   = 0x119A,
    CL_KERNEL_ARG_ADDRESS_LOCAL    = 0x119B,
    CL_KERNEL_ARG_ADDRESS_CONSTANT = 0x119C,
    CL_KERNEL_ARG_ADDRESS_PRIVATE  = 0x119D;
```

**Comment by Spasi** [comment]
@mflament Thanks!
