### ISSUE TITLE
Invalid OpenCL CL_KERNEL_ARG_TYPE_QUALIFIER constant value 

### ISSUE THREAD

**Issue by mflament** [LWJGL/lwjgl3#735]
### Version

3.3.0 (nightly)

### Platform

Linux x64, Linux arm64, Linux arm32, macOS x64, macOS arm64, Windows x64, Windows x86, Windows arm64

### JDK

any

### Module

OpenCL

### Bug description

Expected constant value defined in Open CL [heade](https://github.com/KhronosGroup/OpenCL-Headers/blob/master/CL/cl.h):
```c
#define CL_KERNEL_ARG_TYPE_QUALIFIER                0x1199
```

Actual value defined in [template](https://github.com/LWJGL/lwjgl3/blob/750a0fb95133419c17862809ba226b3f4bd54ed0/modules/lwjgl/opencl/src/templates/kotlin/opencl/templates/CL12.kt#L218)
```kotlin
"KERNEL_ARG_TYPE_QUALIFIER"..0x1999,
```

**Comment by mflament** [comment]
This one took me some time, I was so blind :-)
Fixed here https://github.com/LWJGL/lwjgl3/pull/736

**Comment by Spasi** [comment]
Thanks!
