### ISSUE TITLE
SHA-1 hashes not present anymore in API jar files

### ISSUE THREAD

**Issue by theofficialgman** [LWJGL/lwjgl3#737]
### Version

3.3.0 (nightly), 3.2.3

### Platform

Linux x64, Linux arm64, Linux arm32, macOS x64, macOS arm64, Windows x64, Windows x86, Windows arm64

### JDK

irrelevant

### Module

All

### Bug description

Prior to LWJGL 3.2.3, SHA-1 hashes were available in the api only jar files (in addition to the natives). Beginning in lwjgl 3.2.3, those hashes are no longer available and are only available in the corresponding native JAR files. Since lwjgl 3.2.3 first introduced multiple new architectures on the same platform (armhf/arm64 linux), the old way of packing the .sha1 files into the root of the api JAR would not work anyway even if it was implemented.

Is this an oversight or intentional? It seems to me that builtin hash check has been skipped ever since 3.2.3 with this change:
https://github.com/LWJGL/lwjgl3/blob/ad602750ad87939276d1889b28a757061e90715b/modules/lwjgl/core/src/main/java/org/lwjgl/system/Library.java#L550-L602

**Comment by Spasi** [comment]
@theofficialgman Thanks!

The first 3.3.2 snapshot will include the missing hashes and incompatibility detection should be working. The `.sha1` and `.git` files have also been moved under `META-INF` in the LWJGL JAR files.
