### ISSUE TITLE
Color class

### ISSUE THREAD

**Issue by kenzierocks** [LWJGL/lwjgl3#74]
I would really like to have a utility color class that can be used to just store colors, as I would normally use the `java.awt.Color` class but as #68 shows that's not always going to work well on OSX. I am considering just risking it, or maybe writing my own, but it seems common enough to have in the core library.

**Comment by Spasi** [comment]
Just like vecmath, such functionality is outside the scope of LWJGL and belongs in a separate library (see [JOML](https://github.com/JOML-CI/JOML)). Even if it's common and simple, it's also application-specific (what color space to use, what data-type/precision/dynamic range, etc).

**Comment by httpdigest** [comment]
I very much agree with @Spasi there, and thanks for pointing to JOML!
Roll your own class or use JOML's Vector3f or Vector4f for that.
Just to prevent any upcoming feature request: No, JOML is not going to include a Color/Color3f/Color4f class, for that matter. :)

**Comment by kenzierocks** [comment]
Oh, I was really thinking about some of the more advanced stuff awt Color provides, I guess I'll take what I can from that then.
