### ISSUE TITLE
X Error of failed request:  BadWindow

### ISSUE THREAD

**Issue by Ali-RS** [LWJGL/lwjgl3#742]
### Version

3.3.0 (nightly)

### Platform

Linux x64

### JDK

AdoptOpenJDK 16

### Module

OpenGL, GLFW

### Bug description

When I open a swing window along with the GLFW window, the moment I close the swing window it crashes the app with the below error. I am using LWJGL 3 with jMonkeyEngine.

I am on Linux Mint with Mesa (v20) graphics driver.

### Stacktrace or crash log output

```shell
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x4e0005b
  Serial number of failed request:  1332
  Current serial number in output stream:  1332
```

**Comment by httpdigest** [comment]
Using AWT/Swing together with GLFW is not really supported/possible, because both try to steal each other's OS/window message events.
AWT is using its own window message loop to process the OS/window message events in its EDT thread and you are doing the same with `glfwPollEvents`/`glfwWaitEvents`.

**Comment by Ali-RS** [comment]
@httpdigest thanks for the response. 

Afaik LWJGL added `glfw_async` that makes it possible to use AWT/Swing together with GLFW on Mac. Would a similar solution work for Linux?

**Comment by httpdigest** [comment]
`glfw_async` currently only targets macOS.
And it also _does not_ allow you to create any AWT/Swing windows.
It _only_ lets you use the ImageIO subsystem (e.g. for image loading/storing) and lets you open/use modal dialog windows.
`glfw_async` is basically there to avoid people who already use GLFW to add the `-XstartOnFirstThread` JVM argument.

**Comment by SylvainBertrand** [comment]
Making progress on the problematic example and found out that the drag and drop feature from Swing seems to be causing some trouble.
```
package example;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;

import javax.swing.JFrame;
import javax.swing.TransferHandler;
import javax.swing.WindowConstants;

import org.lwjgl.glfw.GLFW;

public class CodeSnippet
{
   public static void main(String[] args) throws InvocationTargetException, InterruptedException, IOException
   {
      JFrame frame = new JFrame();

      GLFW.glfwInit();

      TransferHandler newHandler = new TransferHandler("Bloppy");
      frame.setTransferHandler(newHandler); // Comment out to get the application to terminate properly.
      frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
      frame.setLayout(new BorderLayout());
      frame.setPreferredSize(new Dimension(600, 600));
      frame.pack();
      frame.setVisible(true);
   }
}
```
As soon as a `TransferHandler` is added to the frame, the `X Error of failed request: BadWindow` will pop up and make the application crash immediately. No idea if that's useful observation but I'll keep digging unless someone has some further knowledge on the more general issue.

**Comment by DeafMan1983** [comment]
That is platform dependent. You need set `glfwGetX11Display` and `glfwGetX11Window` with AWT/Swing and error will be gone.

For Windows `glfwGetWin32Window` and for macOS `glfwCocoaWindow`.

Why do you not expect glfw with platform binding like SDL2 has also platform dependence Via `SDL_GetWindowWMInfo`?

**Comment by Ali-RS** [comment]
Thanks @DeafMan1983 

>You need set glfwGetX11Display and glfwGetX11Window with AWT/Swing and error will be gone.

Not sure how to set these values, can you please show me the code snippet I need to add on my Java code. Thanks!

Best Regards

**Comment by Spasi** [comment]
Hey @Ali-RS & @SylvainBertrand,

Could you please try again with the latest LWJGL snapshot? I cannot reproduce such a crash. I also tried both code snippets by @SylvainBertrand and they worked without issues.

**Comment by Ali-RS** [comment]
Hi @Spasi

Thanks for your response. I can confirm using the latest snapshot the error does not occur.

**Comment by DeafMan1983** [comment]
Sorry for late delay! Find in glfw native / platform check lwjgl3 packages

You should read glfw3 documentation for platform / native
