### ISSUE TITLE
GL.create() assumes GLX on Linux

### ISSUE THREAD

**Issue by asdfjkluiop** [LWJGL/lwjgl3#748]
### Version

3.3.0 (nightly)

### Platform

Linux x64

### JDK

Eclipse OpenJ9 VM 17.0.2.0

### Module

OpenGL

### Bug description

`GL.create()` assumes GLX on Linux using `libGL.so` and `glXGetProcAddress()`. The problem with this is `libGL.so` isn't always available on wayland platforms causing LWJGL initialization to fail. I ran into this bug on a fresh debian install where the only thing installed was the sway wayland compositor. `libEGL` is present but not `libGL` since wayland uses EGL for context management. My game engine works around this by setting `Configuration.OPENGL_EXPLICIT_INIT.set(true)` and then using `GL.create(GLFW::glfwGetProcAddress)` since GLFW uses the API for context creation to implement that function however LWJGL's automatic extension loading should avoid making assumptions about what windowing system is being used as it can break in some cases. To be honest I don't know what a good fix for this is besides just leaving it to the engine/game but I figured I'd bring it up in case anyone had a solution that could be put into LWJGL.

**Comment by Spasi** [comment]
Hey @asdfjkluiop,

That is indeed true, the `GL` class assumes GLX on Linux. However, LWJGL has EGL bindings and GLFW supports EGL (see `GLFW_EGL_CONTEXT_API`). On Wayland, I believe the correct approach would be:

```
Configuration.OPENGL_EXPLICIT_INIT.set(true);
GL.create(EGL.getFunctionProvider());
```

and then you would proceed with the usual GLFW setup.

**Comment by Spasi** [comment]
Hey again,

I have verified that the above workaround works. The one with `glfwGetProcAddress` should also work too.

(on Nvidia hardware, I also need to export `__GL_THREADED_OPTIMIZATIONS=0` to get stable results on Wayland)

Note that these workarounds could be done internally (e.g. after `glfwInit`) by LWJGL, but I'd like to avoid the complications for the time being (premature OpenGL initialization, messing around with reflection and module system restrictions, etc.).

**Comment by Spasi** [comment]
Hey again,

The latest build (`3.3.5-snapshot+4`) includes `Configuration.OPENGL_CONTEXT_API` and automatic Wayland detection, which should resolve this issue without extra code.

(`__GL_THREADED_OPTIMIZATIONS=0` will still be required on NV hardware until their driver is fixed)

**Comment by asdfjkluiop** [comment]
Thanks, cool to see this fixed. I'll definitely give it a try, hopefully this means I can take the wayland detection code out of my own engine
