### ISSUE TITLE
LWJGL Metal Examples

### ISSUE THREAD

**Issue by cacophany53** [LWJGL/lwjgl3#752]
### Question

Does LWJGL have bindings for Metal? If so, are there any examples of an LWJGL application using Metal?

**Comment by httpdigest** [comment]
No, there are currently no Metal bindings. Same with DirectX/Direct3D.
In fact, there is currently only _one_ supported binding that only pertains to a single platform/OS: Oculus VR.

**Comment by cacophany53** [comment]
Thanks.
