### ISSUE TITLE
NFD_PickFolder GTK crashing

### ISSUE THREAD

**Issue by rafi612** [LWJGL/lwjgl3#753]
### Version

3.3.0 (nightly)

### Platform

Linux x64

### JDK

OpenJDK 17.0.2

### Module

NFD

### Bug description

When I'm using NFD_PickFolder function with Swing Window, it crash with following error. It crashing only when I use GTK+ look and feel for Swing window. Without it works normally.

System: Linux Mint 20.3 x64
Desktop: Cinnamon

(LWJGL version is 3.3.1 but can't select it in issue template)

### Stacktrace or crash log output

```shell
(java:7263): GLib-GObject-WARNING **: 18:25:03.260: cannot register existing type 'GdkDisplayManager'

(java:7263): GLib-CRITICAL **: 18:25:03.260: g_once_init_leave: assertion 'result != 0' failed

(java:7263): GLib-GObject-CRITICAL **: 18:25:03.260: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
```

**Comment by Spasi** [comment]
Hey @rafi612,

I don't think there's much we can do about this, but could you please post a simple code snippet that reproduces the crash?

**Comment by rafi612** [comment]
```java
import javax.swing.*;

import org.lwjgl.PointerBuffer;
import org.lwjgl.system.MemoryStack;

import static org.lwjgl.util.nfd.NativeFileDialog.*;

public class NFDTest {

	public static void main(String[] args) {
		
		try {
			UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException
				| UnsupportedLookAndFeelException e) {
			e.printStackTrace();
		}
		
		JFrame frame = new JFrame("NFD Test");
		frame.setSize(500,500);
		
		JButton test = new JButton("Test");
		
		test.addActionListener((actionEvent) -> {
			try (MemoryStack stack = MemoryStack.stackPush()) {
				
				PointerBuffer pointer = stack.mallocPointer(1);
				if (NFD_OpenDialog("Test", "Test", pointer) == NFD_OKAY)
					System.out.println("Selected path is:" + pointer.getStringUTF8());
			}
		});
		
		frame.add(test);
		frame.setVisible(true);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

	}
}
```

**Comment by Spasi** [comment]
Hey @rafi612,

Recent GTK versions require that all GTK functions are called from a single thread. Afaict, AWT interacts with X and libraries like GTK via the `AWT-XAWT` thread, which is not the same as the event dispatch thread used to call the `NFD_OpenDialog` function. This breaks GTK's thread rules and probably causes a deadlock.

Why not use Java's file chooser in the first place?

**Comment by rafi612** [comment]
Default file chooser in swing is a little bit ugly with GTK look and feel. But now I use tinyfd from LWJGL instead and it's work very well.
