### ISSUE TITLE
glfw_async native method crashes when GLFW.glfwSetInputMode() is invoked

### ISSUE THREAD

**Issue by treemark** [LWJGL/lwjgl3#754]
### Version

3.3.0 (nightly)

### Platform

macOS arm64

### JDK

OpenJDK 11

### Module

GLFW

### Bug description

I'm using JME on a mac m1 arm64 with the async library. I'm also using 3.3.1 of LWJGL but it won't let me select that in the pull down.

`Configuration.GLFW_LIBRARY_NAME.set("glfw_async");`

 When JME attempts to initialize mouse input via the method org.lwjgl.glfw.GLFW.glfwSetInputMode() it crashes without logging anything. This method succeeds when using the non-async glfw library.

More details about this issue can be found [here](https://hub.jmonkeyengine.org/t/macos-support-overhaul-apple-m1-and-breaking-changes/45258/133).

**Comment by Spasi** [comment]
Hey @treemark,

Could you please try again with the latest LWJGL snapshot? Also, what values are passed to `glfwSetInputMode`?

**Comment by Spasi** [comment]
Any updates on this?
