### ISSUE TITLE
vkSetDebugUtilsObjectNameEXT crashes with VkInstance and VkPhysicalDevice

### ISSUE THREAD

**Issue by tlf30** [LWJGL/lwjgl3#755]
### Version

3.3.1

### Platform

Windows x64

### JDK

Adoptium 17

### Module

Vulkan

### Bug description

`vkSetDebugUtilsObjectNameEXT` crashes when naming a `VkInstance` or `VkPhysicalDevice`. This appears to be cause by using the function pointer for `vkSetDebugUtilsObjectNameEXT` from the `VkDevice` instead of the `VkInstance`. 
More info can be found here:
[https://forums.developer.nvidia.com/t/vksetdebugutilsobjectnameext-causes-a-crash-when-attempting-to-set-a-name-for-vkphysicaldevice/79517/6](https://forums.developer.nvidia.com/t/vksetdebugutilsobjectnameext-causes-a-crash-when-attempting-to-set-a-name-for-vkphysicaldevice/79517/6)

> Yeah using vkGetInstanceProcAddr() it a bit counter-intuitive, but that’s currently the rule for instance extension functions, even ones with a VkDevice as their first parameter. The Vulkan spec might get updated in this regard and allow vkGetDeviceProcAddr() to be used for these functions. If that happens implementations will get updated to support it too.

EDIT: Also take note: https://github.com/KhronosGroup/Vulkan-Loader/issues/116

### Stacktrace or crash log output

[https://gist.github.com/tlf30/ff2ed51abf4894add8960a11f4ee5057](https://gist.github.com/tlf30/ff2ed51abf4894add8960a11f4ee5057)

Please let me know if you need anything else.
Thank you,
~Trevor

**Comment by Spasi** [comment]
Thank you @tlf30!

**Comment by tlf30** [comment]
Thank you for the fix @Spasim I will test as soon as a snapshot is available.

**Comment by tlf30** [comment]
@Spasi I just tested with the 3.3.2 snapshot. Setting a name on a`VkPhysicalDevice` works now, but setting the name on a `VkInstance` does not, it throws a memory access violation. I am setting up a test with native code to check if it is a driver issue, as I believe the bindings are correct.

**Comment by tlf30** [comment]
@Spasi I have dove into this further. Currently the JVM just crashes with 'Process finished with exit code -1073740940 (0xC0000374)' (IDEA is adding the extra text, just the exit code, no crash log was generated by the jvm). 
Java Test Code:
```java
try (MemoryStack stack = MemoryStack.stackPush()) {
    vkSetDebugUtilsObjectNameEXT(
            device.getDevice(),
            VkDebugUtilsObjectNameInfoEXT.calloc(stack)
                    .sType$Default()
                    .objectType(VK_OBJECT_TYPE_INSTANCE)
                    .pObjectName(stack.ASCII(name))
                    .objectHandle(instance.getNativeHandle())
    );
}
```

I put together a C++ test, and it worked as expects. This also eliminates a driver issue as I tested on the same machine. 
```cpp
 //Test setting instance debug name
VkDebugUtilsObjectNameInfoEXT info;
info.sType = VK_STRUCTURE_TYPE_DEBUG_UTILS_OBJECT_NAME_INFO_EXT;
info.objectType = VK_OBJECT_TYPE_INSTANCE;
info.objectHandle = (uint64_t) *(instance->getVkInstance());
info.pObjectName = "OVK Instance";
info.pNext = NULL;
PFN_vkSetDebugUtilsObjectNameEXT vkSetDebugUtilsObjectNameEXT = (PFN_vkSetDebugUtilsObjectNameEXT)vkGetInstanceProcAddr(*(instance->getVkInstance()), "vkSetDebugUtilsObjectNameEXT");
orVkOK(vkSetDebugUtilsObjectNameEXT(device, &info));
```

I do not see what is going wrong on the LWJGL side. Setting the name works on everything else (I think I have tested all vulkan object types now).
