### ISSUE TITLE
HelloBGFX.java fail on Mac M1

### ISSUE THREAD

**Issue by ker2x** [LWJGL/lwjgl3#756]
### Version

3.3.0 (nightly)

### Platform

macOS arm64

### JDK

tried Zulu and oracle openJDK 16 & 18, x64 & AArch64

### Module

BGFX

### Bug description

Note : I can't select 3.3.1-builld7 in version so I selected 3.3.0 (nightly)

I'm running this exemple https://github.com/LWJGL/lwjgl3/blob/master/modules/samples/src/test/java/org/lwjgl/demo/bgfx/HelloBGFX.java

And it's stuck at :
```
invokePZ:-1, JNI (org.lwjgl.system)
nbgfx_init:1682, BGFX (org.lwjgl.bgfx)
bgfx_init:1694, BGFX (org.lwjgl.bgfx)
main:82, Main (neogridworld)
```
It just wait here forever. Not using significant CPU or memory.

I originally was developing my own app, but it was stuck here, so I tried HelloBGFX and they both have the same problem.

Host: "MacBookAir10,1" arm64, 8 cores, 8G, Darwin 21.4.0, macOS 12.3 (21E230)

Screenshot of debug view : 
[https://i.imgur.com/yS2V0qB.png](https://i.imgur.com/yS2V0qB.png)

### Stacktrace or crash log output

```shell
invokePZ:-1, JNI (org.lwjgl.system)
nbgfx_init:1682, BGFX (org.lwjgl.bgfx)
bgfx_init:1694, BGFX (org.lwjgl.bgfx)
main:82, Main (neogridworld)
```
```

**Comment by mcslee** [comment]
I am seeing the same behavior on my M1 machine also.

FYI there does seem to be an older hack/workaround that can be used to solve this issue:
https://github.com/LWJGL/lwjgl3/issues/619#issuecomment-787466929

This hack is currently working for me to get through bgfx_init() on the 3.3.1 release.

**Comment by Spasi** [comment]
Hey @ker2x,

Have you tried the above workaround?

**Comment by ker2x** [comment]
I gave up on v3 for now, but I'll give it a new try. thx for the update
