### ISSUE TITLE
Where is correct glBufferData() with 4 parameters like (int target, int size, FloatBuffer data, int usage)

### ISSUE THREAD

**Issue by DeafMan1983** [LWJGL/lwjgl3#758]
### Question

Hello everyone, I want know why do you not care with 4 parameters in glBufferData()
because I want make sure same with C++, C# and Java understanding / adknowledge.

Please do not cheat me! I want write same like other programming languages
But why does LWJGL from java cheat like Python?

I am very disappointed because I have problem with red underlines under NetBeans.
![image](https://user-images.githubusercontent.com/57066679/164935599-bcf14431-d8d6-4742-a2c8-bc9a01abc669.png)

It said invalid.

But in C++ is real: glBufferData(9 has 4 parameters
![image](https://user-images.githubusercontent.com/57066679/164936000-aec2d563-a2e8-4dcd-a5ef-31c6a99ef306.png)

I want have real 1:1 from Java, C++, Haxe, F#, C#, Basic or etc....

Thank you!

**Comment by httpdigest** [comment]
Whenever a native function, such as OpenGL's `glBufferData` or `glBufferSubData` or also `glTexImag2D` takes a pointer to memory, LWJGL translates that to a method taking a NIO Buffer, such as a `FloatBuffer`.
The size is then implied by the `remaining()` of that buffer.
So, the native C function signature has an explicit `size` parameter because pointers in C do not carry a size, so we _need_ a separate parameter there. But when using Java/LWJGL, we have the NIO Buffer types, which _do_ carry their sizes, so we can omit the explicit `size` parameter and take the size for the underlying native function call from the buffer's `remaining()`.

**Comment by DeafMan1983** [comment]
Okay but for me. I care about 4 parameters.
```
    public void Data(int size, float[] vertices, int usage)
    {
        FloatBuffer buffer = BufferUtils.createFloatBuffer(size);
        buffer.put(vertices);
        buffer.flip();
        GL15.glBufferData(this.target_buffer, buffer, usage);
    }
```

I made Main.java with lwjgl3
```
import org.lwjgl.opengl.GL11;
import org.lwjgl.opengl.GL15;

public class Main
{
    private static DisplayManager dm;
    private static VertexArrayObject vao;
    private static BufferObject bo;
    private static Renderer render;
    
    private static float[] vertices =
    {
      //  X      Y     Z
         0.0f,  0.5f, 0.0f, // top
         0.5f, -0.5f, 0.0f, // bottom left
        -0.5f, -0.5f, 0.0f, // bottom right
    };
    
    
    public static void main(String[] args) {
        dm = DisplayManager.Create("02 Triangle", 1280, 800);	
        dm.Make();
        
        vao = VertexArrayObject.Gen();
        bo = BufferObject.Gen();
        
        bo.Bind(GL15.GL_ARRAY_BUFFER);
        bo.Data(vertices.length, vertices, GL15.GL_STATIC_DRAW);
        
        bo.Pointer(0, 3, 0, 0);
        bo.Enable(0);
        
        while (dm.IsRunning())
        {
            dm.HandleClose();

            render = Renderer.Clear(GL11.GL_COLOR_BUFFER_BIT, 1.0f, 1.0f * 0.35f, 0.0f);
            render.HandleSwitcher(dm.GetWindow());
            render.Draw(GL11.GL_TRIANGLES, 0, 3);

            dm.Poll();
        }

        bo.Delete();
        vao.Delete();
        dm.Destroy();
    }
}
```
Result: It works fine like C++, C# or other 
![image](https://user-images.githubusercontent.com/57066679/164946041-e2f36fc4-c025-4acb-948c-8385c0c16362.png)

That is why I am very happy because I found solution with size like vertices.length in Java, vertices.Length() in C#, sizeof(vertices) in C++ and vertices.nbyte in Python and other...
