### ISSUE TITLE
why is linux x86 natives missing from lwjgl3?

### ISSUE THREAD

**Issue by jredfox** [LWJGL/lwjgl3#761]
### Question

linux definitely has x86(32 bit) support so why are the natives missing for this? is this a bug? games like minecraft still support 32 bit and I see you have 32 bit on other platforms so why is linux missing?

**Comment by octylFractal** [comment]
Duplicate of https://github.com/LWJGL/lwjgl3/issues/162.

**Comment by jredfox** [comment]
@octylFractal what about missing natives in macOs? they should also have powerpc64 and powerpc32?
