### ISSUE TITLE
Where is XReparentWindow(long display, long window, long parent_window) ?

### ISSUE THREAD

**Issue by DeafMan1983** [LWJGL/lwjgl3#763]
### Version

3.3.1

### Platform

Linux x64, Windows x64

### JDK

OpenJDK 11.x

### Module

LWGL3 and SWT

### Bug description

Hello I want have XReparentWindow it is X11 for Linux and FreeBSD

It mens parent of window example

I want put code like this: 
```
// If you use Linux then you need set
long gtk_win = GTK3.gtk_widget_get_window(comp.handle);
long gdk_win = GDK.gdk_window_get_width(gtk_win);
long x11_win = GDK.gdk_x11_window_get_xid(gdk_win);
long x11_display = GDK.gdk_x11_display_get_xdisplay(GDK.gdk_display_get_default());
X11.Functions.XReparentWindow(x11_display, glfwGetX11Window(window), x11_win);
```
But my Eclipse shows error underline:
![image](https://user-images.githubusercontent.com/57066679/167259837-81587347-41e2-469e-939f-bcdf9eb7169e.png)

Check @Ali-RS He tried to embed GLFW3 inside SWT, AWT or Swing See #742 

It works like SDL2 too 
For WIndows is ok with OS.SetParent, OS.SetWindowPos I know far.
Example:
![image](https://user-images.githubusercontent.com/57066679/167260124-f15df9e7-22e5-4816-9f0d-1b47c6fb2b0f.png)

But for Linux doesn't have XReparentWindow in X11.Functions

Please add `XReparentWindow()` in lwjgl's X11.Functions

Thank you!

### Stacktrace or crash log output

```shell
Invalid because XReparentWIndow doesn't exist in Functions
```

**Comment by Spasi** [comment]
Hey @DeafMan1983,

The X11 bindings are nowhere near complete, only a few functions are included. I'm not sure what you're trying to achieve, or how many more X11 functions you are going to need, but the bindings are defined in [X11.kt](https://github.com/LWJGL/lwjgl3/blob/master/modules/lwjgl/core/src/templates/kotlin/core/linux/templates/X11.kt). You're welcome to submit a PR that defines more functionality.

**Comment by DeafMan1983** [comment]
Hi sorry for late delay. But I don't care about Kotlin because I don't have experience of Kotlin. Sorry I will look for other windowing system like X11, XCB or DF for lwjgl3

**Comment by Spasi** [comment]
You don't need experience with Kotlin and you don't have to "care" about it. This code is only used offline for generating the Java + C bindings, there's no dependency to Kotlin at runtime.
