### ISSUE TITLE
How to call CloseHandle() and close() for external memory API?

### ISSUE THREAD

**Issue by BloCamLimb** [LWJGL/lwjgl3#765]
### Question

LWJGL version: 3.3.0
Modules: assimp, glfw, jemalloc, opengl, shaderc, stb, tinyfd, vma, vulkan

Description:
I want to use `KHRExternalMemoryFd` `vkGetMemoryFdKHR()` to get a POSIX file descriptor then a `EXTMemoryObjectFD` `glImportMemoryFdEXT` to share a Vulkan memory to OpenGL objects. However, from the javadoc:

> Each call to {@code vkGetMemoryFdKHR} <b>must</b> create a new file descriptor holding a reference to the memory object’s payload and transfer ownership of the file descriptor to the application. To avoid leaking resources, the application <b>must</b> release ownership of the file descriptor using the {@code close} system call when it is no longer needed, or by importing a Vulkan memory object from it. Where supported by the operating system, the implementation <b>must</b> set the file descriptor to be closed automatically when an {@code execve} system call is made.

How can I call `close(int)` from `unistd.h` in Java to avoid leaking resources? I didn't find that lwjgl provided such a native binding. And I also need Win32 API, so there's also `KHRExternalMemoryWin32` `vkGetMemoryWin32HandleKHR` and I need `CloseHandle` from `handleapi.h`.

**Comment by octylFractal** [comment]
https://javadoc.lwjgl.org/org/lwjgl/system/linux/UNISTD.html#close-int- exists. I'm not sure why you had trouble finding it?

I don't see CloseHandle for Windows though.

**Comment by BloCamLimb** [comment]
I have found a way for this.
```
/**
 * Native bindings to kernel32.dll.
 */
public class Kernel32 {

    private static final SharedLibrary KERNEL32 = Library.loadNative(Kernel32.class, "org.lwjgl", "kernel32");

    /**
     * Contains the function pointers loaded from the kernel32 {@link SharedLibrary}.
     */
    public static final class Functions {

        private Functions() {
        }

        /**
         * Function address.
         */
        public static final long
                CloseHandle = apiGetFunctionAddress(KERNEL32, "CloseHandle"),
                GetLastError = apiGetFunctionAddress(KERNEL32, "GetLastError");

    }

    /**
     * Returns the kernel32 {@link SharedLibrary}.
     */
    public static SharedLibrary getLibrary() {
        return KERNEL32;
    }

    /**
     * Closes an open object handle.
     *
     * @param hObject A valid handle to an open object.
     * @return If the function succeeds, the return value is nonzero.
     */
    @NativeType("BOOL")
    public static boolean CloseHandle(@NativeType("HANDLE") long hObject) {
        long __functionAddress = Functions.CloseHandle;
        return callPI(hObject, __functionAddress) != 0;
    }

    /**
     * Retrieves the calling thread's last-error code value. The last-error code is
     * maintained on a per-thread basis. Multiple threads do not overwrite each other's
     * last-error code.
     *
     * @return The return value is the calling thread's last-error code.
     */
    @NativeType("DWORD")
    public static int GetLastError() {
        long __functionAddress = Functions.GetLastError;
        return callI(__functionAddress);
    }
}
```
