### ISSUE TITLE
glslang bindings?

### ISSUE THREAD

**Issue by dustContributor** [LWJGL/lwjgl3#77]
Hi! I wonder if doing bindings for glslang would be feasible? (the C API that is).

https://github.com/KhronosGroup/glslang

Console standalone interface is kinda too basic. It would be nice to have a shader validation tool like that, hell it would allow you to make some graphical shader validation tool in Java :3

**Comment by Spasi** [comment]
It could be useful. The API is nice and should be easy to add to LWJGL. But I'm a bit skeptical because I don't think many users will be interested. Also, with Vulkan coming, focus has shifted to SPIR-V and there are many tools/libraries being made for it already. I think we should wait a few months to explore other options.

**Comment by dustContributor** [comment]
Yeah, good points. In the meanwhile I'll be trying [nVidia's Linux OpenGL debugger](https://developer.nvidia.com/linux-graphics-debugger).

**Comment by Spasi** [comment]
Another option: https://github.com/google/shaderc

**Comment by httpdigest** [comment]
I'd vote for adding bindings to the libshaderc part of shaderc. It's painful having to invoke a command line interface executable after every shader modification to build the spir-v files before launching the actual application. A way to use libshaderc as a library inside of a small utility class to compile the shaders at runtime would be great!

**Comment by Hugobros3** [comment]
Considering https://github.com/scenerygraphics/spirvcrossj is abandonned and deprecated now, it would be nice to have a direct replacement for the glslang bindings that used to offer. Also consider that shaderc just wraps glslang, which is the real GLSL compiler.
