### ISSUE TITLE
Heap Corruption on buffer.free() when directly allocated

### ISSUE THREAD

**Issue by tlf30** [LWJGL/lwjgl3#775]
### Version

3.3.2 (nightly), 3.3.1

### Platform

Windows x64

### JDK

Adoptium 17, Adoptium 18

### Module

LWJGL Core

### Bug description

When a buffer that was created using `xxxBuffer.allocateDirect(#)` is freed with `buffer.free()` there is a change for a JVM heap corruption (exit code 0xC0000374) where the JVM will exit without any error log or dump file. 

Since it appears that it is unsupported to free a buffer that was created with the `.allocateDirect` method, perhaps it would be best if the buffer instance that was created performed an override on the `free()` function and threw a `java.lang.UnsupportedOperationException`. 

If nothing else, perhaps with `Configuration.DEBUG_xxx.set(true);`  set, a warning will be printed and the free operation ignored. Otherwise, this is a very difficult bug to track down as the jvm simply exits without any clue as to why.

A simple app to reproduce:
```
public class HeapCorruptionTest {
    public static void main(String[] args) {
        while (true) {
            PointerBuffer temp = PointerBuffer.allocateDirect(100);
            temp.free();
        }
    }
}
```
Zip for full gradle project attached. 
[TestHeapCorruption.zip](https://github.com/LWJGL/lwjgl3/files/8970731/TestHeapCorruption.zip)

Thank you,
Trevor

**Comment by Spasi** [comment]
Hey @tlf30,

With `Configuration.DEBUG_MEMORY_ALLOCATOR` enabled (`-Dorg.lwjgl.util.DebugAllocator=true`), such a bug should be producing an `IllegalStateException` with the message: `The memory address specified is not being tracked: 0x<address>`. Are you seeing something different?

**Comment by tlf30** [comment]
Thank you for the fast response. 

I was not seeing any errors in my main application, I just tested. I have enabled debugging using: 
```
            Configuration.DEBUG.set(true);
            Configuration.DEBUG_FUNCTIONS.set(true);
            Configuration.DEBUG_STREAM.set(true);
            Configuration.DEBUG_LOADER.set(true);
            Configuration.DEBUG_STACK.set(true);
            Configuration.DEBUG_MEMORY_ALLOCATOR.set(true);
            Configuration.DISABLE_CHECKS.set(false);
            Configuration.DISABLE_FUNCTION_CHECKS.set(false);
```

I did add these to my test case, and indeed I see the following error:
```
[LWJGL] MemoryUtil allocator: DebugAllocator
Exception in thread "main" java.lang.IllegalStateException: The memory address specified is not being tracked: 0x298CAD70970
	at org.lwjgl.system.MemoryManage$DebugAllocator.untrack(MemoryManage.java:261)
	at org.lwjgl.system.MemoryManage$DebugAllocator.free(MemoryManage.java:222)
	at org.lwjgl.system.MemoryUtil.nmemFree(MemoryUtil.java:333)
	at org.lwjgl.system.CustomBuffer.free(CustomBuffer.java:60)
	at io.tlf.lwjgl.test.HeapCorruptionTest.main(HeapCorruptionTest.java:21)
```

I will need to investigate as to why debugging is not working in my app. 
Infact, I am not seeing the normal printout either, example from the test:
```
[LWJGL] Version: 3.3.1 build 7
[LWJGL] 	 OS: Windows 10 v10.0
[LWJGL] 	JRE: Windows amd64 17.0.1
[LWJGL] 	JVM: OpenJDK 64-Bit Server VM v17.0.1+12 by Eclipse Adoptium
[LWJGL] Loading JNI library: lwjgl
[LWJGL] 	Module: org.lwjgl
[LWJGL] 	Using SharedLibraryLoader...
[LWJGL] 	Found at: C:\Users\Trevor\AppData\Local\Temp\lwjglTrevor\3.3.1-build-7\lwjgl.dll
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Users\Trevor\AppData\Local\Temp\lwjglTrevor\3.3.1-build-7\lwjgl.dll
[LWJGL] Warning: Failed to instantiate memory allocator: org.lwjgl.system.jemalloc.JEmallocAllocator. Using the system default.
[LWJGL] Java 9 check intrinsics enabled
[LWJGL] Java 9 stack walker enabled
[LWJGL] Closure Registry: simple
```
I will investigate as to why debugging is not working in my app and report back.

**Comment by tlf30** [comment]
Ok, I discovered after some digging in the code that I am setting the `Configuration.DEBUG` flags after code startup, at which point LWJGL is already statically initialized and has already grabbed its copies of the config flags. Moving the flags into the jvm args did indeed work. 

Thank you for the help @Spasi.
