### ISSUE TITLE
AMD64 LWJGL SUPPORT

### ISSUE THREAD

**Issue by XDOneDude** [LWJGL/lwjgl3#778]
### Description

well my pc have the amd64 as the arch, and i want to program a engine in lwjgl but it says mismatch cuz i have a not compatible lwjgl support

**Comment by Spasi** [comment]
Please make sure the JVM architecture matches the LWJGL artifact architecture. There's already support for amd64.

If you're using Maven or Gradle, the LWJGL [build customizer](https://www.lwjgl.org/customize) can generate the appropriate definitions for you.

**Comment by XDOneDude** [comment]
not it works good but now there is a error about funding the glfwkeycallback when i add all the libraries in gradle
