### ISSUE TITLE
Missing functions in GL capabilities when using locale with non-Arabic numerals

### ISSUE THREAD

**Issue by boq** [LWJGL/lwjgl3#779]
### Version

3.3.1

### Platform

Windows x64

### JDK

Microsoft OpenJDK 17.0.3

### Module

OpenGL

### Bug description

`GLCapabilities` is missing entries for "basic" functions like `glEnable` when locale is set to one with non-Arabic numerals.

Cause:
- [Names for major versions are generated in runtime, using `String.format` without explicit locale](https://github.com/LWJGL/lwjgl3/blob/d2c07a68d0ea4d885199f9806c6fecd413bb397a/modules/lwjgl/opengl/src/main/java/org/lwjgl/opengl/GL.java#L422), causing it to use system default
- This results in entries like 
![image](https://user-images.githubusercontent.com/754542/179010387-762b7f41-9e97-4059-890b-cb9016346cd8.png)
- [Extension check assumes version number is written using Arabic numerals](https://github.com/LWJGL/lwjgl3/blob/d2c07a68d0ea4d885199f9806c6fecd413bb397a/modules/lwjgl/opengl/src/generated/java/org/lwjgl/opengl/GLCapabilities.java#L7472-L7474), causing whole method to not run, leaving entries pointing to `FUNCTION_MISSING_ABORT`.

### Stacktrace or crash log output

```shell
FATAL ERROR in native method: Thread[Render thread,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11C.glEnable(Native Method)
	at org.lwjgl.opengl.GL11.glEnable(GL11.java:724)
```

**Comment by Spasi** [comment]
Thank you @boq!
