### ISSUE TITLE
glfw key callback doesn't work on Linux

### ISSUE THREAD

**Issue by mertcanekiz** [LWJGL/lwjgl3#78]
I have tested the same code on both Windows and Linux and it seems that the key callback never gets called on linux but works fine on windows.

**Comment by kappaOne** [comment]
have you tried the latest nightly build of LWJGL3? I recall this issue being there in an older build but should be fixed in the most recent build.

**Comment by mertcanekiz** [comment]
It does indeed work with the latest nightly build. Thanks a lot!
