### ISSUE TITLE
What Remotery Viewer to use?

### ISSUE THREAD

**Issue by snoweuph** [LWJGL/lwjgl3#784]
### Question

What Viewer shouuld I use for Profiling with Remotery?

**Comment by Spasi** [comment]
Remotery's viewer runs in any web browser.

**Comment by snoweuph** [comment]
But where do I get the Viewer from? From the Official repo of Remotery, right? But what version of that Viewer should I use, becaue the newest one doesn't work

**Comment by Spasi** [comment]
The current Remotery bindings are based on [this commit](https://github.com/Celtoys/Remotery/tree/99d3de37ef68d13ea887bb1a1f485ae6921b0f8f). The `1.0.0` release is a few commits ahead, but might be compatible.

To avoid this issue in the future, I'll make sure that the bindings include the Remotery commit used to build them.

I'll also try to update to the latest version in the next 3.3.2 snapshot.

**Comment by snoweuph** [comment]
Nice, thx for the Info. it would be cool if LWGL would mention somewhere like in some example how to use the Remotery for profiling

**Comment by Spasi** [comment]
Hey @snoweuph,

The next 3.3.2 snapshot will include updated Remotery bindings (version 1.2.1) and the following improvements:

- The `Remotery` class javadoc now includes the commit used to create the LWJGL bindings.
- It also includes a script that clones the Remotery repository at that commit. You can then open the viewer at `vis/index.html` and it's guaranteed to be compatible with the bindings.
- Two simple samples are now available, [here](https://github.com/LWJGL/lwjgl3/tree/master/modules/samples/src/test/java/org/lwjgl/demo/util/remotery).

Thank you for opening this issue!
