### ISSUE TITLE
Linux framebuffer bindings

### ISSUE THREAD

**Issue by ghost** [LWJGL/lwjgl3#79]
Hi, can there be some kind of Linux framebuffer bindings (fbdev/directfb)?

**Comment by httpdigest** [comment]
Huh? "Framebuffer bindings?"
There are bindings for [GLFW](https://github.com/glfw/glfw) which provide the necessary functions to create an operating system window with a default framebuffer to render to.
There is also the possibility to create some kind of offscreen context/framebuffer using a hidden window `glfwWindowHint(GLFW_VISIBLE, GL_FALSE)` in GLFW. This in fact uses the window-provided context and framebuffer. It's just that the window itself is not visible to the user.
OpenGL also provides the possibility to create offscreen framebuffers either via the [EXT_framebuffer_object](https://www.opengl.org/registry/specs/EXT/framebuffer_object.txt) (see class [`EXTFramebufferObject`](http://javadoc.lwjgl.org/org/lwjgl/opengl/EXTFramebufferObject.html)), [ARB_framebuffer_object](https://www.opengl.org/registry/specs/ARB/framebuffer_object.txt) (see class [`ARBFramebufferObject`](http://javadoc.lwjgl.org/org/lwjgl/opengl/ARBFramebufferObject.html)) or the core functions in OpenGL 3.0 (see class [`GL30`](http://javadoc.lwjgl.org/org/lwjgl/opengl/GL30.html)).

**Comment by wb9688** [comment]
I mean fbdev or directfb, so you can play your game without X11

**Comment by Spasi** [comment]
I don't think there will be much interest for this. It wouldn't be compatible with GLFW either.
