### ISSUE TITLE
Crash with short module name in Library.detectPlatformMismatch()

### ISSUE THREAD

**Issue by code-disaster** [LWJGL/lwjgl3#794]
### Version

3.3.1

### Platform

Windows x64

### JDK

Corretto 1.8.0_302 (bundled with IntelliJ)

### Module

LWJGL core

### Bug description

I'm (ab-)using `Library.loadSystem()` to load shared libraries. When passing an empty (or short) module name parameter, a call to `detectPlatformMismatch()` will crash because the substring() call in its first code line will be out of bounds.

The name must be shorter than "org.lwjgl." and different to "org.lwjgl" for the crash to happen. Also, can only occur after loading the library has failed already.

**Comment by Spasi** [comment]
Thanks @code-disaster, `detectPlatformMismatch` will ignore non-LWJGL modules in the next 3.3.2 snapshot.

**Comment by Spasi** [comment]
LWJGL 3.3.2 snapshot 3 is now available, could you please verify that it now works for you?

**Comment by code-disaster** [comment]
Yes, works. No more crashes. Now prints an error message and throws UnsatisfiedLinkError.
