### ISSUE TITLE
Maybe binding inprogext.h for OpenAL-soft too?

### ISSUE THREAD

**Issue by Berstanio** [LWJGL/lwjgl3#795]
### Description

It would be great if https://github.com/kcat/openal-soft/blob/master/alc/inprogext.h could be binded to (at least I couldn't find the bindings).
Even if they are marked as "in progress extensions", from my testing some are working and are more like "experimental".
But I would also understand if they don't get added for the time they are considered "experimental".

**Comment by Spasi** [comment]
Hey @Berstanio,

I would prefer to avoid this unless there's a very good reason. Do you have an actual use for a specific experimental extension?

**Comment by Berstanio** [comment]
Hey,

I'm mainly interested in `AL_STOP_SOURCES_ON_DISCONNECT_SOFT`.
https://github.com/kcat/openal-soft/issues/533#issuecomment-825909097
Currently, when a audio device disconnects on windows, all audio sources gets stopped. This is pretty inconvinient, as described in the thread I linked, since it is hard to restart all the sources.

**Comment by Spasi** [comment]
Hey @Berstanio,

Added `AL_SOFTX_hold_on_disconnect` with ab9d3c3eec9c286c83db7c7993a9902aafc4d225. You can try it with `3.3.2-snapshot+10` which was just released.
