### ISSUE TITLE
Vulkan: Many `VkPresentInfoKHR` Buffer Setters Don't Update Size Fields

### ISSUE THREAD

**Issue by gudenau** [LWJGL/lwjgl3#796]
### Version

3.3.1

### Platform

Linux x64

### JDK

openjdk 19-ea 2022-09-20

### Module

Vulkan

### Bug description

Many setters in `o.l.v.VkPresentInfoKHR` do not update the related size fields in the structure when invoked, most other setters that take a buffer handle this automatically. There is an example of this in the same class for the field `pWaitSemaphores`

The affected setters are
- `pSwapchains`/`npSwapchains`
- `pImageIndices`/`npImageIndices`
- `pResults`/`npResults`

**Comment by gudenau** [comment]
I just found that `o.l.v.VkSubpassDescription` has similar issues with the following setters:
- `pColorAttachments`/`npColorAttachments`
- `pResolveAttachments`/`npResolveAttachments`

**Comment by octylFractal** [comment]
Those specifically are currently on purpose, see #539. I suspect the main ones in your issue are as well.

**Comment by gudenau** [comment]
Ah, probably the same thing then.
