### ISSUE TITLE
Kotlin compiler download for ant build is 404'ing

### ISSUE THREAD

**Issue by gerbi7** [LWJGL/lwjgl3#80]
I was just trying to build the repo on a friend's computer but the build is currently failing. It seems that ant is trying to download the kotlin compiler from https://teamcity.jetbrains.com/guestAuth/repository/download/bt345/0.13.599/kotlin-compiler-0.13.599.zip but as I've checked that file is not available. Considering that it seems that this url is specifying a version it seems logical to suspect that they are no longer hosting this older version (they are at around 0.13.776 now by the looks of it) and that this is an issue for lwjgl3.

**Comment by Spasi** [comment]
Updated kotlinc to the latest build. I'm on vacation atm, will find a better solution when I'm back.

**Comment by gerbi7** [comment]
We've gotten everything set up and it seems to be working fine. Thanks and enjoy your vacation!
