### ISSUE TITLE
how to build or package for gradle multi-modules

### ISSUE THREAD

**Issue by HoneyTorres** [LWJGL/lwjgl3#807]
### Question

How to build or package for gradle multi-modules

my major build.gradle.kts:
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    java
    application
    kotlin("jvm") version "1.7.10"
}

group = "io.longtooth.client"
version = "1.0-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_17
java.targetCompatibility = JavaVersion.VERSION_17

repositories {
    mavenLocal()
    mavenCentral()
}

subprojects {
    apply(plugin = "org.gradle.java")
    apply(plugin = "org.gradle.application")
    apply(plugin = "org.jetbrains.kotlin.jvm")

    dependencies {
        implementation(platform("org.lwjgl:lwjgl-bom:3.3.1"))

        implementation("org.lwjgl", "lwjgl")
        and so on.
    }

    tasks.withType<KotlinCompile> {
        kotlinOptions {
            freeCompilerArgs = listOf("-Xjsr305=strict")
            jvmTarget = "17"
        }
    }
}

tasks.forEach {
    it.enabled = false
}

The project tree is 
longtooth-client
build.gradle.kts
------longtooth-client-app
------------src/main/kotlin/package/Main.kt
------------build.gradle.kts
------longtooth-client-ui
------------src/main/kotlin/package/UI.kt
------------build.gradle.kts
------longtooth-client-graph
------------src/main/kotlin/package/Graph.kt
------------build.gradle.kts
------longtooth-client-sound
------------src/main/kotlin/package/Sound.kt
------------build.gradle.kts
------longtooth-client-net
------------src/main/kotlin/package/Net.kt
------------src/main/kotlin/package/Window.kt
------------build.gradle.kts

what need features to build this project

**Comment by httpdigest** [comment]
What? It is unclear what you want/mean. What exactly is the problem? Do you not know how to use Gradle in a multi-module setup? If so, then that's not a question for the LWJGL issues.
