### ISSUE TITLE
Some javadoc with image hyperlinks were generated incorrectly

### ISSUE THREAD

**Issue by NekoCaffeine** [LWJGL/lwjgl3#818]
### Version

3.3.2 (nightly)

### Platform

Windows x64

### JDK

unrelated

### Module

generator

### Bug description

VK10#VkPrimitiveTopology
The link has an unexpected section, "D:\CLONES\KHRONOS\Vulkan-Docs\"

**Comment by Spasi** [comment]
@NekoCaffeine thanks!
