### ISSUE TITLE
Use of deprecated extension EXT_debug_report in HelloVulkan.java

### ISSUE THREAD

**Issue by programmer3481** [LWJGL/lwjgl3#820]
### Question

HelloVulkan.java uses the extension EXT_debug_report, which was deprecated in favor EXT_debug_utils. Should it be changed to use the new extension?

I could write a pull request to port it, but I was wondering if there was any particular reason to be keep using EXT_debug_report.
Note that vulkan_triangle.c(HelloVulkan.java has a broken link to by the way), which is the original GLFW code HelloVulkan.java was ported from, is still using the older debug extension.

**Comment by Spasi** [comment]
Hey @programmer3481, done!

Btw, `HelloVulkan` is indeed a port from an old C demo and not really representative of how LWJGL+Vulkan code should be written. I highly recommend checking out @httpdigest's excellent Vulkan demos in [lwjgl3-demos](https://github.com/LWJGL/lwjgl3-demos/tree/main/src/org/lwjgl/demo/vulkan).
