### ISSUE TITLE
LWJGL_UTIL

### ISSUE THREAD

**Issue by GlobalHelp** [LWJGL/lwjgl3#83]
Hello,
Why have you deleted util in lwjgl 3 ?

This making many of tutorials are obsolete now.

**Comment by Spasi** [comment]
There are better replacements for old util functionality in LWJGL 2. Old tutorials are obsolete anyway, the core API has been completely replaced (Display, input, etc).

**Comment by dustContributor** [comment]
Death to Display/Mouse/Keyboard!
