### ISSUE TITLE
Update to vulkan 1.3.237

### ISSUE THREAD

**Issue by tlf30** [LWJGL/lwjgl3#834]
### Description

Hello @Spasi,
Normally I would not bug you with a Vulkan update request (especially since Vulkan is always pushing out updates),
but in this instance I am keen to play with NVIDIA's new extensions: VK_NV_memory_decompression, VK_NV_copy_memory_indirect. You can read about them here: https://developer.nvidia.com/rtx-io. 

It allows sending compressed assets directly to the GPU for decompression, and in theory (I want to see for myself), decrease load times significantly at multiple stages in the asset load process. 

I don't want to rush you, as I know you are busy with many other things (including your actual job), but I did want to bring this to your attention as this is a very cool extension that I would like to play with in the near future. 

Thank you,
Trevor

**Comment by Spasi** [comment]
Hey @tlf30,

LWJGL `3.3.2-snapshot+8` is now available with Vulkan 1.3.237, MoltenVK 1.2.1 and latest VMA.

**Comment by tlf30** [comment]
Great, thank you!
