### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION in a JNI call

### ISSUE THREAD

**Issue by Frontear** [LWJGL/lwjgl3#836]
### Version

3.3.1

### Platform

Windows x64

### JDK

OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)

### Module

GLFW bindings

### Bug description

This issue was reported over to me from a user in our discord. Upon running their Minecraft game, it proceeded to crash relatively quickly, citing atio6axx.dll, which is an amd dll used by their gpu. I went ahead and reported the issue to MS in [#361](https://github.com/microsoft/openjdk/issues/361) because it seems to relate heavily to an issue that occured a few days prior, but with an NVIDIA driver instead (was not related to LWJGL). This issue specifically arises when LWJGL attempts to invoke glfwCreateWindow, crashing with an exception access violation.

Relevant JVM dump:
[hs_err_pid8924.log](https://github.com/LWJGL/lwjgl3/files/10252925/hs_err_pid8924.log)

**Comment by Spasi** [comment]
Hey @Frontear,

Issues like this are impossible to diagnose from our side. Also, it's almost certain not a bug in LWJGL, but rather one or more of the following:

- a bug in whatever Minecraft modding is going on
- a bug in Minecraft
- a random driver/software/hardware issue on user's machine
- a bug in GLFW

In any case, we won't be able to provide any help without more information or at least a way to reproduce the crash.

**Comment by Frontear** [comment]
Hi,

After doing some digging, it seems entirely related to MS OpenJDK. Many users have reported having JVM crashes, and the dll responsible is more often than not jvm.dll. So far there has been 5+ reports with almost identical traces all linking back to the jvm.dll, and the fact that they use ms openjdk. Switching to eclipse adoptium releases completely resolves all these issues.

**Comment by ArcaneSunku** [comment]
I know this is closed, but I'm not entirely what is the certainty that it is related to MS OpenJDK as I got the very same error for Minecraft modding with the ati6xx.dll which is an AMD related driver. It has been confirmed many times on the Minecraft Forge forums that it is AMD's issue, not Microsoft's JVM. When it is jvm.dll it might be, but his error log clearly states and AMD driver.
