### ISSUE TITLE
Add Draco Bindings for usage with models

### ISSUE THREAD

**Issue by hYdos** [LWJGL/lwjgl3#847]
### Library

Google Draco

### Project page

https://google.github.io/draco/

### Source repository

https://github.com/google/draco

### Platforms

Linux x64, Linux arm64, Linux arm32, macOS x64, macOS arm64, Windows x64, Windows x86, Windows arm64

### Description

We need this native library to be able to effectively save space on models. This is needed any time a model is needed in a environment where space constraints exist

**Comment by Spasi** [comment]
Hey @hYdos,

Do we really need Draco bindings after #773? Is the Assimp integration missing features?

**Comment by hYdos** [comment]
The issue with not having Draco support outside of assimp is that it's impossible for us to use it with a tool such as jgltf (a Java based gltf reader with a few features missing from assimp)

**Comment by Spasi** [comment]
Hey @hYdos,

Assimp has just been upgraded with Draco `1.5.6` (will be available in LWJGL with the next snapshot). Does this cover your use case?

Note that Draco does not provide a C API, making it unlikely we'll ever see LWJGL bindings for it.

**Comment by hYdos** [comment]
It's not ideal and sadly won't alr for me but for anyone using assimp this is perfect
