### ISSUE TITLE
Cursor position callback is called although there is no movement

### ISSUE THREAD

**Issue by intrigus** [LWJGL/lwjgl3#85]
If I don't move the cursor, the callback is still invoked.
My code uses a class from libgdx to load the natives, I hope you can still test this issue.
OS: Windows 7 32 bit
JVM: JRE 8.51

```

package com.intrigus.test;

import org.lwjgl.glfw.GLFW;
import org.lwjgl.glfw.GLFWCursorPosCallback;
import org.lwjgl.opengl.GL;
import org.lwjgl.opengl.GL11;

public class CursorPosTest {
	private static GLFWCursorPosCallback cursorPosCallback;

	public static void main (String[] args) {
//The native loader from libgdx...
		Lwjgl3NativesLoader.load(!Lwjgl3ApplicationConfiguration.disableAudio);

		cursorPosCallback = new GLFWCursorPosCallback() {
			@Override
			public void invoke (long window, double xpos, double ypos) {
				System.out.println("xpos:" + xpos + "ypos:" + ypos);
			}
		};

		if (GLFW.glfwInit() != GL11.GL_TRUE) {
			throw new IllegalStateException("Unable to initialize GLFW");
		}
		long window = GLFW.glfwCreateWindow(640, 480, "Simple example", 0, 0);
		if (window == 0) {
			GLFW.glfwTerminate();
			throw new RuntimeException("Failed to create the GLFW window");
		}

		GLFW.glfwMakeContextCurrent(window);
		GL.createCapabilities();
		GLFW.glfwSetCursorPosCallback(window, cursorPosCallback);
		while (GLFW.glfwWindowShouldClose(window) != GL11.GL_TRUE) {
			GLFW.glfwPollEvents();
		}
	}

}
```

**Comment by intrigus** [comment]
@Spasi Could you please either verify that this is a bug or say what I have done wrong?

**Comment by Spasi** [comment]
I cannot reproduce this, with either the LWJGL tests or the code you posted (without libGDX). What does Sys.getVersion() print for you?

**Comment by intrigus** [comment]
On which platforms did you try the tests?

Sys.getVersion() returns 3.0.0b.
Maven/Eclipse says that I use lwjgl-3.0.0b-20150920.083825-36.jar.

Could you maybe post your test/link to your test?

**Comment by Spasi** [comment]
On Windows 10, same LWJGL build. The tests I tried were:

- Your code, minus `Lwjgl3NativesLoader.load(!Lwjgl3ApplicationConfiguration.disableAudio);`.
- The GLFW [Events](https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/test/java/org/lwjgl/demo/glfw/Events.java) demo.

**Comment by intrigus** [comment]
The GLFW Events demo, has the same problem.
I also tried it without Lwjgl3NativesLoader, but the Issue persists :(

**Comment by Spasi** [comment]
Have you tried with a different mouse or different computer?

**Comment by intrigus** [comment]
Another mouse did not change anything.
It works on Win7 64, but I did not test that myself. Somebody tested it for me.
I also tested it on Win XP 32bit and I have the same problem :(

**Comment by Spasi** [comment]
I'm fairly sure this isn't an LWJGL bug. To verify, could you please run [this test](https://s3.amazonaws.com/build.lwjgl.org/res/events.zip)? It's the GLFW events test (similar to the LWJGL Events demo). I just compiled it for Windows x86.

If there's a trust issue with the .exe, you could clone GLFW and build it locally. You'll need CMake and Visual Studio Community.

**Comment by intrigus** [comment]
It's indeed a GLFW bug, I'm going to report it.
Should I close this Issue now or should I leave it open for some time?

**Comment by httpdigest** [comment]
It must have been fixed during the last days. I had the exact same issue with the cursor position callback being fired every second without moving the mouse. I tested it with a lwjgl nightly build that was about a week old or so. Now, I built everything fresh and the issue is no more.
I was also using Windows 7 x64.
