### ISSUE TITLE
OpenAL AL_SOFT_events extension

### ISSUE THREAD

**Issue by rafaskb** [LWJGL/lwjgl3#854]
### Description

Is there any way OpenAL's `AL_SOFT_events` extension could be added to lwjgl3? I'm a libGDX user and we could really use this extension there. 😁 
https://openal-soft.org/openal-extensions/SOFT_events.txt

Also I see this extension is listed under `openal-soft-1.21.0` here https://github.com/LWJGL-CI/openal-soft/blob/master/ChangeLog#L115, but the [changelog for 3.3.2](https://github.com/LWJGL/lwjgl3/blob/master/doc/notes/3.3.2.md) doesn't say anything about it.

**Comment by Hangman** [comment]
+1
I could use this as well.

**Comment by Hangman** [comment]
Thanks Spasi 🥇

**Comment by Spasi** [comment]
Hey @rafaskb & @Hangman,

LWJGL `3.3.2-snapshot+9` is now available with OpenAL Soft 1.23.0 and the `AL_SOFT_events` extension is included.
