### ISSUE TITLE
OpenAL class `SOFTReopenDevice` not found!

### ISSUE THREAD

**Issue by Brahvim** [LWJGL/lwjgl3#863]
### Module

OpenAL

### Bug description

In nearly every recent release of LWJGL, I do not find the `SOFTReopenDevice` class. Sure, I could compile it from the source and use it that way (I tried adding the class back in myself, but it seems that I failed...), but it is not included by the download customizer, no matter what I change. Has it been removed? If so, why?

I do not feel it has been removed. [Since it is also documented](https://javadoc.lwjgl.org/org/lwjgl/openal/SOFTReopenDevice.html), I expect to find it in the compiled code I get.

...Is there a workaround to this issue?

**Comment by tlf30** [comment]
`SOFTReopenDevice ` is part of the snapshots for 3.3.2. You will need to use a recent snapshot to have access to the class. I checked going back to May 24th of 2022 and it was present in the snapshot, and is present in the latest snapshot. I am not sure what versions you have checked, but the javadocs you linked to are for the latest snapshot.

**Comment by Brahvim** [comment]
Apologies for removing the part specifying LWJGL versions. The _thing is,_ that the OpenAL extension is available in no version of LWJGL. Not even LWJGL `2` subversions!

**Comment by tlf30** [comment]
As stated it is available in the snapshot. I did not see it in the most recent stable release.
