### ISSUE TITLE
Does LWJGL move any data off heap

### ISSUE THREAD

**Issue by Danjhop4** [LWJGL/lwjgl3#881]
### Question

If you use a non direct buffer does it move it off heap I have a program showing 500 so mb and gc spikes

**Comment by knokko** [comment]
No: you can't use non-direct buffers in any LWJGL functions. LWJGL doesn't move any of your byte buffers.

**Comment by Danjhop4** [comment]
> No: you can't use non-direct buffers in any LWJGL functions. LWJGL doesn't move any of your byte buffers.

Ok
