### ISSUE TITLE
AL_SOFT_buffer_length_query extension

### ISSUE THREAD

**Issue by Hangman** [LWJGL/lwjgl3#885]
### Description

I could use another OpenAL extension that is currently missing:
**AL_SOFT_buffer_length_query** (since openal-soft-1.23.1)
[https://openal-soft.org/openal-extensions/SOFT_buffer_length_query.txt](https://openal-soft.org/openal-extensions/SOFT_buffer_length_query.txt)

Especially useful if you have compressed audio data in an AL buffer and can't determine the length by the number of bytes.

Thanks for considering.

**Comment by Spasi** [comment]
Thanks @Hangman, the first 3.3.3 snapshot will include OpenAL Soft 1.23.1 and the new extensions.

**Comment by Hangman** [comment]
Thank you very much.
