### ISSUE TITLE
2D MemCopy Options?

### ISSUE THREAD

**Issue by Speiger** [LWJGL/lwjgl3#895]
### Description

o/
I checked the issue tracker for things of this.
Since LWJGL3 already includes memcpy options.
I would wonder if the possibility of 2D variants could exists?
Mainly because you use 2D textures most of the times anyways and if you want to work with pointers/buffers and wanted to copy a part of a texture from a buffer or to a buffer you would have to come up with your own implementation that may or may not be a for loop that isn't really optimized.

Providing a simple solution like a 2D memcpy option that requires a width to be included to provide you with a good base library of performance would be nice.

Unless something like that already exists in a Library or i missed it somewhere, or you think it isn't really a good idea/solution you can ofc close this issue :)

Just thought maybe its a good idea to implement, so more performant options are more easily accessible :)

**Comment by ws909** [comment]
What kind of copying operation is this? Is it normal memory stored in the RAM, operated on by the CPU? What kind of image layout? Is a for-loop with `memcpy` not sufficient?

**Comment by Speiger** [comment]
@ws909 well if you are working with buffers/pointers it is not so easy to write a for loop using memcopy.
Thats why i suggested that.

Since usually the go to method from most people i have seen is a literal for loop and processing byte byte instead.
Since MemCopy operations exist why not provide a bit more help.

**Comment by ws909** [comment]
> Since MemCopy operations exist why not provide a bit more help.

Because how to copy the memory depends on the memory layouts of the source and destination, the regions copied, etc. It’s not a single function. 

> processing byte byte instead.

That’s only necessary if the source and destination formats differ at the pixel level, or if the rows and columns are laid out differently. Vulkan (and I must assume OpenGL) already provide functionality for this. Especially for Vulkan, this isn’t always supported, neither if you want to do it on the host (CPU), so in that case, you’ll have to write your own (or a very large amount of your own functions, depending on how many format conversions you want to support). The new vector API coming as part of project Panama and Valhalla will be able to speed these homemade algorithms up. That said, if the source and destination formats are the same, can’t you just do a copy of the entire memory? A single call to `mempcy` should suffice for that.

**Comment by Speiger** [comment]
@ws909 ok i had to think of the use-case i was thinking of when creating this issue.
The Idea being that you have a dynamic texture where you want to update segements from.
That allows you to have 2 choices.
- Update the entire buffer every time it changes.
- Keep track of the changes and update the changed areas themselves and upload them as needed.

Second point is you have to either recreate smaller buffers and upload them to the GPU.
If you want to work with ByteBuffs instead of a Int/Long array (Long for HDR) you kinda have to write a really special function to make things work. Memcopy assists in that, but if you work with a 3D array and could define sizes you could also make use of the special optimizations that LWJGL provides.

Panama/Valhalla wouldn't help at all there since it is only "processing big data" not "copying a small piece out of big data".

This is why i suggest it, because i saw they did special optimizations for memcopy itself, and these would hardly take effect compared to if lwjgl could provide special functions that can provide much more optimizations with it.

**Comment by ws909** [comment]
Do you have some code for context?

**Comment by Speiger** [comment]
@ws909 i am in a middle of a rewrite and this is old code that i want to replace (haven't gotten to that part yet)

<details>
<summary>Code</summary>
<p>

```java
	@Override
	public void processChanges(boolean full)
	{
		if(full)
		{
			ByteBuffer buffer = MemoryUtil.memAlloc(data.length * 4);
			for(int i = 0;i<data.length;i++)
			{
				int pixel = data[i];
				buffer.put((byte)((pixel >> 16) & 0xFF));
				buffer.put((byte)((pixel >> 8) & 0xFF));
				buffer.put((byte)(pixel & 0xFF));
				buffer.put((byte)((pixel >> 24) & 0xFF));
			}
			buffer.flip();
			bindTexture();
			GL11.glTexParameterf(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MIN_FILTER, GL11.GL_NEAREST);
			GL11.glTexParameterf(GL11.GL_TEXTURE_2D, GL11.GL_TEXTURE_MAG_FILTER, GL11.GL_NEAREST);
			AllocationTracker.INSTANCE.addGPUBytes(buffer.remaining());
			GL11.glTexImage2D(GL11.GL_TEXTURE_2D, 0, GL11.GL_RGBA, width, height, 0, GL11.GL_RGBA, GL11.GL_UNSIGNED_BYTE, buffer);
			MemoryUtil.memFree(buffer);
			dirtyChunks.clear();
		}
		else
		{
			bindTexture();
			Thread thread = Thread.currentThread();
			for(Iterator<Entry<IntSet>> iter = Int2ObjectMaps.fastIterator(dirtyChunks);iter.hasNext() && !thread.isInterrupted();iter.remove())
			{
				Entry<IntSet> values = iter.next();
				int key = values.getIntKey();
				int chunkX = BitUtil.toFirstShort(key) * 16;
				int chunkZ = BitUtil.toSecondShort(key) * 16;
				int width = 0;
				int height = 0;
				for(IntIterator subIt = values.getValue().iterator();subIt.hasNext();)
				{
					int index = subIt.nextInt();
					width = Math.max(width, ((index >> 4) & 0xF) + 1);
					height = Math.max(height, (index & 0xF) + 1);
				}
				try(MemoryStack stack = MemoryStack.stackPush())
				{
					ByteBuffer buffer = stack.malloc(width * height * 4);
					for(int y = 0;y<height;y++)
					{
						for(int x = 0;x<width;x++)
						{
							int pixel = data[((chunkZ + y) * this.width) + chunkX + x];
							buffer.put((byte)((pixel >> 16) & 0xFF));
							buffer.put((byte)((pixel >> 8) & 0xFF));
							buffer.put((byte)(pixel & 0xFF));
							buffer.put((byte)((pixel >> 24) & 0xFF));
						}
					}
					buffer.flip();
					AllocationTracker.INSTANCE.addGPUBytes(buffer.remaining());
					GL11.glTexSubImage2D(GL11.GL_TEXTURE_2D, 0, chunkX, chunkZ, width, height, GL11.GL_RGBA, GL11.GL_UNSIGNED_BYTE, buffer);
				}
			}
		}
		if(dirtyChunks.isEmpty())
		{
			((ITrimmable)dirtyChunks).trim();
		}
	}
```

</p>
</details>

While it is being processed there is not much you could do with Panama.
And a optimization that i plan to do is store the data instead of a int[] as a long (pointer) and have the pixels automatically GPU aligned and when read i them from the CPU side i simply construct them back since that can be faster.
Or use a different format :)

But a 2D memory copy would be really handy here though 64 bytes at once (though 1024 in in total) would not get the same optimization as the 1024 bytes optimization
The code i am referencing.
https://github.com/LWJGL/lwjgl3/blob/dd3101752c76d4f66a856609042c96596b470a6b/modules/lwjgl/core/src/main/java/org/lwjgl/system/MultiReleaseMemCopy.java#L16C50-L16C50

**Comment by ws909** [comment]
> ```java
> ByteBuffer buffer = MemoryUtil.memAlloc(data.length * 4);
> for (int i = 0; i < data.length; i++) {
>     int pixel = data[i];
>     buffer.put((byte)((pixel >> 16) & 0xFF));
>     buffer.put((byte)((pixel >> 8) & 0xFF));
>     buffer.put((byte)(pixel & 0xFF));
>     buffer.put((byte)((pixel >> 24) & 0xFF));
> }
> ```

Unless I missed something really obvious, one improvement here is at least to do:
```java
final var wrapper = IntBuffer.wrap(data);
final var buffer = ByteBuffer.allocateDirect(data.length * 4);
buffer.asIntBuffer().put(0, wrapper, 0, wrapper.remaining());
```

This is a bulk copy, and leaves you free of the manual loop.

Actually, on second reading, aren't you converting an ARGB to RGBA? That's a format conversion. You can't do a simple bulk copy for that. You necessarily have to loop over every pixel for that.

You're likely better off just keeping the textures stored in RAM, in direct/native memory, instead of Java arrays. This'll provide better performance overall, if you're going to need access to their contents from outside Java.

If you don't want to do this, you should consider keeping a pool of native/direct buffers which you reuse (don't do this with Java arrays (the JVM is better at managing this itself)). Then you won't have to reallocate an intermediate buffer all the time. Perhaps not even a pool is necessary; a `private final ThreadLocal<ByteBuffer> transferBuffers` should suffice.

If you're copying only regions of a texture, how that copy is performed, depends on the layout/format of the source and destination texture. You will need an implementation for each set of these.

> I would wonder if the possibility of 2D variants could exists?

How many, and for which formats, do you envision LWJGL to support?

**Comment by Speiger** [comment]
@ws909 ok you missunderstood a TON of things.

> Unless I missed something really obvious, one improvement here is at least to do:

First: I didn't ask for a 2D optimization for the "Entire Texture copy" but small segments of the texture. That would be the lower part of the code. Where you copy pieces of the original array into a subbuffer to then upload to the GPU, hence the 2D array support since you JUMP AROUND LIKE CRAZY within the buffer.
Second: Your solution is BAD. Like REAL BAD. Read: https://github.com/LWJGL/lwjgl3-wiki/wiki/1.3.-Memory-FAQ#tldr

> You're likely better off just keeping the textures stored in RAM, in direct/native memory, instead of Java arrays. This'll provide better performance overall, if you're going to need access to their contents from outside Java.
If you don't want to do this, you should consider keeping a pool of native/direct buffers which you reuse (don't do this with Java arrays (the JVM is better at managing this itself)). Then you won't have to reallocate an intermediate buffer all the time. Perhaps not even a pool is necessary; a private final ThreadLocal<ByteBuffer> transferBuffers should suffice.

Please read what i wrote:
> And a optimization that i plan to do is store the data instead of a int[] as a long (pointer) and have the pixels automatically GPU aligned and when read i them from the CPU side i simply construct them back since that can be faster.
Or use a different format :)

I even Imply what you just said. Where i keep a pointer where the pixels are GPU Aligned. In other words: RGBA.

> If you're copying only regions of a texture, how that copy is performed, depends on the layout/format of the source and destination texture. You will need an implementation for each set of these.

OpenGL has a SubTexture function where you can upload from a "freshly created buffer" data to a specific region of memory.
How the copy is performed would be simple: I define: I want to copy data in the buffer from location x/y with the bounds of x/y to said other buffer.

> How many, and for which formats, do you envision LWJGL to support?

How many formats? 0. Since even memcpy at the moment expects the user to already have the format prepared in the first place a 2d variant would simply copy data from 1 buffer into a second one without changing the data itself.

Since you are not getting it let me show you mockup code.
```java
public void memcpy2d(ByteBuffer source, ByteBuffer dest, int widthInBytes, int heightInbytes, int totalWidthInBytes) {
	//Implementation from LWJGL3
	//THIS IS WHAT I SUGGEST TO BE ADDDED
}

public class TextureExample {
	ByteBuffer data; //Live data (Could also be a long pointer)
	int width; //Defined by constructor
	int height; //Defined by constructor
	
	public void uploadTextureRegion(int x, int y, int subWidth, int subHeight) {
		ByteBuffer source = this.data;
		source.position((y * width) + x * 4);
		ByteBuffer target = MemoryUtil.memalloc(subWidth * subHeight * 4);
		MemoryUtil.memcpy2d(this.data, target, subWidth*4, subHeight*4, width*4); //The function is suggest to be added
		GL11.glTexSubImage2D(GL11.GL_TEXTURE_2D, 0, x, y, subWidth, subHeight, GL11.GL_RGBA, GL11.GL_UNSIGNED_BYTE, target);
		MemoryUtil.memFree(target);
	}
}
```

**Comment by ws909** [comment]
> @ws909 ok you missunderstood a TON of things.

That happens. I am no stranger to misunderstanding.

**Comment by Spasi** [comment]
Hey @Speiger,

> let me show you mockup code.

See `GL_UNPACK_ROW_LENGTH` for this use-case. It will allow you to pass the source data in `glTexSubImage2D` directly, eliminating the need for a 2d memcpy. Effectively, it's already implemented in the OpenGL driver.

[glPixelStore](https://registry.khronos.org/OpenGL-Refpages/gl4/html/glPixelStore.xhtml) can do a lot for you, but `GL_UNPACK_ROW_LENGTH` and `GL_UNPACK_ALIGNMENT` should cover most cases.

As for having 2d memcpy functionality in LWJGL, I'd say it's out-of-scope. It wouldn't be much more than a for-loop that calls 1d `memcpy` on each iteration, with the appropriate offset/stride. That's trivial to implement in application code. Maybe moving the loop to native code would be beneficial (to eliminate the JNI overhead on each `memcpy` call), but I don't think it's worth the trouble.

**Comment by Speiger** [comment]
Hey @Spasi 
Thank you for the answer.

> See GL_UNPACK_ROW_LENGTH for this use-case. It will allow you to pass the source data in glTexSubImage2D directly, eliminating the need for a 2d memcpy. Effectively, it's already implemented in the OpenGL driver.

Oh so it allows to upload a row instantly passing the full buffer as needed? Yeah ok that could help.
Kinda has to evaluate where unpack row makes sense in the way of OpenGL overhead :)

> As for having 2d memcpy functionality in LWJGL, I'd say it's out-of-scope

It was a suggestion afterall because i thought a lot of people could benefit from that :)
But yeah i can see why it is out of scope. Maybe for LWJGL4 xD /s

Anyways thanks for this valuable information and a great new week for you :)
