### ISSUE TITLE
Assimp appears to have issues parsing floats using exponential notation in .obj files

### ISSUE THREAD

**Issue by ahaggblade** [LWJGL/lwjgl3#899]
### Version

3.3.2, 3.3.1

### Platform

Linux x64

### JDK

OpenJDK 17

### Module

Assimp

### Bug description

When parsing Wavefront .obj files, the Assimp module has some odd behavior for values in the format x.xxxxxxE-xx. Values are somehow always given 8 digits of precision, even when only 7 are supplied. This is particularly odd since floats are only guaranteed 7 digits of precision in Java.

Small case to reproduce:
```
AIScene scene = Assimp.aiImportFile("file", 0);
float y = AIMesh.create(scene.mMeshes().get()).mVertices().y();
System.out.println(y);
```

File contents:
`v 0.0 3.820003E-16 0.0`

Output:
`3.8200032E-16`

Expected output:
`3.820003E-16`

Some other examples I ran into (format is [expected actual]):
`[[-3.820003E-16 -3.8200032E-16] [-1.570124E-16 -1.5701239E-16] [-1.859145E-5 -1.8591449E-5] [-3.804461E-16 -3.8044612E-16] [-1.108573E-16 -1.10857296E-16] [-1.859145E-5 -1.8591449E-5] [-3.820003E-16 -3.8200032E-16] [-3.804461E-16 -3.8044612E-16] [1.854271E-33 1.8542709E-33] [-5.442301E-33 -5.4423008E-33] [-2.10011E-32 -2.1001101E-32] [-3.27853E-32 -3.2785302E-32] [-2.850181E-32 -2.8501812E-32] [-2.887088E-32 -2.8870882E-32] [3.155444E-32 3.1554438E-32] [3.155444E-32 3.1554438E-32] [-3.022244E-32 -3.0222442E-32] [-2.894585E-32 -2.8945852E-32] [-2.453242E-32 -2.4532422E-32] [-2.212605E-32 -2.2126051E-32] [-1.870725E-32 -1.8707249E-32] [-1.128528E-32 -1.12852806E-32] [-8.277577E-33 -8.277578E-33] [-4.234555E-33 -4.2345553E-33] [-2.533625E-33 -2.5336253E-33] [-2.77185E-33 -2.7718502E-33] [-5.013071E-33 -5.0130712E-33] [-9.74262E-33 -9.7426206E-33] [-2.533625E-33 -2.5336253E-33] [-4.234555E-33 -4.2345553E-33] [-8.277577E-33 -8.277578E-33] [-1.128528E-32 -1.12852806E-32] [-1.870725E-32 -1.8707249E-32] [-2.212605E-32 -2.2126051E-32] [-2.453242E-32 -2.4532422E-32] [-2.894585E-32 -2.8945852E-32] [-3.022244E-32 -3.0222442E-32] [-1.248347E-32 -1.2483471E-32] [3.155444E-32 3.1554438E-32] [3.155444E-32 3.1554438E-32] [3.155444E-32 3.1554438E-32] [1.564664E-32 1.5646641E-32] [3.505887E-33 3.5058873E-33] [-3.049452E-32 -3.0494522E-32] [-1.293871E-32 -1.2938709E-32] [-3.20197E-32 -3.2019702E-32] [-3.187313E-32 -3.1873133E-32] [1.854271E-33 1.8542709E-33] [-5.442301E-33 -5.4423008E-33] [-2.10011E-32 -2.1001101E-32] [-3.27853E-32 -3.2785302E-32] [-2.850181E-32 -2.8501812E-32] [-2.887088E-32 -2.8870882E-32] [3.155444E-32 3.1554438E-32] [3.155444E-32 3.1554438E-32] [-5.960464E-10 -5.9604643E-10] [-5.960464E-10 -5.9604643E-10] [-5.960464E-10 -5.9604643E-10] [-5.960464E-10 -5.9604643E-10] [6.493553E-7 6.4935534E-7] [-5.960464E-10 -5.9604643E-10] [-5.960464E-10 -5.9604643E-10] [-5.960464E-10 -5.9604643E-10] [-5.960464E-10 -5.9604643E-10] [-5.960464E-10 -5.9604643E-10] [-5.960464E-10 -5.9604643E-10] [-5.960464E-10 -5.9604643E-10] [-5.960464E-10 -5.9604643E-10] [-5.960464E-10 -5.9604643E-10] [-5.960464E-10 -5.9604643E-10] [6.493553E-7 6.4935534E-7] [-5.960464E-10 -5.9604643E-10] [-5.960464E-10 -5.9604643E-10] [-5.960464E-10 -5.9604643E-10] [-5.960464E-10 -5.9604643E-10] [-5.960464E-10 -5.9604643E-10] [-5.960464E-10 -5.9604643E-10] [1.652972E-18 1.6529721E-18] [1.652972E-18 1.6529721E-18] [1.652972E-18 1.6529721E-18]]`

**Comment by Spasi** [comment]
Hey @ahaggblade,

The number parsing happens internally in Assimp, if that is not accurate enough, then there's nothing LWJGL or Java can do to fix it. Assimp can be built with `ASSIMP_DOUBLE_PRECISION`, but even if that improves parsing precision, the LWJGL bindings are not compatible with it.
