### ISSUE TITLE
How do you build to local files instead of the server

### ISSUE THREAD

**Issue by Danjhop4** [LWJGL/lwjgl3#900]
### Question

I want to mod lwjgl but I can’t work out how to make it on my computer think it may of uploaded instead

**Comment by Danjhop4** [comment]
Opengl was using system32 version the one built into windows

**Comment by Danjhop4** [comment]
https://github.com/Danjhop4/lwjgl3-/tree/master
here are my code changes

**Comment by Spasi** [comment]
For local builds, set the `LWJGL_BUILD_OFFLINE` environment variable to `true`.

There is nothing wrong with OpenGL loading. On Windows, LWJGL loads both `lwjgl_opengl.dll` (bundled with LWJGL) and `opengl32.dll` from the system.
