### ISSUE TITLE
Opengl uses wrong opengl32 

### ISSUE THREAD

**Issue by Danjhop4** [LWJGL/lwjgl3#902]
### Version

3.3.1

### Platform

Windows x64

### JDK

Microsoft openjdk

### Module

Opengl

### Bug description

opengl uses opengl32 in the system32 folder being 32 bit or not tracking memory effecting java mayby tried building a local copy and failled

**Comment by Spasi** [comment]
I don't even know what to write here. Replied to submitter in private.
