### ISSUE TITLE
http/https doc question/problems

### ISSUE THREAD

**Issue by Speiger** [LWJGL/lwjgl3#906]
### Question

Is there a reason why all documentation links are "http" based instead of "https"?
Also in Eclipse (latest version) for whatever reason the "href" links do not work you have to manually copy/paste the URL to open it in browsers.
And I checked with other libraries (Gson for example) and their links work fine.

**Comment by Spasi** [comment]
@Speiger Old URLs have been migrated to new domains and/or `https` where possible. Thanks!

Not sure what might be wrong with links in Eclipse. Is there a difference in javadoc syntax between LWJGL and other libraries?

**Comment by Speiger** [comment]
No problem.

Here is a link i tested and works for a fact:
```java
<p>See the <a href="https://sites.google.com/site/gson/gson-user-guide">Gson User Guide</a>
```

While LWJGL uses this.
```
@see <a target="_blank" href="http://docs.gl/gl4/glGetSamplerParameter">Reference Page</a>
```

That doesn't work.
I assume the <p> could be the difference.

**Comment by Spasi** [comment]
Try copying the LWJGL link to your code and removing the `target="_blank"` attribute. Does it work like that?

**Comment by Speiger** [comment]
@Spasi yeah removing the "target" fixes it.
