### ISSUE TITLE
Overly strict module dependencies

### ISSUE THREAD

**Issue by NekoCaffeine** [LWJGL/lwjgl3#917]
### Question

In the `3.3.3 snapshot`, the module-info of `lwjgl-glfw` explicitly requires `opengl`, `egl`, `vulkan`.
Means that it won't compile without adding these modules to the module path.
Since I'm currently disallowing javac to report `compiler.err.module.not.found`, I can compile my project.

**Comment by Spasi** [comment]
@NekoCaffeine Thanks for the quick feedback, will be fixed in the next snapshot!
