### ISSUE TITLE
[LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers

### ISSUE THREAD

**Issue by LillieoftheMoon** [LWJGL/lwjgl3#924]
### Version

3.2.3

### Platform

Linux x64

### JDK

OpenJDK 20.0.2

### Module

ThreadLocalUtil?

### Bug description

this was the easiest way to inform the LWJGL devs, apologies! I got the following message, 
`[LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.`
The program runs as expected without issue. I am unsure how to check JNI version.

### Stacktrace or crash log output

```shell
`[LWJGL] [ThreadLocalUtil] Unsupported JNI version detected, this may result in a crash. Please inform LWJGL developers.`
```

**Comment by octylFractal** [comment]
This looks like the problem fixed by 0bc28efe6a39ebc9144dcb5dba3a15a3aa4e4f43 in 3.3.2, can you retry with that version?

**Comment by LillieoftheMoon** [comment]
Changed all LWJGL files to the 3.3.3 version, all is well! Thank you!

**Comment by StochasticTinkr** [comment]
FWIW, this is still an issue for me in 3.3.2.
