### ISSUE TITLE
how is lwjgl2 ? the lwjgl3 use glfw is not work in mac Parallels Desktop virtual machine！

### ISSUE THREAD

**Issue by qq1053831109** [LWJGL/lwjgl3#930]
### Question

how is lwjgl2 ? the lwjgl3 use glfw is not work in mac Parallels Desktop virtual machine！

**Comment by knokko** [comment]
I'm a bit late to answer, but basically: LWJGL2 uses a home-made windowing library, and has fewer bindings (not much more than OpenGL). The home-made windowing library gets most stuff done, but real windowing libraries are normally better. That having said, I never tried mac parallels desktop virtual machine.
