### ISSUE TITLE
LLVMGetBufferStart returns String instead of long because of const char* return type

### ISSUE THREAD

**Issue by KitsuneAlex** [LWJGL/lwjgl3#934]
### Version

3.3.3

### Platform

Linux x64, Linux arm64, Linux arm32, macOS x64, macOS arm64, Windows x64, Windows x86, Windows arm64

### JDK

Zulu OpenJDK 21

### Module

LLVM

### Bug description

There is a code generation bug involving the LLVMGetBufferStart function, as it falsely returns a `String` instead of a `long`, because the code generator seems to assume String based on the native function's `const char*` return type. Imo LLVM itself should just return a (const) `void*` there.. But that's not to question for me xD

This small issue has been bugging me for a while as i have to use the `nGetBufferStart` function instead as a workaround.

Thanks for the great work on the LLVM bindings otherwise, really nice to quickly build a compiler in Java :)

**Comment by Spasi** [comment]
@KitsuneAlex This will be fixed in the first 3.3.4 snapshot, thanks!
