### ISSUE TITLE
Binding for the clip2tri (poly2tri and clipper) library

### ISSUE THREAD

**Issue by httpdigest** [LWJGL/lwjgl3#94]
This is probably too specific, but having a binding for the clip2tri library https://github.com/raptor/clip2tri (MIT license) featuring a very simplistic C interface would be great to have in LWJGL 3, in case people want to triangulate arbitrary 2D polygons with holes, such as when rendering OpenStreetMap data (buildings, greens,...).

**Comment by kappaOne** [comment]
in case it helps, was looking into this problem a while back too, found that both LibGDX and Slick2D have a nice collection of 2d triangulators written in Java which seem to work well.

**Comment by httpdigest** [comment]
Thanks, kappa, for mentioning Slick2D. I had had a look at LibGDX but their triangulations (ear and delaunay) all cannot handle holes.
I would definitely favor a Java solution before going native :) so I take a look at Slick2D. Can you say something about the quality of the triangulators there?

**Comment by kappaOne** [comment]
From my tests so far LibGDX's EarClippingTriangulator seems the most robust triangulator. The MannTriangulator is also good and even faster in a few cases than the EarClippingTriangulator, however found it glitched on a few use cases (maybe I was using an unsupported draw order or something).

As for holes, I've found that adding a double edge slice and the hole in reverse to the original points/shape allows you to then pretty much use any triangulator (even those that don't support holes), the full technique can be read about at section 3 of this link http://www.geometrictools.com/Documentation/TriangulationByEarClipping.pdf

I've also written a triangulator based on the technique found here http://www.emanueleferonato.com/2011/09/12/create-non-convex-complex-shapes-with-box2d/ which basically splits any concave shape into convex. Then just brute forces the convex shape into triangles (picks a point in the shape and draws lines to all other points in the shape) which works fast. However at the moment it has a few kinks that I'm trying to iron out before it's usable.

Depending on your usecase GPU triangulation seems to be pretty popular using the stencil buffer technique (probably could also implement it using a FBO and shaders these days). Some details of the implementation can be found [here](http://stackoverflow.com/questions/25422846/how-to-force-opengl-to-draw-a-non-convex-filled-polygon) and [here](http://commaexcess.com/articles/7/concave-polygon-triangulation-shortcut). If usable for your usecase its pretty fast (and supports holes) however has the disadvantage in that it doesn't provide you with the actual points for the new triangles.

**Comment by kappaOne** [comment]
Also I came across [this library](https://github.com/mapbox/earcut) which looks pretty nice, haven't tried it yet though. It has a slightly out of date java port [here](https://github.com/Cawfree/earcut-j). It's not much code so don't think porting the latest javascript version is that much work.

**Comment by httpdigest** [comment]
Thanks, kappa, for all the information; appreciate it!
I finally got to trying the JavaScript earcut library. This one works really great on the browser. I had no issues so far triangulating three million OSM buildings in no time. The resulting triangles are as good as can be with such a triangulation algorithm that only works on existing nodes and does not introduce intermediate vertices to produce less degenerate triangles.
I begun porting it to Java, because I also need to triangulate on the server.

**Comment by httpdigest** [comment]
I think this issue can be closed now, since I have no further need for clip2tri.
