### ISSUE TITLE
native-image experimental options

### ISSUE THREAD

**Issue by Berstanio** [LWJGL/lwjgl3#942]
### Version

3.3.3

### Platform

macOS arm64

### JDK

all

### Module

core

### Bug description

The options `-H:JNIConfigurationResources` and `-H:ReflectionConfigurationResources` are apparently considered experimental.
GraalVM for JDK 21 will give a warning like
```
Warning: The option '-H:JNIConfigurationResources=[...]' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
```
lwjgl3 defines them in this file: https://github.com/LWJGL/lwjgl3/blob/master/config/native-image/META-INF/native-image/native-image.properties

However, this file and the options are not needed at all, since native-image already automatically picks the config files correclty up, based on their name. So just removing `native-image.properties` should be fine. 
I confirmed on my test, that it works correctly without this file.

**Comment by Spasi** [comment]
Hey @Berstanio,

Removed in `3.3.4-snapshot+2`, thanks!
