### ISSUE TITLE
Merge the glfw IME fix PR

### ISSUE THREAD

**Issue by kappa-maintainer** [LWJGL/lwjgl3#946]
### Description

I am working on porting some older Minecraft version to newer Java and encountered some problem with IME keyboard input. 
After further investigation, I found this [pull request](https://github.com/glfw/glfw/pull/2130) fixed every IME related problem and compiled a set of modified lwjgl3 to use it. 
I know the glfw native shipped by lwjgl is modified too, could lwjgl add these fixes to its natives as well?

**Comment by kappa-maintainer** [comment]
I see, we will continue to use our fork until it made into lwjgl.

**Comment by knokko** [comment]
Actually, we also added some of my PRs (for OpenXR/OpengGL interop) that aren't merged yet upstream. Personally, I don't see a problem with adding PRs to our fork whenever it suits us.

**Comment by Spasi** [comment]
I'm not very comfortable with significant features such as this one. If it never gets merged upstream, we may be stuck maintaining a lot of non-trivial code. For this reason, I've marked this as "experimental" in the release notes and it's a separate commit in the [CI repo](https://github.com/LWJGL-CI/glfw).

@kappa-maintainer Could you please test the `glfw-async` implementation as well please? You can download the updated dylib [here](https://www.lwjgl.org/browse/nightly/macosx) (not sure if you're on x64 or arm64). We may have to wrap `_glfwResetPreeditTextCocoa` and `_glfwSetIMEStatusCocoa`.

**Comment by kappa-maintainer** [comment]
We will test the IME binding on our fork. As for the glfw-async on macos, I know a project have been using this for months, will tell them to test.
