### ISSUE TITLE
Failed to dynamically load library: liblibGLESv2.so

### ISSUE THREAD

**Issue by chriscamacho** [LWJGL/lwjgl3#95]
[java] LWJGL Version 3.0.0b build 44
     [java] Exception in thread "main" java.lang.ExceptionInInitializerError
     [java] 	at test.initAndLoop(test.java:57)
     [java] 	at test.run(test.java:26)
     [java] 	at test.main(test.java:64)
     [java] Caused by: java.lang.RuntimeException: Failed to dynamically load library: liblibGLESv2.so(error = null)
     [java] 	at org.lwjgl.system.linux.LinuxLibrary.<init>(LinuxLibrary.java:23)
     [java] 	at org.lwjgl.system.APIUtil.apiCreateLibrary(APIUtil.java:56)
     [java] 	at org.lwjgl.LWJGLUtil.loadLibraryNative(LWJGLUtil.java:215)
     [java] 	at org.lwjgl.opengles.GLES.create(GLES.java:93)
     [java] 	at org.lwjgl.opengles.GLES.create(GLES.java:84)
     [java] 	at org.lwjgl.opengles.GLES.<clinit>(GLES.java:65)
     [java] 	... 3 more
     [java] Java Result: 1

on my system its libGLESv2.so ....!

**Comment by Spasi** [comment]
Thanks! Nightly build 3.0.0b 45 has the fix for this. Please let me know if you encounter any other issues, I haven't tried EGL/GLES on Linux.

**Comment by chriscamacho** [comment]
I notice ANGLE isn't ditributed...
I was able to get it working on linux using opentk binary dependencies, but their 32/64 bit libs have the same name... maybe need angle32 agle64 sub dirs in native for the windows lib loader ?
it would be nice if ANGLE was part of the binary download, so it works "out of the box" for windows users too

**Comment by Spasi** [comment]
That's outside the scope of LWJGL. There are other ways to use OpenGL ES on Windows, for example the [WGL_EXT_create_context_es_profile](https://www.opengl.org/registry/specs/EXT/wgl_create_context_es2_profile.txt) extension and the AMD [OpenGL ES SDK](http://developer.amd.com/tools-and-sdks/graphics-development/amd-opengl-es-sdk/).

**Comment by chriscamacho** [comment]
I've reopened this as build 45 doesn't fix this?
     [java] LWJGL Version 3.0.0b build 45
     [java] Exception in thread "main" java.lang.ExceptionInInitializerError
     [java] 	at test.initAndLoop(test.java:57)
     [java] 	at test.run(test.java:26)
     [java] 	at test.main(test.java:64)
     [java] Caused by: java.lang.RuntimeException: Failed to dynamically load library: liblibGLESv2.so(error = null)
     [java] 	at org.lwjgl.system.linux.LinuxLibrary.<init>(LinuxLibrary.java:23)
     [java] 	at org.lwjgl.system.APIUtil.apiCreateLibrary(APIUtil.java:56)
     [java] 	at org.lwjgl.LWJGLUtil.loadLibraryNative(LWJGLUtil.java:215)
     [java] 	at org.lwjgl.opengles.GLES.create(GLES.java:95)
     [java] 	at org.lwjgl.opengles.GLES.create(GLES.java:86)
     [java] 	at org.lwjgl.opengles.GLES.<clinit>(GLES.java:65)
     [java] 	... 3 more
     [java] Java Result: 1

**Comment by Spasi** [comment]
Thanks, should be fixed in build 46.

**Comment by chriscamacho** [comment]
Thanks!
btw sym linking liblibGLESv2.so to libGLESv2.so works - only tried it out of curiosity !

**Comment by chriscamacho** [comment]
FYI just tried build 46, the issue as been resolved, thanks very much - blisteringly fast response!
