### ISSUE TITLE
please get corrected version of tinyfiledialogs v3.17.4

### ISSUE THREAD

**Issue by vareille** [LWJGL/lwjgl3#960]
### Question

I am the maintainer of tinyfiledialogs.
the missing function realpath() compilation error on freebsd is now solved in tinyfiledialogs v3.17.4
get it from
https://sourceforge.net/projects/tinyfiledialogs

**Comment by Spasi** [comment]
Thanks @vareille, tinyfiledialogs is now updated to v3.18.1.
