### ISSUE TITLE
When will Unsafe be removed?

### ISSUE THREAD

**Issue by bowbahdoe** [LWJGL/lwjgl3#962]
### Question

I've been digging in to OpenAL and noticed some usages of `sun.misc.Unsafe` + a `requires jdk.unsupported` in the module-info.

Given that `Unsafe` will be removed at some point, what are the current plans for moving away from it? Are there particular upcoming APIs (like the foreign memory api? `MultiReleaseMemCopy` is where i found one of the usages.) that are being waited on?

**Comment by ws909** [comment]
Duplicates: 
- https://github.com/orgs/LWJGL/discussions/609
- https://github.com/LWJGL/lwjgl3/issues/853

**Comment by bowbahdoe** [comment]
Its only a duplicate if java.lang.foreign does hit all of the requirements needed to remove unsafe

**Comment by TheMrMilchmann** [comment]
LWJGL 3 supports Java 8 and that won't change before a new major version. Thus, just the release of the new FFI in Java 22 is not enough to replace `Unsafe`. Further, migrating to the new FFI is a significant undertaking and will probably not happen before [value/primitive classes](https://openjdk.org/jeps/401) (or whatever they end up being called) are available.

Sure, `Unsafe` is being removed, but slowly. If this happens before value types are made available, this will be revisited, but that's unlikely. (I would actually be surprised if unsafe removed in the next four years.)

**Comment by TheMrMilchmann** [comment]
I'm closing this for now because it has already been answered. Rest assured that this is on our radar and will be addressed (and announced) in time.

**Comment by dmitriy-bodroff** [comment]
Java 24 has been released and now we are getting the warning.

> WARNING: A terminally deprecated method in sun.misc.Unsafe has been called
> WARNING: sun.misc.Unsafe::setMemory has been called by <...>
> WARNING: Please consider reporting this to the maintainers of <...>
> WARNING: sun.misc.Unsafe::setMemory will be removed in a future release

https://openjdk.org/jeps/498

> Over the past several years, we have introduced two standard APIs that are safe and performant replacements for the memory-access methods in sun.misc.Unsafe:
> 
> [java.lang.invoke.VarHandle](https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/lang/invoke/VarHandle.html), introduced in JDK 9 ([JEP 193](https://openjdk.org/jeps/193)), provides methods to safely and efficiently manipulate on-heap memory, i.e., fields of objects, static fields of classes, and elements of arrays.
> 
> [java.lang.foreign.MemorySegment](https://docs.oracle.com/en/java/javase/22/docs/api/java.base/java/lang/foreign/MemorySegment.html), introduced in JDK 22 ([JEP 454](https://openjdk.org/jeps/454)), provides methods to safely and efficiently access off-heap memory, sometimes in cooperation with VarHandle.

Decided to use warning suppression with the following option.

> `--sun-misc-unsafe-memory-access=allow` allows use of the memory-access methods with no warnings at run time.
> 
> This mode was the default in JDK 23.

**Comment by chorman0773** [comment]
May have misread it. Either way, based on the current cycle, that's next march.
