### ISSUE TITLE
[Question] Is there any reason why Eearly Access 3.3.4 missing lwjgl.jar?

### ISSUE THREAD

**Issue by runlevel5** [LWJGL/lwjgl3#966]
### Question

Steps to reproduce:

* Go to https://www.lwjgl.org/customize
* Choose Everything Preset
* Choose macOS arm64
* Click Download Zip
* Extract the zip file
* Look for `lwjgl.jar` but not found

Notes:

The `lwjgl.jar` file is available in 3.3.3

**Comment by Spasi** [comment]
Hey @runlevel5,

Thanks, fixed with https://github.com/LWJGL/lwjgl3-www/commit/80799a4a3c1e70f61125a9407f6bd8118f57aa29.
