### ISSUE TITLE
joml-primitives missing

### ISSUE THREAD

**Issue by DanaBallinger** [LWJGL/lwjgl3#967]
### Question

joml primitives were moved to a separate project (joml-primitives) since 1.10. Would it be possible to included this in the joml dowload, since key classes are now missing.

**Comment by Spasi** [comment]
Hey @DanaBallinger,

Added with https://github.com/LWJGL/lwjgl3-www/commit/5a3584e72128e22ceb6b40ebabc480e6fa2da56e.
