### ISSUE TITLE
Skia API

### ISSUE THREAD

**Issue by FlysoftBeta** [LWJGL/lwjgl3#969]
### Library

Skia

### Project page

https://skia.org/

### Source repository

https://skia.googlesource.com/skia

### Platforms

Linux x64, Linux arm64, Linux arm32, macOS x64, macOS arm64, Windows x64, Windows x86, Windows arm64

### Description

IMO, Skia is a neat graphics library and can benefit java UI framework development. It has been used in Chromium, Firefox and many other projects.

[The JetBrains one](https://github.com/JetBrains/skiko) only provides awt support, but i want full access of it.

**Comment by TheMrMilchmann** [comment]
Hi @FlysoftBeta, Skiko should already be usable with LWJGL (and GLFW). For Compose Multiplatform, JetBrains provides an (experimental) example showing how to use both together to create a Skia surface for a GLFW window.

Have a look at [the sample](https://github.com/JetBrains/compose-multiplatform/blob/2bb6ec5e65fa89fa0032309918cf17ea71e3695f/experimental/lwjgl-integration/src/main/kotlin/main.kt#L28). If you ignore the Compose-specific set-up, you should still have a Skia surface you can use for drawing.
