### ISSUE TITLE
Unable to create GLFW Window

### ISSUE THREAD

**Issue by Cube5x59999** [LWJGL/lwjgl3#984]
### Question

This is my first time using LWJGL to make a game, but it failed creating the window. but my other computer with the same specs can create a window like normal. what are the reasons which results in unable to create window?

**Comment by knokko** [comment]
I would recommend to try creating the minimal window, as shown in https://www.glfw.org/documentation.html

And could you be more specific about `failed creating the window`? What happens? Does `glfwInit()` return false? Does `glfwCreateWindow` return null?

**Comment by CiroZDP** [comment]
Did you link the natives?

**Comment by TheMrMilchmann** [comment]
I'm closing this as there is no information to work with. If you're still facing this issue, please report back with more information.
