### ISSUE TITLE
Binding bug on glXGetGPUIDsAMD() in GLXAMDGPUAssociation

### ISSUE THREAD

**Issue by SpartanB312** [LWJGL/lwjgl3#988]
### Question

As the title described. The method's parameter are 'int maxCount' and 'int ids but in [https://registry.khronos.org/OpenGL/extensions/AMD/GLX_AMD_gpu_association.txt]
The parameters are 'unsigned int maxCount' and  'unsigned int *ids'.  

There is another implementation in java:
[https://github.com/mattprice28/Cardiff-University/blob/4d3a9bcb9e9624f9c1c380504bb749580f1c4537/Year%203/CM3114/jogamp-all-platforms/jogamp/opengl/x11/glx/GLXExtImpl.java#L59]
They use IntBuffer to return ids.

So, how can I get returned ids in LWJGL3?

**Comment by Spasi** [comment]
Hey @SpartanB312,

It's a bug in the bindings, will be fixed in the next 3.3.4 snapshot.
