### ISSUE TITLE
Broken animations on model imported using Assimp

### ISSUE THREAD

**Issue by controllerface** [LWJGL/lwjgl3#994]
### Version

3.3.4 (snapshot)

### Platform

Windows x64

### JDK

OpenJDK 22

### Module

Assimp

### Bug description

After confirming my test from #990 passed in the latest snapshot, I tried using it in my main project and found that the model loads, but several of the animation keyframes are corrupted. The bug is mainly visual so was hard to make a test case for, but I checked the Assimp issues and looks like someone reported a strikingly similar issue there: https://github.com/assimp/assimp/issues/5642

That looks very similar to what I am seeing and is the same kind of model file as I am using. I am assuming this is probably similar to the last Assimp bug, and just requires a patch to the dependency. Even so, I have attached two log files that I dumped, one from latest stable `test_33.log` and one from the snapshot `test_43.log` that can be diffed to see where there animation data is corrupted.

I can try and make a more concrete test if it helps, but am hoping it's just a quick patch.

[test_model_logs.zip](https://github.com/user-attachments/files/16213629/test_model_logs.zip)

**Comment by Spasi** [comment]
Hey @controllerface,

There's a new Assimp build up with the patch applied, could you please test to see if the issue is fixed?

Download https://build.lwjgl.org/nightly/windows/x64/assimp.dll (for Windows x64) and run your application with `-Dorg.lwjgl.assimp.libname=<path>` or `Configuration.ASSIMP_LIBRARY_NAME.set("<path>")`, where `<path>` is the path to the downloaded file.

**Comment by controllerface** [comment]
Gave it a shot, unfortunately it did not fix the issue, and it made it quite a bit worse. The model is still all scrambled and is also scaled to a crazy size. Just to confirm, I scaled down my model, which I usually render with a scale of `1.0`, to `.01` and the model's proportions looked more correct, but the positions are even crazier than before.

Will attach some screenshots. Here's one base line showing what it normally looks like in `3.3.3`, and then 3 bad ones, `bad.png` is with current snapshot, `bad2.png` is _with_ the dll and using the snapshot, and `bad3.png` is the dll file but forcing the model scale to .01.

<img width="309" alt="good" src="https://github.com/user-attachments/assets/2aaa436e-d0eb-4c41-b1c8-1aadbadb3361">
<img width="331" alt="bad" src="https://github.com/user-attachments/assets/af9dd9c1-25bf-4fe3-b5b4-e08c751cbc7a">
<img width="960" alt="bad2" src="https://github.com/user-attachments/assets/6e3f64fd-bd21-477c-9ce9-eba8999c7d48">
<img width="344" alt="bad3" src="https://github.com/user-attachments/assets/1b6e085e-b1ba-47c7-a2ee-a8e92f5e478b">


Let me know if I can help debug further.

**Comment by Spasi** [comment]
The patched Assimp build includes this commit: https://github.com/assimp/assimp/pull/5643/commits/ea988c13f08706c78985f8b00a9e8241d4a1a1e3. Not sure what else to try, any ideas?

**Comment by controllerface** [comment]
Nothing obvious, I don't think anything is likely to fix it short of rolling back to an older version. 

I did do more diving through their GH open issues and did find several other bugs that looks similar, some with recent activity. Probably not much can be done until those bugs are sorted, I definitely don't have the expertise needed to try and fix the bug in Assimp myself.

Thanks for at least taking a look at this. For the time being I will just stick to a working release, and try new snapshots as they come out, hopefully it gets sorted at some point.

**Comment by controllerface** [comment]
Switched to gLTF format and that works, so I will close. I've got reason to prefer .fbx anyway.
