### ISSUE TITLE
Issue with swapChainExtent changing - kotlin

### ISSUE THREAD

**Issue by Hellwoodoo** [LWJGL/lwjgl3#995]
### Version

3.3.4

### Platform

Windows x64

### JDK

OpenJDK-21.0.2

### Module

Vulkan 

### Bug description

Swapchain extent VkExtent2D seems to change in kotlin, whilst only ever creating it once. Log is shown at creation, and then at second query. 

var swapChainExtent: VkExtent2D? = null

### Stacktrace or crash log output

```shell
17:04:09.527 [DEBUG] - [org.engine.vulkan.Vulkan] - [main] - Swap Chain Extent:
17:04:09.527 [DEBUG] - [org.engine.vulkan.Vulkan] - [main] - width: 2560
17:04:09.527 [DEBUG] - [org.engine.vulkan.Vulkan] - [main] - height: 1057

when querying the same swap chain 

17:05:33.628 [DEBUG] - [org.engine.render.Render] - [main] - Swap Chain Extent:
17:05:33.628 [DEBUG] - [org.engine.render.Render] - [main] - width: 20
17:05:33.629 [DEBUG] - [org.engine.render.Render] - [main] - height: 0
```

**Comment by Spasi** [comment]
Hey @Hellwoodoo,

There's nothing to work with here. Please open a new issue with more information if you've verified an actual problem with LWJGL.
