### ISSUE TITLE
LWJGL 3.3.4 GLFW issues on Linux Wayland

### ISSUE THREAD

**Issue by generaloss** [LWJGL/lwjgl3#998]
### Version

3.3.4

### Platform

Linux x64

### JDK

17, 22

### Module

GLFW

### Bug description

Arch Linux x64 6.10.3-arch1-1, KDE Plasma 6.1.3, **Wayland**

* *glfwExtensionSupported("GLX_EXT_swap_control_tear")* returns true in 3.3.3 | return false in 3.3.4
* *GLFW_CURSOR_HIDDEN* and *GLFW_CURSOR_DISABLED * works in 3.3.3 | doesn't work in 3.3.4
* *glfwSetWindowPos* works in 3.3.3 | doesn't work in 3.3.4
* *glfwGetWindowPos* always returns 0 in 3.3.4
* *window pos callback* works in 3.3.3 | doesn't work in 3.3.4
* *glfwSetWindowIcon* works in 3.3.3 | doesn't work in 3.3.4
* Window contents are cut off in 3.3.4
* Message when **libdecor** package is installed with 3.3.4:
"*libdecor-gtk-WARNING: Failed to initialize GTK
Failed to load plugin 'libdecor-gtk.so': failed to init*"

---

https://github.com/user-attachments/assets/af583e86-28fe-40fe-9d58-7d78d204a561

**Comment by tomwmth** [comment]
Similar issue, but with a dialog window not shown in the video

Platform: Arch Linux x64 6.10.8-arch1-1, KDE Plasma 6.1.4, Wayland

https://github.com/user-attachments/assets/285535fb-b18c-41dd-8503-86937748c81b

**Comment by kles4enko** [comment]
I had something similar with 3.3.4 binaries on MacOS as well (see: https://github.com/LWJGL/lwjgl3/issues/1000)
It seems that native artifacts for 3.3.4 was compiled in broken CI environment...

**Comment by Spasi** [comment]
Hey,

@kles4enko The MoltenVK issue is known and unrelated. It also has very high priority and I'm trying to prepare the 3.3.5 release asap. In the meantime, the latest [snapshot](https://www.lwjgl.org/browse/nightly/macosx) of `libMoltenVK.dylib` has been fixed and you can use it with 3.3.4 (download the shared library and point to it with `-Dorg.lwjgl.vulkan.libname` or `Configuration.VULKAN_LIBRARY_NAME`).

@generaloss The functionality you mention as not working is documented as not supported on Wayland by GLFW itself. For example, the note for `glfwSetWindowPos` is:

> **Wayland**: There is no way for an application to set the global position of its windows. This function will emit `GLFW_FEATURE_UNAVAILABLE`.

If you're seeing differences between 3.3.3 and 3.3.4, it may be something else that has changed. Are you sure that the Wayland backend is even used when running on 3.3.3?

**Comment by generaloss** [comment]
@Spasi
I’m sure I used the Wayland backend if GLFW in LWJGL 3.3.3 cannot use any installed backend regardless of which one is running. I don’t know how to check it.

**Comment by Spasi** [comment]
@generaloss Try the `GLFW_PLATFORM` hint with values `GLFW_PLATFORM_X11` and `GLFW_PLATFORM_WAYLAND`. Then call `glfwGetPlatform()` to see what backend you get.

**Comment by generaloss** [comment]
@Spasi Indeed, LWJGL 3.3.3 automatically selects the X11 backend while 3.3.4 selects Wayland.
