### ISSUE TITLE
Why does GLFWVidMode#refreshRate() not round the refresh rate?

### ISSUE THREAD

**Issue by TCreutzenberg** [LWJGL/lwjgl3#999]
### Question

Hey,

I have a Monitor with a refresh rate of 59.951Hz. 

When I try to retrieve the refresh rate of this monitor with (LWJGL 3.3.3)
```
GLFWVidMode videoMode = GLFW.glfwGetVideoMode(monitor);
int refreshRate = videoMode.refreshRate();
```
refreshRate  is 59. Shouldn't it round the 59.951Hz and return 60?

If I set the fps of my application (game) to 59 I get a visible stutter on fast moving elements every second which I don't get with 60 fps...

Thank you very much in advance!

**Comment by Spasi** [comment]
Hey @TCreutzenberg,

This is a [known issue](https://github.com/glfw/glfw/issues/230).
